### ISSUE TITLE
[Docs] Stack main nav + expand search bar

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1005]
Currently looks like:

![Screen Shot 2019-04-08 at 11 30 00 am](https://user-images.githubusercontent.com/612020/55693651-7a94ae00-59f3-11e9-8680-9b5435a7164b.png)

Proposed look:

![Screen Shot 2019-04-08 at 11 29 22 am](https://user-images.githubusercontent.com/612020/55693664-85e7d980-59f3-11e9-9cd5-4df4e6c69375.png)

Inspired by: https://mobile.twitter.com/adamwathan/status/1114552470745669632

**Comment by nathansimpsondesign** [comment]
The menu items map exactly to the rest of the navigation bar (ie there is unnecessary duplication of 'quick start', guides etc). Maybe a better alternative is to have each list expand like an accordion?

**Comment by JedWatson** [comment]
Personally I think we need to do a bit more IA planning before we rearrange this. The nav on the left is a bit unwieldy and we may want to group pages into multiple top level sections. At that point the primary nav becomes more useful.

E.g Quick Start, Tutorials and Guides could be grouped under a **Guides** section while API, Packages and Field Types could go under an **API** section. I'm really not sure about this, but that's the point. I just want to be careful about removing a layer of organisation from the system prematurely; we have a _lot_ of documentation to write 😬 

I do like the idea of moving the search into the header at some point, especially if we start grouping pages into sections, because it's global across all the docs. But the super-long search field seems unnecessary; with the autosuggest I don't think people will type more than a dozen characters into it ever

**Comment by MadeByMike** [comment]
I think this is a very low priority at the moment. Unless someone really wants to tackle it I think we're better focusing on getting more quality documentation then re-launching with a better website in the future.
