### ISSUE TITLE
Feature Request: Persist Types.Name.full to database.

### ISSUE THREAD

**Issue by metasansana** [keystonejs/keystone#1062]
Currently it's accesible as a virtual. If you think about it though; `name.first` + `name.last` is a piece of data about the entity in question that we are interested in.

**Comment by morenoh149** [comment]
:/ I think that's debatable. http://keystonejs.com/docs/database/#fieldtypes-name adds User.first and User.last fields. You'd like to also add a User.fullname field? that's doable but we need to reach consensus regard that.

**Comment by BerkeleyTrue** [comment]
Seems like you are just doubling the amount of information stored but not really adding more value. `full name` is a composite information.

**Comment by JohnnyEstilles** [comment]
I agree with @BerkeleyTrue. This is a non-issue.

- `name.full` is already indirectly persisted to the db via `name.first` and `name.last`
- `name.full` is always available (though since its a virtual we may need to use `.toJSON()` or `.toObject()`)
- `name.full` is also setable ... (The setter automatically splits it and store the parts in name.first` and `name.last`

Like @BerkeleyTrue says, the suggested feature doesn't really add any value. 

Unless anybody has anything else to add, I think we can consider this issue closed.

**Comment by JedWatson** [comment]
I agree with everyone about why it's not stored, these were my original thoughts.

@metasansana curious though as to why you _did_ want it stored? I've felt that it's limiting from a search perspective sometimes, it *can* make certain queries more awkward. But not enough to want to persist it.

**Comment by metasansana** [comment]
It's data and it's not already stored by the other fields because you have
to perform an operation to get it back ( the virtual function).

What if I want to use the same data in a non keystone application? Or what
if my queries are large forcing me to use ` lean()`?

I will have to do the work of the virtual function for each. Not a big
issue, but that defeats the point of a database!

On 15 Feb 2015 07:50, "Jed Watson" <notifications@github.com> wrote:
>
> I agree with everyone about why it's not stored, these were my original
thoughts.
>
> @metasansana curious though as to why you did want it stored? I've felt
that it's limiting from a search perspective sometimes, it can make certain
queries more awkward. But not enough to want to persist it.

**Comment by morenoh149** [comment]
@metasansana if your concern is performance. Those will be highly application specific.

you could think of the `fullname` field as a precomupted value you want to store in mongodb to avoid several calls to the `+`,`.join()` or `+=` operators.

Also if you're using the same db from another application. Consider that application could do an aggregation query with the `[$concat](http://docs.mongodb.org/manual/reference/operator/aggregation/concat/)` aggregation operator.

If we determine many keystone apps in the wild would benefit from this performance optimization I'm sure we could revisit the topic.

**Comment by metasansana** [comment]
It's not about performance; it's about storing data. That's the purpose of a database after all.

If you consider saving `fullname` duplicate data, then that's kind of a premature optimization,  one that actually creates more friction than benefit actually, because you have to account for it's absence in the form of virtuals, queries with `lean`, external applications etc.

The cost of saving it, is just another field in the name collection in the database.

**Comment by JohnnyEstilles** [comment]
@metasansana, I understand your point of view. However, I believe your making a generalization that isn't broadly applicable. You are correct when you say that this choice can be construed as premature optimization. While that may be true in circumstances such as the ones you enumerate, it may not necessarily be applicable to the majority of Keystone consumers.

Personally, I like the fact that Keystone is unopinionated on the matter. This allows me as a developer to either use the `Type.name` fields as-is and use the existing virtual to construct the `name.full` when I need it or, if I so choose, I can manually duplicate the data on a separate field (see example below). 

I would not have this flexibility if Keystone imposed this choice on me.

```js
List.add({
  name: { type: Types.name }
});
List.schema.add({
    fullName: { type: String } <-- my very own personal full name field
});
List.schema.post('pre', function() {
  this.fullName = this.name.last + ', ' + this.name.first; <-- store full name however you want
});
```

Again, you make a lot of very intelligent and valid points. However, IMHO, as valid as they may be (1) I don't believe they are applicable to most situations, and (2) I prefer a less opinionated Keystone that allows me as a developer to choose how much I want to optimize.

**Comment by JedWatson** [comment]
I actually *like* the idea of storing `name.full` in the database, even though it's not the decision I made when initially implementing it. It would certainly simplify our searching logic and make those queries faster.

Given the scale of data MongoDB can easily handle, storing an additional flattened string probably isn't a concern. If it is, we could make the persistence an option pretty easily.

I'm not sure it doesn't introduce additional complexity though. Where is the "source of truth" for the field? At the moment that's a simple, clear answer.

Also to get the benefit of it at a generic level, if we make it an option, we can't rely on it so it adds complexity rather than removing it.

Those are my thoughts so far, good discussion.

**Comment by JedWatson** [comment]
I *also like* the solution @JohnnyEstilles outlines above, worth pointing out I am primarily interested in this for the purpose of simplifying some of the query logic in Keystone. Doing a fuzzy match database-side on "first last" across two paths is pretty hard at the moment, involves string splitting and multiple $or statements; maybe someone has a more elegant way to do that though.

**Comment by JohnnyEstilles** [comment]
@JedWatson at one point I considered proposing that `name.full` could "optionally" be persisted to the database. Something like:

```js
List.add({
  name: { type: Types.name, 'persist full': true }
});

When `persist full` is `false`, it would default to a virtual, and when `true` it would be a field that is updated on `pre save` hook (like my previous example).

But then I realized how that would complicate searching ... So I decided to give it more thought ...

**Comment by JedWatson** [comment]
@JohnnyEstilles yep, same thought here too. I'm going to reopen this while we consider our options, I'd actually like to come up with a better solution for name-based searching (e.g. being able to use search relevance as a sort in the list view)

**Comment by creynders** [comment]
Allowing easier searching is definitely a valid use case. However, I'm not entirely on-board with the other reasoning here. Avoiding data redundancy is not premature optimization, on the contrary: providing data redundancy for what-if's is. 
I see the usual two-way data binding issues here. The only good solution would be by having a single entry point, i.e. the virtual we already have, which caches the resolved full name (both on "get" and "set") to a separate "protected" field. Otherwise data corruption _will_ occur, no maybes.

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/persist-typesnamefull-to-database
