### ISSUE TITLE
iOS admin app

### ISSUE THREAD

**Issue by perryao** [keystonejs/keystone#1088]
Hi guys,
Apologies if Github issues is the wrong place for this, but I've been thinking of ways I might be able to contribute to keystone development. I'm an iOS developer by trade, so I was thinking it might be cool to have an admin app for iOS. Wordpress has an app that lets you manage content on the go, and this might be something people would like to use with Keystone. Has anyone started working on something like this? If not, would there need to be any changes to Keystone core to support access to an instance of Keystone from an iOS app?

**Comment by morenoh149** [comment]
I think keystone would be more interested in using http://touchstonejs.io/ for such a thing. That being said if you release an app and the community finds it useful. It should matter who made it and with what technologies.

**Comment by perryao** [comment]
I can definitely see how a js approach might be better suited for this community. I'll take a look at touchstone when it's released. Would you mind briefly highlighting the reasons for your suggestion of touchstone? I was pretty interested when I heard Facebook announce React Native, so I'm just curious what might be the pros/cons of both(which might be hard to say at this point since neither framework is released yet).

**Comment by morenoh149** [comment]
@JedWatson was at the announcement and they seemed to acknowledge touchstone.js. I fixed a typo above I meant it *shouldn't* matter how its made.
From what I've heard if react-native makes it out of beta the work done with touchstone.js won't be lost. They can work together. touchstone being more of a UI collection I believe.

**Comment by JedWatson** [comment]
@perryao thanks for the idea - I think it would be excellent to start working on an iOS App for Keystone. Although the Admin UI works reasonably well as a responsive app, it would be a much better user experience to have a native one.

My first thought would be to assess how the dynamic form generation would work, as there are certain field types (e.g. WYSIWYG HTML) that might be challenging to port to a native app using readily available controls.

I would personally lean towards a Hybrid approach (HTML5 / CSS / JS with Cordova and some plugins) because it's easier to imagine how new field types (and custom field types) would be able to be added - If each field type contained a `{Type}Field` React Component that worked for the Web Based Admin UI, and a `{Type}MobileField` React Component that worked in the native mobile app, it would be fairly easy to maintain and extend.

Personally of course I would also use Touchstone, as it's developed by the same core team as Keystone :smile: but this is, more than anything, about having a development and testing environment (JS + Browser) that is familiar to Keystone developers.

That goal would also be achievable with React Native too, and that is a good option to look into. It works quite differently from Touchstone in that it gives you a JavaScript environment to control Native components, rather than a DOM for rendering the UI.

I think as @morenoh149 pointed out though, we don't want to enforce any limitations on what people build as part of the Keystone ecosystem - if you are up for creating a mobile app and it works well then that would be fantastic, regardless of how it's done.

Not a lot would be necessary to enable this development in Keystone itself - we just need to expose some API Endpoints (that are planned to be developed and exposed in the near future anyway as we finish transforming the Admin UI into an SPA with React)

Maybe put a plan together and let us know what you're thinking, how to go about building the mobile app? I'd be happy to support this in any way necessary.

**Comment by virgafox** [comment]
@JedWatson take a look at this too http://reapp.io

**Comment by JedWatson** [comment]
@virgafox across that :) thanks for the heads up!

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/ios-admin-app
