### ISSUE TITLE
Option to disable SSL 3.0

### ISSUE THREAD

**Issue by jesse-ae** [keystonejs/keystone#1110]
In the wake of the POODLE bug we should have the option to disable SSL 3.0 support by setting the `secureOptions` option to `constants.SSL_OP_NO_SSLv3` as detailed here: https://disablessl3.com/#nodejs

**Comment by JohnnyEstilles** [comment]
@jesse-ae unless you're using a pre `0.10.33` version of Node.js this is a non-issue. Since `0.10.33` Node disables `SSLv2` and `SSLv3` by default. See [Node v0.10.33 (Stable)](http://blog.nodejs.org/2014/10/23/node-v0-10-33-stable/).

Maybe we should add a warning in the docs under the [SSL Options](http://keystonejs.com/docs/configuration/#options-ssl) advising developers to use node `0.10.33` or newer if they intend to enable SSL.

**Comment by jesse-ae** [comment]
This works. Thanks @JohnnyEstilles.
