### ISSUE TITLE
Investigate Squire as the default WYSIWYG editor

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1112]
I quite like the look of this: http://neilj.github.io/Squire/

(suggested by @morenoh149 in #739)

Maybe we should use this as the default editor for WYSIWYG HTML fields in Keystone. It's much lighter than TinyMCE, and has the basics that most people would need.

If we do this, we should make it possible to use TinyMCE as an alternative (possibly packaged as a separate npm module, `keystone-tinymce`) so people who need its advanced features can still choose it.

**Comment by arthurtalkgoal** [comment]
Hi @JedWatson,

Can I ask have you tried 
https://github.com/jhollingworth/bootstrap-wysihtml5/

I have been using this one. It quite nice too, 

but there are two things I am finding solution:
1. Upload images to server 
2. Insert code snippets (it's not common problem cf pt 1)

**Comment by mkoryak** [comment]
I have used bootstrap-wysiwyghtml5 and I cannot recommend it. I ran into some issue that required me to modify the source code which is a huge no-no. They have 150 open issues and so getting a fix out for the bug I encountered was not a high priority for them. 

It is much better than ckeditor though, and will work if you dont poke it too much.

**Comment by arthurtalkgoal** [comment]
Good comments @mkoryak. I am looking into squire after I found challenges in making my own button.

**Comment by mkoryak** [comment]
i made an angularjs directive that improves upon some of the ui stuff in the squire-ui (which isnt an official thing as far as i can tell)

you should be able to rip out the important stuff from the angular code if you wanted the same kind of improvements:

http://hourlynerd.github.io/angular-squire/  (refresh a few times if it doesnt load, rawgit is giving me troubles)

**Comment by morenoh149** [comment]
@mkoryak very nice colors.

**Comment by StephenLeicht** [comment]
This would come in really handy for my company's blog. I've been poking around with the source to let the developer specify the wysiwyg editor. I've written up a proposal that I think could work well.

I have a **very** rough PoC of using squire instead of tinymce at https://github.com/StephenLeicht/keystone. Please note this PoC was just to show that tinymce and squire could be refactored into separate modules. I haven't started on what I've proposed below.

#### Prerequisites
Arbitrary scripts would have to be allowed to be loaded into the admin section of keystone so that a non-included editor could be specified (squire, tinymce as a external module like `keystone-tinymce`)

#### Proposed API
Add a `includes` configuration option that takes an array of strings that get added as script tags to the base.jade template

example:
```javascript
keystone.init({
    //other things
    includes: ['/js/admin/extensions.js'];
});
```
then in the exposed browser side Keystone object there could be a Keystone.useWysiwyg() or similar function that accepts an object. Right now the only field I have planned for this object would be `component` which would be a reference to a React component for the HtmlField to use. If this is never called we default to tinymce as to not break backwards compatibility. Each editor could also get it's options from the global Keystone object, if these are set in the wysiwyg options in keystone.

#### Foreseeable good side effects
1. This could lead the way to fully custom third party field types via the includes option. Though that would require more work on top of this.
2. This would also allow a developer to use any wysiwyg editor they prefer just by writing a small react wrapper around said editor


#### Foreseeable bad side effects
It could be relatively easy to break the admin interface if they mess with the Keystone global object or load in a bad script. Though this a pretty minor point as it's easy to do that with any library if you're not careful, but it is something to bring up as that is not possible (as far as I know) currently in keystone.


@JedWatson, what do you think? Would this be something you're interested in seeing me flesh out and creating a pull request for?

**Comment by gaurav21r** [comment]
Might  also throw CkEditor into the mix? TinyMCE and CkEditor are the market leaders in the WYSIWYG Editor Space (for html not markdown). The reason more lightweight Editors exist (and thrive) is because they are a luxury component in most applications.

But in a CMS (Keystone, Drupal, WordPress), the editors take center stage! I have been working with some large clients in the publishing industry and all their experienced editors were very uncomfortable with such "light weight" editors. Basically, people want MS Word inside their CMS.

I strongly recommend moduling out the editor but making CkEditor or TinyMCE still the default.

**Comment by JedWatson** [comment]
I'm really interested in making the editors customisable (so you can plug in CKEditor / TinyMCE / Squire) and agree with most of the comments above.

We need to wait for the next release (0.4) to go live with Elemental UI first though, any progress on this would be throwaway otherwise.

That (or a release shortly after) will define a plugin API for custom field types, and I'll work out how to allow editor customisation into the mix.

Thanks for the input everyone, and the r&d @stephenleicht!

**Comment by morenoh149** [comment]
closing in favor of https://github.com/keystonejs/keystone/issues/1892

**Comment by kidwm** [comment]
@morenoh149 Maybe you should also update the backlog in ROADMAP.md.

**Comment by morenoh149** [comment]
@kidwm well we can still investigate the topic. I just figured we could fold this issue into the other seeing as they are all about wysiwyg editors.
