### ISSUE TITLE
Make existingItem available to list level access control functions

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#1124]

**Comment by JedWatson** [comment]
ref #1125

**Comment by jesstelford** [comment]
I've had an inkling of an idea for a little while where hooks, access control, virtual field resolvers, etc, receive an `async getExistingItem()` instead of `existingItem`.

Then we could run all the Access Control checks in parallel, and only load the existing item if it's actually requested. The existing item loading Promise can be shared with every subsequent call to `getExistingItem()` in that loop.

That solves two problems:
1. Stop blindly loading the existing item before every mutation so it can be passed into Hooks.
2. Optimise for mutations/queries that never actually need the existing item. Ie; it's always fast path by default, and only jumps to slow path (loading `existingItem`) if the data is actually requested within the hook/access control/etc.

Since it's not provided on the Access Control checks currently, maybe this is a good chance to start introducing this API?

**Comment by jesstelford** [comment]
Oh, and `getExistingItem()` can accept a parameter for altering the GraphQL query sent - maybe there's only a single field needed for example.

This introduces added complexity for gathering up all the calls to `getExistingItem()`, then merging all the schema together to batch it in a single request.

**Comment by MadeByMike** [comment]
@timleslie you updated these function recently. Any change to this issue?

**Comment by famel** [comment]
Hi, is there a solution on this issue? Can we somehow have existingitem info in list level access functions (read and update)?

**Comment by timleslie** [comment]
List level access control functions receive an `itemId` and `context` (https://next.keystonejs.com/apis/access-control#imperative-list) which allows them to use the items API (https://next.keystonejs.com/apis/list-items) if they need the existing item.

**Comment by famel** [comment]
Hello, thanx
Should I get last version of keystone5 to use or? Or it will be available to new version (Keystone 6?)
