### ISSUE TITLE
reset the keystone demo content

### ISSUE THREAD

**Issue by trentontri** [keystonejs/keystone#1126]
with the Keystone demo open for anyone to edit it would be ideal to have an auto reset of the content every day or so. This way potential new users won't see titles like "What a crappy and slow system..." on the demo blog site. I worry that without some form of filtering the playful comments will only become worse as Keystone grows.

**Comment by morenoh149** [comment]
+1. I think I'll just nuke it actually. Will update later.

**Comment by trentontri** [comment]
just a thought, what if visitors could still click around but every edit field were set to disabled? It might be more effort than it's worth but I do think the concept of a demo is great for new visitors who are skeptical of this whole NodeJS movement.

**Comment by morenoh149** [comment]
Indeed. I'll revisit this topic when I finish updating the demo repo here https://github.com/r3dm/keystone-demo

**Comment by JedWatson** [comment]
@morenoh149 I've also been planning to rebuild the demo site, we should collaborate ;)

The current repo is a bit nuked, because it went sideways with an alternative design (that should have happened in a branch) and wasn't finished. Been meaning to start from scratch, make it less of a "starter project" (it was from before we had the yeoman generator) and more of a curated demo.

The whole demo experience could really do with some love.

**Comment by joshjung** [comment]
@JedWatson If you are interested in setting up a more comprehensive demo, I would love to help. I'm between projects at the moment so looking for some ways to spend my coding time.
