### ISSUE TITLE
Default values as function

### ISSUE THREAD

**Issue by dcousens** [keystonejs/keystone#1136]
When defining default values it would be useful to allow a functions in addition to static values. For example:

### Current:
``` js
dob: {
    type: CalendarDay,
    format: 'Do MMMM YYYY',
    yearRangeFrom: 1901,
    yearRangeTo: getYear(new Date()), // Gets the date when Keystone is started
},
```

### Suggested:

``` js
dob: {
    type: CalendarDay,
    format: 'Do MMMM YYYY',
    yearRangeFrom: 1901,
    yearRangeTo: () => getYear(new Date()), // Get the date when a user creates a new item
},
```

**Comment by MadeByMike** [comment]
We need to do a better job of describing what this is less technical way. "Default value initialization as lambdas" is not very welcoming for community contributions. @dcousens would you mind having a go at describing what this enables for developers\users?

**Comment by dcousens** [comment]
> Default value initialization functions

**Comment by MadeByMike** [comment]
Let me update it then :p

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
