### ISSUE TITLE
Cannot find ways to add a custom button or links in Admin UI

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1137]
I wanna add a custom function to my model, I tried to a testing function in the model

```
var Client = new keystone.List('Client', {
	autokey: { path: 'slug', from: 'client_id', unique: true },
  track: true,
  testing: function (callback) {
        this.populate('category', (function(err) {
            if (err) return callback(err);
            if (this.category) return callback(null, '/blog/' + this.category.key + '/' + this.key);
            callback(null, '/blog/post/' + this.key);
        }).bind(this));
    }
});

```

but it doesn't update any thing in admin UI.

Can I ask what is the best way to insert my view templates or button in Admin UI?

**Comment by jeffreypriebe** [comment]
I think that you want something like:
```
var Client...
  category: { type: Types.Select, options: 'Cat1, Cat2' },
  testing: {
    type: String,
    watch: 'category',
    value: function (callback) { 
      ... your code as above here...
    }
  }
```
Assuming that you add a field 'category' on your Client as per above (though likely you want a ref lookup from somewhere).

Not sure if the bind on the function will do anything special, since usually the 'this' is the item, so by default 'this.category' would be the category field of the Client object being saved.

Note: In my experience, the function is run on POST, not live in the browser. Not sure if that is an option to change.

From Docs: http://keystonejs.com/docs/database/#fields-watching

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/cannot-find-ways-to-add-a-custom-button-or-links-in-admin-ui/edit
