### ISSUE TITLE
Erratic behaviour with relationship fields in creation modal

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#1139]
Steps to reproduce: 

1/ create a model with multiple relationship fields with `{initial:true}` and click the "create" button on the model's list page.
2/ select a value for the first relationship field

The dropdowns for the next relationship fields are empty:
![screen shot 2015-03-03 at 11 09 04](https://cloud.githubusercontent.com/assets/436347/6460507/01de79fc-c198-11e4-9a0f-37d24afcca15.png)

However the autocomplete behaviour still works as expected.
![screen shot 2015-03-03 at 11 09 26](https://cloud.githubusercontent.com/assets/436347/6460516/09deab72-c198-11e4-82cc-32c03bd0db0b.png)

The same happens if you first select a value, then remove it. Suddenly the dropdown doesn't show any results any more.

**Comment by webteckie** [comment]
@creynders yeah, have pointed it out before in #940 but good thing you open a specific issue for it as #940 got closed with all other issues fixed with select.

**Comment by drlogout** [comment]
In my case only the second relationship field (the second in the image, the third isn't one) doesn't show it's content, if I click on it. It only works if I type.
And that's because it is focused by default (look at the prompt in the image). After I click somewhere else and than again on the field it's working as expected.

![screen shot 2015-04-22 at 12 56 58](https://cloud.githubusercontent.com/assets/6132191/7272935/2cce6892-e8ef-11e4-9227-551711f69309.png)

**Comment by drlogout** [comment]
I seems as if that's the case for every last relationship field (now all three fields are relationship fields).

![screen shot 2015-04-22 at 13 09 14](https://cloud.githubusercontent.com/assets/6132191/7273120/d11192ac-e8f0-11e4-85c2-f8d075d83b69.png)

**Comment by creynders** [comment]
@drlogout ah, the plot thickens :smile: sounds like it should be easy to fix.

**Comment by wmertens** [comment]
this is fixed in master, no?

**Comment by mxstbr** [comment]
Possibly? Can't remember @wmertens

**Comment by Noviny** [comment]
Just checked this and it appears to be solved. Feel free to reopen if you experience this.
