### ISSUE TITLE
Virtuals with dot do not work

### ISSUE THREAD

**Issue by ttsirkia** [keystonejs/keystone#1157]
If follow the instructions http://mongoosejs.com/docs/guide.html#virtuals how to get the virtuals working, they just won't work.

It seems that if I use the dot notation as in the example, it breaks something and does not work. Without dots everything seems to work. I'm not sure if this is a bug or a feature but at least the docs do not say anything about this. Just spent two hours with this issue...

**Comment by morenoh149** [comment]
@ttsirkia share your code

**Comment by ttsirkia** [comment]
A bit simplified version:

```javascript
Session.add({  
  startTime: { type: Types.Number, initial: true, required: true }
});

// Converts minutes to time string (930 => 15:30)
Session.schema.virtual('startTime.asString').get(function() {
  var hour = Math.floor(this.startTime / 60);
  var min = "0" + this.startTime % 60;  
  return hour + ":" + min.slice(-2);
});
```
After querying sessions, the sessions do not have that virtual. The virtual will appear if I change the name to something that does not have a dot.

**Comment by JohnnyEstilles** [comment]
@ttsirkia, Mongoose is working as expected. Since you provided only the code in which you defined the virtual, but not the code you used to gain access to it, I'm going to have to speculate a bit.

Let's assume for a moment that you queried `Session` as follows:

```js
Session.model.findOne(function(err, doc) {
    console.log(doc.startTime.asString); // <-- will log undefined
    console.log(doc.get('startTime.asString"); // <-- will log startTime as a string
});
```

As you're probably already aware there are two ways you can get the value of path in Mongoose.
You can use dot notation on the document hash directly (i.e. `doc.startTime.asString`), or you can use the `.get()` method, passing a string that corresponds to the name of the path (i.e. `doc.get('startTime.asString')`). The document hash generated for us by Mongoose is just a representation of the structure/values of the model using a Javascript object. This is the key issue here.

Take this plain ole Javascript object, for example:
```js
var obj = {
  num: 1,
  str: 'anything',
  bool: true,
  nested: {
    address: 'somewhere',
    postalcode: '12345'
  }
};
```
and we try to do this:
```js
obj.num.another = 2;
obj.nested.city = 'here';
```
this is what would happen:
```js
console.log(obj.num.another); // <-- will log undefined
console.log(obj.nested.city); // <-- will log 'here'
```

This is basically what is happening in your use case above when Mongoose tries to generate the object representation of your schema. Internally, however, Mongoose uses string representations of every path and allows you to access then using the `.get()`. This is why using `doc.get('startTime.asString')` yields the value computed by your virtual, while `doc.startTime.asString`  just returns undefined.

The example in the Mongoose [getting started](http://mongoosejs.com/docs/guide.html#virtuals) page is different from your use case. It is adding a virtual to `name`, which is a nested value, which in itself contains two simple values (i.e. `name.first` and `name.last`). The virtual `name.full` is simply adding `.full` to the `name` nested value. When creating the document hash `doc.name.full` is a valid path.

This is fundamentally why the Mongoose example works and yours doesn't.

I hope my explanation was't to cryptic.

**Comment by ttsirkia** [comment]
Oh, this is so obvious now! Very nice explanation, thank you very much! I didn't realize that the example worked differently because of the nested datatype. The example in Mongoose docs is not very well chosen. After spending at least two hours, I was sure that there must be a bug somewhere because the virtual appeared out of the box when I removed the dot.

**Comment by JohnnyEstilles** [comment]
You're welcome @ttsirkia! I think the Mongoose example presupposes that the developer is familiar with the concepts I laid out in my explanation above. I'm glad my explanation was helpful.

**Comment by ttsirkia** [comment]
Yep. I just couldn't create a connection between these two things. I thought that there was some magic behind the scenes that could add properties like that. Sometimes the explanations are just too simple...

**Comment by morenoh149** [comment]
@ttsirkia I'm sure the mongoose docs could use some pull requests :)

**Comment by hatzipanis** [comment]
@JohnnyEstilles this is a great explanation and helped me immediately. Cheers!

**Comment by JohnnyEstilles** [comment]
@hatzipanis ... my pleasure! :-)

**Comment by Nahrae** [comment]
This is very helpful for me as well.

**Comment by JohnnyEstilles** [comment]
@Nahrae ... glad to be of service! :-)
