### ISSUE TITLE
Media Repository / File Store

### ISSUE THREAD

**Issue by danielkhan** [keystonejs/keystone#1199]
Using cloudinary is a nice and pragmatic solution but it is quite a vendor lock in.
Are there currently any plans to move all files into a repository like store that also allows the re-use on different places?

I've used MongoDBs GridFS with Scala Play in another project and together with some pre-scaling and some decent file-system caching it was a fine solution.
What are your thoughts about this?

**Comment by morenoh149** [comment]
We'd love to integrate all the cloudinary niceties but it's quite an undertaking and we having other more high-priority tasks we want to address.

You can enable GridFS on your personal project but I would recommend AWS S3 for file storage. GridFS is more for making documents larger than 16mb. It enables mongodb to use disk. If you're just storing photos I highly discourage you using GridFS. FYI mongodb wants to run in ram so that alone will make S3 cheaper for this usecase.
