### ISSUE TITLE
LocalFile format not functional in 0.3.4

### ISSUE THREAD

**Issue by Yinear** [keystonejs/keystone#1218]
Anyone noticed?  Such as a local image do not show a preview anymore.  
Am I the only one have this problem?

**Comment by internetErik** [comment]
I don't think local file ever showed in a preview.  I made a pull request to add this for localfile, azurefiles and s3files, since I'd like it for a project.  I got that working for azurefiles (and probably s3 files), but I needed to get back on the project real quick (which only needs azurefiles support) so didn't finish the pull request.

For localfiles, I was having difficulty understanding how I would get the finished URL so I could display the preview.  Want to work on this with me?

**Comment by typ90** [comment]
@internetErik work for a `File` field to replace `LocalFile`, `S3File`, etc. is going to be underway soon according to @JedWatson - I asked about a PR but since the `File` field will replace most of these, I don't think any PRs that implement the preview will go through until they switch over to a `File` field with an `Image` field based on it.

Anyway since I was working on a similar thing earlier today, I managed to figure out how to preview the `LocalFile` and if it's something you're in a rush to implement you can [check out my fork/branch to see how I got it working.](https://github.com/typ90/keystone/tree/image-preview-localfile)

**Comment by JedWatson** [comment]
I've just created #1222 - let's make sure that field meets our needs so we can stop playing catch-up between the various current file field types. All welcome to help.
