### ISSUE TITLE
How do I add auth of MongoDB for KeyStoneJS?

### ISSUE THREAD

**Issue by SLyHuy** [keystonejs/keystone#1248]
I create a user for admin in MongoDB. How do I add user + pass of MongoDB for KeyStoneJS?
Thanks.

**Comment by morenoh149** [comment]
pass in the extra authentication info with mongoose http://mongoosejs.com/docs/connections.html#options

**Comment by SLyHuy** [comment]
I add options in keystone: "mongo": "<MongoStringConnection>" and it will run. Is it right?

**Comment by janajri** [comment]
@SLyHuy you could also set MONGO_URI environment variable.

**Comment by morenoh149** [comment]
I'm assuming his issue is resolved. Feel free to ask to reopen the issue if this is not the case.

**Comment by ChandanBP** [comment]
Is it possible to connect keystone to existing mongodb collections. I am not using mongoose i.e there is no schema definition. Since my website requires changing model structure I did not go for mongoose, instead used native mongodb native driver for connection and creating entities.

Is is possible to keystone in this environment, if yes how
