### ISSUE TITLE
Keystone 5 deployment strategies

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1257]
As Keystone 5 begins to be used in production applications, we need to ensure the deployment story for a Keystone 5 instance is clear, works well under a number of different scenarios, and covers most use cases.

Here are some possible deployment types and notes on how to deploy a Keystone 5 instance to them.

_NOTE: This is a work in progress and we'll continue to fill out this list as we go_

## Servers

Currently supported directly with the `keystone build && keystone start` commands, it's possible to get a production build up and running quickly.

For more flexibility, we also have [_Custom Servers_](https://v5.keystonejs.com/discussions/custom-server).

#### Heroku

See: _How to deploy Keystone 5 to Heroku_: #1265

#### Stand alone Docker Image

See _How to create a Docker Image for Keystone 5_: #1266

#### Docker Clusters on Kubernetes

_coming soon..._

#### Docker Clusters on AWS ECS

_coming soon..._

## Lambda Functions (aka: Serverless)

Deploying to a serverless environment is not compatible with the current `keystone` CLI tool (or [_Custom Servers_](https://v5.keystonejs.com/discussions/custom-server)), and requires a different approach where each [_app_](https://v5.keystonejs.com/discussions/apps) is split into its own serverless function.

### Lambdas on now.sh

See _How to deploy Keystone 5 to now.sh v2 (serverless)_: #1258

### Lambdas on Apex UP

_coming soon..._

### Lambdas with Netlify Functions

_coming soon..._

### Lambdas with Serverless Framework

_coming soon..._

### Lambdas with Google Cloud Functions

_coming soon..._

### Lambdas on Cloudflare Workers

_coming soon..._

### Lambdas on Azure Functions

_coming soon..._

### Lambdas on AWS Lambda

_coming soon..._

### Lambdas with Claudia

_coming soon..._

**Comment by nathsimpson** [comment]
I have multiple KS5 apps on Heroku. I'm here to help any way I can :)

**Comment by kirillrogovoy** [comment]
Just dropping a note that I couldn't use Keystone on AWS Lambda because `npm i @keystonejs/keystone @keystonejs/fields` create more than 500Mb of node_modules/

The AWS hard limit, as of time of writing, is 250Mb.

The problem is 90% the `fields` package that depends on a lot of front-end stuff (for client-side field rendering), every data adapter and its dependencies, Babel, React, and so on.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.

**Comment by airtonix** [comment]
@bladey @jesstelford so is there a barrel issue to track serverless (cloudflare workers)? 

(yes i get that this ticket started out life talking about ks5, but it's value is in it's declaration of hosting options)

**Comment by dcousens** [comment]
@airtonix did you see https://github.com/keystonejs/keystone/discussions?discussions_q=serverless ?

**Comment by airtonix** [comment]
@dcousens nope, but what specifically am i supposed to be looking at there? 

This is just a discussion list.

I guess what Me (and possibly anyone else) are looking for as we evaluate our options for a CMS is an actionable list of accepted roadmap tasks that would result in a working keystone instance on serverless.
