### ISSUE TITLE
extendAdminMeta adds new items to controller config not adminMeta

### ISSUE THREAD

**Issue by SeanDoyleGit** [keystonejs/keystone#1264]
in `@keystone-alpha/fields`

The `extendAdminMeta` function in a fields `Implementation.js` does not add the new data to `this.adminMeta` in a fields `Controller.js` It instead adds the data to `this.config`

**Comment by MadeByMike** [comment]
@SeanDoyleGit Can you describe this bug a little better for me? There is not enough information for someone to pick this up and work on it. Especially outside the core team.

**Comment by Vultraz** [comment]
Figured out what this meant:
![image](https://user-images.githubusercontent.com/3558659/80898320-a3e65180-8d4d-11ea-859a-a95110d6bfb5.png)

Fields like `format` and `yearRangeFrom` are set in `extendAdminMeta` in the implementation and surface as `field.config` instead of `field.adminMeta`. However, `adminMeta` is just a copy of the same object accessible via `AdminMetaProvider` in the Admin UI, so I don't think this is a huge issue. I want to see if I can remove that copy anyway.

I think this should be closed.

**Comment by gautamsi** [comment]
> I want to see if I can remove that copy anyway.

@Vultraz isn't this already done by you?
