### ISSUE TITLE
Is there any way to fully customize SignUp and SignIn pages on KeystoneJS?

### ISSUE THREAD

**Issue by alexander-tsig** [keystonejs/keystone#1271]

**Comment by JohnnyEstilles** [comment]
@alexander-tsig AFAIK, Keystone doesn't have a sign up per se, but you can easily customize Keystone's sign in and sign out functionality by using the `signin url` and `signout url` configuration options, respectively (see [Database and User Auth Options](http://keystonejs.com/docs/configuration/#options-database)).

You can redirect sign in as follows:
```js
keystone.set('signin url', '/path/to/your/signin');
```

Then add the corresponding route to your `routes/index.js` file (or where ever you keep your routes).
```js
// in our routes.js
app.get('/path/to/your/signin', function(req, res, next) {
   ...
});
```

You can likewise customize where users get redirected upon successful sign in and sign out using `signin redirect` and `signout redirect` respectively.

Hope this helps.

**Comment by Nahrae** [comment]
Thanks for your response. 
What about making the framework more flexible?
For example, RoR is a framework can be customized anything, and the devise gem of the Rails framework to be customized.
I think that this framework has the full possibility to do that, since I also customized something using this framework. e.g. I made the following directory structure while using this framework.

app/
  controllers
  models
  views
config/
lib/
public/
routes/   (Honestly, I would like move this directory as well under the config/ .)
tmp/
...
keystone.js

**Comment by JohnnyEstilles** [comment]
The intention is to make Keystone more "customizable". There's already an open discussion on the subject (see issue #912  [Proposed Keystone Package Architecture](https://github.com/keystonejs/keystone/issues/912)).

> `routes/   (Honestly, I would like move this directory as well under the config/ .)`

There's no reason you can't move it to `config/routes/`, then set the `routes` setting to require from that folder within your Keystone app.

```js
keystone.set('routes', require('./config/routes'));
```

**Comment by creynders** [comment]
Closing this, since I assume the OP's been answered? If not, feel free to reopen.

**Comment by madhavinath** [comment]
routing not working after sign in.
