### ISSUE TITLE
Support database agnostic indexes config

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1297]
Currently, to add an index on a field, the config must be passed to the specific adapter in use:

```javascript
keystone.createList('User', {
  fields: {
    name: { type: Text, mongooseOptions: { index: true } }
  }
});
```

Instead, we should add support along side `isRequired`/`isUnique` for database agnostic indexes:

```javascript
keystone.createList('User', {
  fields: {
    name: { type: Text, isIndexed: true }
  }
});
```

**Comment by molomby** [comment]
I'm adding the `isIndexed` field config and updating all relevant field types to support it in #1405.

* The Mongoose field adapters pass all config though to Mongoose (via `mergeSchemaOptions()`)
* The Knex field adapters are a bit more selective; fields that don't support the `isIndexed` or `isUnique` config will error if it's provided

I'm not super happy about the way `MongooseFieldAdapter.mergeSchemaOptions()` handles indexing.. I suspect it will cause us to accumulate indexes. Ie. if an indexes is added to the code and later removed will it be dropped from the DB?

Also, the current Mongoose field adapters don't do any config validation (they pass the same config though to the DB adapter). The effect will often not be intuitive. For any fields that store subdocuments (`File`, `OEmbed`, etc) the `index` and `unique` config will be ignored by Mongoose. This also allows, for example, creating unique constraints on Checkbox fields.

**Comment by MadeByMike** [comment]
@molomby it seems to me like this one is resolved with `isIndex` ? 

If not passing adapter specific config options seems like a reasonable approach to a difficult problem and gives plenty of flexibility.

**Comment by molomby** [comment]
`isUnique` is supported generically by most field types so, yeah, we can probably close this.

There are some notable exceptions. I most cases this is because the meaning of "unique" for that field type isn't obvious:

* `Checkbox` -- Probably not useful
* `CloudinaryImage` -- Unclear what "unique" means; could be file Id, hash the file or something [more complex](https://scholar.google.com.au/scholar?q=near-duplicate+detection+images&hl=en&as_sdt=0&as_vis=1&oi=scholart)?
* `File` -- Unclear what "unique" means; probably file hash would be best
* `Location` -- Unclear what "unique" means; could be exact street address or maybe lng/lat proximity would be better?
* `OEmbed` -- Should be by URL?
* `Password` -- Would create security flaw
* `Unsplash` -- As per `CloudinaryImage`

If a solution developer did want values in one for these field types to be unique, they could either:

* Just add their own indexes to the DB schema, or..
* Create a separate field to flatten the "unique" bits into (eg. a `Text` field) then set that value with a save hook
