### ISSUE TITLE
Relationship values may be saved with the wrong order

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1362]
Following on from #1359, and @mitchellhamilton's comment regarding this API suggestion from @jesstelford:

```js
return {
  disconnectAll: true,
  connect: ids.map(id => ({ id })),
};
```

> Just tried that and it changes the order of the items which would probably be really confusing for users

Since that API is currently our recommended way of "setting" the value of a relationship field, we should ensure it works as expected and saves the items in the given order

**Comment by MadeByMike** [comment]
Can someone help describe this in terms of impact on users?

**Comment by mitchellhamilton** [comment]
The most direct current example of an impact on users is in the Admin UI when you add an item in a to-many relationship, the select will append the new item on the end of the current items but when it's saved, the items are re-ordered which is confusing. It also applies more generally but that's a really direct example.

**Comment by molomby** [comment]
There's somewhat-stalled/ongoing conversation about the nature of relationships in Keystone and what the Relationship field should take on in terms of scope. There are decisions that haven't been made so the current behaviour is undefined and inconsistent.

Depending on how the adapter decides to store the relationship, there might not be an implicit order -- we only see the effect described above because Mongo uses arrays for many-to-many relationships. The Knex adapter uses an adjacency table which (effectively) has no implicit order.

A related topic is duplicates. Can an item A be related to item B more than once via the same "field"? This and order can be thought of as whether the Relationship field type wants to conceptualise related items as a set or a list (in terms of abstract data types).

Then there's talk of adding properties to a relationship.. if the relationship between two items "stores" an order/position, why can't I add other fields to it? This would be super handy but, at some point, you get beyond what the Relationship type itself should tackle.

> we should ensure it works as expected and saves the items in the given order

Personally, I think the relationship field should not guarantee order and (generally) should treat related items like a set. This is the most common case (in my exp.) while also being the simplest to implement and fastest across DB adapters. Other functionality can be build on top of this and/or added to the Relationship field later.

**Comment by MadeByMike** [comment]
Feels like a valid issue from a user perspective - although I understand the distinction around concerns from a db\technical perspective as well.

**Comment by willmatos** [comment]
Have any decisions been made on this? I have a scenario where I am trying to create a Playlist. In this scenario the order is everything.

**Comment by mwcz** [comment]
This is pretty important to me too.  I have a similar requirement to @willmatos.  Relationships would be by far the best way to define a dynamic-length list of ordered items.

**Comment by molomby** [comment]
Reiterating [earlier comments](https://github.com/keystonejs/keystone/issues/1362#issuecomment-519381778) – relationships in KS don't intentionally store the order in which items are attached. As such the order of related items returned in a query is undefined (unless, of course, a sort is specified in the query). This is by design and true for all cardinalities (ie. many-to-many, one-to-many).

**Comment by alexanderlperez** [comment]
@molomby it's possible to retrieve the order of items set in the field from, say, Postgres by appending the "orderby <the relationship table>.id ASC" in an actual query.  That's what I did while exploring the possibilities of getting this to work within the existing Keystone framework.  

Making that happen, though, is still an outstanding question.  Is that possible?

**Comment by jhohlfeld** [comment]
Hi, I landed at this issue after initially setting up keystone and going through the getting started tutorial. After some instant success I am now stuck on exactly this issue.

This thread (https://stackoverflow.com/questions/66034621/keystonejs-user-defined-order-for-relationship) talks about using another intermediate list: make a list to describe the sorting order of the relation between two other lists (many to many). This however feels awkward and I would like to ask if this is still the only way to get sorting order within relationships?

I would prefer not to add a hook or some hacky SQL to reach my goal.

**Comment by GraySmith00** [comment]
I also am facing this issue. I have Pages and Sections models that have a many-to-many relationship, but the user should be able to provide the order for the Sections on the Pages. This can be done in Drupal and in Strapi via drag-and-drop using dynamic zone, so I'm hoping this gets added to Keystone as well.
