### ISSUE TITLE
Add exact API for setting the value of relationship fields

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1363]
We discussed this before (I think in person) but currently, when you want to "set" the value of a relationship field to a specific array of IDs (i.e how the Admin UI works, based on the value of the relationship select field) our recommended API is this:

```js
{
  disconnectAll: true,
  connect: ids.map(id => ({ id })),
}
```

I'm of the opinion we should introduce a new option called `value` or `exact` or `set` or `ensure` or something, which basically says: "this is the array of values that should exist".

If that key is provided, keystone would internally ensure that included ids are _present_ in the stored value, and any ids _not present_ are removed. For database adapters that support ordered relationship values, we would also ensure the values are stored in the correct value.

While I think this provides a _more explicit_ API, I think it's also important for relational databases where disconnecting and connecting items results in an insert/delete from the relation table.

At the moment, the current API would (or at least implies it should) _remove_ all the existing records, then insert new ones, which would be a fair bit of unnecessary database churn every time a relationship field is saved. There's no reason to rewrite the values, so I think adding this new API is a better approach and allows the intention of the operation to be more explicit.

If it's provided along with any other instructions to `disconnect` or `connect`, we should throw a validation error from GraphQL

**Comment by gautamsi** [comment]
should we have this taken care transparently in case things comes as plain. like if there are only re setting the 1:1 value, instead of {connect ....} we simply send this as `field = value`, value being the id of relationship object or full relationship object with an `id` field. this was it is very simple dev flow rather than complexity of each time the connect disconnect stuff
for one to many it may also be fine to pass on array with id or array of object with id.  Would be helpful in many workflow requiring back end call to graphql mutations.

**Comment by MadeByMike** [comment]
@JedWatson can you please review this. Has thinking evolved further on this one? I know we've had a lot of discussions on the initialData/seeding/createItems and relationships is any of that captured here?
