### ISSUE TITLE
Consistent Lat/Lng display

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1367]
As raised in #1365

Our `Location` field displays lat / lng pairs in the GeoJSON / MongoDB format: `[lng/lat]`. The `Geopoint` flips this and displays it in the more familiar order, `[lat/lng]`.

We need to make this consistent across the system. Considerations:

* at this point I'm not sure it would be a great idea to change Location as it may be confusing for users who don't notice the label change.
* it's probably a good idea to present the data in the same order it is stored, which is `lng/lat`
* everywhere I remember seeing the pair surfaced in a UI or in other conventions, I think it's presented `lat/lng` so it might be better to be consistent with that
* other places people are familiar with working with lat/lng (google maps, etc) it's `lat/lng`

Would appreciate feedback on this before we make a change, I'd like to get this updated for the next release (scheduled for this week).

**Comment by morenoh149** [comment]
I think it doesn't matter as long as it's consistent and documented. That being said I'd vote for the more conventional ordering. The fact that Mongo stores in a particular order should be an implementation detail.

**Comment by WingedToaster** [comment]
Regardless of what is decided, I agree the format should be consistent between the GeoPoint field and the Location field.

I feel strongly that the display should be the in the ubiquitous Lat / Lng format. An end user and/or client (non-programmer) isn't going to know or care that the data is stored in the database in GeoJSON format. Leaving it in the Lng / Lat format will make it more prone to user error and confusion since it is not in the format that is commonly used, even if the field is clearly labeled. I could see some users thinking the field was mislabeled and enter it in Lat / Lng anyways. Additionally, exporting the data for import somewhere else could cause problems if the other system expects the format in LatLng.

Also, just as an example, coming from the native app space, all the API calls for setting up a coordinate on a map always list Latitiude first when instantiating a coordinate, even if the Map API supports GeoJSON.

iOS: <a href="https://developer.apple.com/library/ios//documentation/CoreLocation/Reference/CoreLocationDataTypesRef/index.html#//apple_ref/c/tdef/CLLocationCoordinate2D">CLLocationCoordinate2D</a>

Android: <a href="http://developer.android.com/reference/com/google/android/gms/maps/model/LatLng.html">LatLng</a>

**Comment by morenoh149** [comment]
@WingedToaster I like your reasonings

**Comment by JedWatson** [comment]
@jossmac let's fix this in the Elemental rebuild

**Comment by webteckie** [comment]
I prefer that however I put it in it comes out.  It is very surprising to see how it gets flipped and you don't notice it unless you know about the issue or are paying close attention.  btw, this was opened a while back :-)

**Comment by mxstbr** [comment]
I think this is fixed, so I'll close this. Let me know if that's not the case!

**Comment by molomby** [comment]
Old issue but I'll add my 2c.

The [ISO 6709 standard](https://en.wikipedia.org/wiki/ISO_6709) states that "latitude comes before longitude". User interfaces should comply with this.

It's annoying that many tools in this space (Google API, Mongo, etc) flip these but we basically have to go with what the DB wants (lng,lat) so that other tools can work with the data. 

But why don't the `Location` and `Geopoint` types should surface both "orderings" as properties?
 Ie.. `latlng` and `lnglat` properties, replacing the existing `geo` property on locations. Individual `lat` and `lng` properties should probably also be available. 

This would make it a lot less confusing when working with coordinates in the app; developers will need to make an explicit ordering choice when working with the values.
