### ISSUE TITLE
Should we migrate to TypeScript?

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1373]
**Pros**

- TypeScript's strict types can catch a small percentage of type-related bugs
- Code navigation tooling is very mature, especially in VSCode

**Cons**

- Requires a separate compile step (but can integrate nicely with Babel)
- There is [a cost to adding TypeScript](https://medium.com/javascript-scene/the-typescript-tax-132ff4cb175b).
- All core developers have to learn a new language (TypeScript)
- There are a lot of [issues](https://mobile.twitter.com/phaser_/status/1126547233162387456) [with](https://mobile.twitter.com/mpjme/status/1135660290048217094) [TypeScript](https://mobile.twitter.com/sebmck/status/1145919537071525889).
- Opting out of TypeScript can be very hard

**Let's vote!**

Click 👍 or 👎 on this issue to cast your vote for migrating to TypeScript

**Comment by gautamsi** [comment]
[Why TypeScript is the best way to write Front-end in 2019](https://medium.com/@jtomaszewski/why-typescript-is-the-best-way-to-write-front-end-in-2019-feb855f9b164)

Some more encouragement for using TypeScript (especially when you have trouble):

* you can ignore certain errors with `// @ts-ignore`  [in `.ts` files](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments)
* You do not have to invest in _**all or nothing**_ approach when moving to TypeScript, [you can roll gradually](https://gist.github.com/OliverJAsh/13b5410843d6bee692927897f0c84197#how-we-gradually-migrated-to-typescript-at-unsplash). 
* You dont have to convert the code to use TypeScript, it can statically check `.js` files and infer types. with jsdoc in place (properly) it will be even more useful. (VS Code features)

It does integrate well with [Babel 7
](https://babeljs.io/docs/en/babel-preset-typescript)

a two part blog from MS on how to smoothly migrate to Typescript: 
[How to Upgrade to TypeScript Without Anybody Noticing](https://devblogs.microsoft.com/typescript/how-to-upgrade-to-typescript-without-anybody-noticing-part-1/)


On Opting out:  You can be careful when you start and use it in least invasive manner, when you have more confidence you can abandon the idea of opting out :) 

* TypeScript is just a compiler, you can get raw JS out of it and be done with TypeScript. the raw JS may be ugly but with `esnext` config in compiler you can get very clean code from TypeScript. 
* Babel plugin for typescript is very fast, someone can easily write a plugin to get pure JavaScript out of Babel transpilation step (there is nothing yet, but some work in progress)

**Comment by jesstelford** [comment]
Thanks for the links and thoughtful pointers!

> you can ignore certain errors with // @ts-ignore in .ts files

Have you seen any issues where [`ts-ignore` is itself ignored in consuming projects](https://mobile.twitter.com/200ok/status/1148048122821541888)?

**Comment by gautamsi** [comment]
> Have you seen any issues where ts-ignore is itself ignored in consuming projects?

Workarounds are for tricky situations not for monkey patching everything :)
Excessive use of workaround is expected to break things.

**Comment by JedWatson** [comment]
Just throwing another data point in the ring, next@9 just added native support for typescript (including for API Routes). Given the popularity of Next and how nice they've made the DX of using TS with it, I wouldn't be surprised if this adds velocity to TS adoption.

The Next team also had good things to say about it in their [v9 announcement](https://nextjs.org/blog/next-9):

> Over the past few months we’ve migrated most of the codebase to TypeScript, this has not only reinforced our code quality, it also allows us to provide types for all core modules.

I'm _generally_ in favour if we can make the DX smooth as butter in Keystone (and Keystone powered projects; would be interesting to see how this interacts with Next's support when you're using our `next-app` integration).

I think there are a lot of implicit APIs in Keystone that types would add a valuable level of clarity to; and there are [tools out there](https://github.com/atlassian/extract-react-types) our friends at Thinkmill and Atlassian are working on to automatically generate docs from types which could be a huge improvement to where we are now (most of our package APIs are undocumented at the moment) 

However as per Jess's set of cons, when static type systems go bad they can go really bad and create frustration / waste a lot of time. So I think a prerequisite for moving to TS would be having someone who's committed to owning TS Support; available to up-skill current team members, and help support contributors / review PRs for correct TS usage / etc.

Without a high level of commitment to it, I can easily introducing TS doing more harm than good.

---

On a separate note; we currently have ad-hoc Flow usage in the client-side code for the Admin UI. My impression is that hasn't been a net win. So I'd be inclined to remove that as a first step, and our UI Library could be a good / isolated place to experiment with incremental adoption of TS before we commit to using it for other modules & back-end code as well.

**Comment by gautamsi** [comment]
I can own the TypeScript first steps
* starting to add it as passive player like the Flow use so far (using `checkJs: true` compiler flag). once that makes any sense, we can move further.

**Comment by jesstelford** [comment]
I resonate strongly with the point of [this tweet](https://twitter.com/jordwalke/status/1149611805943062529?s=20):

> Type annotations can be helpful when prototyping, but usually writing type annotations just kills your productivity/workflow. Total static typing doesn't mean you have to write this stuff out! Languages with full inference means annotate as much as you want.

Unfortunately I've heard too many times that Typescript's inference isn't very great, so it's often an all-or-nothing option, resulting in wasted time fighting a type system when that level of "safety" (whether real or not) isn't needed.

**Comment by gautamsi** [comment]
Well, different people different opinions. To see the usefulness you have to try yourself. If you search twitter, you can find 100s of kudos, big open source projects benefitted from TypeScript. Even the library which inspired most of this repository styles/patterns (nextjs) moved to TypeScript.

Most negativity about TypeScript is type annotation in general (and for solo developers), most kudos are for code quality, maintainability and being helpful in team environments. You got to choose which one makes sense for you and the project.

I think the benefits outweigh the demarits. When we move towards extension based approach, it will be extremely helpful to use TypeScript to publish the api contracts. Documentation generation is one other benefit. 

At this point developers would not be using Keystone codebase to create their project like early days, most packages are published frequently and they are free to use it with vanilla or TypeScript projects. Even vanilla js projects can get benefits from TypeScript annotation.

I see thay having more TypeScript discussion is not leading anywhere. We should be more focused in gaining community momentum otherwise this will again fell off people radar like v4. 

One problem Keystone project might face is the way lists are being configured and named, renaming the list would not guarantee the rename of name in `createList`, as this is being string.

**Comment by jesstelford** [comment]
Having worked in typed languages in the past, [this tweet](https://twitter.com/_brotzky/status/1150130324090658816) resonates really well with me:

![Screenshot_20190714-182934](https://user-images.githubusercontent.com/612020/61181154-ac7c6880-a611-11e9-893c-05a43fc280e2.png)

**Comment by gautamsi** [comment]
I did have few moments like this when I could not figure out few things, you learn to avoid obstacle and move on. you certainly do not get to "stop coding forever" frustration in JUST 3 HOURS. May be I am still in learning mode.

I had similar 3 hr moment when I was using keystone (v4) for the first time, had I stopped using it, I would not be here. 

I converted Keystone and the generator (v4 beta 7) to TypeScript, took few days, but never had such frustrating moment with TypeScript (despite so much es5-es6 conversion issues) and I still don't consider myself a seasoned developer yet.

I don't have anything to say any further about this, not in an endeavour to try fix every frustration everyone has with TypeScript, not paid by Microsoft to promote this.

**Comment by Wiltel492018** [comment]
Typescript... Great start. Gitter Done!!!
WiltelGithub
Wiltel49@gmail.com
AAS WTI MICHIGAN

**Comment by 1337cookie** [comment]
Will this mean building a project using Keystone will be done using TypeScript or just the Keystone codebase?
I love being verbose when I can but sometimes I like to just write ugly code that works that I can refine later.

**Comment by MadeByMike** [comment]
I think we should be careful about creating a barrier to entry, both for users and contributors. 

@jesstelford Can we describe a problem that we are having now that TypeScript would solve for us?

**Comment by gautamsi** [comment]
@1337cookie just the keystone code base would use TypeScript if this is accepted. Switching to TypeScript in Keystone code base does not mean everyone has to start using TypeScript to consume the project. for example nextjs is in TypeScript now but you can use it in your TypeSceript or vanilla JS project, its your choice.

**Comment by Wiltel492018** [comment]
Typescript is a great Language Instruments to assist your other Code.
JavaScript. Maybe other's.
WiltelGithub
AAS WTI MICHIGAN
Wiltel49@gmail.com

**Comment by jesstelford** [comment]
An interesting video from AirBnB's @brieb talking on how & why AirBnB migrated to Typescript: https://youtu.be/P-J9Eg7hJwE

Of particular interest are their look back at retrospectives and how many bugs could have been prevented thanks to types, and their automated tooling for the conversation.

**Comment by gautamsi** [comment]
I have created this PR https://github.com/keystonejs/keystone-5/pull/1454 for inputs. This showcases how easy it is to adapt to TypeScript. This one is first attempt with all in approach as mentioned in the video in https://github.com/keystonejs/keystone-5/issues/1373#issuecomment-515719655. This does have some errors which is caught by Typing system even when there is not much done for type checking yet. 

I also think with Type checking and proper publishing of type definitions, it will be helpful in enabling new scenarios like passing Field Type instance instead of configuration object in List. this can enable more complex field types for list.

**Comment by dcousens** [comment]
@jesstelford to sum up,  is the primary concern the "tax" of introducing typescript?
For me,  I wouldn't care if the codebase was written in typescript or not,  but I would care if type inference struggled when using the Keystone modules _in_ a typescript environment.

**Comment by w01fgang** [comment]
Statistically, static typing doesn't prevent all bugs. Moreover, most strict programming languages have more issues tagged with 'bug' label. [source](https://medium.com/javascript-scene/the-shocking-secret-about-static-types-514d39bf30a3)
Yes. Adding static types to any vanilla JS project decreases bug density, that's a fact. And it introduces new types of bugs: "bugs in type definitions" which is more difficult to find.
In our company, we widely use Flow for static typing. It does not force to write typed code, and you can always add types later. Also, react-relay generates Flow types with relay-compiler, which is quite handy.
Having Flow could be helpful, and yet developers who are not familiar with static typing in JS still can contribute to the project skipping on types.
In my development experience, I agree with @jesstelford. If you need to put `any` because TS doesn't compile the code that you know that 100% works (tests), there is no benefit in switching from vanilla JS.

**Comment by w01fgang** [comment]
@gautamsi how many bugs did you found by adding TS in your PR #1454?
I saw many `Object`, `Function`, and `*` in Flow definitions, which is an alias of `any`.
If we use `any` as a type, there is no sense to use static typing. Maybe we can fix Flow types that we already have before making conclusions that it wasn't helpful? Because if we add TS with the same approach, we'll introduce complexity.

**Comment by gautamsi** [comment]
@w01fgang the branch used all in approach with TS and I could spot several issues which could be prevented by properly typing. I did not add all the Types yet. Most of the issues are that function signature has changed but still passing wrong argument. Some cases the property is being accessed is not defined or not in the original class and may have been added by some other method.

TypeScript is not immune from bugs or having quirky situation where you don't have any other option than `any` or `@ts-ignore`. that said, if you face so much of this, then something is wrong in the approach or probably the Typing is not going to help. in any case how do you know without trying ?

**Comment by w01fgang** [comment]
that's right, static typing, in general, is not immune from bugs
if we want to add TypeScript to prevent bugs, that's not the case.
Of course, adding types can help to find bugs, and it can be done by adding tests as well.
To provide a better development experience for people who use Keystone we can add type definitions in *.d.ts files or DefinitelyTyped, right @gautamsi.

**Comment by MadeByMike** [comment]
Can we try and focus this on the pros/cons for TS in Keystone and not general debate around whether or not we like static types in JavaScript.


What I've got so far:

| Pros | Cons |
| ------------- | ------------- |
| Static Typing (obviously)  | May deter new contributors |
| Less bugs  | Slower builds and tests |
| Easier resolution of many bugs  | Slower development time |
| Investment may pay off as project gets larger  | Investment in converting |

I think this list is pretty "static" but we can add to it if needed. I think we all understand these pros and cons but keep debating the amount/significance of each. Instead let's focus on:

## Other things to consider

- Some packages will not benefit much from this and because features in Keystone are made up of (usually) small packages. In theory it should be easy to isolate and test each of these without TypeScript
- Exceptions to this are the Admin UI, Relationships and core features like Lists. These probably have the most to gain from using TypeScript. 
- TS might not do much to help with  bugs related to interoperability between packages.
- Thing are moving pretty well at the moment. I'm not seeing any sings of pressure or consistency in bugs that is telling me that a move to TypeScript now would see any immediate benefit. 

(I think this last point is  pretty important. I don't want to invest in this until I can say yes, it will solve a problem we are having right now.)

**Comment by 1337cookie** [comment]
Autocomplete and inline docs when editing are quite big pros for keystone consumers. Easy for me to be pro TypeScript when I'm not writing the thing 😄.  An implementation using *.d.ts or Definitely Typed seems like It would reduce many of the cons, most importantly the potential cost to development speed, contributor adoption and ability to opt out of TypeScript later if necessary.

**Comment by jesstelford** [comment]
@1337cookie brings up a good point; there are two different ways we could implement TypeScript:

1. Write all Keystone 5 code in TypeScript
2. Supply type definitions for all of Keystone 5's exposed APIs

#2 would certainly be easier to implement and maintain while also providing the biggest ROI for the KS5 core team 🤔

**Comment by dcousens** [comment]
@gautamsi I disagree, please don't litter the code with JSDoc

**Comment by gautamsi** [comment]
@dcousens there is no other option, if we dont want to covert code to TypeScript and still want to use the  typings in consuming projects, only two options are there'

1. hand code the typing - lengthy and chances of lot of human errors. (probably generate it once using other tools and then hand code rest as there is no type inference in most cases)

2. use JSDoc comments (useful for documentation as well) and TypeScript features which would automatically generate all the typings.

I certainly would not volunteer for number 1.

**Comment by thekevinbrown** [comment]
I'm in favour of using Typescript for Keystone.

It saves me hours hunting down silly things like typos and expecting the wrong shape as a function parameter which are instantly highlighted when using Typescript but only reveal themselves at runtime otherwise.

**Comment by gautamsi** [comment]
this is good read on how to use typescript without typescript https://medium.com/@martin_hotell/build-100-type-safe-react-apps-in-vanilla-javascript-bd29a8364078

**Comment by gautamsi** [comment]
now that #2028 is now going to land soon, should we provide any guideline to add typescript, at least in the form of comments based typing.

**Comment by gautamsi** [comment]
another big move (Yarn pkg) from Flow to TypeScript - https://hub.packtpub.com/yarn-releases-a-roadmap-for-yarn-v2-and-beyond-moves-from-flow-to-typescript/

should we now? (re-inforcing the subject 😄 )

> Keystone repo is already moved away from Flow although there may be some remnant

**Comment by w01fgang** [comment]
@gautamsi thanks for pointing it out, an excellent example of how migration to TS impacts the number of contributors.
The development of Yarn on TypeScript started a year and a half ago and still have 60 contributors vs. 507 contributors on Yarn on pure JS. 😞
TypeScript, it's not a silver bullet. People are pushing it like a religion, and still, they use `any` everywhere, which destroys the main reason for using types and creates a false sense of safety. If you have at least one `any` in your codebase, you are not safe.
And still, I think having type definition on DefinitelyTyped it's a great idea, @thekevinbrown thank you for that.

**Comment by gautamsi** [comment]
@w01fgang I don't understand the reasoning of impact in number of contributors here (yarn) !!!

Yarn (js) has been used for over 4 years (or even 8 years if you see npm version history). it has overtaken npm long ago, people at some point used npm only to install yarn and forget that there was any npm in there system 😄 .

you are comparing that to the rewrite effort happened probably in closed group over last one year. The very first release is not even public (only 2 RC so far) as yarn@latest is still pointing to v1. They have just switched the main website to v2 and probably going to release first v2 release before end of month. they are just getting started. 

more points for fair comparison

|   	|   Yarn (JS)	|  Berry (Yarn TypeScript) 	|
|---	|---	|---	|
|   age	|   4 years	|   1 year 	|
|   first release	|   0.15 was released 3 years ago, (0.1 ~8 years ago)	|  9 days ago (still RC) 	|
|   Star	|   37K	| 1.5k  	|
|   fork |   2.9K	|   129	|
|   contributors > 10 commit	|   21	|   7	|
|   contributors >= 5 commit	|   40	|   10	|

we have to wait few month and see how it progress just like Keystone took off only after made public and renaming of repo from keystone-5 to keystone.

Now compare this scenario with Angular in pure JS over 8 years they had only 1576 contributors, while in 4 years the TypeScript base of Angular >= 2.0 has attracted 1079 contributors.

Compare this to Atom (pure JS, 436 contributors) vs VSCode (pure TypeScript, 1063 contributors), Atom which started this editor and later vscode evolved on top of electron (or atom shell) now has more contributors so with this logic TypeScript is better, right?

I strongly believe people contribute based on what they use, love to use and what they want to see in the thing they use. And at last they keep contributing if that contribution is welcomed. as soon as the repository has many stale PR the number of new contributors drop drastically. There may be some % of people who do not contribute if that is TypeScript and some stay away if there is no TypeScript.

> If you have at least one `any` in your codebase, you are not safe.

no one is claiming TypeScript as silver bullet, that is why you have to deal with quirky situation and bugs (future feature) and have `any` in codebase (probably many `any`). Only thing is that some people always find the glass "half Empty" and not "half Full"

if you compare similarly to Keystone back in 0.3/0.4 and now you will find that after being open for more than 6 month it had only gained 1.5k stars that too after renaming to `keystone` from `keystone-5` earlier it was <100 stars before rename, I guess similar things will happen when `berry` is renamed to `yarn`.

A note on contributors, anyone fixing a spelling mistake and removing/adding a `,` becomes a contributor. TypeScript does not come in the way of those contributors. 

DefinitelyTyped became popular when TypeScript did not have good way to use the package.json for loading types, it came as replacement to TSD. Major quirk is that if contributors are not updating the definition regularly, over the period it becomes stale and bloats the codebase with even more `any`.

**Comment by stefanpl** [comment]
> […] and some stay away if there is no TypeScript.

Just here to say that I'm one of those.
Evaluating different framework options for an app migration, plain JS is a clear no-no.
