### ISSUE TITLE
Add currency code to Money field

### ISSUE THREAD

**Issue by mcauser** [keystonejs/keystone#138]
Add 3 letter ISO 3166-1 or 4217 country codes to Money fields.
http://www.xe.com/iso4217.php

eg.

    price: { value: 29.95, currency: 'AUD' }

You could limit the available currencies by providing a whitelist in the model.

    price: { type: Types.Money, currency: ['AUD', 'USD'] },

If you wanted to get fancy, you could add symbols too.
http://www.xe.com/symbols.php

**Comment by wmertens** [comment]
So the options are:
* Break the API starting with 0.4, make Types.Money be an object and provide a default updater script that will automatically convert all Types.Money Number fields to Objects.
* Have the field be stored as a Number or and Object depending on the contents. 

Since in most cases the currency will be the default currency, the second option seems to be the best one, and it is also backwards compatible.

Is it not possible with Mongoose to do this?

**Comment by mxstbr** [comment]
I don't think the second option is a good idea, from a newcomers perspective to the codebase we have too many lets-not-break-this-now temporary solutions already that mess up our code.

Lets leave this as-is for the 0.4 release, and then do a big breaking update for 0.5?

**Comment by wmertens** [comment]
The idea is that the second option is backwards compatible and more
space-efficient to store in the common case…

On Sat, Mar 26, 2016, 11:47 PM Max Stoiber <notifications@github.com> wrote:

> I don't think the second option is a good idea, from a newcomers
> perspective to the codebase we have too many lets-not-break-this-now
> temporary solutions already that mess up our code.
>
> Lets leave this as-is for the 0.4 release, and then do a big breaking
> update for 0.5?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/issues/138#issuecomment-201945062>
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/add-currency-code-to-money-field)!
