### ISSUE TITLE
KeystoneJS.com running old version

### ISSUE THREAD

**Issue by milosdakic** [keystonejs/keystone#1385]
http://keystonejs.com/ is showing current version as 0.3.5.

**Comment by morenoh149** [comment]
Running edge on the main site isn't a priority. As long as we test major version bumps sufficiently using things like https://github.com/JedWatson/keystone-demo I think we're fine.

**Comment by milosdakic** [comment]
Isn't 0.3.8 a stable release?

**Comment by morenoh149** [comment]
Misspoke. I meant latest version (stable or otherwise).

**Comment by JedWatson** [comment]
That's actually my bad, I didn't push a docs rebuild (partly because it's a painful process)

FWIW that is just a generated value in the source code; keystonejs.com is actually running on github pages and not Keystone.

I'll update the site when I push the next version (probably later today, preparing it now)

Will be much easier when we separate the docs site, I'll implement a build process to automate the gh-pages rebuild + push.

**Comment by JedWatson** [comment]
Fixed
