### ISSUE TITLE
Feature request: Build bundle once.

### ISSUE THREAD

**Issue by BerkeleyTrue** [keystonejs/keystone#1421]
I have noticed a stark decrease in the response and performance of the admin panel. Time to load a page is incredibly slow happens on every page transition. 

It would be awesome to give the user the option have the admin bundled together on build or start and have everything bundled together.

**Comment by JedWatson** [comment]
@BerkeleyTrue are you using the latest version? Because (except when the `KEYSTONE_DEV=true` environment variable is set) the bundle _is_ cached, and is not even watched for changes between process starts.

Also, the bundle is always built immediately when Keystone starts.

The bundle is _not_ cached between process restarts, so the first request takes a few seconds while it builds, this may be something we can optimise in the future.

If you are still using 0.3.8, this was an issue in that release and part of the reason for the rewrite of our Browserify integration.

**Comment by BerkeleyTrue** [comment]
Yeah latest version seems to work a lot better. It's still a pain going between pages, especially when bandwidth is slow. I am guessing there is a roadmap somewhere make the admin panel into a SPA?

**Comment by JedWatson** [comment]
@BerkeleyTrue sure is, 0.4 will release this. Check out the `elemental-integration` branch for a preview (of progress, SPA changes won't land until everything is reactified)
