### ISSUE TITLE
Create a create-items package 📦

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#144]
Following on from #138

We've now got a lot of code in core for creating items, which seems like a distinct concern.

I'm wondering if we should split it out into its own package:

```
import { createItems } from `@keystonejs/create-items`;

createItems(keystone, {
  User: [{ name: 'Jess Telford' }],
});
```

Might make something like a `ref` export (see #143) make more sense too - feels weird having something so specific exported from `@keystonejs/core`.

Not 100% sure this is worthwhile, given the main reason for splitting packages is usually either:

* It's some nontrivial amount of functionality that users should opt into rather than have bundled, or
* We might want to version it separately (how implicitly coupled to Keystone's API is this?)

... alternatively, @jesstelford did you have other plans for the `relationship-utils` that would see them better colocated in core long term?

**Comment by MadeByMike** [comment]
I've closed a bunch of other issues related to createItems because the direction for this should now be focused either on using `executeQuery` or a possible migration framework/pattern: https://github.com/keystonejs/keystone/discussions/299

Leaving this issue open as it might be the correct path for future deprecation of create items.
