### ISSUE TITLE
Memory usage in production

### ISSUE THREAD

**Issue by AntonioFernandezFernandez** [keystonejs/keystone#1466]
Keystone memory usage in production is too much higher. It started at 200 Mb and raise to 300-400 Mb hitting 5-10 urls. ¿Is this normal?.

My current installation:
keystonejs version 0.3.11
node.js version 0.12.3
ubuntu 14.04

I currently set mongodb as session storage and NODE_ENV variable to "production"

**Comment by lojack** [comment]
Sounds normal to me. NodeJS will fill memory to fit the space allowed and has multiple levels of garbage collection it'll run when running low on memory. I have a medium sized site that takes up around 800MB of memory once started. Stays at that level even when under high load.

It also isn't the worst idea to periodically restart node since memory leaks do happen. I haven't had any issues with this, but I know its fairly standard practice. If performance becomes a big concern, I'd definitely suggest adding a caching server in front of your Keystone installation. Keystone+Nginx are a really good combination for this.

**Comment by morenoh149** [comment]
+1 nginx. Recently read [this](http://nginx.com/blog/inside-nginx-how-we-designed-for-performance-scale/) article. Plus you get zero-downtime upgrades.

**Comment by gmmeyer** [comment]
You can also do the same thing with systemd.
