### ISSUE TITLE
Relationship items expected be an array of strings, not Mongo's ObjectIds

### ISSUE THREAD

**Issue by thiagodebastos** [keystonejs/keystone#1499]
In the `afterChange` hook, I was comparing `updatedItem.id` with the array of ids of related items.
The array of ids of `Relationship` items is an array of Mongo `ObjectId`s while `updatedItem.id` is a string.

This can yield unexpected results, like the `currentItem.id` never being found in an array of related item's ids.

Example code (I've removed anything unrelated):
```js
keystone.createList('SkillNode', {
  fields: {
    id: MongoId.primaryKeyDefaults.mongoose.getConfig(),
    parents: {
      type: Relationship,
      ref: 'SkillNode.children'
    }, 
    children: {
      type: Relationship,
      ref: 'SkillNode.parents',
      many: true
    },
  },
  hooks: {
    afterChange: ({ updatedItem }) => {

      const { children, existingItem, id } = updatedItem

      console.log(children.findIndex(el => {
        return el === id                         // false
      }))

      console.log(children.findIndex(el => {
        console.log(typeof el, typeof id)        // object string
        console.log(Object.keys(el))             // [ '_bsontype', 'id' ]
        return el.toString() === id.toString()   // true
      }))
      return updatedItem
    }
  }
});
````

**Comment by singhArmani** [comment]
@MadeByMike : I was trying to reproduce this issue by creating list as mentioned above. But this causes admin UI to freeze the moment you hit the **create** button to insert a new list data. Need more clarification on this.

**Comment by bladey** [comment]
Hi @thiagodebastos and @singhArmani,

In an effort to maintain the KeystoneJS project going forward, we're closing issues related to [Keystone 5](https://github.com/keystonejs/keystone-5) to make way for the next version called [Keystone Next](https://next.keystonejs.com).

The existing **Keystone 5** codebase has been moved to [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) which is now in a 6-12 month active maintenance phase.

You can learn more about the next version which we’re calling **Keystone Next**, which is now [in preview](https://next.keystonejs.com).

If you feel this issue is still relevant and require assistance, please open a new issue in the [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) repository.

Thank you for your continued support as we push towards this next major new version of KeystoneJS!
