### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by jdarling** [keystonejs/keystone#150]
Ok, we have CSV Export and Download, how about CSV Import?  I'm working on a rewrite of a small local website and am using Keystone for the project.  Thing is, we literally have 1000's of contacts already in our DB and I'll have to migrate them.  To that avail it would be nice if there were an option to import CSV files into the DB.

I know I can one time them through scripts, but every time we do a show we get more contacts and they get put into a spreadsheet then sent to me to put into the website for mailings.  Would be cool if I could just tell them to go import the list each time :)

**Comment by frederik** [comment]
Workaround: I ended up with an import model that takes a model type and an attachment + a save hook that started the file processing (in the background, updating a log field in the import model after the import had finished). This works out nicely because I now get a history of all uploads to the data - an import functionality would still be great.

**Comment by morenoh149** [comment]
@frederik nice work on solving it :+1: Does keystone need to change anything to make this easier?

**Comment by frederik** [comment]
I feel that adding a generic CSV Upload button next to the Download should be the way to go long term. However, this is not as easy as it first appears because once you have relationships in your model you need to work with keys to have a meaningful upload.

A plugin system that could provide a custom upload button for models (so I don't have to use a pre.save hook) would be something worth exploring imho. I haven't followed any efforts related to that though - so maybe that's possible already.

**Comment by xianlin** [comment]
I have made some codes on adding CSV upload button and logic at here: (still need to improve/customize though)
https://github.com/keystonejs/keystone/issues/1434

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/post/keystonejs/csv-import)!
