### ISSUE TITLE
Yeoman generated Keystone Project fails to install on OpenShift for missing gyp dependency

### ISSUE THREAD

**Issue by niravshah** [keystonejs/keystone#1521]
Hi All, 

I generated a new Keystone project using the Yeoman generator and pushed it to my NodeJs, Mongo OpenShift box. The build fails with a missing gyp error. Full error trace below. Would appreciate any pointer on how to solve this.

ImportError: No module named gyp

Thanks!
Nirav

remote: Traceback (most recent call last):
remote: File "/opt/rh/v8314/root/usr/bin/gyp", line 15, in 
remote: import gyp
remote: ImportError: No module named gyp
remote: gyp ERR! configure error
remote: gyp ERR! stack Error: gyp failed with exit code: 1
remote: gyp ERR! stack at ChildProcess.onCpExit (/opt/rh/nodejs010/root/usr/lib/node_modules/node-gyp/lib/configure.js:343:16)
remote: gyp ERR! stack at ChildProcess.emit (events.js:98:17)
remote: gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:820:12)
remote: gyp ERR! System Linux 2.6.32-504.16.2.el6.x86_64
remote: gyp ERR! command "node" "/opt/rh/nodejs010/root/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote: gyp ERR! cwd /var/lib/openshift/559fa9944382ec4cf1000106/app-root/runtime/repo/node_modules/keystone/node_modules/keystone-utils/node_modules/limax/node_modules/cld
remote: gyp ERR! node -v v0.10.35
remote: gyp ERR! node-gyp -v v1.0.2
remote: gyp ERR! not ok
remote:
remote: npm info cld@2.4.3 Failed to exec install script
remote: npm ERR! EEXIST, open '/var/lib/openshift/559fa9944382ec4cf1000106/.npm/0fe9cfe4-6-npm-mime-db-1-14-0-package-tgz.lock'
remote: File exists: /var/lib/openshift/559fa9944382ec4cf1000106/.npm/0fe9cfe4-6-npm-mime-db-1-14-0-package-tgz.lock
remote: Move it away, and try again.
remote: npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
remote: npm ERR! command "node" "/opt/rh/nodejs010/root/usr/bin/npm" "install" "-d"
remote: npm ERR! cwd /var/lib/openshift/559fa9944382ec4cf1000106/app-root/runtime/repo
remote: npm ERR! node -v v0.10.35
remote: npm ERR! npm -v 1.4.28
remote: npm ERR! path /var/lib/openshift/559fa9944382ec4cf1000106/.npm/0fe9cfe4-6-npm-mime-db-1-14-0-package-tgz.lock
remote: npm ERR! code EEXIST
remote: npm ERR! errno 47

**Comment by jeffreypriebe** [comment]
Looks like this is a common issue people are running into on OpenShift (I haven't used it):
https://forums.openshift.com/need-cairo-installed-for-node-module
https://forums.openshift.com/node-sqlite3-module-fails-to-install
Last link [suggests a custom Node.js for OpenShift](https://github.com/ramr/nodejs-custom-version-openshift).

Depending on how OpenShift works, you might want to try running npm install locally so that the node_gyp executes locally. Then push all the files up. At that point any npm install shouldn't need to run the node_gyp stuff and it won't matter that gyp isn't there.
This may not work depending on how OpenShift works.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
