### ISSUE TITLE
Custom styles dropdown for WYSIWYG?

### ISSUE THREAD

**Issue by dallasbpeters** [keystonejs/keystone#1532]
**Desired result:** Have a drop down with class names that can be applied to elements w/i the WYSIWYG. I have need to select a paragraph and add a `.help` class to it. The docs are a bit unclear, or I'm just not following. Any help would be super appreciated!

**Comment by jeffreypriebe** [comment]
I was just looking at this myself. First finding was the TinyMCE support for this.
If you check the [TinyMCE demo](http://www.tinymce.com/tryit/basic.php), you'll see a "Formats" dropdown (as we as a "Format" 'main menu' item).
These appear to be not be a separate plugin, but somehow an option that needs to be enabled - haven't found what yet.

Possibly you simply [configure the "formats" object for TinyMCE](http://www.tinymce.com/wiki.php/Configuration:formats)? If so, not sure where in keystone you'd have to do that as I don't see it in the [list of configuration items](http://keystonejs.com/docs/configuration/#options-ui).

From using TinyMCE in other systems, I know that it can work exactly as you describe: adding a class to a selected HTML block (or injecting a new block with the class).

**Comment by jeffreypriebe** [comment]
Wow, that worked exactly as it should. Simple change to your keystone.init 
Two options:
 1. You can simply add the `styleselect` as an additional button to `wysiwyg additional buttons`. This will give you the "default" format as seen on [the basic TinyMCE demo](http://www.tinymce.com/tryit/basic.php).

 2. If you want custom styles then in addition to adding the `styleselect` button, you pass in the `style_formats` object and you'll get the custom format that you want, as per [the TinyMCE custom formats demo](http://www.tinymce.com/tryit/custom_formats.php):
```
'wysiwyg additional options': {
	'style_formats': [
		{title: 'Ugly Text Options - Don\'t Use', items: [
			{title: 'Bold text', inline: 'b'},
			{title: 'Red text', inline: 'span', styles: {color: '#ff0000'}}
		]},
		{title: 'Inline', items: [
			{title: "Bold", icon: "bold", format: "bold"},
			{title: "Italic", icon: "italic", format: "italic"}
		]}
	]
}
```
n.b. You can also skip the groups/headings by not including them and simply promoting up the format items (e.g. instead of having the two objects under `style_formats[0].items`, those objects are the objects directly in the `style_formats` array - [the TinyMCE custom formats demo](http://www.tinymce.com/tryit/custom_formats.php) is setup this way).

["Grouping" documentation for TinyMCE style formats](http://www.tinymce.com/wiki.php/Configuration:style_formats).

**Comment by mxstbr** [comment]
It appears @jeffreypriebe answer the question perfectly, so I'll close this!

**Comment by icdindia** [comment]
doesnt seem to be working with the latest keystone and tinymce.. can any one test it out?
