### ISSUE TITLE
Can we make the order column order items using Underscore or add Numerical support to OrderBy?

### ISSUE THREAD

**Issue by Mentioum** [keystonejs/keystone#1569]
Currently ordering in the Admin UI orders lexicographically (unless I've missed an option somewhere?).  Which is great unless you are using numbers, in which case it's annoying.  Any chance we can have support for numerical values added.  I feel since you can define that a Type.Select is numeric one might expect it to order numerically in the admin?:

```javascript
order: { 
    type: Types.Select,
    numeric:true,
    options:  '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25',
    required: true,
    initial:true
}
```

**Comment by Mentioum** [comment]
I just used the sortable: true option for some parts instead of using a custom order field.  For places I needed to explicitly order things better I just did it in the controller in JS after I got the data out. I still think this would be a nice but I don't think its necessary.

**Comment by JedWatson** [comment]
I think being able to define an arbitrary field in the schema that maps to the sort field is an interesting idea, but it would probably conflict with the sorting implementation.

You can set `defaultSort` to any path (including a numeric `Select`) and set that in the "edit item" form... You do need to remember to `.sort('path')` in your queries though because it won't be automatically applied.

**Comment by Mentioum** [comment]
Only just saw this @JedWatson .  Didn't realise I could set ```defaultSort``` to any path.  Thanks for that tidbit of info!
