### ISSUE TITLE
Relationship filters with :_id not working?

### ISSUE THREAD

**Issue by dahei** [keystonejs/keystone#1589]
Hi, 

I am struggling with the relationship `filters` prop when using `:_id`

It's just not working (Keystone 0.3.13). My Use Case:

A have a collection (Images) where each Item can have one related Project from the `Project` collection.

Visa versa within each Project I want to link to one Image from the `Image` collection - but only(!) image items which are related to *this* project.

As far as I understand, both models have a relationship:

__Image__

    Image.add({

        [other props .....]

	project: {
		type: Types.Relationship,
		ref: 'Project'
	}
});

__Project__

    Project.add({

        [other props .....]

	image: {
		type: Types.Relationship,
		ref: 'Project',
            filters: {project: ':_id'} // show only images which are related to *this* project
	}
    });

Is is it a bug or am I doing it wrong?

Thank you!

**Comment by JedWatson** [comment]
Your setup looks good, so this may be a bug. I'll check it out.

**Comment by mxstbr** [comment]
This is probably fixed in 0.4, so I'll close it for now, feel free to comment again if you're running into this!

**Comment by wosevision** [comment]
Hey!

Could anyone confirm whether this was indeed fixed in 0.4.x? I've never been able to get this particular feature working with this setup, and like @dahei said,

> It's just not working

even after upgrading. The select still displays relationships for selection, but it displays _every single item_ available which is getting to be a whole ton. I'm using the #nested-lists branch right now, which seems to have the 4.0.0-beta.1, but couldn't get it working on the master branch after doing a test install anyway.

I'm filtering by `:_id` two places, simplest possible configuration (no nested fields or anything) I think of... Here's what one looks like:

**Building**

```js
...
	default: {
		label: 'Default scene',
		type: Types.Relationship,
		ref: 'Scene',
		filters: { parent: ':_id' },
		initial: true
	}
```

**Scene**

```js
...
	parent: {
		label: 'Building',
		type: Types.Relationship,
		ref: 'Building',
		initial: true,
		index: true
	},
```

Any thoughts on this? Thanks!

**Comment by ipavlenko** [comment]
Have the same problem, in 4.0.0-beta.7

**Comment by ipavlenko** [comment]
As a workaroud you can create synthetic hidden propery and copy the value of your _id to this property using pre-save hook. Then (after your model will be resaved) you will have ability to filter using this property.
