### ISSUE TITLE
Add case options to text fields

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#1641]
Add an option to the Text field to allow case options that will force upper or lower case of case insensitivity. This will allow fields in the database to be configured with these options and make @molomby happy.

**Comment by molomby** [comment]
This is important for uniqueness -- currently putting a unique constraint on an email field (for example) will not prevent entry of duplicate addresses.

Notes..

* Using hook that forcing case up or down is an _ok_ solution (and probably what we'll do) but it creates a migration problem if you have existing mixed case data
* This setting also impacts the filters exposed via GraphQL (ie. no need for the insensitive `..._i` filters)
* The `Uuid` field type encountered this [same problem](https://github.com/keystonejs/keystone-5/tree/master/packages/fields/src/types/Uuid#casing)
* Another way to solve this (on some DB platforms) is to mealy "desensitise" the index by forcing case there, rather than on the data itself. (Eg.. `create unique index users_email_unique on users(lower(email));`). This allows you to maintain the original casing of the input values.

**Comment by molomby** [comment]
Related: @mikehazell just pointed me to [`citext` type module](https://www.postgresql.org/docs/current/citext.html), included with Postgres, that solves this well. It stores the original value but implicitly converts to lower case before performing any comparisons.

**Comment by EricKit** [comment]
@molomby how did you apply citext to your keystone instance?

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
