### ISSUE TITLE
Add a DateRange field type

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#1642]
Add a date range field type. This is significantly different from the date field that it may require its own type.

**Comment by jossmac** [comment]
I've recently built this in another project using [react-day-picker](http://react-day-picker.js.org/). Happy to implement for keystone, but I'd like to wait until the release of [version 8](https://github.com/gpbl/react-day-picker/issues/942), which has an improved architecture and [hooks](https://reactjs.org/docs/hooks-intro.html) API.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
