### ISSUE TITLE
Nested objects in List schemas are not listed in Mongoose schemas

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1657]
I suspect this is an issue with the way we're registering nested paths in the mongoose schema, mongoose doesn't seem to understand that objects represent their containing keys.

Which means for this schema:

```
MyList.add({
  some: { nested: { path: String } }
});
```

This should work, but fails:

```
myListItem.some = { nested: { path: 'value' } };
```

**Comment by LorbusChris** [comment]
Is `Schema.Types.Mixed` used?  http://mongoosejs.com/docs/schematypes.html#mixed
In general it seems that MongoDB doesn't really allow for true multi-dimensional arrays. From what I've found It is recommended to just create a new sub-collection (model), and link it. 

Now for that implementing the GraphQL language for querying in the backend would really be nice, because it could look up data from a subcollection introspectively for you.. 
```
var MyList = new mongoose.Schema({
  name: {
    type: String
  },
  nestedItems: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'NestedItem'
  }]
});
```

**Comment by LorbusChris** [comment]
-Sorry, just noticed this has nothing to do with Types.Mixed
