### ISSUE TITLE
WYSIWYG issue with dependsOn

### ISSUE THREAD

**Issue by serafimsaudade8** [keystonejs/keystone#1686]
When we have a field with type: 'Types.Html' and wysiwyg: true, depending on another value (eg. dependsOn: {type: ['internal']}), the TinyMce editor does not load. It only loads after modifying the dependent value to the desired result and saving the document.

**Comment by creynders** [comment]
Not sure whether that fixes it, but I'm pretty sure `type`'s a reserved word (set either by keystone or mongoose). Maybe try renaming it to something else and see whether that fixes it?

**Comment by vikrant1011** [comment]
so i did some testing and the issue still remains. Following are the details on how to replicate the issue:


CASE 1:
```
{ con: { label: "c on or off", type: Boolean }},
 	{ ctextselect: { label: "C Text", type: Types.Html, wysiwyg: true, dependsOn: { con : true } } },

In the above case the wysiwyg is working flawlessly.
```

CASE 2:
```
{ c1select: { label: "Select Number of Components", type: Types.Select, options : ['1', '2', '3'] } },
 	{ heading: 'Component 1', dependsOn: { c1select : ['1', '2', '3'] } },
 	{ c1text: { label: "C1 Text", type: Types.Html, wysiwyg: true ,  dependsOn: { c1select : ['1', '2', '3'] } } },
```
In CASE 2 the wysiwyg does not work. What you get is a just a text area. 

No matter what name you give, the wysiwyg does not work. 

Please look into this issue otherwise i will have to add multiple boolean fields to activate html fields.

**Comment by vikrant1011** [comment]
FIX: https://github.com/keystonejs/keystone/pull/1319

**Comment by mxstbr** [comment]
Since #1319 is merged, this was fixed, so I'll close this issue. Thanks @vikrant1011!
