### ISSUE TITLE
[0.4] Use check marks instead of buttons to accept input?

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#1721]
In the following screenshot, wouldn't it be more UX if a checkmark (accept input) is placed next to the X (delete input)?  Those two "Add Item" buttons next to each other look kind of weird, IMO.

![image](https://cloud.githubusercontent.com/assets/5872515/10383382/13fce7ac-6dfc-11e5-8f89-fec62c075395.png)

OS:  Windows 10
Browser: Chrome

**Comment by nifl** [comment]
Chiming in. 

In the array type context, the 'X' to remove an item requires less input from the user than a '✓' to confirm. In most cases when the user adds an item, it is intentional and no need to confirm. An acceptance requirement would likely be initially missed by the user and caught by validation.

The 'add item' buttons are a bit awkward in this particular screenshot but keep in mind that once an item is added to to the 'Favorite Numbers' field, a text field will act as separator.

**Comment by jossmac** [comment]
@webteckie just checking desired layout and behaviour:

The "Add Item" button would be replaced by an empty field, with some helpful placeholder text like "New Item (hit enter to add)" with a button accompanying it to the right?

Perhaps a `+` icon rather than a checkmark?

* * *

This could be opt-in for `array` fields via the model, as @nifl mentioned it does obscure the behaviour a little and could be missed by someone unfamiliar with the pattern. Something like:
```jsx
texts: { type: Types.TextArray, quickEntry: true }
```
Maybe not `quickEntry` but you get the idea :)

**Comment by webteckie** [comment]
@jossmac maybe just spell it out:
```
Add Favorite Words

Add Favorite Numbers
```
or
```
+ Favorite Words

+ Favorite Numbers
```

**Comment by creynders** [comment]
Personally I'd go for a fat green `+` next to the `X` and that's it

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/use-check-marks-instead-of-buttons-to-accept-input!

**Comment by mxstbr** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/use-check-marks-instead-of-buttons-to-accept-input!
