### ISSUE TITLE
Image Gallery field

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#1730]
# Feature request
I want to use an Image Gallery field where I can add multiple images to the field (kind of array). 

This is needed to provide variable number of images in a list item and display them inline as thumbnail and as popup carousel to cycle through images

## Describe the solution you'd like

`admin-ui` should display the thumbnails inline and on clicking it open a larger images like carousel (popup in same page). There should be option to select specific image as primary (hero image)

## Describe alternatives you've considered
Considered to use Image list with relationship fields, but the display is not optimal for list of images, it is still a drop down with text only items 

This will be helpful and better approach over creating a relationship field, on another thought, if display of relationship items can be done using thumbnails and carousel view, it may also work.

**Comment by VinayaSathyanarayana** [comment]
Will be a useful addition to KeystoneJS

**Comment by MadeByMike** [comment]
I can see how this would be a useful addition. Many content management systems I've used have a gallery as a separate content type so the same gallery can be reused on other items. It also seems like the correct structure to store the data. So... it seems like this would be the sensible approach for Keystone as well. 

I wonder if adding repeating sections and array field types (#313, #195) would solve this as well as other use-cases like this rather than a more narrow field type. I think with these and the addition of admin UI hooks we could make it much easier to create custom features like this.

**Comment by gautamsi** [comment]
I think current fields can also handle this with little improvements.

one of the option is to have widgets/components for Relationship fields, like for this we can say
```js
keystone.createList({
//........
heroImage: { type: Relationship, ......., many: true, view/*(/display/uiHint/etc)*/: "gallary", thumbs: "thumb path on relationship field", image: "full image path for relationship  field"} 
//......
});
```
You can also have option to browse gallery for choosing images instead of `react-select` (wrapped in archUi/select) for this type of setup. 

this can also be extended to load custom widgets/elements for relationship field display per my other PR #1739 . 

I do see your point, I suggest we have an asset management feature which may use cloudinary or other adapters.

**Comment by MadeByMike** [comment]
Yeah a Relationship can be used to represent a lot of different things. The more I think about this, the more I'm realising that a set of different "views" for relationship fields could provide a lot of flexibility and solve several feature requests. cc @molomby

**Comment by MichaelZaporozhets** [comment]
This feature was present in keystone 4x as field: CloudinaryImages
https://v4.keystonejs.com/api/field/cloudinaryimages/

Hopefully it's a simple port.

**Comment by maximelebreton** [comment]
This feature is a **high priority**, how can we develop websites without it?

**Comment by abhijithvijayan** [comment]
Migrating from v4 to v5 broke due to this change.

I had set multiple image uploads set in v4.

Is there a timeline for this feature?

**Comment by alobodig** [comment]
We've been working on a field type for this in one of our own projects. We'll publish it soon.

**Comment by alobodig** [comment]
We just published our [custom Cloudinary gallery field](https://www.npmjs.com/package/@globobeet/keystone-cloudinary-gallery-field). Please check it out and let us know what you think!

**Comment by gautamsi** [comment]
Seems like can not get to the repo, is source private?

**Comment by joshlasdin** [comment]
@gautamsi Oops, we had it private while developing, just made it public. Thanks for the heads up :+1:

**Comment by MadeByMike** [comment]
In many ways this issue is a view on a relationship field. I'd like to see how we can solve this with: https://github.com/keystonejs/keystone/pull/2885 as well as with the new field and adminUI hooks.

**Comment by maheraldous** [comment]
It has been almost a year and this feature wasn't made. When will you do it for local upload. Like normal upload to the hosting server. I tried to make it by myself but I am not that good in custom list. I hope if you can make just this possible to do via GraphQL then you can wait to fic it's layout in the Admin UI because the headless part of KeystoneJS (GraphQL) which made as choose to use the KeystoneJS.

**Comment by gnimmelf** [comment]
Hi guys,

looking into image gallery as well. I found [this](https://keystonejs.com/docs/guides/document-fields#object-fields) in the next docs, but it is still unclear to what extent an image gallery is provided "out of the box".

Since this issue has been "open" for so long, is there a really simple idiomatic way to create an image gallery?

Cheers,
Flemming

**Comment by maheraldous** [comment]
> Hi guys,
> 
> looking into image gallery as well. I found [this](https://keystonejs.com/docs/guides/document-fields#object-fields) in the next docs, but it is still unclear to what extent an image gallery is provided "out of the box".
> 
> Since this issue has been "open" for so long, is there a really simple idiomatic way to create an image gallery?
> 
> Cheers,
> Flemming

@gnimmelf I just gave up on KeystoneJS and started my own GraphQL server. Yes it was a lot of work in the beginning but I can edit it how I want.

**Comment by predmaxim** [comment]
I hope the Keystone team has plans to implement mass upload of images and files.
