### ISSUE TITLE
A select with number at start of value throws an error

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#1768]
# Bug report

## Describe the bug

If you create a list with numbers at the start of the value of will throw an error on start.

` message: 'Syntax Error: Expected Name, found Int "0"',`

## To Reproduce

1. Create a list like: 

```
keystone.createList('ExampleList', {
  fields: {
    age: {
      type: Select,
      options: '0-18,19-35,36-50,50+',
    },
  },
});
```
2. Start Keystone.

It doesn't seem to matter if you use the array notation either:
```
keystone.createList('ExampleList', {
  fields: {
    age: {
      type: Select,
      options: [
        { label: '0-18', value: '0-18' },
        { label: '19-35', value: '19-35' },
        { label: '36-50', value: '36-50' },
        { label: '50+', value: '50+' },
      ],
    },
  },
});
```

## Expected behaviour

I can't see a clear reason why this cannot work. There are no limitations on storing this in a text field in the DB or on the possible values in HTML.

## System information

I was using Knex Adapter

## Additional context

Is Monday.

**Comment by molomby** [comment]
I assume this has something todo with things starting with numbers not being valid JS identifiers? Although I can't think why this would _actually_ be a problem here.. 🤔

It's worth noting that error is from the GraphQL layer.. Maybe some Admin UI code is seeing "0-18" and casting it to a Number? Would be useful to see the GraphQL query being run.

Re: Selects; see also #398. Further, given #851 and #1471 maybe this is an opportunity to revamp the Select field type a bit? The current solution/lack of formality seems very "first pass" to me.

**Comment by molomby** [comment]
It's because we're using GraphQL enums so the values are subjected to the limits enforced there; @JedWatson

**Comment by singhArmani** [comment]
@MadeByMike: This issue is related with how we are enforcing to have **Enums** for [creating Graphql query](https://github.com/keystonejs/keystone/blob/0da2ce99b93a171b64c1877399fb173aa03e646c/packages/fields/src/types/Select/Implementation.js#L31) in [Select](https://github.com/keystonejs/keystone/tree/master/packages/fields/src/types/Select) field.  

In specs **Enums** values are [Name tokens](http://spec.graphql.org/June2018/#sec-Appendix-Grammar-Summary.Lexical-Tokens). Which means the regex expression validating enum values is `/^[_A-Za-z][_0-9A-Za-z]*$/`, which prevents starting values with a digit or having single digit values. 
Consequently, to achieve the above use case, we need to construct options values to match the pattern described above. 
Following could be the valid **options** values: 

- `_0_18,_19_35,_36_50,_50 plus`
- `A_0_18,A_19_35,A_36_50,A_50 plus` (where A stands for Age group)

**Comment by timleslie** [comment]
Solution options:
 1) Continue to use `enum` and generate **better error messages** and **provide more explicit docs**.
 2) Change our implementation away from using `enum` to support a broader range of options. This would require a major breaking change and would require a significant change to how we handle this field type. I'm not sure there are any good reasons to do this, but it's something we should discuss.

Implementing the docs and error messages in option 1) is something we can and should do before we make a final decision on option 2).

**Comment by gautamsi** [comment]
Another option would be to use custom view for Field (soon) and use a custom logic for Select Field. 

another option would also be to have a Select Field sourced from another list, there you can have all possible value or even allow user to create new item in sourced list. I have custom example working, as soon as custom Field view spec is finalized we can add that in contrib repo.

**Comment by MadeByMike** [comment]
I really think the solution is to fix this even if it's a breaking change. It makes no senses to limit the types of data that people can put in the value of a select. I need to understand more about how this is a breaking change.
