### ISSUE TITLE
Support "Upsert", aka "UpdateOrCreate" mutations

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#182]
Interestingly, these existed in GraphCool, but not in Prisma or OpenCRUD:

```graphql
input UpdateOrCreatePostInput {
  id: ID # NOTE: Optional - passing this does an update, not passing this does a create
  # ...the rest of UpdatePostInput
}

type Mutation {
  updateOrCreatePost(data: UpdateOrCreatePostInput): Post
}
```

Greatly simplifies client code by not having to check for IDs, and switch to a different query.

In the case that you're trying to update with an ID that doesn't exist, it would throw an error the same as when doing `updatePost(id: "idontexist")`

**Comment by jesstelford** [comment]
@molomby I like that idea! Goes perfectly with https://github.com/keystonejs/keystone-5/issues/699

**Comment by molomby** [comment]
@molomby writes:

> This doesn't strike me as a very common requirement [..]

Yeah, scratch that; this would be super handy. 

Definitely worth separating the filters from the data being updated though.

I wonder if this should fit into how we configure multi-field uniqueness in Keystone. Ie. currently, we can specify a single field is unique using the `isUnique` flag but adding unique constraints across multiple fields must be done behind the scenes, in the DB.

Upserts seem to be useful when you know _some_ information about an item but maybe not whether it exists or not so, implicitly, don't have the items `id`. (If you have the `id` you have less of a problem because, race conditions aside, know whether to call create or update). _But_, **the "some" information you know really needs to uniquely identify one item** (or one potential item). Without this restriction it gets a lot more complicated -- we end up trying to solve upserts, multi-item updates, multi-item creates, etc. all at the same time.

So... if we give app devs a way of specifying sets of fields that should be unique within the list (eg. `user` and `event` in the `Rsvp` example above), that same config could be used to provision upsert mutations, using the same sets.

Eg. something like this:

```js
keystone.createList('Rsvp', {
   fields: {
      user: {
         type: Relationship,
         ref: 'User',
         isRequired: true,
      },
      event: {
         type: Relationship,
         ref: 'Event',
         isRequired: true,
      },
      isAttending: {
         type: Checkbox,
         defaultValue: false,
      },
   },
   // A made up, multi-field unique constraint configuration
   // The object key is arbitrary; just a handle we use to name the mutation and underlying constraint
   uniqueFieldSets: {
      pair: ['user', 'event'],
   }
});
```

Could cause this additional GraphQL schema to be created:

```graphql
type rsvpPairUpsertWhereInput {
   user: ID!
   event: ID!
}
type rsvpPairUpsertInput {
   isAttending: Bool
}
// .. all the other types

type Mutation {
   upsertRsvpPair(
      where: rsvpPairUpsertWhereInput!,
      data: rsvpPairUpsertInput!
   ): rsvpOutputType
   // .. all the other mutations
}
```

There could of course be multiple sets of unique fields, resulting in multiple unsert mutations for a single list.

**Comment by molomby** [comment]
I think this is functionality is dependant on unique indexes which, themselves, get a lot more useful when you start dealing with compound indexing. Anyone actioning this should also be across #2304.

**Comment by jesstelford** [comment]
This may come back once Prisma support is fully baked in Keystone Next, but for now I will close this.

**Comment by MurzNN** [comment]
Seems Prisma already have the `upsert` method?
https://www.prisma.io/docs/concepts/components/prisma-client/crud#update-or-create-records

**Comment by johanneshiry** [comment]
@jesstelford Any chance that this will be available in KeyStone Next soon? Or is it available and I just didn't saw it?

**Comment by timleslie** [comment]
@johanneshiry This isn't available for Keystone Next just yet, but we're it's on our feature list to be planned into future development. I can't give you an ETA on it just yet.
