### ISSUE TITLE
Render Markdown and WYSIWYG fields in Cells

### ISSUE THREAD

**Issue by ashinzekene** [keystonejs/keystone#1829]
# Feature request

Render Markdown and WYSIWYG fields in Cells

## Describe the solution you'd like
I feel it would be better to render the texts in the lists for both markdown and html contents

![image](https://user-images.githubusercontent.com/20991583/67481811-7f047980-f65a-11e9-8aa8-94230e31f668.png)

**I can work on this**

**Comment by jesstelford** [comment]
Do you mean instead of seeing

> \*\*yaha\*\*

We'd see

> **yaha**

?

That could work well for inline styling. What about things like newlines and other block-level elements? Would they be rendered as inline also? We'd need to make sure the content still stays on a single line.

**Comment by MadeByMike** [comment]
We'd also need to make sure it is safe. If there is user generated content and we're rendering it this is a big XSS target.

**Comment by VinayaSathyanarayana** [comment]
I agree that security has to be factored in

**Comment by ashinzekene** [comment]
@jesstelford the text can always be trimmed both from the component and with CSS

@MadeByMike I think, we can sanitize the input

**Comment by bladey** [comment]
Hi @ashinzekene,

Thank you for writing this up.

In an effort to maintain the KeystoneJS project going forward, we're closing issues related to [Keystone 5](https://github.com/keystonejs/keystone-5) to make way for the next version called [Keystone Next](https://next.keystonejs.com).

The existing **Keystone 5** codebase has been moved to [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) which is now in a 6-12 month active maintenance phase.

You can learn more about the next version which we’re calling **Keystone Next**, which is now [in preview](https://next.keystonejs.com).

If you feel this issue is still relevant and require assistance, please open a new issue in the [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) repository.

Thank you for your continued support as we push towards this next major new version of KeystoneJS!
