### ISSUE TITLE
Make the orderBy input field an `enum`, not a `String`

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#183]
Enforces the type checking, and makes the code more explicit.

Current:

```graphql
type Query {
  allPosts(
    where: EventWhereInput
    orderBy: String
	# ...
  ): Post
}
```

Proposed:

```graphql
enum EventWhereOrderBy {
  title_ASC: Boolean
}

type Query {
  allPosts(
    where: EventWhereInput
    orderBy: EventWhereOrderBy
	# ...
  ): Post
}
```

**Comment by molomby** [comment]
> The idea was some field types might want to support novel, custom collations.

Thinking about this more, I reckon this would be useful, especially for the more complex types like images and files. It could be pretty useful to sort an image field based on width, height or file size.

Also, **bump** to this issue generally. I'd love to get this fixed sooner rather than later; it'll be a breaking change so let's not build to much on it while it's wrong.

**Comment by timleslie** [comment]
Another thing to consider here is access control. If a field does not have read permission, should we allow sorting based on it?

**Comment by molomby** [comment]
Just noting here from offline discussion -- the enum should be introduced as `sortBy`. This is both the correct name for this argument and allows us to (easily?!) have backwards compatibility with the `orderBy` string argument. (If suppled `sortBy` should take precedence.. or maybe error if both are supplied?)
