### ISSUE TITLE
Keystone Express app

### ISSUE THREAD

**Issue by kelthenoble** [keystonejs/keystone#1835]
Hey what's up @JedWatson : I been having a few problems integrating keystone into the company I intern for, codebase. So I came across a unique opportunity. Well since i been having problems integrating keystone into a big app. I was advised to just make a simple express app & integrate keystone into it. And i been searching keystone express resources, mainly this one :arrow_right:  https://github.com/keystonejs/keystone/wiki/How-to-Add-Keystone-to-an-Already-Existing-Express-App
and keystone over at googlegroups. 

I really enjoy tinkering with keystone, but I don't quite understand it all, just yet. So I think it would be great if keystone had a repo showing an app with keystone & express together. Since Keystone is an open source node.js cms & a lot of companies using it. I thought that this was a fortuitous chance for me to commit to Awesome keystonejs & learn it as we build this Light app showing Express & Keystonejs working in harmony. 

I don't think it would be time consuming since your are the creator of keystone & i already have the skeleton of this app :arrow_right:  https://github.com/kelthenoble/Keystone-Express

**Comment by JedWatson** [comment]
Hey @kelthenoble, that's great - thanks for the contribution!

I think the best way to do this would be to add to our existing demo project - what do you think of submitting a PR that sets up the express app as per your repo, but is otherwise equivalent to the main `keystone.js` start script?

i.e. add an `express.js` script to the root of https://github.com/keystonejs/keystone-demo

You might also be interested in the custom setup scripts in the new test project: see `express.js` and `advanced.js` in https://github.com/keystonejs/keystone-test-project

These are a WIP demo of the new API that will be in 0.4 for this sort of use case.

**Comment by kelthenoble** [comment]
Okay Jed @JedWatson  Sounds Great, but a bit of a challenge, but sounds like a plan, count me in.
