### ISSUE TITLE
keystone.use() - Middlewares

### ISSUE THREAD

**Issue by ganobrega** [keystonejs/keystone#1846]
# Feature request
The feature is a `.use()` for middlewares functions.
## Is your feature request related to a problem? Please describe.

The problem is the organization in the main file, blending models declarations with others setups.

## Describe the solution you'd like
To implement a function in Keystone prototype that callback with keystone instance in parameters. Like the [app.use()](https://expressjs.com/en/api.html#app.use) of [express](https://github.com/expressjs/express).

``` js
//index.js

import { Keystone } from "@keystone-alpha/keystone";
import UserModel from './models/User.js';

const keystone = new Keystone({
  name: PROJECT_NAME,
  adapter: new MongooseAdapter()
});

keystone.use( UserModel );

...
```

``` js
//models/User.js

import { Text, Checkbox, Password } from "@keystone-alpha/fields";

export default keystone => {
  keystone.createList("User", {
    label: "Usuários",
    fields: {
      name: { type: Text },
      email: {
        type: Text,
        isUnique: true
      },
      isAdmin: { type: Checkbox },
      password: {
        type: Password
      }
    }
  });
};

```

**Comment by timleslie** [comment]
Hi @ganobrega, thanks for asking this question! There are a number of different patterns for creating lists depending on how you want to structure your files. In your example the way to use your model using the existing API would be:

```js
import { Keystone } from "@keystone-alpha/keystone";
import createUser from './models/User.js';

const keystone = new Keystone({
  name: PROJECT_NAME,
  adapter: new MongooseAdapter()
});

createUser(keystone);
```

At the moment we don't plan to add a `.use()` method here for a few reasons. First, it doesn't add  any functionality which isn't already possible, while adding one more method to our supported API. It will also make it more difficult for a reader of the code to follow, as they'll have to understand what `keystone.use(model)` is doing, rather than just reading a regular function application. The last reason is that creating lists in keystone is actually quite different to using middlewares in express. Having a method called `.use()` implies to the reader that they are somehow similar and they might go looking for similarities where there are none.

One of the thing's we working on at the moment is building example projects for people to use as starting points for their own projects. We're hoping that these will give good examples of the best way to structure list creation for projects on a range of scales.
