### ISSUE TITLE
Better Apollo client HTTP error message

### ISSUE THREAD

**Issue by vgavro** [keystonejs/keystone#1865]
Apollo client always throws parsing error, even if there was HTTP error.
Related ticket: https://github.com/apollographql/apollo-feature-requests/issues/153
Consider this ApolloError:
```
updateError.networkError.name "ServerParseError"
updateError.networkError.response.ok false
updateError.networkError.response.status 413
updateError.networkError.response.statusText "Payload Too Large"
updateError.message "Network error: Unexpected token < in JSON at position 0"
```
We got toast: `Network error: Unexpected token < in JSON at position 0`
Even if there is already ticket in Apollo (which is not going to be resolved in near time, I guess), we may want to one of those:
* throw more obvious error in our apollo fetch implementation
* **OR** reformat error if `e.networkError.name == "ServerParseError" && !e.networkError.response.ok`

related source files:
`packages/app-admin-ui/client/pages/Item/index.js`
related tickets: #1659

**Comment by bladey** [comment]
Hi @vgavro,

Thank you for taking the time to write up this issue.

In an effort to maintain the KeystoneJS project going forward, we're closing issues related to [Keystone 5](https://github.com/keystonejs/keystone-5) to make way for the next version called [Keystone Next](https://next.keystonejs.com).

The existing **Keystone 5** codebase has been moved to [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) which is now in a 6-12 month active maintenance phase.

You can learn more about the next version which we’re calling **Keystone Next**, which is now [in preview](https://next.keystonejs.com).

If you feel this issue is still relevant and require assistance, please open a new issue in the [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) repository.

Thank you for your continued support as we push towards this next major new version of KeystoneJS!
