### ISSUE TITLE
Integrate management of environment variables

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#189]
At the moment, the demo sites and yeoman generator include the dotenv package for managing environment variables.

It would be neater if Keystone managed this itself (either bundling dotenv or with a customised version).

**Comment by wmertens** [comment]
Is this still a desirable feature?

Might I otherwise suggest the use of https://github.com/lorenwest/node-config which allows configuring projects in JSON, YAML, … and overriding by production/dev/testing as well as with mapping environment variables to config settings. This works very well for keeping placeholder values in git with secret values only on the installs. It is great!

**Comment by mxstbr** [comment]
I don't think this is desireable, dotenv works just fine. I'll close this for now, feel free to reopen if you have other feelings!
