### ISSUE TITLE
Instance safe Keystone?

### ISSUE THREAD

**Issue by ericelliott** [keystonejs/keystone#1946]
I'm working on adding React view engine capabilities to Keystone (https://github.com/keystonejs/keystone/issues/1943).

I'm trying to write unit tests to test the view engine settings. To do so, I'd like to do something like this for each test:

```js
import keystone from 'source/keystone';
const app = express();
keystone.set('app', app);
```

The question is, how do I guarantee that the tests are not affecting each other if `keystone` is a singleton?  Ideally, I'd like it to behave like a factory:

```js
import initKeystone from 'source/keystone';
const keystone = initKeystone(options);
const app = express();
keystone.set('app', app);
```

Then, in the next test, I just pass different options to `initKeystone()` and get a different Keystone instance back. No worries.

This feature could also be used to break a single Keystone app into several microservices, each with different Keystone configurations. That could help make larger apps more scalable.

Is anybody else interested in this topic?

**Comment by JedWatson** [comment]
@ericelliott already on it - see #1896

The work has largely been done by @creynders and @snowkeeper but that branch is currently failing tests since some epic conflict resolution by @creynders.

He was going to look into it and help me get the tests passing but has been caught up with a big deadline at work... Hopefully soon? Otherwise you're welcome to code review it + help get it green so we can merge.

**Comment by creynders** [comment]
I hope to have some time today. The deadline's having some fallout, but I think dust should settle today a little. I want to get it in ASAP too, since due to its nature even minor changes create conflicts.

**Comment by ericelliott** [comment]
Rock and roll! 🎸🎶🔥

**Comment by ericelliott** [comment]
Let's close this and track in 1896
