### ISSUE TITLE
Nested lists, aka. "repeating fields", "sublists"

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#195]
Can we support a type like:

```javascript
keystone.addList('Zip', {
  fields: {
    foo: {
      type: List,
      fields: {
        bar: { type: Text },
        when: { type: DateTime },
      },
    },
  },
});
```

Possible implementation is treating this as syntax sugar which sets up another list, but with config to hide from Admin UI, etc.

ie, the above is roughly equivalent to:

```javascript
keystone.addList('Zip', {
  fields: {
    foo: {
      type: Relationship,
      ref: '_Zip_df45afe',
    },
  },
});

keystone.addList('_Zip_df45afe', {
  fields: {
    bar: { type: text },
    when: { type: DateTime },
  },
  admin: {
    includeInNav: false,
    includeInGraphQL: false,
  },
});
```

**Comment by danny-stateside** [comment]
Nested fields for the admin UI would be awesome, maybe adding a type called parent, like . . . 
`{ type: Parent, ref: 'PapaList' }`
This can later be used to display the fields under the parent and manage some sort of relationship.

**Comment by MurzNN** [comment]
Before Keystone I actively used the Drupal CMS and it have "repeating fields" by default for any field type, here is how to define this:
https://www.drupal.org/docs/drupal-apis/entity-api/defining-and-using-content-entity-field-definitions#s-multivalue-fields
```php
$fields['my_field'] = BaseFieldDefinition::create('string')
  ->setLabel(t('The label of the field'))
  ->setDescription(t('The description of the field.'))
  ->setCardinality(3);
```
and
```php
$fields['my_field'] = BaseFieldDefinition::create('integer')
  ->setLabel(t('The label of the field'))
  ->setDescription(t('The description of the field.'))
  ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED);
```

At storage side - those field values, if field have cardinality > 1, are stored in separate SQL table, and joined to entity on load. If cardinality == 1 (default), they are stored in separate column in same table, as entity.

This is the best realization on API side, because users simply set `cardinality` > 1 to make multi-valued field.

**Comment by MurzNN** [comment]
Other good way of implementation is in Strapi framework: they are implement multi-valued fields as relation to sub-list, here is example: https://strapi.io/documentation/developer-docs/latest/concepts/models.html#components

On database side this is simply separate list (stored in separate table), but on API side all those values are loaded automatically together with main item, and those "sub-lists" are not listed in main list, and can't be created separately.

So on Keystone side we can implement this way via adding some mark like "isSublist" to hide them in Admin UI interface from list of all available Lists.

**Comment by JedWatson** [comment]
I wanted to add a note here to say that we're going to tackle this general feature in Keystone Next, and it's on the public roadmap 🎉 

https://next.keystonejs.com/roadmap#nested-json-fields

We probably want to explain it there better, because the roadmap description is specific to the implementation, but when I wrote that, I was thinking of this specific use case.

We've also been adding functionality to Relationships that make it possible to implement a "nested fields"-style workflow in the Admin UI, so we'll probably actually end up covering this from both perspectives:

**Related Lists that look and feel like Nested Lists**

You can set up relationship fields in lists to give the Admin UI experience of "nested, repeating fields" while actually using  full relational database features behind the scenes, including independent access control, field and index management, independent querying through the GraphQL API, etc

(going back to @jesstelford's original proposal, that is basically syntax sugar for the config at this point; we may or may not actually build another API for defining lists like that, depending on how easy it ends up being to create the relationships otherwise, and how much of our current API we would need to duplicate. it's something definitely worth looking into, but I'm also a big fan of "one way to do things")

(also note that today, you can preview where we're at with this in the `examples-next/todo` app, have a look at how Phone Number relationships work with Users)

**Nested repeating fields**

We're planning a Field Type that's going to store JSON behind the scenes, which you define with list-like schema syntax, and produces the "nested repeating fields" UI in the Admin UI. These will be more intended for use-cases like defining navigation structure, or data where you're always going be loading the complete set of items at once.

The key differences between this field type and using a related list would be:

* JSON items will be sortable (relationships are not currently sortable in a many-one or many-many relationship, and changing that is a large amount of work with a lot of questions attached)
* All the JSON items will be retried when the field is queried, so you can't filter or paginate the results through the API like you can with related items
* You can't load the JSON items independently of the item they are embedded in

This is all roughly translatable to the MongoDB concept of "separate collection, related by Ids" vs. "nested documents".

@MurzNN I _think_ that the JSON nested repeating fields will work very similarly to what you're proposing in terms of functional behaviour, especially this part:

> API side all those values are loaded automatically together with main item, and those "sub-lists" are not listed in main list, and can't be created separately.

imo both capabilities above are important for Keystone to have, we should try and make the use-cases for them overlap as little as possible though because they have distinct pro's and con's.

**Comment by MurzNN** [comment]
@JedWatson, great thanks for so detailed description of plans! 

Yes, JSON field will be good solution for most of common tasks, and will be good to have it not only for MongoDB backend, but for PostgreSQL too (using `jsonb` column type). At first iteration of implementation it can be even a simple textarea in Admin UI (because it is not too easy to design the interface for complex JSON data), this will be enough for projects, that use Keystone only as GraphQL backend (like mine projects), and Admin UI is only fallback interface for raw editing of data.

So will be glad to have the JSON field type at first time, even with textarea in Admin UI!

But the other type of repeating fields, based on relations, is very useful too! And we already have most of functional for implement them properly! I think that wasting time for implementing syntax sugar is not necessary, current implementation with separate schema declaration for each "sublist" is pretty good, adding some option like `isSublistOf: parentList` will be enough. 

And the most wanted features with relations for our projects now are:

1. Implement the "hard attach" of sublist items to parent item: allow only create new and delete already attached subitems, without ability to move subitem from one parent item to another. And implement delete hook - when user delete the parent item, remove also all attached subitems. This will solve many problem, that we potentially got with current implementation, when using relations as sublists. Also hide from Admin UI the menu item for sublists and ability to operate with them without parent item.

2. If we will have the "hard attach" mode, we can simply implement saving the order of attached sublist items! This can be implemented via selecting the numeric field in sublist, that will be used to store the numeric weight of each sublist item (0, 1, 2, etc), and filling it when the parent item is saved. Because we have the "hard attach" mode, we can be sure that each subitem is attached to only one parent item, and recalculate the order from 0 to N on each save, with overwriting previous values. This implementation is used already long time in Drupal Framework, named as "delta" field. So each repeating field is stored in separate table with "delta" field, that store the order of this item in parent entity.

What do you think about this idea?

**Comment by MurzNN** [comment]
> @bladey closed this 26 minutes ago 

Can you please comment the reason of closing - is this feature implemented or not possible to implement?

**Comment by bladey** [comment]
Hey @MurzNN!

Apologies for the non-comment here.

Nested Lists are not currently implemented, but they are a feature that’s on our roadmap. We are closing this issue for now because we are trying to keep our issue backlog as a place to capture bugs and issues that need to be fixed, rather than a discussion area for planned features. The information in this ticket will not be lost, and we’ll update our roadmap with more details once we begin work on this feature.

**Comment by LasseRosenow** [comment]
@bladey What about introducing a feature-request workflow based on github discussions? Directus is doing this and its pretty amazing and fixes the whole separation of concern problems.

**Comment by Ebeldev** [comment]
Like @vincentvandijck without repeated nested content keystonejs is missing some real case uses.

**Comment by ssyberg** [comment]
Following
