### ISSUE TITLE
CSRF problem in CMS with delete button in a detail page

### ISSUE THREAD

**Issue by PeterCervienka** [keystonejs/keystone#1998]
Hello everyone,

I have one strange deleting issue in the detail page of any entity. I am using keyston's CMS system for administration of data and when I click on the delete button I get an error message: "There was a problem with your request, please try again."
![cms_error_msg](https://cloud.githubusercontent.com/assets/9879956/11930284/4eba1b24-a7e2-11e5-9216-c2a14e06304b.png)

I found these logs on the server:
12:46:19,501 - debug: GET /keystone/posts 200 1300.586 ms
12:46:22,410 - debug: GET /keystone/posts/5630ae31119c56d40f494dd7 200 371.527 ms
12:46:22,562 - debug: GET /keystone/api/posts/5630ae31119c56d40f494dd7?drilldown=true 200 7.058 ms
12:46:22,605 - debug: GET /keystone/api/post-categories/5612725eefbe6f201a3157b7?simple 304 7.107 ms
12:46:22,614 - debug: GET /keystone/api/users/55e054fe515300e40d252a0d?simple 404 7.063 ms
12:46:22,665 - debug: GET /keystone/api/post-categories/autocomplete?context=relationship&q=[object%20Object]&list=posts&field=category& 304 6.455 ms
CSRF failure
12:46:25,678 - debug: GET /keystone/posts?delete=5630ae31119c56d40f494dd7&_csrf=208I2Gl5ebxx+908tfXzMT1vT3P72Gstfcu1s= 200 1205.262 ms

The strangest thing is that this error is shown just sometime and I am able to remove the same entity on second/third attempt

My first assumption was that there is some problem with data (inconsitance or something like that), but removing from a list (via trash can icon) works without problems.

Do you have some idea, where could be the problem?

Thanks.
Peter.

**Comment by ryedin** [comment]
+1

Very non-descript "CSRF Failure" that only happens sometimes (after search for an item and trying to delete it).

**Comment by erg0dic** [comment]
What session store are you using? I have seen this myself with file-sessions.

**Comment by kalms** [comment]
Seeing this. Session store is mongodb.

**Comment by bassjacob** [comment]
@PeterCervienka Thanks for reporting this.

From your description this is not so easy to reproduce. Is there a codebase I could look at to see what's going on?

**Comment by christroutner** [comment]
I have no tangible evidence to contribute to this, only that I too have experienced some strange CSRF behavior when trying to implement the CSRF security feature on my APIs. It will throw the 'CSRF failure' even though I've restarted keystone.js and logged out and back in.

**Comment by bassjacob** [comment]
Do you have a public repo I can clone to try help? How are you enabling csrf?

**Comment by christroutner** [comment]
I haven't had very good luck with GitHub links to repositories, but here it goes.

You can check out the CSRF code in the [unstable branch](https://github.com/skagitpublishing/ConnextCMS/tree/unstable) of [ConnextCMS](http://connextcms.com). For example, the [/routes/api/page.js](https://github.com/skagitpublishing/ConnextCMS/blob/unstable/routes/api/page.js) file shows how I use the CSRF library to check the CSRF token before executing the *create* API call. The code is commented out because I need to find some time to check into this CSRF issue in further detail.

I haven't exactly figured out how to reproduce the behavior, but it frequently occurs when I am going through rounds of killing the keystone.js process, restarting it, and then interacting with it through API calls.

If I kill the `keystone.js` node process then restart it, I would expect it to throw a CSRF error until I log out and back in as I would have an invalid CSRF token at that point. What's happening is that when I log out and back in, I never *receive* a CSRF token. I've gone so far as to stop keystone.js in the debugger in order to look at the CSRF token. `security.csrf` *does not exist*. i.e. `security.csrf == undefined`

I have no idea what's causing it. I honestly haven't had time to dig deeper into this issue.

**Comment by stennie** [comment]
Closing as a duplicate of #2043.
