### ISSUE TITLE
Add Documentation for Programatic Authentication

### ISSUE THREAD

**Issue by cowlingj** [keystonejs/keystone#2038]
# Feature request

## Is your feature request related to a problem? Please describe.

My problem is that I can login to the Admin UI and get access to restricted data, but I couldn't find out how to do this programmatically in the docs. I eventually stumbled on [these tests](https://github.com/keystonejs/keystone/blob/master/api-tests/auth-header.test.js) that step through just that, but that was a lot of work to find how to do programmatic authentication.

## Describe the solution you'd like

I would like programmatic authentication to be included in the docs, perhaps a section in Advanced>Authentication (there's a section there for "Logging in to the Admin UI", so that's the place I first expected to find info on programmatic access). 

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by bladey** [comment]
Hi @cowlingj,

Thank you for taking the time to write up this issue.

In an effort to maintain the KeystoneJS project going forward, we're closing issues related to [Keystone 5](https://github.com/keystonejs/keystone-5) to make way for the next version called [Keystone Next](https://next.keystonejs.com).

The existing **Keystone 5** codebase has been moved to [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) which is now in a 6-12 month active maintenance phase.

You can learn more about the next version which we’re calling **Keystone Next**, which is now [in preview](https://next.keystonejs.com).

If you feel this issue is still relevant and require assistance, please open a new issue in the [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) repository.

Thank you for your continued support as we push towards this next major new version of KeystoneJS!
