### ISSUE TITLE
Multiple file upload for a record

### ISSUE THREAD

**Issue by forrestab** [keystonejs/keystone#2065]
# Feature request

## Is your feature request related to a problem? Please describe.

I am looking for the ability to upload multiple files per record.

## Describe the solution you'd like

It would be great if the `File` type could be updated to accept a `many` option similar to the `Relationship` type. With this solution the `multiple` attribute for `<input type="file">` can be utilized and multiple files can be selected at the same time instead of something like a repeater/array of type `File`.

## Describe alternatives you've considered

I have considered creating a files collection with a `File` field and using a relation with `many: true` in the other collections to associate many files to one record, but I am not sure about this approach.

**Comment by hvandusen** [comment]
after making my first list i would also love the ability to upload multiple files per record. thanks for all the great work on keystone :)

**Comment by maheraldous** [comment]
@timleslie

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
