### ISSUE TITLE
Multiple Mongoose Connections Support

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#207]
In my BYO express setup, in which I have one keystone connection per vhost, there seems to be an issue connecting to mongoose/mongod on the second keystone instance.  Bring up one vhost at a time with its keystone instance works just fine.  Are multiple mongoose connections not supposed to work in the latest keystone registered with npm?  Is this a known issue that will be looked into?  Maybe what's described at http://www.nodejsnotes.com/2013/05/mongoose-and-multiple-database.html ?

Error:

...\node_modules\keystone\index.js:575
			throw new Error("KeystoneJS (" + keystone.get('name') + ") failed to start:
			      ^
Error: KeystoneJS (XXX) failed to start:

Mongo connection error
    at NativeConnection.mongoose.connection.on.on.mongoConnectionOpen (...\node_modules\keystone\index.js:575:10)
    at NativeConnection.EventEmitter.emit (events.js:95:17)

**Comment by erg0dic** [comment]
I figured out how to do this today. My use case:

I have two mongo database, one "staging" and one "live". Staging database is what gets updated on edits through the admin ui. Live database receives updates from a publishing process.

The "live" database is instantiated like this:
```javascript
keystone.start({
  onMount: function () {
    keystone.liveMongoose = keystone.mongoose.createConnection(url);
  }
});
```

You have to wait for keystone to connect to mongo first, otherwise you will clobber the connection.

To instantiate a Model against the "live" database, you can do this:
```javascript
  let Model = keystone.list('SomeModel');
  let LiveModel = keystone.liveMongoose.model(collectionName, Model.schema)
```

Hope this helps,
Rob

**Comment by webteckie** [comment]
@erg0dic interesting!  Will check your solution out when I get a chance.

**Comment by creynders** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. From now on submit feature requests on [productpains.com](https://productpains.com/product/keystonejs)!

https://productpains.com/post/keystonejs/multiple-mongoose-connections-support
