### ISSUE TITLE
Is there a guide for the migration of keystone v4 to v5?

### ISSUE THREAD

**Issue by pipejiva** [keystonejs/keystone#2090]
# Question about Keystone

There is a guide or good practices for migrating from the version of keystone 4 to keystone 5.

Thank you!

**Comment by internetErik** [comment]
I am interested in this, too. I have been exploring migrating by using a [Custom Server](https://www.keystonejs.com/guides/custom-server) and setting up my routes in there instead.

I'd be curious if people have other thoughts about this.

**Comment by gautamsi** [comment]
see this for what is blocking - https://github.com/keystonejs/keystone/issues/1818

I have a contrib package which is here - https://github.com/keystonejs-contrib/keystonejs-contrib/tree/upgrade-to-keystone-alpha-16

you can use notion of v4 views with use of proper graphql queries, this needs upgrade to latest keystone but I am unable to figure out the challenge with the routes issue in express with limited availability until mid Jan

**Comment by MadeByMike** [comment]
Unfortunately we can't have a simple  migration guide from version 4 to 5.
 
Keystone 5 is a complete re-write. It uses graphQL rather than rest APIs, it's headless rather than relying on server rendered templates, and has support for additional database options other than Mongo.

In terms of the underlying architecture Keystone 5 is much more modern and flexible than Keystone 4 was. 

Have a look at the road-map: https://www.keystonejs.com/guides/road-map I acknowledge here that we want to do more to improve the on-boarding experience including for people "migrating" from 4 to 5 but there is a lot to do and Keystone 4 is stable so there is no need to move unless you want to re-platform applications.

**Comment by Dhruvkagrawal** [comment]
ok
