### ISSUE TITLE
JS injection allows in comments box

### ISSUE THREAD

**Issue by kenjim83** [keystonejs/keystone#2103]
Hey awesome Node.js CMS!

I was playing around with the demo site and noticed that it allows javascript in the comments box

ex. http://demo.keystonejs.com/blog/post/hi-2#comment-id-56991ff76c17540300765c1e

Just thought you guys would like to know! :)

**Comment by mxstbr** [comment]
Not entirely sure what this is about since the demo post got deleted, but I cannot run arbitrary JS in the comment field

<img width="262" alt="screen shot 2016-03-15 at 17 52 40" src="https://cloud.githubusercontent.com/assets/7525670/13769832/c625f796-ead6-11e5-9a50-ca8471fe2c7d.png">

I'll close this issue for now, if this is not what this issue was about please comment/reopen!

**Comment by morenoh149** [comment]
I hope this got fixed. When this issue was made I definitely saw a browser alert displayed. Hopefully keystone is sanitizing user input or at the very least sanitizing it before rendering the template.

Relevant? https://github.com/keystonejs/keystone-demo/blob/master/templates/views/post.jade#L38

http://jade-lang.com/reference/attributes/#unescaped

**Comment by geloescht** [comment]
@mxstbr Please reopen, JS injection is possible if code is wrapped in a valid script tag. Demonstrated here: http://demo.keystonejs.com/blog/post/test-from-omnitrix#comment-id-56e88f9087dfe50300007fde

**Comment by mxstbr** [comment]
Damn, thanks. Did you enter `<script>alert('bla');</script>` into the comment box?

**Comment by geloescht** [comment]
I used `<script type="text/javascript">` actually, but yeah, nothing too fancy.

**Comment by mxstbr** [comment]
This should be as easy as changing `!=` to `=` on the keystone demo site I think, not sure why we don't escape the comments actually.
