### ISSUE TITLE
Increment minimum Node version compatible

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#2112]
There have been a couple of reports of keystone not working on older (pre v4) node versions.
https://github.com/keystonejs/keystone/pull/2109#issuecomment-172375525
https://github.com/keystonejs/keystone/issues/1704

Would we be open to declaring support of a stable node version such as Node v4.2.4 LTS?
See https://github.com/keystonejs/keystone/blob/master/package.json#L159

**Comment by ericelliott** [comment]
I'm all for this. :+1:

**Comment by christroutner** [comment]
So I've tried a couple times now and I can't get Keystone to install. I've been told that the master branch has since been upgraded to v0.4.0.

I'm using Node v4.2.4 installed via nvm.

I've tried both the 'yo keystone' installer and simply cloning the repo and running 'npm install' to install the dependencies. Both choke.

Any recommendations on a branch or commit hash to use? Perhaps a commit hash combined with a specific version of node (like 4.2.4) will work?

**Comment by morenoh149** [comment]
master + node v5 should work. Please share your error.

**Comment by christroutner** [comment]
Thanks for the tip. I still ran into a couple speed bumps, but I was able to recover. Here are the complete instructions that I used for getting the latest version to install with Node v5. [I also created a fork](https://github.com/christroutner/keystone) in case future commits break the build and the below install instructions.

Instructions for installing Node:  https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs

node v5.5.0
npm v3.3.12
Ubuntu 14.04 on Digital Ocean Droplet

sudo npm install -g yo
npm install generator-keystone

I called my project keystone4.
cd keystone4
node keystone.js

Which ran KeystoneJS, but gave me this error:
trout@Development:~/keystone4$ { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

Going through the Issues, I found a reference to this Stack Overflow discussion:
http://stackoverflow.com/questions/28651028/cannot-find-module-build-release-bson-code-module-not-found-js-bson

cd ~/keystone4/node_modules/mongodb
npm install

cd ~/keystone4/node_modules/mongodb/node_modules/bson/ext/
nano index.js

change this line:
bson = require('../build/Release/bson');
to this line:
bson = require('../browser_build/bson');

**Comment by morenoh149** [comment]
seems like 0.12 is desired. https://github.com/keystonejs/keystone/issues/2151#issuecomment-180985590

**Comment by JedWatson** [comment]
@morenoh149 I'm really hoping to keep the next version compatible with 0.12 so that anyone who's running in an older version of node or iojs can use the latest keystone as soon as it's released

We haven't made any _deliberate_ updates that would break compatibility

The next major version (I'd really like to rapidly followup 0.4 with a 1.0.0 release) will absolutely require 4.0+ and we'll be declaring support of a stable node version such as Node v4.2.4 LTS like you said.

When we do that, we can clean up a bunch of old code and take advantage of new ES2015+ features but I'd prefer to do that as a separate cleanup step from the current major updates.

This is a **soft position**. If something comes up that we want/need and would break compatibility with 0.12 we can drop the requirement for that version. Node 4+ has been out long enough that I don't think it's unreasonable to require it, let's just see how we go.

**Comment by JedWatson** [comment]
Also @christroutner thanks for that detailed log of how to get it working; looks like an issue in the mongodb driver, any chance you could open an issue on that repo & follow it up with them?

If mongoose or mongodb break compatibility with 0.12 we'll have to pin the version or follow them, but I would be surprised if it doesn't come with a major version bump...

**Comment by christroutner** [comment]
Sure @JedWatson. I opened an issue in MongoDB's bug tracking forum:
https://jira.mongodb.org/browse/NODE-659

**Comment by christroutner** [comment]
I don't totally understand their response:

Version 1.4 is not supported by Node 5.5.0. We only guarantee support for LTS

See the comments in the bug report:
https://jira.mongodb.org/browse/NODE-659

**Comment by creynders** [comment]
They mean they made sure 1.4 works in node v4, but don't bother to do the same for v5, since it's not LTS. Which totally makes sense.
