### ISSUE TITLE
When using Knex, it does not create table

### ISSUE THREAD

**Issue by james1888** [keystonejs/keystone#2136]
# Bug report

## Describe the bug

When using Knex, it does not create table.

## To Reproduce

`yarn create keystone-app todo-app`

project name: todo
template: Todo
adaptor: knex

`createdb todo`

## Expected behaviour

When I go to check if the table exists in pgAdmin, it does not.

## Screenshots

![image](https://user-images.githubusercontent.com/8617506/71239737-e62c6a80-2339-11ea-8d2f-370ca4ff50cf.png)

![image](https://user-images.githubusercontent.com/8617506/71239759-f9d7d100-2339-11ea-96e6-bbca6f3cb7a9.png)

## System information

- OS: macOS
- Browser (if applies): Chrome

**Comment by thomascallahan** [comment]
Same here, but on Windows. If I manually create the table and rows, it kind of works but I'm clearly not setting something up in the ID field correctly because newly-created items have blank IDs. Everything works just fine when using MongoDB. 

I've been working on a very large and complicated project for about a year now using MongoDB and Keystone 4. For a smaller personal project I wanted to try Keystone 5 and my web host offers Postgres so I was hoping to use it rather than pay for MongoDB hosting somewhere separate from my web host. Between this issue and what seems to be the need to manually add rows and tables anytime the data model changes, Postgres may be more trouble than it's worth.

**Comment by dijs** [comment]
I am having the same issues. No tables are created on initialization. It's very frustrating.

**Comment by MadeByMike** [comment]
This is expected behaviour. You'll need to run `yarn create-tables` see the quick start guide here: https://www.keystonejs.com/quick-start/
