### ISSUE TITLE
When to remove Object.assign polyfill

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#2139]
We are relying on `object-assign` npm module [here](https://github.com/keystonejs/keystone/blob/3927e817370f91ed52e709479cec476e1bebe484/lib/content/page.js#L2). When do we know to remove this polyfill?

**Comment by ericelliott** [comment]
On the browser, it's probably better to use [Polyfills.io](http://polyfills.io/). `Object.assign()` is not supported in any version of IE, so it will need a polyfill for 2-3 more years, I would guess.

On the server, if we drop support for 0.12, we can remove the polyfill now, because `Object.assign()` is supported in Node 4.x+.

**Comment by mxstbr** [comment]
We're going to keep supporting 0.12 until after the v0.4 release (#2112).

Closing this issue as @ericelliott answered the question perfectly!
