### ISSUE TITLE
LocalFileAdapter publicUrl is not a URL

### ISSUE THREAD

**Issue by Abogical** [keystonejs/keystone#2157]
# Bug report
## Describe the bug
When using the `LocalFileAdapter`, the `publicUrl` returned from the GraphQL query is a relative path, not a URL.
## To Reproduce

1. Setup a list which contains a field using the `LocalFileAdapter`.
2. Create a record which fills that field.
3. Query the `publicUrl` of that field via GraphQL.
4. GraphQL response for `publicUrl` is a relative path.

## Expected behaviour

GraphQL response is expected to be a URL. If this was the intended behaviour, `publicUrl` is a misleading name.

## System information

- OS: Linux
- Browser: KDE Falkon (Uses WebKit).

**Comment by gautamsi** [comment]
This may be correct behavior as you do not know what exactly is the url someone is accessing. the app may be running behind apache or nginx proxy, you can map that url if you need them in client app.

**Comment by Abogical** [comment]
I was under the impression keystone would serve these files automatically. Do I have to add a [static app](https://www.keystonejs.com/keystonejs/app-static/) to serve these static files?

**Comment by gautamsi** [comment]
Yes

**Comment by Abogical** [comment]
@gautamsi Thanks! You can close the issue, but I believe this may need to be better documented. Maybe `publicUrl` should've been `path`?

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
