### ISSUE TITLE
Easy way to open item without Label column

### ISSUE THREAD

**Issue by karmux** [keystonejs/keystone#2166]
# Feature request

## Is your feature request related to a problem? Please describe.

When you hide Label column then it's not possible to open a document from the list anymore since Label is the only clickable column. Workarounds include manually editing URL in the browser or copying link from the three dots (...) menu and pasting it to the URL in the browser.

## Describe the solution you'd like

Add a new menu option `Open` under the three dots (...) menu of the list item. As a result there will be three options in that menu in the following order: `Open`, `Copy Link` and `Delete`.

## Describe alternatives you've considered

- entire row is clickable (configurable)
- there's a small clickable icon between checkbox and first column on each row that opens that document in the detailed view (configurable)

## Additional context

n/a

**Comment by ayush-goyal** [comment]
How do you configure Keystone so the entire row is clickable? Also, is there a way to hide the label column?

**Comment by gautamsi** [comment]
fork admin ui and use it in your package or monorepo

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
