### ISSUE TITLE
Unable to align CloudinaryImages within Content field

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#2230]
# Bug report

## Describe the bug

Clicking a CloudinaryImage no longer displays options for left/center/right alignment.

## To Reproduce

![no-image-alignment](https://user-images.githubusercontent.com/612020/72231478-ca05ab80-360f-11ea-831c-21b2e6b3672b.gif)

Interestingly, if you highlight the image, the options appear:

![alignment-select](https://user-images.githubusercontent.com/612020/72231489-d853c780-360f-11ea-8f03-b3151a64da84.gif)

But then weirdness happens with where the `+` appears (ie; not on the line below)

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
