### ISSUE TITLE
Admin interface flyout: Fields lose focus when user presses shift

### ISSUE THREAD

**Issue by aminimalanimal** [keystonejs/keystone#2237]
# Bug report

## Describe the bug

In the admin interface, pressing shift causes fields in the Create flyout to lose focus. This makes it difficult to type uppercase letters and special characters without saving a new item, then editing that item in its dedicated page.

## To Reproduce

1. Generate a new project if you don't already have one. My project was generated today from `npm init keystone-app` with Nuxt and Mongoose selected
2. Run `npm run dev`
3. Navigate to http://localhost:3000/admin in your browser
4. Click Todos in the lefthand bar
5. Click “+ Create” in the upper righthand corner. The `name` field should be focused
6. Hold shift to start typing in a name.

The field loses focus.

## Expected behaviour

The field should not lose focus, allowing capital letters and special characters to be input into the field.

## System information

- OS: macOS Mojave 10.14.6
- Browser: Chrome, Safari, Firefox

**Comment by mattwaler** [comment]
Was just about to open this issue!

**Comment by tvanantwerp** [comment]
It appears the the `shift` key is triggering renders further up the component tree that just pressing other keys. Probably that's why focus is being lost. I tried digging through the component tree and the source code, but I wasn't able to identify a clear reason for this.

![Jan-17-2020 12-33-48](https://user-images.githubusercontent.com/2487968/72633099-bd41ca00-3925-11ea-865c-71567133e851.gif)

**Comment by Vultraz** [comment]
Is this still a problem with the latest `app-admin-ui` package? I cannot reproduce this.

**Comment by Sylchi** [comment]
still there in 5.9.5

**Comment by Vultraz** [comment]
I really still cannot reproduce this... 🤔

**Comment by Sylchi** [comment]
Search box rerenders when shift is pressed. Only way to make capital letters is with Caps lock or pasting

**Comment by Sylchi** [comment]
This issue still persist within the latest version

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
