### ISSUE TITLE
Add docs for `create-keystone-app` CLI args

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#2276]
New CLI args were added in #2273 - we need to document them.

**Comment by gabipetrovay** [comment]
@jesstelford Let me give you a PR for it as well.

Do you know if changesets are also required for documentation updates? I see that there would be at least 2 packages changed with this update: the create app (for all arguments) and some guides updates with code samples. Does it sound right?

**Comment by jesstelford** [comment]
If it's purely docs, no changeset is required (as we don't "release" the docs), but if it includes changes to a package's README, etc, then we usually just add a `patch` bump to ensure the docs make their way to npm.

**Comment by gabipetrovay** [comment]
👍

**Comment by jesstelford** [comment]
Actually, I take that back; you should do a patch bump for the `@keystonejs/website` package. I don't think it requires it, but good to be consistent.

**Comment by gabipetrovay** [comment]
And another question on my previous changeset.

When I created it, I bumped the minor version. But I still see in the repo that this package still has the old version (`1.4.1`) instead of a bumped (`1.5.x`) what I was expecting. Do you know if this [package.json](https://github.com/keystonejs/keystone/blob/master/packages/create-keystone-app/package.json#L4) will be updated by some other tools (upon release for example?)
