### ISSUE TITLE
Module parse failed in /admin/signin

### ISSUE THREAD

**Issue by sinbargit** [keystonejs/keystone#2283]
There is a blog demo in the demo-projects dir, after I try to run it there is a error at /admin/signin:
```
Uncaught Error: Module parse failed: Unexpected token (32:4)
You may need an appropriate loader to handle this file type.
| 
|   return (
>     <ApolloProvider client={apolloClient}>
|       <ToastProvider>
|         <ConnectivityListener />
    at Object../public.js (module.js:22)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object.0 (module.js:22)
    at __webpack_require__ (bootstrap:723)
    at bootstrap:790
    at bootstrap:790
```

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
