### ISSUE TITLE
Custom mutations from lists missing in the GraphQL 

### ISSUE THREAD

**Issue by wbarcovsky** [keystonejs/keystone#2319]
# Bug report
Custom mutations, defined in the lists is not apllied in the GraphQL

## Describe the bug
I tried to execute mutation "startPasswordRecovery" from meetup demo project and got error
```
Cannot query field \"startPasswordRecovery\" on type \"Mutation\".
```
Trying to use this functionality from web page ends up with the same result

## To Reproduce

1. Start meetup demo
2. Go to the graphQL console
3. Execute mutation
```
mutation {
  startPasswordRecovery(email: "test@mail.com") {
    id
  }
}
```
4. GraphQL send error message
5. Mutation also missing in the mutations list

## System information

- OS: Linux mint 19.2
- Browser: Google Chrome

## Additional context
Mutations that I add with `keystone.extendGraphQLSchema` works just fine

**Comment by gautamsi** [comment]
Those are moved into `keystone.extendGraphQl` function, no longer list level.

It would have been great to keep this functionality instead of consolidating. As related features should be kept together. I could create global level queries and mutations with `extendGraphQl` and also have some list level graphql customization to keep related things together.

**Comment by gautamsi** [comment]
this should close, the meetup demo site has been fixed.
