### ISSUE TITLE
access control serialization vs graphql endpoint

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#2321]
Would this be possible to run access control queries in nodejs and expose their outcome over graphql? 

What I mean is `maybeAccess` which is true for function type can be queried over GraphQL and not need to be derialized. 

generic true and false should be good and serialized and when it is function we can wrap that in a graphql query which can be queried when updating or creating item.

obviously there will be edge case when the access depends on input field value.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
