### ISSUE TITLE
Understanding the change from Bootstrap to Element UI in 0.4

### ISSUE THREAD

**Issue by EduardoAC** [keystonejs/keystone#2331]
Can I ask why did you leave Bootstrap framework for Element UI instead of create automated npm upgrading? 

I'm interested about this core have an improvement from Bootstrap Option when we have browserify with Bootstrap and Bootstrap 4.0 is coming out.

**Comment by morenoh149** [comment]
Closing as not an issue. For discussion please use the [gitter](https://gitter.im/keystonejs/keystone)

reading http://elemental-ui.com/

> Why build another UI kit?

> 
> We believe there is a need for a high quality, modular set of UI scaffolding components and controls for React that are built from the outset to natively implement React patterns.
> 
> Elemental UI has been born to solve real-world requirements in projects we work on, and for use in the node.js content management platform KeystoneJS.
> 
> Our goal is to create a set of functional and unopinionated components that are useful on their own or together, with an unobtrusive default style and flexible theme capabilities.
> 
> Thanks and credit go to the many other great CSS Component libraries that have been developed and whose shoulders we stand on, especially Bootstrap.

another point is Jed is the owner of both projects so it'd be natural to dogfood it here

**Comment by JedWatson** [comment]
@EduardoAC to add some more depth to the reasoning:

- Bootstrap has moved to SASS with v4 so there'd be some rework anyway since we've invested heavily in LESS in the past
- Bootstrap's built-in components use jQuery which we're trying to completely remove from Keystone
- We were maintaining our own React components with Bootstrap classes applied sporadically, and it wasn't particularly robust / clear what was going on
- We want to develop Keystone's unique UI design over time, not be bound to Bootstrap's generic styling

I'm aware of projects like `react-bootstrap` but fundamentally to implement what we have in mind, we want to be in control of our own UI framework, and the best way to do that and have a robust, we'll tested and documented outcome is to open source it as its own project, which is why we created Elemental UI.

While that project could have lived entirely within Keystone, it would then have been less valuable to the whole community, and we ourselves have used it on a number of React front-ends so it's been :+1: so far.

**Comment by EduardoAC** [comment]
@JedWatson, you are pointing really good reasons to create this new framework that I agree with all of them. The point to avoid JQuery is great even AngularJS tend to use. 

Your explanation, it's what I was looking for in the Elements UI website but I couldn't find it and I put the subject here because the core team is not often involve in the chat at least when I connected. 

I would love push forward this framework And contribute to do it possible.
