### ISSUE TITLE
Support PassportAuthStrategy in Keystone5 Admin UI

### ISSUE THREAD

**Issue by PoulpiFr** [keystonejs/keystone#2334]
# Feature request

## Is your feature request related to a problem? Please describe.

Using Passport based Oauth2 to handle the Admin UI auth would be handy in order to force the use of our Oauth2 provider instead of storing our Admin Passwords in Keystone and rely on Admin UI login page.

## Describe the solution you'd like

Handle the Passport based auth strategy in the Admin UI application.

## Describe alternatives you've considered

We can store all our Admin passwords in Keystone DB and use the Password auth strategy. But we're stuck with Keystone to store our Admin Passwords, which we would like to avoid at some point.

## Additional context

See: https://github.com/keystonejs/keystone/blob/master/packages/app-admin-ui/index.js#L29

I'm not sure what is the need of `@keystonejs/auth-passport` without this feature to be honest.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
