### ISSUE TITLE
if condition both true and false conditions have same code

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#2346]
# Bug report

## Describe the bug

https://github.com/keystonejs/keystone/blob/905f9542987b385130111e528ad90f43ce919880/packages/fields/src/types/Virtual/prettyData.js#L18

if condition above both true and false conditions have same code

## Expected behaviour

Update the logic

**Comment by MadeByMike** [comment]
Since we don't know what data we are getting back from a virtual field it's hard to know how to display it. The plan is to add more logic here to handle different types of data as best as possible.

Can we change the scope of this issue to be improving the presentation of different data types?

A quick list might be:

  - Images
  - String
  - Number
  - JSON
 - Boolean
 - Array
 - null/undefined
 
Any other special types like images that I am missing? Maybe we could do something special with URLs and IDs... I wonder if we can even defer rendering to the field cell view, if we can determine the Keystone field type 🤔 

There is a lot we can do but the goal is a simple and useful.

**Comment by MadeByMike** [comment]
I'm going to close this issue since there is a todo in the code:
```
// ToDo: Better presentation for more types of data
```
The if statement exists to demonstrate where it should be improved. Future issues should implement the above suggestions ☝️
