### ISSUE TITLE
Unable to update OEmbed urls in content editor

### ISSUE THREAD

**Issue by SeanDoyleGit** [keystonejs/keystone#2357]
# Bug report
Unable to update the URL for an OEmbed block in the content editor

## Describe the bug
In the content editor Users are able to save OEmbed blocks with links to external site or videos.

Once the content is saved the user can update the OEmbed to a different URL. However when the user saves, the OEmbed does not update its URL and is reset to the original URL.

The root issue is probably because the content editor uses a relationship query `create` when the OEmbed is first created, but then uses the relationship query `connect` for all following saves.

The solution is to change the content editor to replace the OEmbed with a new one whenever the URL is changed.

![OEmbed issues](https://user-images.githubusercontent.com/42298774/74213157-12d28200-4cec-11ea-93bc-f7abfd79c320.gif)

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
