### ISSUE TITLE
editor.js Keystone is not defined error

### ISSUE THREAD

**Issue by programmer4web** [keystonejs/keystone#2357]
var href = Keystone.adminPath + '/' + data.path;

file path: keystone\admin\public\js\content\editor.js

where is Keystone defined on frontend?

**Comment by jacargentina** [comment]
@JedWatson I can't find where is _used_ the file `admin/public/js/content/editor.js`. It's obsolete?

**Comment by creynders** [comment]
Could it be the same problem as in #2374 ? If so, please downgrade node to v5.6

**Comment by JedWatson** [comment]
`editor.js` is old, but not obsolete - it simply uses jQuery to pick up on data attributes and add "edit" buttons into the front end that link into Keystone.

Turns out this was a bug introduced recently when the path to the Keystone Admin UI was made dynamic... I'll fix it now so it defaults to `/keystone` if there's no config option set.
