### ISSUE TITLE
[AdminUI] Field Oembed Iframely adapter: Can't pass optionnal parameters

### ISSUE THREAD

**Issue by maximelebreton** [keystonejs/keystone#2371]
Hello,

We should pass optionnal parameters to Iframely's adapter,

Like in this example: 
https://iframely.com/embed/https%3A%2F%2Fsoundcloud.com%2Fluuuge%2Fno-mj?_hide_comments=true&_horizontal=true

We can specify:
`_hide_comments=true&_horizontal=true
`  

So we **should** do this:
```js
const iframelyAdapter = new IframelyOEmbedAdapter({
  apiKey: "...", // Get one from https://iframely.com
  _hide_comments: true,
  _horizontal: true
});
```
But this is not the case.

Thanks!

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
