### ISSUE TITLE
[AdminUI] Possible to disable fields according to other field value?

### ISSUE THREAD

**Issue by maximelebreton** [keystonejs/keystone#2372]
Hello,

Is it possible to show/hide or enable/disable some other fields according to an other Select field value (in the same list).

**Example:**
```js
const options = [
  { value: 'TEXT', label: "text" },
  { value: 'CHECKBOX', label: "Checkbox" },
  { value: 'COLOR', label: 'Color' },
];

keystone.createList('Rsvp', {
  fields: {
    choose: { type: Select, options },
    ifText: { type: Text }, // enable/show only if choose value is TEXT
    ifCheckbox: { type: Checkbox }, // enable/show only if choose value is CHECKBOX
    ifColor: { type: Color } // enable/show only if choose value is COLOR
  },
});
```

Thanks!

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
