### ISSUE TITLE
prefill props in createItemmodal doesn't generate correct mutation object 

### ISSUE THREAD

**Issue by wuichen** [keystonejs/keystone#2374]
# Bug report

## Describe the bug

prefill props in createItemmodal doesn't generate correct mutation object on relationship fields. The UI looks correct, but doesnt save correctly when clicking create.
 
## To Reproduce

1. setup title and page field in prefillData
`{title: 'something', page: 'someid'}`

2. open admin list and click create.

3. createitemmodal pops out with correct title and page information in the UI

4. click create -> doesnt save correctly and shows the error in network tab. check image

## Expected behaviour

should create correctly according to the prefilldata on relationship field

## Screenshots
<img width="639" alt="Screen Shot 2020-02-16 at 4 58 36 PM" src="https://user-images.githubusercontent.com/6353587/74601859-a5ed2c80-50dd-11ea-8c5d-241342dd6668.png">
<img width="1030" alt="Screen Shot 2020-02-16 at 4 55 38 PM" src="https://user-images.githubusercontent.com/6353587/74601860-a84f8680-50dd-11ea-8bc0-8799d4bb59f8.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]

**Comment by gautamsi** [comment]
after the recent refactor you can not use this form for duplicating data, you can only have one instance of `<CreateItemModal />` usually that is rendered on list page and item page. if you try to use some hook, it will open both window.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
