### ISSUE TITLE
Installing keystonejs project dependencies fail

### ISSUE THREAD

**Issue by danielrvt** [keystonejs/keystone#2391]
It seems like keystone has to many dependencias and npm just runs out of memory. See this: [http://stackoverflow.com/q/35880189/1348596](http://stackoverflow.com/q/35880189/1348596) for details

**Comment by snowkeeper** [comment]
Have you deleted the node_modules directory and run `npm install` again

**Comment by radiovisual** [comment]
Sometimes it takes me a few tries as well, but this isn't a keystone problem, it's a problem with npm. I run into this same problem when I attempt to install modules that have lots of dependencies. Something that works for me is to run `npm install -ddd` to get the super-verbose output. It [could be that there are race conditions somewhere in the install process](https://github.com/npm/npm/issues/7862#issuecomment-93998432), and running the install with the verbose output creates a few extra milliseconds, decreasing the chance of certain race conditions. It does seem to help me most of the time, but it could just be a coincidence...

**Comment by radiovisual** [comment]
Because I have this problem a lot (not necessarily with Keystone, but with other large modules), I [wrote a small utility](https://github.com/radiovisual/npm-install-que) that might help ease the pain when installing dependencies on large projects. It's a wrapper around `npm install` that basically installs the modules one at a time while keeping a list of modules that failed. This information can be useful because it helps you find the problematic modules, and also lets you focus your diagnosis (or re-install attempts) on only the failed modules, instead of having to re-install the entire stack of dependencies all over again.

**Comment by mxstbr** [comment]
> this isn't a keystone problem, it's a problem with npm.

I'll close this issue, if you think this is a bug related to keystone feel free to comment/reopen!
