### ISSUE TITLE
How do the custom Admin pages work in the demo-projects/blog example?

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2398]
This is not an issue per se, but we are looking to use Keystone in a large project but we would want to be able to customise the Admin panel.  I've been reviewing https://github.com/keystonejs/keystone/pull/1019/files as well as looking at https://github.com/keystonejs/keystone/tree/master/demo-projects/blog and although it looks good, I don't understand the logic behind it, that is, what we would need to implement to make it work. 

Is it the case that when you use the Keystone NextJS app (which is good for us), if you add a folder `/admin/pages` the Keystone app will look there and use those custom admin pages instead of the regular ones?  What are the possibilities and constraints in this setup?  I'm assuming we have full access to the rest of the app, the controllers, the DB from these pages as well....

I also noticed that @JedWatson notes in https://github.com/keystonejs/keystone/pull/1019 that 

> Note this lacks SSR support, and I didn't put as much effort into the examples, but it's otherwise (I think) identical in functionality.

Does it lack SSR support just for the admin part, or does adding custom admin pages somehow affect SSR support in the rest of the app? (SSR is the reason we're using next)

Thanks for any info.

**Comment by justintemps** [comment]
I would also be very interested to know how the custom pages work.

**Comment by MadeByMike** [comment]
It's all documented here: https://www.keystonejs.com/keystonejs/app-admin-ui/#pages 

What are the possibilities and constraints in this setup? - I't basically just a page that becomes part of a react application. Using the graphQL API you can do anything you could do in the adminUI however you'll need to build your own components. We do export some components from the adminUI as well as hooks allowing you to use parts of the AdminUI interface in your custom pages. Putting this together is up to you, it's mostly just a blank canvas.

I _think_ there is no SSR support for custom pages currently.

**Comment by gautamsi** [comment]
@ra-external I guess you wanted to know if the no-ssr would affect your rest of next-js app

No it does not affect the rest of app, in fact you would not be able to use these pages in your nextjs pages due to reason that when you use pages in admin-ui custom pages you are assuming some of the hooks and routing available for you. which makes it easy to integrate with the flow. 

I have used custom pages only to make it feel like part of admin ui, if you customize look and feel of it like rest of nextjs app then probably better to use nextjs/graphql outside of the admin-ui. 

I have moved most of my code to hooks.
