### ISSUE TITLE
Upload file from backend using keystone.executeQuery

### ISSUE THREAD

**Issue by tomasgvivo** [keystonejs/keystone#2399]
I'm trying to make fixtures for my keystone application's stage environment and I need to create file uploads from the backend.

I can not find any example on how to "upload" a file using `keystone.executeQuery()`.
Is it even possible?

**Comment by gautamsi** [comment]
see example here - 
https://github.com/keystonejs-contrib/keystonejs-contrib/blob/a27031ddc1c0b101a93bac3cba861774c9083abd/examples/blog-view/routes/views/new-post.js#L32
this is how you would populate the input field for graphql query.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
