### ISSUE TITLE
Virtual field orderBy doesn't sort correctly

### ISSUE THREAD

**Issue by JuhG** [keystonejs/keystone#2400]
# Bug report

## Describe the bug

I'm trying to sort a list by a virtual field, but it doesn't seem to work.
Also adding more "methods" or "computed fields" based on virtual fields are not clear to me.

## To Reproduce

Here's the list definition:

```js
keystone.createList('Comment', {
  fields: {
    // ... other fields
    parent: {
      type: Relationship,
      ref: 'Comment',
    },
    commentCount: {
      type: Virtual,
      graphQLReturnType: `Int`,
      resolver: async ({ id }) => {
        const response = await request(
          'http://localhost:3000/admin/api',
          `query($id: ID!) {
            _allCommentsMeta(where: { parent: { id: $id } }) {
              count
            }
          }`,
          { id }
        )

        return response._allCommentsMeta.count
      },
    },
  },
})
```

## Expected behaviour

The number itself is working and correct, but ordering is incorrect.

## Screenshots

Here's how the items are sorted:

![Screenshot 2020-02-19 at 17 42 40](https://user-images.githubusercontent.com/10765158/74854198-4ee69200-533f-11ea-8df6-d4749acfcfe4.png)

## Additional context

In general I'm not completely familiar how these fields work. For example it looks like it's not possible to reference a virtual field while creating another virtual field. In the example above I couldn't add another field that has a value based on commentCount. Is there a way to create helper methods for this use case?

```js
keystone.createList('Comment', {
  fields: {
    // ... other fields
    doubleField: {
      type: Virtual,
      graphQLReturnType: `Int`,
      resolver: async item => {
        return item.commentCount * 2 // not possible
      },
    },
  },
})
```

In server land I used to be able to add a new method to a "model class" similar to this:
```
// pseudo code

class Comment {
    public function comments() {
        return DB.all(Comment).where(parent, '==', this.id);
    }

    public function commentCount() {
        return count(this.comments());
    }

    public function doubleField() {
        return this.commentCount() * 2;
    }
}
```

What's the recommended way to do this?
Thanks for the cool library!

**Comment by molomby** [comment]
Hey @JuhG, Keystone doesn't currently support ordering by virtual fields and (as far as I know) has no plans to add this. The limitation is due to how virtual fields work -- the resolver function needs to be evaluated on the application server so, to get the values, the entire item needs to be read from the DB into the node process.

Consider how this would play out if a query like this was performed once your DB has a million comments:

```graphql
query {
   allComments (first: 10, orderBy: "commentCount") { id subject }
}
```

To resolve this, Keystone would need to load _all_ comments out of the DB, call your `commentCount` resolver function for each one, order the set on this value then return the top 10 comments.

This is only a problem because the `commentCount` values are being evaluated when the ordering operation is taking place. If the field was a normal, persisted value, the ordering operation can be palmed off to the database engine.

That's what you should probably be doing in this case -- flattening the `commentCount` values out into a standard `Integer` field that's stored in the DB. The value only changes (needs to be recounted) when a comment is added, not when they're read out or ordered. You can use the [hooks functionality](https://github.com/keystonejs/keystone/blob/master/docs/api/hooks.md#list-hooks) to update the cached counts anytime a child comment is created or deleted. I'd suggest the `afterChange` and `afterDelete` hooks since, in this context, you're updating the parent, not the item itself.

I haven't run (or linted) this code but something it this should work:

```js
```

**Comment by molomby** [comment]
Hey @JuhG, Keystone doesn't currently support ordering by virtual fields and (as far as I know) has no plans to add this. The limitation is due to how virtual fields work -- the resolver function needs to be evaluated on the application server so, to get the "virtual" values, the entire item needs to be read from the DB into the node process.

Consider how this would play out if a query like this was performed once your DB has a million comments:

```graphql
query {
   allComments (first: 10, orderBy: "commentCount") { id }
}
```

To resolve this, Keystone would need to load _all_ comments out of the DB, call your `commentCount` resolver function for each one, order the set on this value then return the top 10 comments.

This is only a problem because the `commentCount` values are being evaluated when the ordering operation is taking place. If the field was a normal, persisted value, the ordering operation can be palmed off to the database engine.

That's what you should probably be doing in this case -- flattening the `commentCount` values out into a standard `Integer` field that's stored in the DB. The value only changes (needs to be recounted) when a comment is added or deleted, not when they're read out. You can use the [hooks functionality](https://github.com/keystonejs/keystone/blob/master/docs/api/hooks.md#list-hooks) to update the cached counts anytime a child comment is created or deleted. I'd suggest the `afterChange` and `afterDelete` hooks since, in this context, you're updating the parent, not the item itself.

I haven't run this code (so there's probably errors) but something like it this should work:

```js
// Because the afterChange and afterDelete hooks have a similar
// signature, we can reuse the same function
const updateSiblingCount = ({
  operation,
  existingItem, // The child comment that's just been created or deleted
  actions: { query },
}) => {
  // Ignore operations other than create and delete
  if (operation !== 'create' && operation !== 'delete') return;

  // If this is a top-level comments with no parent we can ignore it
  if (!existingItem.parent) return;

  // Get the new, correct count of siblings
  const { errors: readErrors, data: { siblings } } = await query(`
    query($parent: ID!) {
      siblings: _allCommentsMeta(where: { parent: { id: $parent } }) { count }
    }`,
    { variables: { parent: existingItem.parent } }
  );
  if (readErrors.length > 0) rethrow errors[0];

  // Save the new count to the parent comment item
  const { errors: updateErrors } = await query(`
    mutation(parent: ID!, $newCount: Int!) {
      updateComment(id: $parent, data: { commentCount: $newCount }) { id }
    }`,
    { variables: { newCount: siblings.count, parent: existingItem.parent } }
  );
  if (updateErrors.length > 0) rethrow errors[0];
};


// The list
keystone.createList('Comment', {
  fields: {
    // ... other fields
    parent: { type: Relationship, ref: 'Comment' },
    commentCount: { type: Integer, defaultValue: 0 },  // Just a standard field
  },
  hooks: {
    afterChange: updateSiblingCount
    afterDelete: updateSiblingCount
  },
});
```

Notice too our use of the `query` function (from the `actions` argument). This gives us direct access to the GraphQL schema without needing to "query ourselves" over HTTP, using `request`. It's covered in the hook docs.

**Comment by JuhG** [comment]
Awesome thanks, that makes a lot of sense!
Using next.js is that `actions: { query }` function somehow available in a `pages/api/` file?
