### ISSUE TITLE
Hidden option fo field or autohide.

### ISSUE THREAD

**Issue by ds-codemag** [keystonejs/keystone#2426]
I think that if user hasn't access to edit some fields or all lists it should be unvisible for him. Now when i take acces to edit for e.g. password field user still see this and even can edit but when he is saving form he gets alert that he can't edit this field or list. I think that this is not user friendly. And i think if user hasn't acces to create or delete items from list buttons should be hidden to. It will be more more user friendly.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
