### ISSUE TITLE
Move Core DB Adapters code from @keystonejs/keystone package into their own

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#2446]
I suggest we split the code for keystone and the base adapters. this way there will be no dependency to keystone package. 

IF I wanted to fork the keystone package and this being a dependency for adapters, you are forced to create two pacakges and there may be more dependency chain.

keystone and admin-ui is prime candidate for forking out if I need to use custom actions/UI hooks, which is taking very long in conception even after basic infrastructure are in place. We could have shipped the suggestions in https://github.com/keystonejs/keystone/issues/1054#issuecomment-485860330 and came back later to improve, unfortunately taking forever. 

I can create a PR for `@keystonejs/adapter-base` if it makes sense. this change should not affect any consuming code unless they have used custom adapters. 

I found that all fields are dependents on adapters and the chain goes on, we have to split this to make it possible for easy customizations.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
