### ISSUE TITLE
Use npm dist tags

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#2448]
I think it would be a good idea to use npm dist tags and release more often to npm. I.e. I'd go for `stable` for v0.3.x and `next` or something for v0.4.x
Related to keystonejs/keystonejs-site#76 You could set it to

```json
{
  "dependencies": {
    "keystone": "stable"
  }
}
```

and be done with it.

Also, I think people will try out v0.4 a bit faster if it's released on npm

**Comment by kadosh1000** [comment]
I agree, the only reason I don't use v0.4 is that it's not on npm and I don't want to complicate my deployment process.

**Comment by mxstbr** [comment]
Sounds like a great idea :+1: PR maybe?

**Comment by mxstbr** [comment]
To give an update on this: I think this is a very good idea to give early adopters a fast way to a new version.

The problem with 0.4 is that a lot is borked and in a state of transition at this very moment, and we cannot have people using it like this. Enabling users to use it right now would increase the noise in the repo a lot without being that helpful since we're aware of the grave problems.

I'll close this issue for now and release a version under the `next` tag as soon as I can responsibly say that we have a useable version. (hopefully that time's not far away!)
