### ISSUE TITLE
crono and moment

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#2493]
I see the use of moment in `TextDayTimePicker` component in `@arch-ui/day-picker` is due to `chrono-node`

```js
  // why are we using moment when it's so large and provides a mutable API?
  // because chrono uses it and consistency is nice and
  // will probably make bugs with conversion less likely
```

now that `chrono-node` is moved on to dayjs, should we refactor the use of moment with wither `dayjs` or with `date-fns`. 
caveat is that `date-fns@v2` has incompatible formatting strings with both `moment` and `dayjs`

**Comment by Vultraz** [comment]
date-fns v2 has an option (I can't remember which exactly, I just remember it was there when I was looking into updating to it last year) to disable warnings about the old-style formatting strings.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
