### ISSUE TITLE
extend use of labelField option

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#2496]
Admin UI currently always shows Label field which can be configured using `label` or `labelResolver`

I want to have Label column (first one) to be replaced with the field I say in `labelField` config. This way my list is clean and I can have clickable link on labelField I want not a default `Label`. 

also the `linkField` config in ListTable and `ListRow` is not exposed to list. this should be good option to have this in list config to show link on specific field as well as option to hide Label field.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
