### ISSUE TITLE
ResolveInput Hook for File field not saving data correctly

### ISSUE THREAD

**Issue by mherrema** [keystonejs/keystone#2503]
# Bug report

## Describe the bug

When using the `File` field type on a list along with the `resolveInput` hook, data isn't being saved correctly, resulting in some fields being blank in the admin ui.

## To Reproduce

1. Create a list that uses the `File` field type (using local file in my case)
2. Add a `resolveInput` hook to the field as follows:
```
hooks: {
         resolveInput: ({ resolvedData, }) => resolvedData
}
```
3. Upload a file/item to that list (I tested with an mp3 file)
4. See a blank field listed for the file name

## Expected behaviour

The file field should allow the `resolveInput` hook to manipulate (or simply return in this case) the `resolvedData` object and save the file correctly and display the file name.

## Screenshots

![Screen Shot 2020-03-09 at 9 30 58 PM](https://user-images.githubusercontent.com/3245025/76271106-c415fa80-624d-11ea-9afb-1b1da9a66a3b.png)

## System information

- OS: macOS
- Browser: Chrome

**Comment by Falbana** [comment]
Hi, I encoutered the same problem, turns out that if you use the `resolveInput` hook inside the file field (not after the fields), you have to return only the input file and not resolvedData (resolvedData contains all the data, not only the file)
`file: {`
`  ...`
`  hooks: {`
`    resolveInput: async ({ resolvedData }) => {`
`      var fileInput = resolvedData.file;`
`      ...`
`      return fileInput;`
`}}}`

Hope it helped

**Comment by mherrema** [comment]
Interesting, I'll give that a try, thanks. Maybe this will prompt an update to the documentation then.

**Comment by ra-external** [comment]
That's it, see https://github.com/keystonejs/keystone/issues/2508

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
