### ISSUE TITLE
Improve createAuthStrategy docs and error messages

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#2584]
<img width="480" alt="Screen Shot 2020-03-25 at 8 36 07 am" src="https://user-images.githubusercontent.com/616382/77479375-c4301000-6e73-11ea-8c5d-f7bc8f66cc9a.png">

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
