### ISSUE TITLE
gqlName for authenticateUserWithPassword is undefined

### ISSUE THREAD

**Issue by EricKit** [keystonejs/keystone#2589]
# Bug report

When doing field level checks on access control the field `gqlName` is undefined when authenticating a user with `authenticateUserWithPassword`. 

This is a problem because no user is currently logged in when this check runs, so `accessItem.authentication` is `{}`. To get information that isn't accessible to the public (ie is admin only or only the user himself can see) on this mutation, the only way I see to set up the access controls is to check if the `gqlName` is `authenticateUserWithPassword` and an `existingItem` exists or if `accessItem.authentication` does exist do the standard  `isAdmin` / `isUser`.

## To Reproduce

Check the AccessItem.gqlName on a `authenticateUserWithPassword` in a field access control check.

## Expected behaviour

gqlName is `authenticateUserWithPassword`

## Additional context

On https://github.com/keystonejs/keystone/blob/master/packages/keystone/lib/List/index.js line 503 (And 643, but not this bug) the 6th argument is not there. That is the argument for `gqlName`. To make this work, the 6th argument could read `{ gqlName: info.path.prev.prev.key }`, which works in my case. I didn't do a pull request because I'm sure there is more to this than just that one case.

`packages/keystone/lib/List/index.js` line 503

```javascript
      const access = context.getFieldAccessControlForUser(
        this.key,
        field.path,
        undefined,
        item,
        operation,
        { gqlName: info.path.prev.prev.key }      
      );
```

**Comment by timleslie** [comment]
I believe an alternate solution (for your use case) would be to pass through the `info` object into `getFieldAccessControlForUser` and downstream functions so that system developers can make use of all the different properties it contains.

I also think that trying to pass `gqlName` through to `getFieldAccessControlForUser` is not something we should even be trying to do, since once we're down to the level of resolving field items we don't *really* have good info on what kind of a request it came from (e.g. perhaps it came from a custom mutation or query!).

I'm open to discussions and opinions on both of these points, there's a good chance there are other complications I've not yet considered.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
