### ISSUE TITLE
Render HTML5 input element types: color, date, time

### ISSUE THREAD

**Issue by pll33** [keystonejs/keystone#2636]
This is in reference to #2535. There are some unexpected side effects when adding HTML5 input type attributes to the following input fields: color, date, datetime.

For color and date fields, adding the type attribute will draw the browser's built-in color or date picker when the input is selected. In these cases, it duplicates the existing implementation. 

For time fields (in datetime), the input format needs to be changed from `h:mm:ss a` to `HH:mm:ss` according to [W3 spec](https://www.w3.org/TR/html-markup/datatypes.html#form.data.time). 

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input for browser support.

**Comment by webteckie** [comment]
@JedWatson can you please give some insight as to possible approaches here?  Thanks!

**Comment by ttsirkia** [comment]
Also the input types especially for dates and times are pretty ugly and hard to use in desktop browsers. They work well only on mobile devices. There are also formatting and localization issues.

**Comment by mxstbr** [comment]
I'm leaning towards using our custom inputs, since then it's the same input and styling no matter what browser or OS you use. I think most users that aren't web developers value consistency over proper HTML tags.
Our components admittedly aren't perfect yet, but we'll improve them over time and make them better!
