### ISSUE TITLE
Admin UI: After user signs in, redirect them where they were trying to go

### ISSUE THREAD

**Issue by zenflow** [keystonejs/keystone#2656]
# Feature request

## Problem

When a signed out user tries to access a page in the admin UI, they're redirected to signin. After signing in, they're redirected to the Admin UI home ('/admin`). Then they need to find the link/location they were trying to go to, and navigate there again. This could be easier for the user.

## Proposed solution

When a signed out user tries to access a page in the admin UI, they're redirected to signin with query param `?redirect=/path/to/intended/page`. 
After a user signs in, they're redirected to the `?redirect` path, if it exists, otherwise to the Admin UI home ('/admin`).

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
