### ISSUE TITLE
pass through field attributes to nested fields

### ISSUE THREAD

**Issue by sgireddy** [keystonejs/keystone#2678]
I am working on a function that returns custom object based on "custom attributes". In this case I am using an attribute called "ui". I am able to extract regular attributes in the "init" hook but not "name" which is keystone custom type(Types.Name) which has been handed over to mongoose as name.first & name.last. Looks like keystone has been intercepting attributes but not passing through. 

Ideally I want to extend model-transform to return a JSON string by field attribute (like give me all fields marked as initial or index or ui etc). Please suggest a fix. 

Member.add({
 	name: { type: Types.Name, required: true, initial: true, index: true, ui: true },
	username: { type: String, required: true, initial: true, index: true, unique: true, ui: true },
    	email: { type: Types.Email, displayGravatar: true, ui: true },
    	phone: { type: String, initial: false, required: false, index: true, ui: true },
    	DoB: { type: Types.Date, initial: true, required: true, index: true, ui: true },
	status: { type: Types.Select, options: ['active', 'suspended', 'inactive', 'orphaned', 'deleted'], default: 'active', index: true, ui: true }
});

Member.schema.post('init', function(m){
    var fields = this.model('Member').schema.paths;
    _.forOwn(fields, function(k, v) {
        if(k.options.ui && m._doc[v] !== undefined){
            console.log( v + ": " + m._doc[v]);
        }  
    });
});

**Comment by geloescht** [comment]
You mean while enumerating the fields in a document you get paths that are not defined in the list? This is natural, as you said, because keystone uses subdocuments for some field types. You use mongoose methods only, so you cannot know the structure of the keystone list.
Instead of what you are doing you should a) enumerate the list instead of the document. You would lose all fields not defined in the list. Or b) search the corresponding list by first parsing the path [using split('.') ] and then looking for attributes in the list options object.
By the way, you should avoid accessing properties prefixed with an underscore. Those are mostly used for private props.

**Comment by sgireddy** [comment]
No, put it this way. Here is the code for model-transformer. Let's add a feature to it where it takes a field attribute as an option and generates JSON for only those where this attribute is set. In the example above, I want to ToJSON to extract where attribute "ui: true" to filter fields. My code above extracts all but "name" as it is a complex type and the attribute "ui" is being lost when it was sent to mongoose, I want to preserve the attribute "ui" in the schema so I could use it later, in this case "ToJSON".

function modelToJSON(schema, fn) {
	// support KeystoneJS Lists, which have the schema property nested
	schema = schema.schema || schema;
	schema.set('toJSON', { transform: function(doc, rtn, options) {
		rtn.id = rtn._id;
		delete rtn._id;
		delete rtn.__v;
		if (fn) {
			var result = fn.call(doc, rtn, options);
			if (result) rtn = result;
		}
		return rtn;
	}});
}

exports.toJSON = modelToJSON;

**Comment by geloescht** [comment]
options.ui is never sent to mongoose because it is not a property of the schema field but of the keystone field. Lists and schemata are different things, keystone generates the schema from the list but does not copy options 1:1. This is by design. You should match the the mongoose model to the corresponding keystone list and extract the ui option from it.

**Comment by sgireddy** [comment]
I guess I have a solution (for my problem at least), not sure it is the best solution. For Keystone Lists its pretty easy as we have direct access to the Model and its fields. Need to enhance to allow custom functions the way model-transformer does. 

This wouldn't work for mongoose in general due to subdocuments.

var _ = require('lodash');
function modelToJSON (Model) {      	
	var fields = Model.fields;     
	Model.schema.set('toJSON', { transform: function(doc, rtn, options) {		
		var j = {};        
    _.forOwn(fields, function(k, v) {
        if(k.options.ui && doc._doc[v] !== undefined){
            j[v] = doc._doc[v];                
        }  
    });    
		return j;
	}});
}

exports.toJSON = modelToJSON;
