### ISSUE TITLE
Plugins in keystone JS?

### ISSUE THREAD

**Issue by hamadkh** [keystonejs/keystone#2683]
Is it possible to add plugins into the keystoneJS Admin UI without messing around with its Source code too much ??

**Comment by mxstbr** [comment]
Not yet, extensibility of the admin interface is a big feature we're very much working towards. #2566 is the second big step in the direction, which will be the main point of the 0.4 release which should be released *soon*!

(Also, see #1898)

**Comment by Fogetti** [comment]
+1

I would really love this feature. In my case I would like to have my own text fields with special markdown syntax and preview modes that the [marked](https://github.com/chjj/marked/pull/35) library doesn't support at the moment so I have to modify the marked and Keystone sources also. Another use case would be to use the [Code Sample](https://www.tinymce.com/docs/plugins/codesample/) TinyMCE plugin which is also not possible because it needs custom button icon, and it needs 2 additional external references on the Keystone admin page.
