### ISSUE TITLE
Image upload through AdminUI fails with server error: [Network error]: ServerParseError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2686]
# Bug report

## Describe the bug

When I go to the AdminUI and click on CREATE in my Image list and then click on UPLOAD FILE and select a file, when I click on CREATE a second time (this time inside the little window that opened on the first 'create') to upload the image, the image upload fails.

## To Reproduce

1. Create an Image list using a `LocalFileAdapter` to upload the image

```
// index.ts
const staticPath = 'public';
const staticRoute = '';
const imageFileAdapter = new LocalFileAdapter({
	src: `${staticPath}/images`,
	path: `${staticRoute}/images`
})
```

```
// lists/Image.ts
import { File } from '@keystonejs/fields';
import log from '../util/log';

export default (keystone, { imageFileAdapter }) => {
	log(`file adapter for image ${imageFileAdapter}`);
	keystone.createList('Image', {
		schemaDoc: 'Image for Article',
		labelResolver: item => item?.file?.originalFilename ?? '',

		fields: {
			file: { type: File, adapter: imageFileAdapter }
		}
	});
};
```
2. Add this Image list to Keystone app
3. Boot app and go to AdminUI (AdminUI has AuthStrategy enabled)
4. Go to Image list.  Click on CREATE to create new Image.  Select a file to upload and then click on CREATE a second time to upload it.  

The following errors are traced to the console
 
![error3](https://user-images.githubusercontent.com/60699805/78758526-8e644e80-797e-11ea-9f4d-a175db69cbe3.png)

and the network info is

![error2](https://user-images.githubusercontent.com/60699805/78758317-388fa680-797e-11ea-891e-5f6a2c677a69.png)

## Expected behaviour

The image should upload and be stored on the server and reflected in the AdminUI

## Screenshots

![upload-image](https://user-images.githubusercontent.com/60699805/78758036-c3bc6c80-797d-11ea-8f6b-ba066cba7c7c.png)

## System information

- OS: MacOS 10.14
- Browser: Chrome, Firefox (latest)

## Additional context

Image upload through the AdminUI worked for the first 6 weeks of our project, stopped working about two weeks ago (for reasons unknown, although the code was the same -- change in keystone packages?), _started working again_ last week after an upgrade of all packages, and since a new upgrade in the last two days to the very latest packages has stopped working again, but with different errors.

These are the package versions I have now:

```
  "@keystonejs/adapter-mongoose": "^8.0.1",
    "@keystonejs/app-admin-ui": "^5.9.5",
    "@keystonejs/app-graphql": "^5.1.5",
    "@keystonejs/app-next": "^5.1.2",
    "@keystonejs/app-static": "^5.1.2",
    "@keystonejs/auth-password": "^5.1.5",
    "@keystonejs/field-content": "^5.4.5",
    "@keystonejs/fields": "^9.0.0",
    "@keystonejs/fields-markdown": "^5.1.5",
    "@keystonejs/fields-wysiwyg-tinymce": "^5.2.3",
    "@keystonejs/file-adapters": "^6.0.1",
    "@keystonejs/keystone": "^8.0.0",
    "@keystonejs/list-plugins": "^5.1.4",
    "@keystonejs/oembed-adapters": "^5.1.3",
```

**Comment by npinon** [comment]
+1

**Comment by npinon** [comment]
By the way the problem is the same with Cloudinary files. It's probably due to Apollo client upload

**Comment by npinon** [comment]
If it can help I have solved the problem. It was because I was using an nginx reverse proxy.
By check the logs I have found : 
`2020/05/07 12:34:39 [crit] 20447#0: *6 open() "/usr/local/var/run/nginx/client_body_temp/0000000001" failed (13: Permission denied)`

Solved by giving the right permissions on this folder

**Comment by MadeByMike** [comment]
@ra-external the 400 response tells me something is crashing on your server side. You should get an error in the terminal where Keystone is running.

`Unexpected token < in JSON at position 0` basically means it got a HTML response (400 page) when it expected JSON.

**Comment by ra-external** [comment]
@MadeByMike Thanks -- we solved this a while ago, I can't remember what it was.  I believe, again, updating the Keystone packages might have solved it.

**Comment by mananclassplus** [comment]
not solved yet

**Comment by spaghettiguru** [comment]
We also had this issue and it was indeed solved by updating keystone packages to their latest versions. Looks like the fix was made in @keystonejs/app-graphql package [here](https://github.com/keystonejs/keystone-5/blob/540fe1e6959dfcf65733f7e925470197adec052c/packages/app-graphql/index.js#L48) - by using the graphql-upload middleware directly instead of apollo's integrated one, but I also updated other keystone packages so I can't say if updating only this single package will fix the problem.

I also disabled uploads in apollo config, as suggested [here](https://www.apollographql.com/docs/apollo-server/data/file-uploads/#uploads-in-node-14-and-later), not sure if this is required though.
