### ISSUE TITLE
List Config parameters should be allowed to be functions 

### ISSUE THREAD

**Issue by 3lijah** [keystonejs/keystone#2698]
# Bug report

## Describe the bug

When implementing Wysiwig/TinyMCE as a List field, the `images_upload_handler` key-value is stripped and ignored because it points to a function.

## Expected behaviour

The TinyMCE field should receive this parameter and run the function in it.
## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]

## Additional context

```
package.json:
"@keystonejs/fields": "^9.0.0",
"@keystonejs/fields-wysiwyg-tinymce": "^5.2.3",
"@keystonejs/keystone": "^8.1.1",
```

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
