### ISSUE TITLE
Error: Attempted to execute keystone.query() before keystone.prepare() has completed.

### ISSUE THREAD

**Issue by Megidd** [keystonejs/keystone#2706]
# Bug report

## Describe the bug

Running command `yarn create-tables`, an error is thrown:

```
yarn run v1.22.4
$ keystone create-tables
i Command: keystone create-tables
×
Error: Attempted to execute keystone.query() before keystone.prepare() has completed.
    at Keystone.executeQuery (C:\Users\m3\home-decor-startup-web\node_modules\@keystonejs\keystone\lib\Keystone\index.js:113:13)
    at Object.module.exports [as onConnect] (C:\Users\m3\home-decor-startup-web\initial-data.js:10:22)
    at C:\Users\m3\home-decor-startup-web\node_modules\@keystonejs\keystone\lib\Keystone\index.js:460:37
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createTables (C:\Users\m3\home-decor-startup-web\node_modules\@keystonejs\keystone\bin\commands\create-tables.js:11:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce

I'm following instructions on [quick start](https://www.keystonejs.com/quick-start/), steps:

1. Run `yarn create keystone-app home-decor-startup-web`
2. Answer questions like this:

```
√ What is your project name? ... home-decor-startup-web
√ Select a starter project » Starter (Users + Authentication)
√ Select a database type » PostgreSQL
√ Where is your database located? ... postgres://postgres:surplus@localhost/home-decor-startup
√ Test database connection? ... No / Yes
√ Successfully connected to postgres://postgres:surplus@localhost/home-decor-startup
√ Copying project files
Installing dependencies with yarn. This will take a few minutes.
√ Installed dependencies
```

3. Run `cd  home-decor-startup-web` and then run `yarn create-tables`
4. Upon running `yarn create-tables` command, error is thrown:

```
yarn run v1.22.4
$ keystone create-tables
i Command: keystone create-tables
×
Error: Attempted to execute keystone.query() before keystone.prepare() has completed.
    at Keystone.executeQuery (C:\Users\m3\home-decor-startup-web\node_modules\@keystonejs\keystone\lib\Keystone\index.js:113:13)
    at Object.module.exports [as onConnect] (C:\Users\m3\home-decor-startup-web\initial-data.js:10:22)
    at C:\Users\m3\home-decor-startup-web\node_modules\@keystonejs\keystone\lib\Keystone\index.js:460:37
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createTables (C:\Users\m3\home-decor-startup-web\node_modules\@keystonejs\keystone\bin\commands\create-tables.js:11:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behaviour

I'd expect _quick start_ to go smoothly without any error.

## Screenshots

![2020-04-10 17_01_10-Window](https://user-images.githubusercontent.com/17475482/78991266-cd94ca00-7b4d-11ea-9fa5-a0813efa6969.png)

## System information

- OS: Windows 10
- NodeJS v12.16.2
- `yarn` 1.22.4

**Comment by jesstelford** [comment]
## Workaround

To get you unblocked for now, in your `index.js` file, comment out the following line:

```
  onConnect: initialiseData,
```

Run `yarn create-tables` again (it should succeed now), then uncomment that line.

## Why did it error?

The error is thrown due to `initialiseData` in the demo setup which attempts to run `keystone.executeQuery`.

`initialiseData` is being run during `create-tables` because the table creation process requires connecting to the database, and the sample project has specified `initialiseData` as a function to run once connection is complete (`onConnect: initialiseData`).

## What's the fix?

Related to: https://github.com/keystonejs/keystone/pull/2703, however I don't think that would fix the issue entirely.

If we move the definition of `executeQuery` as per #2703, it will be able run without throwing the reported error. However, mutations will most likely fail as keystone has not yet been told about the GraphQL schema.

Normally, the GraphQLApp tells keystones about the schema during the `prepare` phase (ie; while setting up the express middlewares). But since `create-tables` doesn't need a full express server to run, it's only ever calling `keystone.connect()`, _not_ `keystone.prepare()`.

The fix would be ensuring the schema is registered as part of the `keystone.connect()` call, allowing `create-tables` to continue calling `keystone.connect()`, which in turn calls `onConnected`, which in turn calls `keystone.executeQuery()`, which will then have knowledge of the compiled schema.
