### ISSUE TITLE
View List with label

### ISSUE THREAD

**Issue by aseleznev** [keystonejs/keystone#2758]
If a label is specified for a list, an error occurs when you try to open it with the "View list" button.
1.
<img width="438" alt="image" src="https://user-images.githubusercontent.com/2737115/79451893-bac43e80-8000-11ea-9af0-85a30279ef59.png">
2.
<img width="580" alt="image" src="https://user-images.githubusercontent.com/2737115/79451963-d16a9580-8000-11ea-8f3f-0642e6d80f89.png">
3.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/2737115/79451973-d62f4980-8000-11ea-8342-ab6a174d6ca5.png">

- OS: macOS
- Browser: [chrome, firefox]

**Comment by Vultraz** [comment]
What versions of `@keystonejs/keystone` and `@keystonejs/app-admin-ui` are you using?

**Comment by aseleznev** [comment]
"@keystonejs/app-admin-ui": "^5.9.5",
    "@keystonejs/keystone": "^8.0.0",

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
