### ISSUE TITLE
Huge Admin UI dev bundle

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone#2760]
I noticed the Admin UI dev bundle is really, really large. Haven't checked production size, but it definitely seems like this could be optimized. It often leads to long delays in reloading the admin UI after restarting the server.

![image](https://user-images.githubusercontent.com/3558659/79455292-62a92e80-8038-11ea-9cc1-daf997eb3c1e.png)

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
