### ISSUE TITLE
Do you have any commercial support? Or list of projects based on Keystone?

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#2770]
# Question about Keystone

Ok. For example, I want to use Keystone in my pet project. But I need to know that the Keystone project still exists and will be a supporter after some years.

The list of Keystone based projects can increase my confidence in the choice. Or information about the financing of the Keystone project may also help me. Maybe something about commercial support will help?

Thanks!

**Comment by Abogical** [comment]
Keystone is supported by [Thinkmill](https://www.thinkmill.com.au/?utm_source=github&utm_medium=badge&utm_campaign=react-select)

**Comment by pahaz** [comment]
Yes, but what about projects? It's important to know real-life projects based on the Keystone. Is this a small pet project or some large scale applications ... Who uses it? Where can I find some success stories? Does the Keystone have any success stories?

**Comment by benjibuiltit** [comment]
Valid question... With that said, just going to throw this out there that it's not very likely your non-existent pet project outlast a framework that's been in development [since 2013](https://github.com/keystonejs/keystone-classic/blob/master/HISTORY.md).

Worrying about it's success and the failure of it's underlying framework before it event exists is the definition of premature optimization. If your project is successful, you could always become the commercial support you're hoping Keystone has :)

**Comment by MadeByMike** [comment]
@pahaz yes there are a bunch of large and medium sized, commercial projects using Keystone in production currently. I don't want to discuss any without permission first. Perhaps you should ask  on the Slack so people can willingly offer their own examples.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
