### ISSUE TITLE
UX/Security on fresh installation (yo generator)

### ISSUE THREAD

**Issue by xied75** [keystonejs/keystone#2786]
Hi all,

Got my first try on keystonejs today. Surprisingly I saw my password showing on the home page to the whole world in bold font, not mentioning it would be cached by google and friends. So then I came here to find related issues, without success.

1, what is the design purpose to show me the password I just typed 5 minutes ago in yo?
2, if the password is going to be published free, shouldn't there be a warning in yo?
3, luckily the password is stored with hash and salt in the mongodb, is that because you can't reverse the password from the hash therefore you keep it in _templates/views/index.jade_ in plain text?

Final question, why nobody even bothered?

**Comment by jstockwin** [comment]
Firstly, I'm not a Keystone member, so they may give you a different answer, but from my experience using Keystone I'd say this:

See the note at the end of [this](http://keystonejs.com/docs/getting-started/#runningyourapp-writingupdates) section in the docs. 

"You probably don't want to store your real password in the code, so it's a good idea to set the default password to something simple, then sign in and change it using Keystone's Admin UI after you start your app for the first time."

So yes, it's intended that your password is shown, since yo just creates an update script to add the user. The password is probably stored in plaintext in `updates/0.0.1-admin.js` too. The idea is that you create a default user account, and then log in and immediately change the password. 

To answer your points as best as I can specifically, 
1) For new users who don't really know their way around and have just accepted the default settings in yo, so might not actually realise what the password is. 
2) Perhaps this isn't a bad point. 
3) The only reason the password is shown in index is the same reason as point 1. It's nothing to do with security. The idea is that you log in and change your password, and all the password handling is very secure if done this way. 

Does that answer your question?

**Comment by mxstbr** [comment]
Started typing out the answer, but what @jstockwin said is pretty much perfect! :+1:

I agree that we should probably add a warning, I've opened an issue in the `generator-keystone` repo for it! https://github.com/keystonejs/generator-keystone/issues/182

**Comment by Arcrammer** [comment]
—________________________________________________— WHYYYYYYYYYYY
