### ISSUE TITLE
Better documentation/error handling regarding relationship paths

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#2812]
It appears that the `path` needs to be the plural of the model you are referencing.

In the docs we see the example of 
`User.relationship({ path: 'posts', ref: 'Post', refPath: 'author' });`

But in this case changing `path` to anything other than `posts` causes problems. The [docs](http://keystonejs.com/docs/database/#relationship-definitions) say:
"`path` - the path of the relationship reference on the Model"
which I don't think quite makes this clear. 

Further, if you do set it to something other than posts, no errors are ever thrown, but the admin ui stops working properly, and the browsers console logs errors like:
`Uncaught TypeError: Cannot read property 'expandColumns' of undefined`
but if you didn't open your browsers console you'd never see any error messages, it just wouldn't work properly. 

Is it intended that that `path` has to be the name of the model the relationship is with? 
If yes, could the documentation be clearer here? Should we add some kind of check that throws a meaningful error for this?
If no, then this is a bug that needs fixing.

**Comment by creynders** [comment]
I think this is a duplicate of #2319

**Comment by mxstbr** [comment]
I don't know @creynders, I think this does need some documentation if that's really the case!

**Comment by webteckie** [comment]
I just bumped into this issue as well.  Yes, it seems that previously it was misleadingly fine to set `path` to a field path in the list model defining the relationship.  It seems that today it is more correctly implemented to enforced that it should be the path of the list where the relationship is defined, where that list `path` is defined in the docs as:
```
path String	The path used for the list in the Admin UI. Defaults to a slugified form of key.
```

I think the doc should change slightly to clarify that all options refer to the list where the relationship is defined:
```
User.relationship({ path: 'posts', ref: 'Post', refPath: 'author' });

Options

ref String - the list key of the model that has the relationship field

path String - the list path of the model that has the relationship field

refPath String - the relationship field path in the referenced list
```

I may have to revisit #2319 in light of this as I may have been confused all along :-)

**Comment by creynders** [comment]
Now I'm confused too. What is the difference between `path` and `refPath`? I always thought `path` is just the name you want to give it in the List where you declare the link-back. I.e.

List Post:
author: relationship field to User

List User:
User.relationship({path: 'articles', ref:'Post', refPath:'author'});

Which would mean that User models have a `articles` property with the `Post` references.

**Comment by jstockwin** [comment]
@creynders if you are correct, and `path` should just be any name which the user decides, then there is a bug, since it has to be the name of the model. 

From the docs, my understanding was that `path` should be the user-readable name which will be displayed alongside the user, telling you which posts they have published (in the setting of your example). Whereas `refPath` would be displayed alongside the posts, and say which user authored the post. 

However, it appears that `path` MUST be the model in question. I.e. I think your example would break unless you change `path` from `articles` to `posts`. 

If your example should work, then this is a bug. If this is intended behaviour, then the docs are misleading. IMO this is a bug, and your example should work, but happy to be told otherwise.

**Comment by fiws** [comment]
There seems to be a bug here. I just upgraded my install from some old 4.0 commit and all my models with relationships just broke in the admin UI.
The admin throws `Uncaught TypeError: Cannot read property 'expandColumns' of undefined`
at ~ this line https://github.com/keystonejs/keystone/blob/dcb4e4667a5cbeef4f099af9be81a33e3d5c8921/admin/client/App/screens/Item/components/RelatedItemsList.js#L24

**Comment by webteckie** [comment]
@creynders yeah, and previously `path` seem to have worked that way, which I think is the reason I opened #2319 since that behavior stopped working for me.  Now path, as I defined above, is just the path assigned to the list of the model that defines the relationship.  And refPath is just the field within that list model that defines the relationship.  The question I think would be, is there a need at all to define a local path for the reverse relationship definition?  If not, then I think we're good as-is.  Some people may have to change their reverse relationship configuration as per this thread and we should probably add this to the wiki as a breaking change between 0.3 and 0.4.

**Comment by webteckie** [comment]
@fiws you need to update your reverse relationship configuration as per this threa's recommendation.  @JedWatson is this an intended breaking change or was it unintentional?

**Comment by mxstbr** [comment]
Highly likely unintentional.

**Comment by JedWatson** [comment]
This is a bug introduced in the Admin UI refactor.

To clarify:

Lists have a `key` and a `path`.

The key is the primary way of identifying and looking up a list instance in Keystone. By convention it is singular. It's the first argument you pass to the `List` constructor, and is similar to a Model key in Mongoose. e.g `PostCategory`.

The path is usually derived from the key, and is a lower case dash-separated plural version, appropriate for use in URL paths. It is similar to a collection name in Mongoose. e.g. `post-categories`

When you create a relationship, you specify a `ref` (i.e. the Key of the related list; this is how mongoose `ObjectID` paths are defined, which is where this pattern came from) as well as a `refPath` (i.e. the path in the related list where the source relationship is defined) and finally a `path` (i.e. how the relationship is identified).

The bugs introduced came from a misunderstanding of how these all work when the Admin UI refactor was done. Specifically, Lists were switched to being referred primarily by their `path` because that's how they are sourced from the URL (rather than this being a once-off, it was implemented everywhere). Making matters worse, lists were exported by `path` from a module called `ListsByKey` - which was super confusing. Then, relationships were updated to identify the referenced list with the relationship `path` and not the `ref`. With some setups of keys and relationships, this _almost_ made sense, which is why there was so much confusion. (e.g. for Post Categories, it makes sense to have a relationship with the path `posts` that refers to the `Post` list and the `refPath` `category`, which actually works after this change, because the path of the `Post` list is coincidentally `posts`)

I've addressed this by refactoring the `ListsByKey` module into `Lists` which exports both `listsByKey` and `listsByPath` and fixing up the relationships and other references.

If someone can think of a clearer way to document this I'm all for it, since I have taken this knowledge for granted since the start I've underestimated how clearly it needs to be explained, and someone else may be a better judge of how to do that now I've explained how it all works. If anybody's still not clear, let me know :)

**Comment by webteckie** [comment]
@JedWatson perhaps the option should have been called `refKey` instead of just `ref` :-)

**Comment by jstockwin** [comment]
@JedWatson 
"(e.g. for Post Categories, it makes sense to have a relationship with the path `posts` that refers to the Post` list and the `refPath` `category`, which actually works after this change, because the path of the `Post` list is coincidentally `posts`"

So, the `path` MUST be the name of the model (e.g. it must be `posts` because the model is `Post`), however the `refPath` can be anything? e.g. `category` and not `post-category` for a model `PostCategory`?

**Comment by webteckie** [comment]
Hmmm...I don't think that's how it is after his change :-)

If you have:
```
var ThatList = Keystone.List('ThatList');
ThatList.add({itemList: {type: Type.Relationship, ref: 'Item', many: true}
```
and then you have:
```
var ThisList = Keystone.List('ThisList');
ThisList.relationship({ref: 'ThatList', refPath: `itemList`, path: 'items' }
```

So `items` is a relationship path local to ThisList that refers to the itemList in ThatList.

@JedWatson is this the correct understanding as per your changes?

**Comment by JedWatson** [comment]
@webteckie that is correct.

**Comment by JedWatson** [comment]
> @JedWatson perhaps the option should have been called refKey instead of just ref :-)

I think there are a few things that could be clearer, but it would be inconsistent

In Mongoose when you specify an ObjectID path with a referenced list (which is how we implement Relationship fields)

```
someSchema.add({
  fieldPath: { type: Mongoose.Schema.Types.ObjectID, ref: 'MyOtherModel' }
});
```

Which we've brought across as-is for Keystone:

```
SomeList.add({
  fieldPath: { type: Types.Relationship, ref: 'MyOtherList' }
});
```

And therefore it is consistent to use the same option when specifying reverse-relationships on a List:

```
MyOtherList.relationship({ path: 'things', ref: 'SomeList', refPath: 'fieldPath' });
```

**Comment by JedWatson** [comment]
@jstockwin 

> So, the path MUST be the name of the model (e.g. it must be posts because the model is Post), however the refPath can be anything? e.g. category and not post-category for a model PostCategory?

The `path` can be whatever you like. It's equivalent to the path of a field in the schema. Think of it as a unique key on the List representing that relationship.

The `refPath` is the `path` of the field in the `ref` (list) that you are _referring_ to. Think of it as the path of a field in the list where the relationship data is actually stored.

I'm just saying that, coincidentally, the path in my example _could_ be `posts`, which also happens to be the `path` of the List that `ref` points to, which means the example would still continue working even with the broken implementation before my fix. Other configurations would break however, due to the bug.

**Comment by jstockwin** [comment]
Okay, so the docs are correct. I think it's just wording like `the path of the relationship being referred to in the referred Model` that can be quite confusing. It's very specific, and says the correct thing. It just needs reading a few times. 

It should perhaps be made extra clear which ones need to be a certain name, and which ones we can choose. I.e. if the relationship has been added in `ThatList`, then the `refPath` in `ThisList` has been determined, whereas I can choose whatever `path` I like. 

Also, the fact that the `ref` on `ThisList` and on `ThatList` don't match up is initially confusing until you understand what's going on, however I think the docs are very clear here.

**Comment by JedWatson** [comment]
I think it's clearer when there's not _also_ a new bug that's just been introduced 😉

**Comment by jstockwin** [comment]
Yeah, that helps too :)

We could always just add a note in the docs linking to this thread for anyone who is having problems. 

Regardless, happy for this issue to be closed as/when you see fit.

**Comment by JedWatson** [comment]
:+1:

Not bad that we all got to have this discussion and get clarity, and yeah - good reference!

**Comment by webteckie** [comment]
btw, at least, the following:
`path String - the path of the relationship reference on the Model`
should probably be changed to:
`path String - the path of the relationship reference on the User model`

as `on the Model` is to ambiguous, IMO.

**Comment by webteckie** [comment]
well, that's bad...but probably in parentheses to put it in the context of the example:
`path String - the path of the relationship reference on the model (the User model in this example)`

or something along those lines

**Comment by JHerculesVW** [comment]
Having just been struggling with this same topic, the best thread that actually made me understand how to use this function came from one Steve Holgado [on this Stack Overflow post](https://stackoverflow.com/questions/46258439/keystonejs-display-many-to-many-relationships-in-the-model-adminui). He says:

>Regarding the relationship options:
>**path** is the name you want for the field on the model.
>**ref** is the referred Model (the one that has the relationship field).
>**refPath** is the field in the referenced model that has the relationship.

Furthermore, the example code he provided showed something that I didn't pick up from the official documentation: that the **refPath** in .relationship needs to be the same name as the declared Types.Relationship field in the referring model.

In short: the docs could be more clear that these two items need to use the same field name. Basically, if I had to write it, I would tweak Steve's explanation to say:

>**path** is the field name you want to use in the current Model.
>**ref** is the key or name of the referred Model (one which has a Types.Relationship field that points at the current Model).
>**refPath** is the name of the Types.Relationship field in the referred model.

This way, the nomenclature is comparable between explanations of each field, hopefully making it easier to follow.

**Comment by stennie** [comment]
@JHerculesVW Your comment is on a closed issue from a few years ago. Can you please check the [Keystone 4 documentation on Relationships](https://keystonejs.netlify.com/documentation/database/relationships) and [create a new issue](https://github.com/keystonejs/keystone/issues/new) with any suggested improvements.

The current description varies from the one you've quoted, so it would also be helpful to include the relevant document url(s) that need revision.

Thanks,
Stennie

**Comment by JHerculesVW** [comment]
Will do, though this article is pretty high on the search results for this topic, so I thought I'd save the next person some time.
