### ISSUE TITLE
[Orderby]: Sort connected field through GRAPHQL Param

### ISSUE THREAD

**Issue by Jorgexyx** [keystonejs/keystone#2818]
# Feature request
Currently, I have been unable to find a way to sort a nested field in a list with the GraphQL Endpoint

A clear and concise description of what you want and what your use case is.

## Describe the solution you'd like
Have the orderBy allow a nestfield sort such as
orderBy: business__locationName_DESC
## Describe alternatives you've considered
Provide a way to access the exisiting sort function for the graphql orderBy params that way we can implement our own versions.

**Comment by MadeByMike** [comment]
@Jorgexyx the `orderBy` method is going to make use of the underlying database rather than a javascript sort function. As you can imagine, allowing this to be a function could crash applications with a complex sort and a few thousand records.

One option I have for you is a custom graphQL query that will allow you to extend the graphQL schema: https://www.keystonejs.com/keystonejs/keystone/#extendgraphqlschemaconfig

With this you should be able fetch the data manually and apply any sort condition needed. 

If there was enough interest we might consider adding the ability to use sortBy with multiple fields, but for now I think a custom query is the best solution.
