### ISSUE TITLE
Reordering of sortable Lists is broken

### ISSUE THREAD

**Issue by jsander** [keystonejs/keystone#2831]
When reordering Items of a sortable List in 0.4 via drag&drop, the API request to update the sortOrder value is not fired.

**Comment by mxstbr** [comment]
Good catch, thanks!

**Comment by TSFoster** [comment]
I've located where the bug is, it's in [ItemsTableRow.js, line 103](https://github.com/keystonejs/keystone/blob/dcb4e4667a5cbeef4f099af9be81a33e3d5c8921/admin/client/App/screens/List/components/ItemsTable/ItemsTableRow.js#L103). Inspecting the `droppedOn` object in my browser, I think you should be calculating the `newSortOrder` with `.index` (and maybe also `.pageSize` and `.currentPage`).

I hope this helps

**Comment by mxstbr** [comment]
Would really appreciate a PR implementing this change @TSFoster!

**Comment by TSFoster** [comment]
@mxstbr Done. I was hesitant to fix it myself as I don't have experience with React, and I wasn't sure on a couple of lines in the function. But tests pass and drag & drop is now working for me!

**Comment by JedWatson** [comment]
Fixed by #2963
