### ISSUE TITLE
Accessibility Testing as Part of CI

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#2835]
# Feature request

We should use https://github.com/pa11y/pa11y to test KeystoneJs for accessibility testing.

While I understand that Accessibility was taken care of earlier 
https://github.com/keystonejs/keystone/pull/83
https://github.com/keystonejs/keystone/pull/524

It becomes essential that the accessibility testing be part of CI

**Comment by MadeByMike** [comment]
If we were to make this a CI tool we'd probably look for something that integrates with our cypress tests.

I'm not sure CI is the way to go here however. I think it probably need regular auditing by human reviewers.

**Comment by VinayaSathyanarayana** [comment]
Continuous Integration: 
- https://github.com/pa11y/pa11y  can be integrated into Cypress test chain
- CI Tests are to help ensure that our Accessibility Support is retained while we add new functionality/code. Rapid feedback will ensure that we do not end up with ```technical debt```


Human Review/Audit
- Is essential and useful, but cannot be done frequently

**Comment by VinayaSathyanarayana** [comment]
We could look at https://github.com/mfrachet/cypress-audit -- for this.

**Comment by MadeByMike** [comment]
I think Lighthouse CI is the way to go it looks really good and will give us performance metrics as well as some basic a11y test. I'm weary of slowing down CI too much so any PR for this should include some measure of the impact.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
