### ISSUE TITLE
Can't build AdminUI properly

### ISSUE THREAD

**Issue by lucatk** [keystonejs/keystone#2836]
# Bug report

## Describe the bug

I'm trying to contribute to the project. I wanted to try out some changes on the admin-ui.
I've read the contributing guidelines.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. git clone project
2. Ran `yarn`
3. Ran `yarn` in packages/app-admin-ui
4. Made changes to app-admin-ui
5. Ran `yarn build`
6. Substituted @keystonejs/app-admin-ui package in my project for my local version (using `yarn add PATH_TO_LOCAL_CLONE/packages/app-admin-ui`
7. Ran yarn start:dev, navigated to admin UI in browser
8. See error

## Expected behaviour

The admin UI to work.

## Screenshots

![](https://snipboard.io/hjxVa2.jpg)

## System information

- OS: macOS Catalina
- Browser (if applies): Google Chrome 80.0.3987.163

## Additional context

The build and KeystoneJS startup seems to work like normal (no errors)

**Comment by Vultraz** [comment]
The way I've been contributing is via running one of the demo projects. They're symlinked to the packages in `/packages`, so you can clone the monorepo and test out your changes that way.

1. Clone repo and create your branch.
2. Make changes directly to `packages/app-adminu-i/
3. In root `package.json`, change the `demo` script to `"demo": "yarn --cwd ./demo-projects",` (needed because of #2632 )
4. Run `yarn dev` to launch the default demo (Todo List) to test your changes, or `yarn demo $demoName dev` to pick another.

**Comment by gautamsi** [comment]
@Vultraz you can make us of your own projects using a `projects` folder. see https://github.com/keystonejs/keystone/pull/1832

**Comment by Vultraz** [comment]
....huh! That I did not know. 😱

**Comment by MadeByMike** [comment]
@lucatk this is likely because of the workspace configuration. There are ways around it but a better way would be to edit the admin-ui package directly on your own branch. Copy it somewhere if you'd like to reference the code. Also hit my up on the slack https://community.keystonejs.com/ if you'd like some help
