### ISSUE TITLE
[Mongoose-adapter] Bug with duplicate items when paginating results with sorting by not a unique field.

### ISSUE THREAD

**Issue by shyshkovdev** [keystonejs/keystone#2840]
This issue occurs when executing a query request with parameters "skip", "first" and "order by". 
![Screenshot from 2020-04-27 10-18-10](https://user-images.githubusercontent.com/56384926/80344564-77739680-8870-11ea-84fc-8ee5ee2626d2.png)
![Screenshot from 2020-04-27 10-18-26](https://user-images.githubusercontent.com/56384926/80344567-780c2d00-8870-11ea-8d4f-3cfed671bf39.png)
This issue is related to the use of the mongoose aggregate() method and it is thoroughly described on stackoverflow.com:
https://stackoverflow.com/questions/51805886/mongodb-aggregation-skip-and-limit-with-sorting-bring-duplicate-records-in-pagin
https://stackoverflow.com/questions/44692075/mongo-db-duplication-issue-while-using-sorting-with-limit-and-skip-in-aggregatio

As a solution, you can add a default sorting parameter for a unique "id" field. 

For example:
$sort:{
    some_not_unique_field: 1,
    _id: 1
}

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
