### ISSUE TITLE
Option createInline: true breaks admin ui

### ISSUE THREAD

**Issue by w01fgang** [keystonejs/keystone#2855]
When the option `createInline: true` is setted on the relationship field the page doesn't loads, I see only the loading progress.
The console writes error with `this._itemsCache`. I tried to find the error, but I found only one wierd thing:
*fields/types/relationship/RelationshipField.js*
```
cacheItem (item) {
		item.href = Keystone.adminPath + '/' + this.props.refList.path + '/' + item.id;
		this._itemsCache[item.id] = item;
	},
```
In one of iteration `this._itemsCache` is `undefined`, but I can't find why it disappears.

**Comment by mxstbr** [comment]
Is that on `master`?

**Comment by w01fgang** [comment]
Yes it's on `master`.
I like new interface, so I want to test it.

**Comment by mxstbr** [comment]
Thanks for doing that, will take a look!

**Comment by jstockwin** [comment]
This can now be demonstrated in current master by running the following command, with XXXX replaced with this issue number.
`node test\e2e\server.js --env default --config ./test/e2e/adminUI/nightwatch.json --group test/e2e/adminUI/tests/group999FixMe/XXXX.js`

When this issue is fixed, please move `XXXX.js` to `.../group007Misc/somethingSensible.js`, and also change `'demonstrate issue XXXX': function(browser)` in this file to something more sensible. If you can see a way to make these tests more generic, or add additional testing, then please go ahead.
