### ISSUE TITLE
Cant get updatedAt_utc of undefined

### ISSUE THREAD

**Issue by leonalicious** [keystonejs/keystone#2902]
# Bug report

Here is the background

1. I have created a module, lets name it `ModuleA`,  with extended plugins at List level with 
`plugins: [
      byTracking(),
      atTracking({
        format: DATE_FORMAT
      }),
    ],
`
2. after the `moduleA` is created, i try to get the `adapter` from the `moduleA`, and try to run `adapter.findOne or adapter.findById`, works well if the record is found, BUT error occurred when condition is not met. However, after debugged, i found out

here is the error screenshot

![image](https://user-images.githubusercontent.com/4065175/81085695-21ff4f80-8f2a-11ea-87c2-34fd9ab2647a.png)

and here is the solution, but i am not familiar with the code, hoping someone can help with it

![image](https://user-images.githubusercontent.com/4065175/81085462-d351b580-8f29-11ea-8ef6-608afd9ebeea.png)

**Comment by MadeByMike** [comment]
How do you get into a state where there are no fields stored in the Db?

**Comment by leonalicious** [comment]
there are `fields` store inside the DB, my wild guess, the issue here simply because when there are no records being returned, yet, because of using `plugins: [ byTracking(), atTracking() ]`, it will still try to get and set the value for `updatedAt_offset` on top of `undefined`

**Comment by gautamsi** [comment]
`postReadHook` is different, you can have this problem even if you have a DateTime field in list without the plugin and no record returned in GraphQl

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
