### ISSUE TITLE
Cloudinary Image not Displaying

### ISSUE THREAD

**Issue by MattchZA** [keystonejs/keystone#2920]
Hi there

Battling to get the Cloudinary images I've uploaded to display on my page. I have uploaded them in the admin ui no issues. The images are uploading and being saved correctly in Cloudinary. But they don't display on my page. 

![screenshot 2016-05-23 15 27 40](https://cloud.githubusercontent.com/assets/19174608/15472371/11a0a162-20fb-11e6-9434-c4b9dcd1a4d8.png)

When I inspect the page the image urls are there, the images just aren't displaying. Any thoughts why this would be happening?

**Comment by jstockwin** [comment]
@MattchZA When you say the image urls are there, are they correct cloudinary urls? (Can you post an example)

**Comment by MattchZA** [comment]
Hey @jstockwin thanks for the prompt reply. 

This is the url of the image as it appears in Cloudinary:
![screenshot 2016-05-23 15 37 15](https://cloud.githubusercontent.com/assets/19174608/15472685/b9278e04-20fc-11e6-8606-417ff3405a99.png)

and then here is a screen shot of the page inspection: 
![screenshot 2016-05-23 15 37 37](https://cloud.githubusercontent.com/assets/19174608/15472714/d8d4d0fe-20fc-11e6-8624-df4751f84e1e.png)

**Comment by jstockwin** [comment]
@MattchZA Hmm, strange. It looks like the helper is not returning the correct url. Is that nunjucks you're using?

**Comment by MattchZA** [comment]
@jstockwin it's swig. I've copy pasted the examples as per the Keystone demo and keystonejs.com documentation.

**Comment by jstockwin** [comment]
@MattchZA Hmm, not sure on this I'm afraid - I've never tried using swig. What happens if you do `artist.image.limit(450,550)` in place of `artist._.image.fit(450,550)`? (or maybe even just `artist.image.fit(...)`)

I was hoping it'd as it is with handlebars and there would be an explicit helper, but its not. It uses the same function as the jade templates on the demo site use, so I can't see why it's not working whereas everything is fine on the demo site.

**Comment by MattchZA** [comment]
@jstockwin tried all those variations and more. Doesn't change anything. 

I have the demo setup as swig which I use as a reference when I get stuck. So this is an exact copy paste of that. When I use the Keystone basic setup that you get when you first load, the images load and display no problem. But when I put my own details in it doesn't work. 

I could have this completely wrong. I've edited it as instructed but I could be wrong? This is in node_modules/keystone/fields/types/cloudinaryimage/CloudinaryImageType.js 
![screenshot 2016-05-23 16 15 22](https://cloud.githubusercontent.com/assets/19174608/15473821/3b68739c-2102-11e6-82a9-30cd95e036a4.png)

**Comment by jstockwin** [comment]
Ah, you really shouldn't need to change anything inside node_modules. 

That `keystone.set` line should be in `keystone.js` in your project root, and you do not need the `CLOUDINARY_URL=` bit.

However, this will expose your api key to anyone you show the source code to. What you should really do is create a `.env` file in your project root, and from there you can simply add the following line to that `.env` file. If you do this, you won't need the `keystone.set` bit at all, it'll be done for you.  You should also add `.env` to your gitignore, to keep your api secret a secret :smile: 
```
CLOUDINARY_URL=cloudinary://api_key:api_secret@cloud_name
```
Don't forget to also revert `node_modules/keystone/fields/types/cloudinaryimage/CloudinaryImageType.js` to whatever if was before you changed it. 

Finally, since we've established that this is not a keystone issue, we're closing all questions and support requests to keep the issue tracker unpolluted. If you're still having problems then please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Comment by MattchZA** [comment]
Ahhhh! Thank you for helping me out man. All is working correctly. Legend!
