### ISSUE TITLE
Installation failed with "yo keystone"

### ISSUE THREAD

**Issue by zoltanradics** [keystonejs/keystone#2930]
### Expected behavior

I was following the "Get Started" page, "Commands". I wanted to install the latest version of keystone and startup  new project. 

### Actual behavior

After the keystone-generator installed, tried to do "yo keystone" and the installation has started but it does not generate the project. I got the following error:

<img width="1680" alt="screen shot 2016-05-24 at 10 21 49" src="https://cloud.githubusercontent.com/assets/878239/15497152/7c9bc296-2199-11e6-95f8-4630b36aea57.png">

Thanks for helping me out!

**Comment by zoltanradics** [comment]
It seems like the problem happening when you choose Grunt.

**Comment by jstockwin** [comment]
@zoltanradics Since this is an issue with the generator, please could you file it on the issue tracker for keystone-generator [here](https://github.com/keystonejs/generator-keystone/issues), and close this issue.

I've had a quick look, but am not very familiar with the generator so don't think I'm going to be able to help, sorry. Hopefully if you file it against the generator someone more familiar with the code will get chance to take a look.

**Comment by morenoh149** [comment]
Moved https://github.com/keystonejs/generator-keystone/issues/200
