### ISSUE TITLE
Migrations framework/patterns and docs (aka. "Migration Adapters")

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone#299]
Update -- See the [Oct 2019 comments](https://github.com/keystonejs/keystone/issues/299#issuecomment-542945038) for the latest thoughts here.

---

A framework and/or documented patterns on how to handle data and structural DB migrations in apps.

This probably has multiple components/layers to it. Relational DBs will often require structural changes to be made, presumably before Keystone itself starts. Apps should also be given the opportunity to perform data migrations within the Keystone environment (eg. seed data, etc.).

There's plenty of prior art for these processes:

* At the structural level, the Knex adapter will presumably leverage [Knex migrations](https://knexjs.org/#Migrations) while, for Mongoose, such structural aren't really an issue.
* For data the Keystone-level, data-centric migrations, Keystone 4 had "updates" and KS5 has some preliminary seed data functionality.

@jesstelford Also points to the [Symphony](https://symfony.com) framework as an example of a well thought out solution to these issues.

**Comment by molomby** [comment]
There's been some discussion on this (@JedWatson, @MadeByMike, @sarneaud, @timleslie) and we've converged around the concept **migration adapters** (in a similar vein to DB adapters).

Basically:

* There's a defined interface for performing migrations and reporting some limit status information back to keystone
* If a migration adapter is configured, KS hands control over to it during start up. This happens
	- After the DB connection is established
	- Before the GraphQL server(s) are routed traffic
	- Possibly also after the web server is started? The idea being that a "please wait, migrations being performed" page could be displayed with some status info.

The adapter is responsible for:

* Tracking a set of versions
	- Most likely a set of files on disk, corresponding to specific versions and containing of "upgrade" and "downgrade" functionality
* Tracking which migrations have been applied (using a system table/collection in the DB), eg..
	- A migration adaptor build on [Knex migrate](http://knexjs.org/#Migrations) would use `knex_migrations`
	- The Keystone 4 migration framework used a collection called `app_updates`
* Rolling the DB (up or down) to specific version
	- Specified with whatever versioning system the adapter uses (semver, timestamps, etc.) or a reserved `latest` token by default
	- We'll probably evolve a convention of using a `DB_MIGRATE_TO_VERSION` env var or similar
* Locking the DB
	- So multiple instances of the app don't attempt to apply migrations in parallel
* Retrieving the current and latest version ids and identifying if a migration is required
	- The adapter supply it's own version comparison operations (this would let someone implement version ranges, proper semver support, etc.)

Conceptually the start up flow in KS might look vaguely like this:

```js
// Skip if no migration adapter is configured for the app
if (migrationAdapter) {

	// Collect version info and establish if action is required
	const {
		currentVersion,
		targetVersion,
		isMigrationRequired,
	} = migrationAdapter.getVersionInfo({ targetVersion: DB_MIGRATE_TO_VERSION });

	if (isMigrationRequired) {
		// Start serving maintenance/status page..?
		// Eg. `Please wait, rolling DB from version ${currentVersion} to ${targetVersion}...`

		// Perform the migration or wait for it to complete if another thread has a lock already
		await migrationAdapter.migrateOrWaitForVersion(targetVersion);

		// Stop serving the maintenance/status page and continue normal start up
	}
}
```

**Comment by thekevinbrown** [comment]
Hey guys,

I've been using Mikro ORM on another project. We ended up doing a completely different migration setup to what they have out of the box, but they have a schema generator object that you pass a DB connection to and your lists, then it gives you back an array of strings of the SQL that's needed to run in order to get the database to match the schema in the code.

Their implementation is here: https://github.com/mikro-orm/mikro-orm/blob/master/lib/schema/SchemaGenerator.ts

I think the migration adapter stuff is great, but it'd need to build on top of something like a diff schema generator in the Knex Adapter (or a schema generator package that accepted a Knex Adapter instance as an argument). Is this something you'd accept a PR for?

I think if we can ship this basic building block first rather than trying to boil the ocean out of the gate, there'd at least be some kind of tooling people can leverage to solve their own problems without having to tackle all the complexities of, "But what if there are multiple servers? What about serverless?" etc. People could get the SQL and do with it what they please, which might even give rise to these migration adapters as community packages.
