### ISSUE TITLE
Support for full Unicode in frontend (Elvish (Sindarin) language)

### ISSUE THREAD

**Issue by Pszek** [keystonejs/keystone#2993]
I cannot paste sindarin phrases into CMS. It supports Punjabi or Tamil for example, but much more important - Sindarin is not supported. Please consider it important.

**Comment by creynders** [comment]
Whether this request is in jest or not ... 
We're closing all feature requests to keep the issue tracker unpolluted. If you really want this feature, please post it to https://productpains.com/product/keystonejs 
Thanks

**Comment by wmertens** [comment]
@creynders Actually, IMHO this is a bug rather than a feature request. [Tengwar](https://en.wikipedia.org/wiki/Tengwar) is assigned some private space in Unicode, and [Everson Mono](https://en.wikipedia.org/wiki/Everson_Mono) can display it.

It works fine in the Keystone admin UI: http://demo.keystonejs.com/keystone/post-comments/571611e5b541d30300b3361c

But the frontend pages don't work: [Frontend](http://demo.keystonejs.com/blog/post/first-test#comment-id-5755d06558973f0300afc70b) / [Admin UI](http://demo.keystonejs.com/keystone/post-comments/5755d06558973f0300afc70b)

So there is something wrong with full Unicode support in the frontend comment boxes, even the initial paste doesn't work. No idea what. Also not sure if we care :)

**Comment by jstockwin** [comment]
Doesn't work in the admin UI for me? Unless this is just because it's been saved or something.
![image](https://cloud.githubusercontent.com/assets/8227759/15835535/5e9dd4a2-2c28-11e6-9a36-cdf293dbf229.png)

**Comment by wmertens** [comment]
@jstockwin you need to install Everson Mono
![image](https://cloud.githubusercontent.com/assets/54934/15835784/e33962a4-2c31-11e6-85c2-c60b554e799a.png)

**Comment by wmertens** [comment]
Oh and the second one does not work in admin UI because it was added via the frontend and was broken
![image](https://cloud.githubusercontent.com/assets/54934/15835814/083c5214-2c32-11e6-9279-3f5147ff4a93.png)

**Comment by wmertens** [comment]
Reopening so we can decide if we want to fix this.

**Comment by mxstbr** [comment]
I think we should fix it, but it's not the highest priority ever.

Who knows, maybe someday somebody wants to run a Tolkien fan forum on Keystone…

**Comment by wmertens** [comment]
I'm sort of hoping that a new React frontend would fix this
automagically. Of course, that's pretty far off, and in the mean time
I'm stumped as to why this works on the backend but not the frontend

**Comment by morenoh149** [comment]
"I think we should fix it, but it's not the highest priority *ever*."

**Comment by josephg** [comment]
Is the problem with all astral plane unicode characters? Do `𝄞` and `𝒲` work?

**Comment by wmertens** [comment]
@josephg well they don't seem to work on github on my phone :-)

If you can paste them in the admin ui, and they show up in the column view, I think that's ok. I have no idea why they don't work in the frontend. Maybe the templating engine doesn't handle unicode properly?

**Comment by Noviny** [comment]
The frontend concern seems to be with the demo project, not with keystone core, as @wmertens showed. Closing this again. Issue should be created for the generator or test-project if they need this suppot.
