### ISSUE TITLE
download/export of Markdown fields is empty if HTML doesn't exist

### ISSUE THREAD

**Issue by WelltokCaleb** [keystonejs/keystone#3001]
When downloading a list that contains Markdown, the resulting output is empty for Markdown fields, unless those fields also have HTML. 

### Expected behavior
Any given markdown field should be populated with the Markdown stored in the object, not the HTML. This may be a bit of an edge case, since an editor working directly in the UI, when saving, would persist both the .md and .html, but this is not the case if a document is created via API.
### Actual behavior
A markdown field is populated with data from the .html property, not the .md.
### Steps to reproduce the behavior
1. Open the list view for a type that has a Markdown field.
2. Download (making sure to include the column with the Markdown).
3. Note in resulting CSV that the field is empty.
### Obvious fix:
/fields/types/markdown/MarkdownType.js line 96, change this.paths.html to this.paths.md:
` markdown.prototype.format = function (item) {
	return item.get(this.paths.md);
}; `

**Comment by jstockwin** [comment]
@WelltokCaleb If you think you've got an easy fix then a Pull Request would be great!

**Comment by WelltokCaleb** [comment]
👍 PR on it's way.

**Comment by JedWatson** [comment]
@WelltokCaleb can you clarify how the documents are being populated? You mention using the API...

The point of the Markdown field is to automatically store both markdown and html (where the markdown is the source, and the html is the expected output)

See here: https://github.com/keystonejs/keystone/blob/master/fields/types/markdown/MarkdownType.js#L63

There is a setter that should automatically update the html value when the markdown is updated on a document instance, I'd be curious how you're bypassing that in your application.

Updating the `format` method as you've done in #3002 isn't a straight-forward fix as it would break the expected behaviour (i.e. "formatting" the markdown field should always return html)

If it's valuable to be able to export markdown from a markdown field (which makes sense, really) I think we should explicitly work out how to make that possible, rather than changing the default formatting behaviour here. I'm open on suggestions about how we would configure that!

In the meantime you could also work around this by specifying a custom `toCSV` method on your schema, which will be used when the csv is generated (I'll have to look up how to do that, don't have the reference handy now)

**Comment by WelltokCaleb** [comment]
Thanks, @JedWatson. I have a "bulk import" process that allows our editors to import a ton of entries from a spreadsheet. All of the text they work with is Markdown, and we use Markdown on the way out for displaying. In the import process, the HTML does not get auto-created, so for all entries that get put in Keystone this way, we only have the .md. It is valuable to us to export the markdown, and my proposed solution would be to add another func to MarkdownType.js like this:

markdown.prototype.getMarkdown = function (item) {
    return item.get(this.paths.md);
  };

and then add a conditional to the getCSV's getData func, something like:
if (field.type === 'markdown')  { data[path] = field.getMarkdown(item) }

If you like this approach, I'll update the PR accordingly.

**Comment by JedWatson** [comment]
Hey @WelltokCaleb, sorry this took so long to get back to.

I've refactored the CSV generation for 4.0 so that for complex fields (i.e. they store an object in the database) a column is added per property in the stored value. That means that if you export a markdown field, it will now include two columns:

* `contentMd`
* `contentHtml`

Does that resolve this issue for you? The new behaviour is live in the 4.0 beta

The only real difference between this and what you're proposing here is that you'll always get the `html` exported as well, which we could solve but I'd approach that in a more generic way (so you could customise per-field which properties are exported from complex fields)

**Comment by JedWatson** [comment]
See #3436 - I've also added support for a `.toCSV` method on each field, which will let you export _just_ the markdown if you like. The whole system should be powerful enough to allow a heap of customisation for specific fields without any special field handling, so I'm calling this good to close.

@WelltokCaleb let me know if you have any other feedback on it!
