### ISSUE TITLE
Cannot find module '../../fields/types/wysiwyg/trueColumn

### ISSUE THREAD

**Issue by zxf969175364** [keystonejs/keystone#3033]
cause by lib/list/field.js 
```
// Wysiwyg HTML fields are handled as a special case so we can include TinyMCE as required
	 if (options.type.name === 'html' && options.wysiwyg) {
	 	this.fieldTypes.wysiwyg = true;
	 }
```
if I add wysiwyg to options, wysiwyg  will set to fieldTypes, but there is not wysiwyg  in types

**Comment by mxstbr** [comment]
Having that issue as well, must've happened because of the @JedWatson refactor 3 days ago. Trying to find the culprit!

**Comment by zxf969175364** [comment]
I deleted those lines, it seem work well now

**Comment by benkroeger** [comment]
stumbled over the same thing (and applied same solution as @zxf969175364 ). Are there any side-effects expected? The code looks like there is a reason for it (although my app works fine with just removing it)

**Comment by mxstbr** [comment]
Do you have any WYSIWYG fields? Are they still working?

**Comment by benkroeger** [comment]
yep, I have WYSIWYG fields and they are working

**Comment by benkroeger** [comment]
I think the original intention was to include tinyMCE in the build-process by "including" it in the `fieldTypes`. However, now it's [imported](https://github.com/keystonejs/keystone/blob/master/fields/types/html/HtmlField.js#L4) in the `HtmlField` and thus included by babel automatically.

**Comment by JedWatson** [comment]
@benkroeger good sleuthing. It's not included by browserify though, because we're shimming it to the global `tinymce` object though (on the window, loaded by a script tag). We actually don't depend on the `tinymce` package at all. See `package.json`

I've applied a quick fix to correct this behaviour, and realised that somewhere along the way we lost our conditional check around loading the WYSIWYG editor if you don't need it - removing those lines would have broken that, but it got dropped when all the templates were combined in the recent Admin UI refactor (ping @mxstbr)

I'm going to restore that too, in the meantime latest master is working agin with WYSIWYG fields. Sorry about breaking it!

**Comment by JedWatson** [comment]
Sorry - just to clarify I'm not 100% sure it was in there before the admin UI refactor @mxstbr - if not, it should have been, but not necessarily something you introduced!
