### ISSUE TITLE
Authed user relationship with many:true doesn't include referred IDs within hooks/access functions 

### ISSUE THREAD

**Issue by enhancers** [keystonejs/keystone#3042]
# Bug report
Authed user relationship with many:true doesn't include referred IDs within hooks/access functions 

## Describe the bug

After declaring a user model that includes a many-to-many relationship with another model (e.g. referring a Team model), if you try to access referred IDs within hooks/access functions you will find out that the field is completely missing from the available data (context.authedItem / authentication). It would be enough to at least have the referred IDs (like it is for the one-to-many case).

## To Reproduce

To reproduce the issue just start debugging hooks/access functions during execution.

## Expected behaviour

Authed user item should include the relationship field with the referred IDs.

**Comment by gautamsi** [comment]
that field is not for `many:true` ssee https://www.keystonejs.com/keystonejs/fields-authed-relationship/#differences-from-relationship

**Comment by enhancers** [comment]
@gautamsi thanks for your reply, but we are using the standard Relationship field.

**Comment by timleslie** [comment]
What you are seeing is the expected behaviour, but it is definitely a gotcha the first time you encounter it, and we need to call it out better in the docs.

The `existingItem` in hooks and `authedItem` in access control represent the internally stored items. These are database objects, and represent the data contained in the database row of the table associated with the list. In the case of a many-many relationship, this will not include any of the relationship info, as you observed.

To obtain details of related items you need to perform a subsequent query from within your hook or access control method.

The reason for this design choice is that we cannot know ahead of time what data the user will want to use in their hooks/access-control functions and for items with many related items the cost of finding all related items can be huge. This would lead to poor performance of all operations, even though most of the time the related data would not be used.

**Comment by enhancers** [comment]
@timleslie thanks for your reply. That makes totally sense, but as highlighted by other issues at the moment it's not possible to perform async operations within access control functions and it's not available any query handler.

What I would expect is at least to see the IDs of the referred entity. In Keystone 4 it was exactly like that, if the relations wasn't populated you had at least the IDs. That would give the opportunity to check a match of IDs between User entity and the other ones. It would be enough to perform basic membership logics (e.g. team membership checks on entities).

Thanks for your time!

**Comment by MadeByMike** [comment]
@enhancers it is possible to have `async` access control functions. I've got some examples here: https://github.com/keystonejs/keystone/pull/3044/files#diff-3b2710f1baace4992abe2a0539e68194

**Comment by enhancers** [comment]
@MadeByMike thanks for the example!
