### ISSUE TITLE
"Username or password was incorrect" error after a while

### ISSUE THREAD

**Issue by IonutMorariu** [keystonejs/keystone#3070]
# Bug report

## Describe the bug

Sometimes, after a couple of days of use, suddenly the password for a user is no longer correct, without doing anything to it. It just stops working and I have to reset it via the api, because i can no longer access the admin UI

## To Reproduce

Install the user auth demo, connect it to a database and start using it. Come back after a day or two and the password is no longer working.

## Expected behaviour

It should recognise the password everytime, but after a while it gives the wrong password error.

## System information

- OS: Ubuntu 18.04

**Comment by MadeByMike** [comment]
@IonutMorariu I've been running projects with the same auth set-up as the demo and the passwords have never changed for me.

We've also got long running projects in production and haven't seen this. 

Could it be that you are re-initialising the data in the database? 

Check if you have any scripts running in development that might re-create tables. It should be safe but it's a good idea to remove the onConnect script from the example after the project is initialised.

If you change your project name and have not otherwise configured a database URL you might be changing the name of the default database.

**Comment by IonutMorariu** [comment]
@MadeByMike The database is not changing or re-initilising as everything still works, all the lists i have, with data in them work perfectly.  I removed the onConnect script from the index.js, but the issue appears with the server running, so the onConnect script should not run.

The issue, I think, is that suddenly the bcrypt part, where it compares the password i send with the hash from the database (which is still there, i checked and that doesn't go anywhere) is giving a false response.

And the weird part about it, is that I cannot find any pattern to reproduce it, but it might have something to do with interacting with the admin ui and my client application at the same time.

**Comment by MadeByMike** [comment]
@molomby do you know anything that can cause this?

**Comment by IonutMorariu** [comment]
Managed to find a fix to the error. It was caused by a call to the update function of the adapter, inside a custom mutation
