### ISSUE TITLE
Filtering list by Id in Admin UI throws error if entered string is not exactly 12 bytes

### ISSUE THREAD

**Issue by ayush-goyal** [keystonejs/keystone#3075]
# Bug report

## Describe the bug

When filtering by Id in the Admin UI, a GraphQL error is thrown if the entered string is not exactly the length of an Object Id.

## To Reproduce

For example, 

1. Select on any list from the side
2. Click filters
3. Select Id
4. Type in any random string
5. Click apply

You will receive a GraphQL error stating `GraphQL error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters GraphQL error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters`. Also, you will not be able to view the list until you clear your cookies and refresh the screen.

## Expected behaviour

The normal list should be shown with no objects matching the filter without the error.

## Screenshots

<img width="1085" alt="Screen Shot 2020-06-01 at 1 17 52 AM" src="https://user-images.githubusercontent.com/8273038/83378522-e6c83300-a3a6-11ea-9495-61bf4f4769e2.png">

## System information

- OS: macOS
- Browser: Google Chrome

**Comment by molomby** [comment]
I'm not sure I agree with your "expected behaviour"...

Why do you want to be able to enter values that aren't valid for the field type you're using? You seem to be using the `MongoId` field type for your `id` fields here. It's specifically for Mongo ObjectIDs so it makes sense (to me at least) that suppling an invalid value to filter with would error out.

Note, there's nothing forcing you to use `MongoId` for your `id` fields, it's just the default when you're using the Mongoose adapter. You could, for example, use the `Text` field type then set the ID values to whatever you want. I suspect this isn't covered in the docs/guides yet (can't find it) but there [some notes here](https://github.com/keystonejs/keystone/issues/1834#issuecomment-547211757) that might help.

**Comment by ayush-goyal** [comment]
@molomby I'm open to any change you suggest for the expected behavior. You are correct that I am using MongoId. I just believe that if someone mistypes and tries to search by Id, the app shouldn't crash entirely. As I stated in my original message, the only way to fix it is to clear the cookies and refresh the app. There should definitely be a safeguard in place against this, whether with validation checking when filtering or through some other method.

**Comment by Temkit** [comment]
i think here it's expected behavior.
following your steps, but when you try to search with a 24 length string it works for example try to tap :  5f96d1ad53f63f947f5c9ec7 ...

i was facing the same issue but within queries, sub fields when null gives error ! 
for example : 

```
 allProduits(where: {AND: [{name_starts_with_i: $tap}, {active: true}]}) {
    id
    image_300 {
      id
      publicUrl
    }
    name
    mensualite
    apport
    duree
    marque{
      id
      name}
  }
```
when there is no 'Marque' i have the same error you pointed, for the same reason i guess !

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
