### ISSUE TITLE
Inconsistency in data passed to hooks (especially empty items in 'resolvedData')

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#3102]
I have an issue regarding the `resolveInput` and `validateInput` hooks— specifically what’s passed in `resolvedData` and `existingItem`.  There seem to be some inconsistencies and @jesstelford suggested I raise the issue here.

When I first create a new item in the AdminUI, in the ‘half window’ on the right, in the hook, `existingItem` is obviously `{}`, and `resolvedData` is an object that contains any of the fields that have been filled in.  But those fields that have not been filled in are simply `undefined` , not `null`.  However, if I am modifying an existing item, and then delete the data for one of the fields, then `existingItem` will contain all the fields that have been filled in prior to this modification, and `resolvedData` will contain `null` for the fields where data has been removed, not `undefined`.

That is, to my understanding, the only time that `undefined` is passed in a field in `resolvedData` is on `create`, that is, when existingItem is `{}`

This becomes particularly problematic if you wish to write tests for the hooks as it becomes a bit tricky to understand what is being passed in, particularly in resolvedData.

I was asked to make a reproducible example but at this stage of the project it's a bit tricky to reduce what are fairly complicated list, field and hooks relationships to something basic.  I'm hoping that the above will suffice as a starting point.  If not, I'll try to work up a stripped-down example.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
