### ISSUE TITLE
Date field as name prevents list to detail link

### ISSUE THREAD

**Issue by wmertens** [keystonejs/keystone#3126]
### Steps to reproduce the behavior
1. add a date field to a model
2. add a `map: {name: 'datefield'}`
3. go to model list
### Expected behavior
1. somehow be able to go to detail view
### Actual behavior
1. cannot click on anything, need to remove mapped name column to show id column to click

**Comment by jstockwin** [comment]
This can now be demonstrated in current master by running the following command:
`node test/e2e/server.js --env default --config ./test/e2e/adminUI/nightwatch.json --test test/e2e/adminUI/tests/group999FixMe/3126.js`

When this issue is fixed, please move `3126.js` to `.../group007Misc/somethingSensible.js`, and also change `'demonstrate issue 3126': function(browser)` in this file to something more sensible. If you can see a way to make these tests more generic, or add additional testing, then please go ahead.

P.S. Currently the date field is very broken, so the test doesn't actually make it as far as demonstrating the issue. But once the date field is fixed, it should work.

**Comment by mxstbr** [comment]
@wmertens I think this might be your changes:

```
POST /keystone/api/legacy/dates/create 400 32.681 ms
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (d:\Documents\Development\GitHub\keystone\node_modules\express\lib\response.js:719:10)
    at ServerResponse.send (d:\Documents\Development\GitHub\keystone\node_modules\express\lib\response.js:164:12)
    at ServerResponse.json (d:\Documents\Development\GitHub\keystone\node_modules\express\lib\response.js:250:15)
    at ServerResponse.apiError (d:\Documents\Development\GitHub\keystone\admin\server\middleware\apiError.js:34:7)
    at d:\Documents\Development\GitHub\keystone\admin\server\api\item\legacyUpdate.js:8:23
    at d:\Documents\Development\GitHub\keystone\node_modules\mongoose\lib\model.js:3331:16
    at d:\Documents\Development\GitHub\keystone\node_modules\kareem\index.js:207:48
    at d:\Documents\Development\GitHub\keystone\node_modules\kareem\index.js:127:16
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by jstockwin** [comment]
That create problem is actually happening on all fields. See #3203

**Comment by export-mike** [comment]
This is no longer an issue in keystone 4.0.0-beta.5, I've added tests to a branch proving this is no longer an issue. https://github.com/keystonejs/keystone/tree/feature/nightmare

Closing, please reopen if the issue reappears

**Comment by askdesigners** [comment]
I'm on the latest release and I'm still seeing this issue. When setting a field to have a mapped name (so that the admin UI is actually useful in showing related documents) there is no way to get to a record detail. This mean you have to choose from one broken behavior (showing IDs everywhere for linked items) or another broken behavior (no way to access details). Kind of sucks. 

If it was fixed before, can someone maybe tell me some work around for this?

**Comment by askdesigners** [comment]
Aha! So this breaks when you also include the field in the `defaultColumns` option. 

So to reiterate, this is still not really behaving as expected.
