### ISSUE TITLE
`gqlOutputFieldResolvers` will not work for nestedType on customQuery

### ISSUE THREAD

**Issue by leonalicious** [keystonejs/keystone#3130]
# Bug report

## Describe the bug

version of `"@keystonejs/fields": "^12.0.1"`

## To Reproduce

1. I created my own `customQuery`,and within it, will execute an existing `graphql query` and the end result is returned with expanded data structure.
![image](https://user-images.githubusercontent.com/4065175/84001823-fdb7e800-a999-11ea-9492-1edcc2241386.png)

2. however, when the expanded data structure which is passed into the `gqlOutputFieldResolvers` again, we will be hitting with some error, as the data being passed is not `items with raw ID`, instead they are `object with expanded data structure` from step 1.
![image](https://user-images.githubusercontent.com/4065175/84001999-496a9180-a99a-11ea-9138-485a129bbfd1.png)

3. Not too sure if i clarify the issue clear enough, however,  i have created my own Temporary solution, which is i will replace the `object` back with `raw ID` so that the desired params will be passed into `gqlOutputFieldResolvers` successfully.

![image](https://user-images.githubusercontent.com/4065175/84002241-b41bcd00-a99a-11ea-82b7-0b9ac387180a.png)

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
