### ISSUE TITLE
[0.4] pre:routes hook called after createDynamicRouter

### ISSUE THREAD

**Issue by mahnunchik** [keystonejs/keystone#3162]
### Steps to reproduce the behavior

keystone.pre('routes', passport.initialize());
keystone.pre('routes', passport.session());
### Expected behavior

`pre:routes` is called before all routes https://github.com/keystonejs/keystone/blob/master/server/createApp.js#L114
### Actual behavior

`pre:routes` is called after `createDynamicRouter` https://github.com/keystonejs/keystone/blob/master/server/createApp.js#L87

**Comment by wmertens** [comment]
Could you make a PR? This is assuming `pre:routes` is the correct hook for running before all routes, right @JedWatson?

**Comment by JedWatson** [comment]
This might have been an unintentional breaking change... the hook to add middleware before the Admin UI's router is now `pre:admin`, the `pre:routes` hook just happens before the `routes` config is loaded.

Thinking about it, that doesn't make a lot of sense because the user (app developer) controls everything that happens in the routes anyway so that makes the `pre:routes` hook pretty useless :/

**Comment by mahnunchik** [comment]
But `pre:admin` hook became very useful 😉

**Comment by JedWatson** [comment]
@mahnunchik yeah, and it's clearer too. Maybe we just note that as a breaking change, and remove `pre:routes`?

**Comment by mahnunchik** [comment]
@JedWatson I think that all hooks should be mentioned in documentation. About removing, I don't know, we may leave `pre:routes` as is.

**Comment by blargity** [comment]
I added a comment about this to the documentation for v4 here: https://github.com/keystonejs/keystone/commit/5588c8859fd879ad89109c9338cada79f858b861

I'll go ahead and close this issue, if anyone wants to improve the docs, PRs are always welcome.
