### ISSUE TITLE
Relationships throwing error

### ISSUE THREAD

**Issue by junaid33** [keystonejs/keystone#3164]
# Bug report

## Describe the bug

I'm trying to create relationships between multiple lists but the Admin UI is throwing an error.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Clone this repo: https://github.com/junaid33/ks-error-repro
2. Add local postgres connection URL to .env
3. npm install, npm run create-tables, npm run dev
4. Go to localhost:3000/admin/graphql
5. Enter this to create a user: 

mutation {
  createUser(
    data: {
      name: "Keystone"
      email: "admin@keystonejs.com"
      password: "password"
    }
  ) {
    id
    name
    email
  }
}

6. Log into localhost:3000/admin using created log-in.
7. Click on OrderItem, ChannelItem, and Match and you will see errors

## Expected behaviour

OrderItem, ChannelIem, and Match should not have errors and should be able to be created.

## Screenshots

These are screenshots on the error 

<img width="1030" alt="Screen Shot 2020-06-16 at 5 36 25 PM" src="https://user-images.githubusercontent.com/34615258/84837703-5de40500-affe-11ea-8f36-6695dc8705f2.png">
<img width="986" alt="Screen Shot 2020-06-16 at 5 33 06 PM" src="https://user-images.githubusercontent.com/34615258/84837705-5e7c9b80-affe-11ea-8603-f1914dc7478d.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]

**Comment by junaid33** [comment]
May be related to: https://github.com/keystonejs/keystone/issues/2828

And it seems to work fine with MongoDB, just not Knex/Postgres

**Comment by junaid33** [comment]
I was able to fix the "Cannot destructure propety 'rel' of 'fieldAdapter'" error. I didn't have the User relationship added to the ChannelItem and ShopItem. Once added, the error went away.

The 

`GraphQL error: select "t0".* from "public"."Match" as "t0" left outer join "public"."User" as "t0__user" on "t0__user"."id" = "t0"."user" where true and ("t0__user"."id" = $1) order by "input" ASC limit $2 - column "input" does not exist` '

error is still there for the Match list. It works on Mongoose but throws error on Knex/Postgres.

**Comment by josemf** [comment]
@junaid33 in case you are still wondering,

I did stumbled with this issue today and after some review I realized this is a bug that happens for lists which first field is a relationship and the relationship database id is a foreign key to the list (the table doesn't have the field).

This is fixed by changing some code in `QueryBuilder { }` class in `adapter-knex.js`.
I'll publish a PR soon.

**Comment by josemf** [comment]
#4704 https://github.com/keystonejs/keystone/pull/4704

**Comment by josemf** [comment]
#4719

Updated PR

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
