### ISSUE TITLE
how to use v 4.0

### ISSUE THREAD

**Issue by SmallShrimp** [keystonejs/keystone#3179]
I wish to use v 4.0 ,but how to use,please.

**Comment by promethe42** [comment]
@SmallShrimp use the `master` branch.

**Comment by wmertens** [comment]
@SmallShrimp it's `v0.4` BTW :) To use, instead of `npm i keystone` use `npm i -S keystonejs/keystone`, which will install the git version. Every time you then run `npm i keystone` it will grab the latest `master`.

I recommend using npm v3, it is better with git.

Closing now. This issue tracker is meant for issues, not questions, and this question is more for [Stack Overflow](https://stackoverflow.com/questions/tagged/keystonejs).

**Comment by SmallShrimp** [comment]
thanks
