### ISSUE TITLE
[0.4] Cannot create new items

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#3203]
### Steps to reproduce the behavior

Start the test server, Try to add a new item. 

### Expected behavior

Keystone should add a new item. 

### Actual behavior

Keystone completely crashes.
```
POST /keystone/api/legacy/<insert any list name here>/create 400 13.503 ms
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (d:\Documents\Development\GitHub\keystone\node_modules\express\lib\response.js:719:10)
    at ServerResponse.send (d:\Documents\Development\GitHub\keystone\node_modules\express\lib\response.js:164:12)
    at ServerResponse.json (d:\Documents\Development\GitHub\keystone\node_modules\express\lib\response.js:250:15)
    at ServerResponse.apiError (d:\Documents\Development\GitHub\keystone\admin\server\middleware\apiError.js:34:7)
    at d:\Documents\Development\GitHub\keystone\admin\server\api\item\legacyUpdate.js:8:23
    at d:\Documents\Development\GitHub\keystone\node_modules\mongoose\lib\model.js:3331:16
    at d:\Documents\Development\GitHub\keystone\node_modules\kareem\index.js:207:48
    at d:\Documents\Development\GitHub\keystone\node_modules\kareem\index.js:127:16
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by mxstbr** [comment]
@jossmac @wmertens could this have been one of your recent changes?

**Comment by wmertens** [comment]
argh! I thought it was something in the new API, but this is the old API so it must be elsewhere.

**Comment by wmertens** [comment]
the good news is that I traced it down to my commit. The bad news is that it's MY commit :)

**Comment by wmertens** [comment]
Ok, it's something in Name, that is causing validation to fail and then to
crash the server due to it running another route

**Comment by wmertens** [comment]
So when I run `node test/e2e/server.js --notest` and then try to create a boolean, it tries to POST an empty form. This is obviously wrong, and I don't know yet why this happens, perhaps because I removed text refs as much as possible.

The other problem is that is you try to POST an empty form, the ensuing validation error causes Express to double-respond somehow.

**Comment by wmertens** [comment]
Found it, it was because of the new refs. The submitForm in CreateForm uses a ref to a React Component, which is not a DOM element and getting the formdata from it returns empty.

Luckily, the form is actually passed in the event, so not necessary to keep a ref. Unluckily, using that actual form makes no difference. No clue, and no more time today :( I guess reverting that change will fix it for now.

All this code would be greatly simplified by using redux-form, in which case the submit will get the data from Redux and forms can be closed and opened with the previous data etc.
