### ISSUE TITLE
No cookieSecret value was provided

### ISSUE THREAD

**Issue by gasparteixeira** [keystonejs/keystone#3247]
# Bug report

## Describe the bug

I followed the instructions to start a project with authentication using mongodb and I start by running yarn dev. 
No user was created and I got this message: 

No cookieSecret value was provided. Please generate a secure value and add it to your app. Until this is done, a random cookieSecret will be generated each time Keystone is started. This will cause sessions to be reset between restarts. See [https://www.keystonejs.com/keystonejs/keystone/#config

I am not sure what to do. I was looking for a tutorial for dummies but I couldn't find it. 

What should I do? create a cookieSecret? Where? I do have two files . index.js and initial-data.js

Kinda really lost. I didn't like the initial experience I had

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]

**Comment by Vultraz** [comment]
Ah, that link didn't get updated. This is the section you want: https://www.keystonejs.com/keystonejs/keystone/#cookiesecret

Basically, if the `cookieSecret` option isn't provided to the `Keystone` constructor, a random one will be generated each server start in **dev** mode. In **production** mode, you must provide a `cookieSecret` or you won't be able to start the server.

**Comment by gasparteixeira** [comment]
@Vultraz  I've already check that section. So where should I define this? Is  there a .env file or I should create one? Just in case, I want to let you know  that I just ran the project through whatever I have on the website's doc. Looks like the documentation is not updated to the code.  I am just sharing my experience

**Comment by Vultraz** [comment]
You can use env variables if you want, sure.

As for the message, it's just a warning, and you can continue to work on the demo project without providing a `cookieSecret` value.

**Comment by molomby** [comment]
Hey @gasparteixeira, thanks for your feedback. The getting started process is something we're hoping to focus on soon. It has some sharp edges, as you've noticed.

The [docs](https://www.keystonejs.com/keystonejs/keystone/#cookiesecret) Vultraz linked to are for the Keystone class. If you scroll to the top of that page it might make more sense. You'll have a line in your `index.js` where you create your Keystone object (ie. `new Keystone({ ... })`). This is where you can pass a `cookieSecret` value to Keystone to silence that warning message.

In terms of where the actual value comes from, it could be an environment variable that's set when the node process is started, you could put it in `.env` file and use something like [dotenv](https://www.npmjs.com/package/dotenv) to load it, you could pull it from some kind of centralised secret manager or any number of other sources. This is really a project-specific decision that Keystone doesn't have an opinion on.

If this is just a toy app you're playing around with locally then you can ignore the message, or even hardcode `cookieSecret` to a static value. Not setting `cookieSecret` won't break anything about the app, it just causes Keystone to use a random one each time. As the warning says, this cause sessions to be reset between restarts, so (if you have auth enabled) you'll need to sign in again each time you start the node process.

Since that incorrect link in the warning message has now been [patched](https://github.com/keystonejs/keystone/pull/3249) I'm going to close this issue. However I'll make a note for when we come to improve the getting started process to address this setting specifically.
