### ISSUE TITLE
error building - Unknown plugin "add-module-exports"

### ISSUE THREAD

**Issue by ellipticaldoor** [keystonejs/keystone#3329]
I updated to the latest versión of the master branch and now when I try to start the app I get the following error:

```
------------------------------------------------
KeystoneJS Started:
reco2 is ready on port 3000
------------------------------------------------

GET / 304 149.256 ms
GET / 304 65.248 ms
GET /keystone/ 200 9.092 ms
2016-08-16 09:08:09 error building App/index.js:
Unknown plugin "add-module-exports" specified in "/Users/miguel/src/gremyo/reco2/node_modules/inline-style-prefixer/package.json" at 1, attempted to resolve relative to "/Users/miguel/src/gremyo/reco2/node_modules/inline-style-prefixer" while parsing file: /Users/miguel/src/gremyo/reco2/node_modules/inline-style-prefixer/static.js
```

**Comment by PatrickJongmans** [comment]
I have the same issue:
Related to #3223

**Comment by SharadKumar** [comment]
Ditto.

**Comment by SharadKumar** [comment]
Clearing `node_modules` as in #3223 didn't work this time.

```
2016-08-16 23:08:66 error building App/index.js:
Unknown plugin "add-module-exports" specified in "/Users/xxx/GitHub/yyy/node_modules/inline-style-prefixer/package.json" at 1, attempted to resolve relative to "/Users/xxx/GitHub/yyy/node_modules/inline-style-prefixer" while parsing file: /Users/xxx/GitHub/yyy/node_modules/inline-style-prefixer/static.js
```

**Comment by dijs** [comment]
Does someone have a fix here? I am seeing the same issues.

**Comment by GwonHyeok** [comment]
@dijs
i have same issue 

if you npm install in node_module/inline-style-prefixer, this issue solved temporary

**Comment by ellipticaldoor** [comment]
@GwonHyeok npm install **inline-style-prefixer** didn't worked for me.

**Comment by GwonHyeok** [comment]
@ellipticaldoor  
npm install in  node_module/inline-style-prefixer directory not project root directory

ex) 
cd $PROJECT_ROOT/node_module/inline-style-prefixer && npm install

**Comment by PatrickJongmans** [comment]
@GwonHyeok / @ellipticaldoor temporary fix is correct.

`cd [project_folder]/node_modules/inline-style-prefixer && npm install`

**Comment by dijs** [comment]
Okay, the npm install fixed that package, I still see two other similar errors:

```
08:56:10 web.1  | 2016-08-17 08:08:78 error building FieldTypes:
08:56:10 web.1  | Unknown plugin "transform-inline-environment-variables" specified in ".../node_modules/jss/.babelrc" at 0, attempted to resolve relative to ".../node_modules/jss" while parsing file: .../node_modules/jss/lib/index.js
08:56:10 web.1  | 2016-08-17 08:08:78 error building FieldTypes:
08:56:10 web.1  | [BABEL] .../node_modules/jss-px/lib/index.js: Using removed Babel 5 option: .../node_modules/jss-px/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets while parsing file: .../node_modules/jss-px/lib/index.js
```

Maybe use the same fix? I will try.

**Comment by dijs** [comment]
Okay, I had to use `npm install --ignore-scripts` to fix the `jss` error.

The `jss-px` error still exists. It looks different.

**Comment by GwonHyeok** [comment]
in my case, that issue does not occurred

Maybe i think this problem is same issue

i think this problem came from some libraries that using  babel

**Comment by GwonHyeok** [comment]
@dijs

First : remove node_modules directory (project root)
Second : npm install
Third : cd node_modules/inline-style-prefixer && npm install
Fourth : node keystone.js

How about this solution 

In my case working well

**Comment by dijs** [comment]
@GwonHyeok No, these steps led to my previous errors:
```
2016-08-17 19:08:18 error building FieldTypes:
Unknown plugin "transform-inline-environment-variables" specified in ".../node_modules/jss/.babelrc" at 0, attempted to resolve relative to ".../node_modules/jss" while parsing file: .../node_modules/jss/lib/index.js
2016-08-17 19:08:33 error building FieldTypes:
[BABEL] .../node_modules/jss-px/lib/index.js: Using removed Babel 5 option: .../node_modules/jss-px/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets while parsing file: .../node_modules/jss-px/lib/index.js
```

**Comment by ellipticaldoor** [comment]
@GwonHyeok your solution works fine for me.

How I can add the bug tag to the issue, I'm searching but I cant figure out how to do it.

**Comment by jstockwin** [comment]
@ellipticaldoor I think it's only members that can add tags. I've just done it for you. 

Sorry nobody on the team has got round to looking at this yet - we're all very busy trying to get 0.4 shipped ASAP. I'm afraid I also don't have time right now, and I'm not sure I'd be able to help with this one, but I'll try and re-produce it myself if I get time. It sounds to me like this is a problem with one of our packages rather than keystone itself though?

**Comment by benkroeger** [comment]
this is somehow caused by browserify trying to run `aphrodite` through babelify... with it's local configuration. When adding `aphrodite` to`admin/client/packages.js`, this error is gone. I also ran `node build.js` to make sure that `aphrodite` is then included in `public/js/packages.js` but then I see an error that the module `aphrodite` can not be loaded in my browser.
Looks like this only happens when you have keystone installed as a dependency?!

**Comment by jstockwin** [comment]
Has anyone tried adding `"ignore":["node_modules"]` to `.babelrc`? Because `babel-plugin-add-module-exports` and `babel-plugin-transform-class-properties` are devDeps they're not installed and babel chokes on it. We're not exactly sure why babel is running on node_modules, it shouldn't be by default. 

I've got to head out now, but if this fixes it then if you submit a PR someone else might merge it in for you. cc/ @creynders

**Comment by benkroeger** [comment]
with commit https://github.com/keystonejs/keystone/commit/05bbfc4c51cdcc4814714e3216844685fc8d300b, three new files were introduced `admin/client/App/screens/List/components/ListHeaderSearch.js`, `admin/client/App/screens/List/components/ListHeaderTitle.js`, and `admin/client/App/screens/List/components/ListHeaderToolbar.js`. All of which import from `aphrodite` rather than `aphrodire/no-important`. When changing all these files to use `aphrodite/no-important` instead, it works again

**Comment by mxstbr** [comment]
Aweosme, thanks @benkroeger!

**Comment by jacobbubu** [comment]
The issue is still there with latest [keystone](https://github.com/keystonejs/keystone.git#f92632977d309f79bda0676d51a98615da7e0f3d).

```
2016-08-19 15:08:95 error building FieldTypes:
Unknown plugin "transform-inline-environment-variables" specified in "/Users/rongshen/trash/keystone-demo/node_modules/jss/.babelrc" at 0, attempted to resolve relative to "/Users/rongshen/trash/keystone-demo/node_modules/jss" while parsing file: /Users/rongshen/trash/keystone-demo/node_modules/jss/lib/index.js
2016-08-19 15:08:98 error building FieldTypes:
[BABEL] /Users/rongshen/trash/keystone-demo/node_modules/jss-px/lib/index.js: Using removed Babel 5 option: /Users/rongshen/trash/keystone-demo/node_modules/jss-px/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets while parsing file: /Users/rongshen/trash/keystone-demo/node_modules/jss-px/lib/index.js
```

**Comment by SharadKumar** [comment]
Yes - I face the same.. still.

**Comment by benkroeger** [comment]
@jacobbubu this issue is about the babel plugin `add-module-exports` being reported as **unknown**. Your error message looks completely different though.
Please try

```
rm -rf node_modules
npm install
KEYSTONE_PREBUILD_ADMIN=true npm start
```

and watch your terminal for error messages after server start.
If the problem is still there, you should open a new issue... since it's most likely unrelated

**Comment by jacobbubu** [comment]
Thanks @benkroeger. I will open a new issue for that.

**Comment by ellipticaldoor** [comment]
works nice for me now 👍

**Comment by dijs** [comment]
@jacobbubu I am still facing the jss-px issue also...

**Comment by SharadKumar** [comment]
I am getting:

```
2016-08-19 23:08:80 error building FieldTypes:
Couldn't find preset "stage-0" relative to directory "/Users/Sharad/GitHub/xxx/node_modules/react-jss" while parsing file: /Users/Sharad/GitHub/xxx/node_modules/react-jss/lib/index.js

2016-08-19 23:08:81 error building FieldTypes:
Unknown plugin "transform-inline-environment-variables" specified in "/Users/Sharad/GitHub/xxx/node_modules/jss/.babelrc" at 0, attempted to resolve relative to "/Users/Sharad/GitHub/xxx/node_modules/jss" while parsing file: /Users/Sharad/GitHub/xxx/node_modules/jss/lib/index.js
```

**Comment by benkroeger** [comment]
@dijs @SharadKumar please see #3352 #3350

**Comment by jhlord163** [comment]
'yarn add babel-plugin-add-module-exports' or use npm
