### ISSUE TITLE
Unable to set custom collection name

### ISSUE THREAD

**Issue by amirmamaghani** [keystonejs/keystone#3340]
# Bug report

## Describe the bug

I have a MongoDB collection named `transaction` (not `transactions`) and I can not change that because it's production app. 
I created a list:
```
module.exports = {
  plural: 'transaction' ,
  schema: { collection: 'transaction' },
  adapterConfig: { tableName: 'transaction' },
  fields: {
    to_address: {
      type: Text,
      isRequired: true,
    },
  },
}
```
and I'm getting the following:
```
Error: not authorized on DB to execute command { create: "**transactions**", writeConcern: { w: "majority" }, lsid: { id: UUID("7f298343-5b5b-42d5-86b4-0fdb3b4e54da") }, $clusterTime: { clusterTime: Timestamp(1596562160, 2), signature: { hash: BinData(0, 852CEDDB9517F83E6234493224EBE91638AF64F5), keyId: 6818894661306810370 } }, $db: "DB" }
```

read-only access is set on purpose, the most important thing it that `create: "**transactions**"` uses the wrong collection.

## Expected behaviour

I would love to have an option to set custom collection name. As you can see from the example, I already tried everything I read in docs.

**Comment by amirmamaghani** [comment]
anybody?

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
