### ISSUE TITLE
Mongodb sorting issue with mongodb when list has more than 10000 items

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#3348]
# Bug report

## Describe the bug

Seems to be Issue with sorting in mongodb when there are more than 40-50 pages, see the error

`Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.`

fields we are using is indexed

## To Reproduce

have a list with more than 10000 items, there will be issue when you load list page and try to go page number 30+ (or even bigger based on how mongo is configured, this one is at default config).

list page will break with error and in chrome dev tools you can see there are errors is graphql query return value.

## Expected behaviour

It should not have errors

## System information

- OS: Windows
- Browser: Chrome

**Comment by gautamsi** [comment]
we still have this issue.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
