### ISSUE TITLE
Admin validation not rejecting empty 'select' fields with isRequired:true

### ISSUE THREAD

**Issue by ClientsideDesign** [keystonejs/keystone#3367]
# Bug report

When creating a new item in the admin UI, field validation is not preventing form submission where a `select` field has `isRequired:true`, but a selection has not been made, e.g.

    fruit: {
        type: Select,
        options: ['apple', 'pear', 'banana'],
        dataType: 'enum',
        isRequired: true
    },

The user is able to submit the form without selecting a value for 'fruit' and a new item is not added to the list.

## To Reproduce

Create a field with `type:select`, `isRequired: true` and some options, but no default value. Attempt to add a new item to the list from the admin UI, without selecting a value from this field.

## Expected behaviour

The UI should alert the user that a required value for the select field has not been provided and prevent form submission.

## System information

- OS: macOS
- Browser safari
- @keystonejs/keystone 13.1.0
- @keystonejs/fields 16.0.0

**Comment by gautamsi** [comment]
you should add a defaultValue if this has to have a value.

**Comment by ClientsideDesign** [comment]
I disagree; sometimes an interface needs to prompt the user to consider which option is correct.

A UI for a veterinary practise with a dropdown for gender set to `male` by default would definitely introduce data errors.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
