### ISSUE TITLE
Unable to init a project

### ISSUE THREAD

**Issue by jonhewines** [keystonejs/keystone#3368]
Hi

I'm currently unable to create a new project following the documentation [here](https://www.keystonejs.com/quick-start/).

If I try with npm, I get quite far but installation fails after testing the db connection:
<img width="1570" alt="Screenshot 2020-08-10 at 12 24 26" src="https://user-images.githubusercontent.com/25984928/89778301-2a58bf00-db05-11ea-864c-af3b835495e5.png">

If I try with yarn, I don't get that far - there seems to be a 404 on eslint-scope dep.
<img width="1569" alt="Screenshot 2020-08-10 at 12 25 34" src="https://user-images.githubusercontent.com/25984928/89778293-26c53800-db05-11ea-83cd-7f65dd979338.png">

My versions are:
Node: v12.16.1
npm: v6.13.4
yarn: v1.7.0

Any help much appreciated!

**Comment by dabbid** [comment]
Same error for me, on Ubuntu 18.04.4, with:
- nodejs v12.18.3
- npm v6.1416
- yarn v1.22.4
- mongodb with successful connection test

**Comment by joselcvarela** [comment]
Me too. I have investigated this and the problem is in this request
`https://api.github.com/repos/keystonejs/keystone/commits?path=.github/release-count&sha=create-keystone-app-from-github` from `copy-example-project.js` on create-keystone-app.

As workaround I have installed 3.2.3 like this: `npm i -g create-keystone-app@3.2.3` and then ran `create-keystone-app app_name`

**Comment by joselcvarela** [comment]
@jonhewines I think you should be more specific on your title or message because I couldn't find this issue by searching the keywords the error generated.

**Comment by jonhewines** [comment]
@joselcvarela thanks for your answer and feedback on my post - you're right, I hadn't considered the keyword search. Thanks on both counts!
