### ISSUE TITLE
Management mode "Select all" only selects current page

### ISSUE THREAD

**Issue by mxstbr** [keystonejs/keystone#3374]
I'm not 100% sure our backend would even support this at the moment, but when in management mode on a list with more than one page and clicking "Select all" it still only selects one page. (which there's a separate button for)

![screen shot 2016-08-23 at 16 16 17](https://cloud.githubusercontent.com/assets/7525670/17881993/f8ed5418-694c-11e6-8eb7-50c273047535.png)

**Comment by mxstbr** [comment]
Temporary fix for the beta was to remove that button – we'll properly fix that for the full release.

**Comment by jstockwin** [comment]
ref: af357c5d377afb88449473131ec55951fa868d83

**Comment by jstockwin** [comment]
@mxstbr So, I've found a way to do this, but I'm currently making an API request to get all the items when you click the `all` button. I'm also going to have to make that call quite often, to see if the all button should be active. Two options:

1) I'll write some logic to make sure the API call only goes out if strictly necessary. 
2) We can load all the data as soon as the list is first loaded. 

Tempted to go with the 1st option - it'll be slow with lots of data either way, and it'd be best to restrict this to usage of the select all button?

**Comment by jstockwin** [comment]
Actually, scratch that. I thought `itemCount` wasn't always correct, but it is. It's just it's common for `props.items` to be e.g. (for 4 items per page, and 5 items in total, viewing the first page)
![image](https://cloud.githubusercontent.com/assets/8227759/18972113/ba4ca7bc-868f-11e6-94b4-2d880d7e91ce.png)

I now only make a potentially long and slow API call when select all is pressed.

**Comment by IVANLEE99** [comment]
this  is a big bug

**Comment by sonyafung** [comment]
Hi, I want to confirm, I am using Keystone JS version 4.2.1, and this bug is still happening. 

I know that Keystone 4 is "retired" and that there is a version 6 now, but if someone could go back to version 4 and look into this, me and some other people like IVANLEE99 would really appreciate it. 

This is a great CMS and I want to recommend it to even more people that I know of, to use it, but if someone could fix this bug in the previous version 4, a lot of people would really appreciate it.
