### ISSUE TITLE
Wysiwyg is not displayed in production

### ISSUE THREAD

**Issue by jobmbay** [keystonejs/keystone#3376]
Wysiwyg is well displayed in DEV but is no more displayed in prod.

**Comment by MadeByMike** [comment]
@jobmbay can you please give us a little more information. There's no code in the WYSIWYG which is aware of environment variables, so it's likely some other error that's resulting in this. 

- Which package versions are you using? 
- Can you be really specific about what you mean by "not displayed"? 
- Is everything else working?
- Any console errors in the browser or terminal\logs?
- Can you run locally in production mode?

**Comment by jobmbay** [comment]
Sorry @MadeByMike for not giving more information.

I am using the 5.3.5 version

All fields work except for the wysiwig.

In dev, the text editor is displayed correctly but in prod, the editor is not displayed to give you a hand to write. It's like a hidden field
dev: 
![Capture du 2020-08-14 08-36-06](https://user-images.githubusercontent.com/13869468/90231639-00f0a980-de0b-11ea-9198-24fbd40ca30d.png)

prod:
![Capture du 2020-08-14 08-50-19](https://user-images.githubusercontent.com/13869468/90231840-444b1800-de0b-11ea-814c-02450ee2e6a2.png)


Here are the console error: 

/tinymce-assets/themes/silver/theme.js:1 Uncaught SyntaxError: Unexpected token '<'
41
/admin:1 EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
/__webpack_hmr:1 Failed to load resource: net::ERR_TIMED_OUT
40
/admin:1 EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.

**Comment by mwcz** [comment]
I had the same issue the other day, but the environments were reversed.  My Wysiwygs were displaying in prod, but not in dev, because my development server's routing rules  were preventing the tinymce assets from loading.

Can you check your network tab in devtools and look for the tinymce js and css files?  In my setup, they're served under the path `/tinymce-assets`, but it might be different for yours.

**Comment by vanarok** [comment]
I had the same problem in production, but at the same time it was impossible to log into the admin interface, but I could go directly to the interface. This is due to the fact that secureCookie: true during production launch. In normal dev mode, everything works fine, and I also installed an ssl certificate on my server, now the login and editor work fine in production.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.

**Comment by richardvanderdys** [comment]
So is Wysiwyg and HTML fields just not supported at all anymore? I feel like this is a big step backwards. A few days ago I found out that my Keystone 4 project using Mongo as a backend would have to be re-written since the DB auto-upgraded on me. This is fine, but when I went to upgrade, looks like I have to manually convert all of my data to Postgres, and I noticed that an HTML field is not even supported anymore. What should a developer do in this case?
