### ISSUE TITLE
app-nuxt after build and yarn start, all pages and all route will be 404, in yarn dev work fine!

### ISSUE THREAD

**Issue by bookyo** [keystonejs/keystone#3402]
after update keystonejs to 13.0, app-nuxt build and start will cause this error.
![QQ图片20200817115123](https://user-images.githubusercontent.com/20472717/90355789-fee35080-e07f-11ea-881f-014431be2ff4.png)
all route and all pages will be 404 like screenshot.

but in develop (yarn dev) , nuxt work fine. i think this maybe keystone in production not start nuxtjs server.

**Comment by bookyo** [comment]
```
  "dependencies": {
    "@keystonejs/adapter-mongoose": "^9.0.0",
    "@keystonejs/app-admin-ui": "^7.3.0",
    "@keystonejs/app-graphql": "^6.0.0",
    "@keystonejs/app-nuxt": "^5.1.3",
    "@keystonejs/auth-password": "^5.1.11",
    "@keystonejs/fields": "^16.0.0",
    "@keystonejs/fields-authed-relationship": "^1.0.7",
    "@keystonejs/fields-wysiwyg-tinymce": "^5.3.1",
    "@keystonejs/file-adapters": "^7.0.2",
    "@keystonejs/keystone": "^13.1.1",
    "@keystonejs/list-plugins": "^7.0.3",
    "@keystonejs/server-side-graphql-client": "^1.1.1",
    "@nuxtjs/apollo": "^4.0.0-rc17",
    "@nuxtjs/moment": "latest",
    "axios": "^0.19.2",
    "connect-mongo": "^3.2.0",
    "core-js": "2.5.7",
    "cross-env": "^7.0.0",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-session": "^1.17.1",
    "graphql-tag": "^2.10.1",
    "lodash": "^4.17.19",
    "moment": "^2.27.0",
    "nuxt": "^2.14.0",
    "vuetify": "2.3.4",
    "vuetify-notify": "^1.0.6"
  },
```

**Comment by bookyo** [comment]
I found use custom server can fix this issue.

1. create server.js in project root path.
```
const express = require('express');
const { keystone, apps } = require('./index.js');

keystone
  .prepare({
    apps: apps,
    dev: process.env.NODE_ENV !== 'production',
  })
  .then(async ({ middlewares }) => {
    await keystone.connect();
    const app = express();
    app.set('trust proxy', true);
    app.use(middlewares).listen(3000);
  });
```
2. yarn build
3. start server in production
```
NODE_ENV=production node server.js
```
project work fine like before keytonejs 12.0.

**Comment by joselcvarela** [comment]
I am getting this error too (404 NOT FOUND) on GET /admin.
But in development everything runs fine.

I am using Postgres inside Docker, but I don't think that can be related.

**Comment by joselcvarela** [comment]
I could finally solve this issue, but `yarn build` fails silently and shows success at the end.
The problem was in `@keystonejs/fields` package. I have a deprecated version installed (it has dependencies on `@apollo/react-hooks`, but this package is not maintained anymore).

So in order to solve the problem you just need `yarn add @keystonjs/fields@latest`.

Curiosly this not happens in development mode.

NOTE: I have created a project about a 2 weeks ago with CLI but it seems some packages installed have old versions which causes errors. In other words, the project installed with CLI is not ready to use right away (at least for me).

**Comment by bookyo** [comment]
@joselcvarela my issue i think maybe /packages/keystone/bin/commands updated cause it. few days ago dev.js and start.js update, and update keystone to 13.0 will cause my issue, in production nuxt-app not start in keystone server, maybe connect middleware fail. I use custom server, and use apps in middleware solved this issue.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
