### ISSUE TITLE
0.4 FileType error

### ISSUE THREAD

**Issue by imshenshen** [keystonejs/keystone#3437]
My English is horrible 😢 
When i dynamic create A model(load config from db and register the model), in admin.js _FieldTypes.Fields don't have the type that added later. 

https://github.com/imshenshen/cmsOfKeystonejs/blob/master/models/Schema.js#L94

as in my work dir `models/test.js`

``` javascript
Schema.add({
        test:{type:Types.Date,label:"testDate",initial:true}})
```

then the `_FieldTypes.Fields` has `date` attr

![26044043-8196-4af1-990d-5a6fcd180cc4](https://cloud.githubusercontent.com/assets/19701958/18048172/34400a72-6e13-11e6-935f-97f3f0416680.png)

but when i add a Types.Date dynamic( in`models/*.js` don't have a model with a type Date)
![image](https://cloud.githubusercontent.com/assets/19701958/18048255/b8524366-6e13-11e6-8916-fefc45df1a47.png)

**Comment by ellipticaldoor** [comment]
I found the problem! I'm using the frankfurt region of s3 and it seems like know (one dependency of keystone) doesn't support this. Here is more info https://github.com/Automattic/knox/issues/254

**Comment by mxstbr** [comment]
@ellipticaldoor is this the wrong issue you responded to?

**Comment by ellipticaldoor** [comment]
@mxstbr sorry I didn't intended to reply in this issue 😓

**Comment by wmertens** [comment]
The FieldTypes are Fields, which make the input fields of the admin UI. The input fields get stored in the database using the schema. I tried to make some sense of it in #3320 but that is not complete.

So basically, both date and datetime store their data in mongo as dates.

**Comment by JedWatson** [comment]
I *think* what you're seeing is that only **used** field types are included in the `FieldTypes` bundle. This is to reduce the file size when your app loads, as irrelevant code is not included.

In your case, if you're dynamically creating lists after Keystone starts, that'll break for you. There may be other issues too, because we assume when you start your app that your lists have been defined.

Obviously you have a use-case, so it's not simple, but right now that's not 100% supported.

A workaround for this would be to create a list with _all_ the potential field types in it, and hide it, but there may be other issues too. Let us know how you go.

e.g

```js
var FieldsList = new keystone.List('FieldsList', { hidden: true });
FieldsList.add({
  date: Types.Date, // etc
});
```

**Comment by wmertens** [comment]
Ah I misunderstood the problem.
Note that the https://github.com/keystonejs/keystone/tree/webpackify branch should not have problems with this.

**Comment by Noviny** [comment]
Closing this as an issue after Jed's addressing of how to work around this. This is unlikely to make us rearchitect for this use-case, however may be easier in the future.
