### ISSUE TITLE
GraphQL syntax error when using cloudinary image

### ISSUE THREAD

**Issue by kaaljabr** [keystonejs/keystone#3442]
## Description

Trying to use cloudinaryImage field. Keystone fails to start throwing a GraphQL syntax error

## To Reproduce

Followed the instructions at: https://www.keystonejs.com/keystonejs/fields-cloudinary-image/

```
const { Keystone } = require('@keystonejs/keystone');
const { CloudinaryAdapter } = require('@keystonejs/file-adapters');
const { CloudinaryImage } = require('@keystonejs/fields-cloudinary-image');

const keystone = new Keystone({...});

const fileAdapter = new CloudinaryAdapter({
  cloudName: process.env.CLOUDINARY_CLOUD_NAME,
  apiKey: process.env.CLOUDINARY_KEY,
  apiSecret: process.env.CLOUDINARY_SECRET,
  folder: 'my-keystone-app',
});

keystone.createList('Image', {
  fields: {
    image: { type: CloudinaryImage, adapter: fileAdapter },
  },
});

```

## System information

- OS: macOS

## Additional context

error thrown:

```
✖ Initialising Keystone instance
GraphQLError: Syntax Error: Expected :, found (
    at syntaxError (project/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (project/node_modules/graphql/language/parser.js:1404:40)
    at Parser.parseInputValueDef (project/node_modules/graphql/language/parser.js:890:10)
    at Parser.optionalMany (project/node_modules/graphql/language/parser.js:1497:28)
    at Parser.parseInputFieldsDefinition (project/node_modules/graphql/language/parser.js:1052:17)
    at Parser.parseInputObjectTypeDefinition (project/node_modules/graphql/language/parser.js:1036:23)
    at Parser.parseTypeSystemDefinition (project/node_modules/graphql/language/parser.js:708:23)
    at Parser.parseDefinition (project/node_modules/graphql/language/parser.js:146:23)
    at Parser.many (project/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (project/node_modules/graphql/language/parser.js:111:25)
    at parse (project/node_modules/graphql/language/parser.js:36:17)
    at parseDocument (project/node_modules/graphql-tag/lib/graphql-tag.umd.js:135:16)
    at gql (project/node_modules/graphql-tag/lib/graphql-tag.umd.js:176:10)
    at project/node_modules/@keystonejs/keystone/lib/Keystone/index.js:533:17
    at Array.map (<anonymous>)
    at Keystone.getTypeDefs (project/node_modules/@keystonejs/keystone/lib/Keystone/index.js:533:8) {
  message: 'Syntax Error: Expected :, found (',
  locations: [ { line: 3, column: 31 } ]
}
```
```
"@keystonejs/fields-cloudinary-image": "^1.0.2",
"@keystonejs/file-adapters": "^7.0.3",
```

**Comment by dilignt** [comment]
I also get this error.  Does anyone know of a solution?

**Comment by nkappler** [comment]
I get this error using @keystone/fields-color
any solutions to this yet?

**Comment by dilignt** [comment]
I also get this error with Wysiwyg and Content packages, as well as CloudinaryImage on a different keystonejs project.  It seems that this is quite a serious issue in that the additional packages just don't work but presumably not for everyone or else surely there would be a fix available?  I'm on Windows 10 with node v12.18.3.

In order to make progress I've trawled through the code and made this change to node_modules/@keystonejs/keystone/lib/ListTypes/list.js

```diff
1016c1016,1020
<           ${flatten(updateFields.map(field => field.gqlUpdateInputFields)).join('\n')}
---
>           ${flatten(updateFields.map(field => {
>               if (typeof field.gqlUpdateInputFields === 'function')
>                   field.gqlUpdateInputFields = field.gqlUpdateInputFields();
>               return field.gqlUpdateInputFields
>           })).join('\n')}
1031c1035,1039
<           ${flatten(createFields.map(field => field.gqlCreateInputFields)).join('\n')}
---
>           ${flatten(createFields.map(field => {
>               if (typeof field.gqlCreateInputFields === 'function')
>                   field.gqlCreateInputFields = field.gqlCreateInputFields();
>               return field.gqlCreateInputFields
>           })).join('\n')}
```

I'm afraid I'm snowed under with deadlines and I don't have time to completely investigate and do a proper fix + pull request, but hopefully this might help someone do that or at least make progress

thanks

    "@keystonejs/adapter-mongoose": "^9.0.1",
    "@keystonejs/app-admin-ui": "^7.3.0",
    "@keystonejs/app-graphql": "^6.1.0",
    "@keystonejs/app-static": "^5.1.2",
    "@keystonejs/auth-password": "^5.1.13",
    "@keystonejs/fields": "^16.0.0",
    "@keystonejs/fields-content": "^9.0.5",
    "@keystonejs/fields-wysiwyg-tinymce": "^5.3.15",
    "@keystonejs/keystone": "^13.1.1",
    "@keystonejs/list-plugins": "^7.1.1",
    "@keystonejs/server-side-graphql-client": "^1.1.0",
    "@keystonejs/utils": "^5.4.1",

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.

**Comment by dilignt** [comment]
It is so frustrating for those of us trying to go to production with this version of Keystone that critical outstanding issues such as this one are simply closed without being addressed.  I know that this version is now in "maintainence mode", but how is the community able to maintain it when they don't know what the issues are because they have been closed without resolution?  Is it your intention that outstanding issues such as these are reopened in the keystone-5 repository?  

It seems that this is not maintence mode, but simply mothballing this version of the project, with no prospect of any maintenance at all.  When pull requests such as [this one](https://github.com/keystonejs/keystone/pull/2260) are invited to be applied to Keystone Next instead, signalling that there is no prospect of them ever being released in current form, how will we ever go to production with any new fixes or features?

I have been a huge fan and avid user of all the versions of Keystone for years, and I'm sure that Keystone Next will be great, but it is not ready for production yet either, and for those of us trying to make a success of small startup businesses and deliver to clients right now using Keystone, and who don't have the bandwidth to fork and maintain our own bespoke versions, this repeated mothballing of Keystone versions before they are production ready is extremely disappointing and has a huge impact on our ability to deliver for our customers and clients.
