### ISSUE TITLE
Required DateTime and Boolean Fields not Validated Correctly

### ISSUE THREAD

**Issue by johanjordaan** [keystonejs/keystone#3460]
### Steps to reproduce the behavior
Create two fields in some model:
dueDate: { type: Types.Datetime, initial: true, required: true, index: true },
isHidden: { type: Types.Boolean, initial: true, required: true, index: true },

Then create a new item using the admin front end, ensuring that the two values are correctly filled in.

### Expected behavior
I expect the new item to be saved to the db.

### Actual behavior
I get an error saying the dueDate and isHidden is required.

**Comment by JedWatson** [comment]
For completeness, confirming that required booleans are expected to be true, this is an exceptional but documented case and exists because we support processing checkbox input in FormData.

Might revisit that in the future if there's a more sane way to do it, as I'd prefer not to have that sort of edge case in Keystone, but right now this is sort of a "necessary evil".
