### ISSUE TITLE
Warning: connect.session() MemoryStore is not designed for a production environment,

### ISSUE THREAD

**Issue by ellipticaldoor** [keystonejs/keystone#3478]
I'm releasing an keystonejs in production and I'm getting this warning. How I can fix it?

```shell
Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.
```

**Comment by jstockwin** [comment]
Try using a different session store, for example `connect-mongo`. See the `session store` part of the docs [here](http://keystonejs.com/docs/configuration/#options-database).

**Comment by ellipticaldoor** [comment]
Awesome thanks!

What is the default value of session store? I can't find it.

**Comment by jstockwin** [comment]
I mean, from the error message it's presumably `MemoryStore`, but I could not find it anywhere either. 
We get it [here](https://github.com/keystonejs/keystone/blob/17c0de91f8217db856809a13f06db2770a89addf/lib/core/initExpressSession.js#L38), but I'm not sure where it's actually set. 

Since this is solved, I'll close the issue.

**Comment by KhalilKhalaf** [comment]
Ok looks like we can use some properties that can control this behavior: `interval`, `maxAge`, `cookie`, `saveUninitialized`, `resave` .. etc

More can be found here: [MongoDB fix: connection.session() MemoryStore is not designed for a production environment](https://digitalrizzle.wordpress.com/2013/04/26/mongodb-fix-connection-session-memorystore-is-not-designed-for-a-production-environment/)

Also that there are some hacks around this error, for example:

- Handle the error instead of crashing: https://stackoverflow.com/a/44884800/5890227

- use cookie-session instead of express-session: https://stackoverflow.com/a/37022764/5890227

- And/Or to force-clean all sessions in a custom function on our own: https://stackoverflow.com/a/10761522/5890227

I had same issue and did a quick research which is worth sharing. Hope it helps!

**Comment by madc0w** [comment]
The trouble with connect-mongo is that it does not seem to support the "mongodb+srv" protocol, which is new since Mongodb 3.6. We've tried all manner of solutions, including Mongoose, all to no avail.

Can somebody please suggest a Mongodb-based session store that works with mongodb+srv?
