### ISSUE TITLE
🐞 Relationship fields are broken when using multiple adapters.

### ISSUE THREAD

**Issue by altechzilla** [keystonejs/keystone#3520]
I have 3 adapters, one for each MongoDB Atlas database. I'm trying to create a many-to-many relationship between two collections under the same database (hobbies and interests). 

**Issue #1:** They create a new collection for each adapter instead of just the adapter they belong to.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/8274669/91631839-477a0280-e9cc-11ea-856c-27bde284a72c.png">

**Issue #2:** Rather than creating a new collection, they should just create an array of Object IDs just like one-to-one / one-to-many relationships. I know this second one is more like a feature question, but any idea on how to achieve that?

Thanks!

**Comment by altechzilla** [comment]
@timleslie

**Comment by gautamsi** [comment]
there is plan to remove this feature, see #3222

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
