### ISSUE TITLE
Relationship link to linked model page is broken

### ISSUE THREAD

**Issue by jasonfungsing** [keystonejs/keystone#3528]
### Steps to reproduce the behavior
In the Demo website, go to posts
http://demo.keystonejs.com/keystone/posts

Click author in anyone of those post has an author
### Expected behavior
Should link to Author/User page

### Actual behavior
Shows an `Error!`

I can't see the log for the demo, but is my own app, the API call is incorrect.

It should be 
`GET /keystone/api/users/{userId}?drilldown=true`

it is actually
`GET /keystone/api/posts/{userId}?drilldown=true 404 3.423 ms`

**Comment by jstockwin** [comment]
Some additional info: the `to` prop provided to the react `Link` is correct, and is correct on the page.
In the DOM, the `<Link/>` and the `a` it contains both have the correct `to` prop and `href` attributes respectively. 

If you open the link in a new tab, rather than just clicking on it, then everything works fine. Similarly if you refresh the page everything works fine. The only thing going wrong is the API call. I assume this is to do with react doing SPA stuff? Perhaps it makes this api call after the `id` prop has been updated, but before the `list` or `model` (or whatever it's called) prop is updated. I haven't managed to find where this happens yet, but will keep looking.

**Comment by jstockwin** [comment]
Found it. See PR for a fix. cc @JedWatson @mxstbr
