### ISSUE TITLE
Work out pattern for providing Select label to UI builders

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#354]
The graphql API makes the `value` of a `Select` field available, but does not make the `label` available. The Admin UI obtains the `label` field over the `adminMeta` interface. We need to decide what is the correct way to make this available to project builders. We can perhaps do this over the graphql API, or possibly by making some `adminMeta`-like object available. Either way, we need to document the pattern.

**Comment by jesstelford** [comment]
I really like the graphQL `type` option ☝️ Great solution!

**Comment by MadeByMike** [comment]
@jesstelford how much of the `adminMeta` could be passed via the `graphQLAPI`? If the answer it all of it I definitely think an `adminMeta` GQL endpoint should be a priority issue.

If not, I don't think we should invest in changing this except to fix any bug. 

Is this related to #1768 ?

**Comment by MadeByMike** [comment]
Work is in progress on this: https://github.com/keystonejs/keystone/pull/3056 as well as a recent overhaul of adminMeta. There are also other issues related to custom views for the select component. And adminUI hooks have been added since this issue... I think one way or another this can be solved now and I'd rather see a new issue if required that takes into account recent developments. Closing this one as stale.
