### ISSUE TITLE
Keystone admin loads very slowly after restart in production [bug]

### ISSUE THREAD

**Issue by ellipticaldoor** [keystonejs/keystone#3548]
Hi, I'm running keystone in production mode in a server with little cpu and when I restart the admin it takes more than one minute to load the admin page for the first time.

I'm using beta1, there's a way to avoid recompiling? like an option for caching everything the first time until something changes?

**Comment by wmertens** [comment]
We are solving this in #3360, by precompiling. However, Jed would prefer the build system to remain in production to allow customization, so we're not sure yet how this will work.

**Comment by ellipticaldoor** [comment]
oh! I see, but for the moment can I avoid it?

**Comment by mxstbr** [comment]
#2915

**Comment by jstockwin** [comment]
@ellipticaldoor You can set I think `KEYSTONE_PREBUILD_ADMIN=true` in your `.env` file, which will make the admin UI compile when you start your server rather than the first time you load the admin UI. Should work as a temporary fix, as long as you're happy for you app to be a little slower to start.

**Comment by gokulkulkarni1987** [comment]
@jstockwin  you saved our day thanks a ton.
