### ISSUE TITLE
Keystonejs documentation

### ISSUE THREAD

**Issue by jodybrewster** [keystonejs/keystone#3708]
# Bug report

## Describe the bug

Hey I'm new to keystone, but I think your documentation is missing a global install?  Do you npm install -g keystone or something before the npm init step?

A clear and concise description of the bug.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]

**Comment by maheraldous** [comment]
Hi I had the same problem to get the setup done. So I found out that this video https://www.keystonejs.com/ in the home page of the keystone will guide you step by step and it worked for me.

**Comment by bookyo** [comment]
npm init keystone-app my-app
# or
yarn create keystone-app my-app

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
