### ISSUE TITLE
There is no way to set dev server bind address (hostname)

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#3776]
# Bug report

At the moment you can only set `--port`.

**Comment by bookyo** [comment]
hi bro, you can use custom server.
server.js
```
const express = require('express');
const { keystone, apps } = require('./index.js');

keystone
  .prepare({
    apps: apps,
    dev: process.env.NODE_ENV !== 'production',
  })
  .then(async ({ middlewares }) => {
    await keystone.connect();
    const app = express();
    app.set('trust proxy', true);
    app.use(middlewares).listen(3000);
  });
```
and change 3000 to your want. start server.js use node server.js

**Comment by pahaz** [comment]
Yes, I know. I already use it. I think it's a part of the default CLI.

**Comment by gautamsi** [comment]
if you use PORT env in .env and load using NODE_OPTIONS like this

`"dev": "cross-env NODE_ENV=development NODE_OPTIONS=\"-r esm -r dotenv/config\" DISABLE_LOGGING=true keystone dev",`

I have used esm for es6 style importing.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
