### ISSUE TITLE
List search input loses focus after debounce

### ISSUE THREAD

**Issue by petrkrizek** [keystonejs/keystone#3871]
# Bug report

## Describe the bug

After you type something into search input and wait for debounced search trigger, the search input will lose its focus. 

## To Reproduce

Create some list and try to search...

## Expected behaviour

Don't lose focus because sometimes users write slowly.

**Comment by JakeCasey** [comment]
Messed around with this the other day-- it also happens on pressing shift. I think it has something to do with the Suspense component above it rerendering the whole component.  I'm sure it's the same problem as #2237. I was able to 'fix' it by just pulling the search component of the Suspense render, but I don't know enough about Suspense to know what else that might break.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.

**Comment by aleygues** [comment]
Hi there, this bug is still present in the Admin UI and pretty bad for production releases (which is my case). From my point of view, this bug should be fixed in the active maintenance mode. Is there any possibility to take a look?

Thanks for your work!
