### ISSUE TITLE
Documentation on KeystoneJs on AWS Lambda is misleading

### ISSUE THREAD

**Issue by jacobdoran** [keystonejs/keystone#4032]
Love Keystone JS however the documentation mentions "Custom server as a Lambda" and gives an example of running a KeystoneJS GraphQL app in a lambda function using "serverless-http". However, in practice, this does not work because the packaged size is well over 250mb. I tried using "serverless-webpack" to get it down but unfortunately, some of the libraries have eval'd requires and expressions in a require so this didn't work. Maybe with a lot of messing about with webpack config this would be possible to get working but this would seem a rather unstable and unwieldy solution.

May I suggest that this Lambda example is removed from the documentation and instead a more accurate statement concerning Lambda support is given? Unless of course, I am missing something and if so feel free to advise me.

**Comment by wesbos** [comment]
I also talked to @jesstelford about hosting on Vercel and he said "Not all of it unfortunately - some of our dependencies wouldn't package correctly for deployment to serverless."

So I agree that this should be taken out of the docs unless it is possible. Maybe submit a PR @jacobdoran ?

**Comment by JedWatson** [comment]
Thanks for the feedback @jacobdoran and sorry this has been misleading. I know @jesstelford put a bunch of work into this early on which would have been when those docs were written, but I think since then it's stopped being feasible and I agree we should remove the lambda example from the docs until it's more possible.

fwiw we're working on a major update to the Admin UI, which has everything built as a Next.js app, and we're hoping that makes it a lot easier to deploy on platforms like Vercel in the future (as well as making Lambda builds possible again)

that's not today though, we'll revisit the hosting documentation when we've shipped it.

a PR to update the docs based on your experience would be great if you have a chance @jacobdoran

**Comment by jesstelford** [comment]
Yep, those docs are horribly out of date now.

Apologies for leading you down a fruitless path @jacobdoran!

**Comment by jacobdoran** [comment]
Created a pull request: https://github.com/jacobdoran/keystone/pull/1

**Comment by JedWatson** [comment]
@jacobdoran I just realised that you've opened that PR against your fork - would you mind opening it against the main keystone repo? I'd be happy to merge it.

**Comment by jacobdoran** [comment]
Thanks - fairly new to making contributions on Github. Hopefully done it correctly this time:
https://github.com/keystonejs/keystone/pull/4097

**Comment by JedWatson** [comment]
That did it! Thanks again. The updated docs should be published to the site in a few minutes.
