### ISSUE TITLE
Cannot read property 'rel' of undefined

### ISSUE THREAD

**Issue by ioandev** [keystonejs/keystone#4046]
# Bug report

## Brief

One of the adapters is undefined for a post hook, so the graph API throws an exception after executing a mutation
`adapter-mongoose.js` fails on the first line:
`const { cardinality, columnName, tableName } = adapter.rel;`

The exception: https://gist.github.com/ioandev/7f6f34fbd38acebd088835d3c9463b2f
The keystone: https://github.com/ioandev/keystonejs-issue

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Clone the repo
2. execute `yarn dev`
3. create an article with the UI
4. go to the graphql and execute:

```
mutation incrementPageViews($id: ID!) {
  incrementPageViews(id: $id) {
    currentViews
  }
}

data:
{"id": "5f972bf38489da23406c34ac"} -- an id of an existing article
```

The issue seems to be with a hook post update, as the views do in fact get updated.
The error comes from this update:
```
const newItem = await adapter.update(id, {
	...oldItem,
	views,
});
```

## Expected behaviour

No exception should be thrown

## System information

- OS: Windows

## Additional context

Trying to follow the tutorial from https://www.keystonejs.com/guides/custom-schema

**Comment by Temkit** [comment]
Same problem here !!!

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
