### ISSUE TITLE
Cannot login to AdminUI in production build

### ISSUE THREAD

**Issue by vramirez122000** [keystonejs/keystone#4142]
# Bug report

## Describe the bug

When running the production build of the meetup example, cannot login to AdminUI. It works when running in dev mode
or in production if the PasswordAuthenticationStrategy is removed. Nevertheless, my use case requires authentication
to the AdminUI app.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. cd examples/meetup
2. yarn && yarn build && yarn start
4. Open http://localhost:3000/admin
5. Attempt to login with admin user
6. Login page refreshes but no navigation to dashboard. Browser network log shows that the authentication mutation
was posted but the response is unavailable to view.

## Expected behaviour

Navigation to admin dashboard

## System information

- OS: Fedora 32, Centos 8
- Browsers: Firefox 82, Chromium 86
- @keystonejs/demo-project-meetup version 6.2.8

**Comment by vramirez122000** [comment]
Workaround https://gist.github.com/molomby/6fa22c165e0025f0f83d55195f3c6e37

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
