### ISSUE TITLE
Keystone 4 documentation

### ISSUE THREAD

**Issue by Noviny** [keystonejs/keystone#4181]
We recently made a big push to update our documentation, as well as streamline the process of updating it in the future. To that end, we've redone the documentation site using gatsby, and have put it up on netlify.

What would be great is feedback on the documentation we've got. If you've got some time, a bit of a review would be amazing.

The most important pages to look at are:
-  [the getting started page](http://keystonejs.netlify.com/getting-started)
- [yo generator guide](http://keystonejs.netlify.com/getting-started/yo-generator)
- [setting up guide](http://keystonejs.netlify.com/getting-started/setting-up/part-1)
- [Documentation launch page](http://keystonejs.netlify.com/documentation)

The questions I'm most interested in are:
- Can I find the information I want?
- Is the information clearly presented?

Feedback is welcome here, or if you find an issue you can solve, you can make a PR to the [docs](https://github.com/keystonejs/keystone/tree/docs) branch.

Thanks in advance!

**Comment by christroutner** [comment]
There are a lot of common pitfalls that aren't captured in the *yo
generator guide*. Pitfalls such as specific versions of node to use or
avoid, or having to install yo as sudo (I think, it's been a while). Add to
this that the master branch of Keystone is often broken. That leads to a
lot of frustration and a lack of adoption.

**Comment by Noviny** [comment]
@christroutner Just checking, are you flagging this as three separate issues?

1. Node version specification not provided
2. No information about sudo installing if you cannot globally install
3. Master branch of keystone is often broken

The third does not seem to be a generator or documentation issue, as the generator pulls a set version from npm, and doesn't interact with master.

**Comment by gcortese** [comment]
Hi - i would like to use keystone 4 for a project, can you please let me know if/what in the documentation you mention is up-do-date and 'reasonably' complete ?  
Thanks a lot,
giovanni

**Comment by bill-kidwell** [comment]
As previously mentioned, there is no mention or pre-requisites.  I was unsure which version of node.js would work.  I am using v6.11.2.  I also ran into problems due to the lack of python.

I got a number of warnings when installing generator-keystone

$ npm install -g generator-keystone
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

NOTE: Please advise if I should open separate issues for these.

---

Upon creating a project with yo keystone, there were additional warnings.
There was also an error because I needed python on the path.  I am unsure, based on the output whether that is optional or not.  I recommend that you state it up front, and if it is not optional, that generator-keystone fails.

npm WARN deprecated letsencrypt-express@2.0.6: letsencrypt-express has been renamed to greenlock-express and will now be maintained as such.
npm WARN deprecated localhost.daplie.com-certificates@1.2.5: Moved to localhost.daplie.me-certificates
npm WARN deprecated letsencrypt@2.1.8: letsencrypt has been renamed to greenlock. Please find it at npm greenlock
npm WARN prefer global marked@0.3.6 should be installed with -g

gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

---

Re: the structure, I found a couple of discrepancies between the generator's output and the docs.  It may be due to the options that I chose.  It also may be due to the python errors I saw. It might be wise to call that out if they are intentional.

I marked them with asterisks below.

```
|--lib  *not present*
|  Custom libraries and other code
|--models 
|  Your application's database models
|--public
|  Static files (css, js, images, etc.) that are publicly available
|--routes
|  |--api *not present*
|  |  Your application's api controllers
|  |--views 
|  |  Your application's view controllers
|  |--index.js 
|  |  Initialises your application's routes and views
|  |--middleware.js
|  |  Custom middleware for your routes
|--templates
|  |--includes *not present*
|  |  Common .pug includes go in here
|  |--layouts 
|  |  Base .pug layouts go in here
|  |--mixins
|  |  Common .pug mixins go in here
|  |--views
|  |  Your application's view templates
|--updates
|  Data population and migration scripts
|--package.json
|  Project configuration for npm
|--keystone.js
|  Main script that starts your application
```
---

The section on the User.js file appears to be out of date.
I assume the Relationships section is added as part of answering Yes to the blog option.  I can leave that out and submit a pull request if the content below is correct.

```
var keystone = require('keystone');
var Types = keystone.Field.Types;

var User = new keystone.List('User');

User.add({
  name: { type: Types.Name, required: true, index: true },
  email: { type: Types.Email, initial: true, required: true, index: true },
  password: { type: Types.Password, initial: true },
  canAccessKeystone: { type: Boolean, initial: true }
});

User.register();
```
is now
```
/**
 * User Model
 * ==========
 */
var User = new keystone.List('User');

User.add({
	name: { type: Types.Name, required: true, index: true },
	email: { type: Types.Email, initial: true, required: true, unique: true, index: true },
	password: { type: Types.Password, initial: true, required: true },
}, 'Permissions', {
	isAdmin: { type: Boolean, label: 'Can access Keystone', index: true },
});

// Provide access to Keystone
User.schema.virtual('canAccessKeystone').get(function () {
	return this.isAdmin;
});


/**
 * Relationships
 */
User.relationship({ ref: 'Post', path: 'posts', refPath: 'author' });


/**
 * Registration
 */
User.defaultColumns = 'name, email, isAdmin';
User.register();
```
---
Here you start talking about settings in keystone.js (I think)

> Authentication and Session Management
For Keystone to provide authentication and session management to your application, it needs to know a few things:

> The option user model must be the name of the Model that Keystone should look in to find your users. If you use a different model name, be sure to set the option correctly.

but you don't mention keystone.js.  Educated guess.

---

> Routes & Views </br>
> Usually, the easiest and clearest way to configure the logic for different routes (or views) in your application is to set up all the bindings single file, then put any common logic (or middleware) in another file.

I think this should read "in your application is to set up all the bindings [in a] single file"

I'll pick up from here next time.

**Comment by bill-kidwell** [comment]
@Noviny, 

Can you confirm this is the type of feedback you are looking for?  I noticed a few things out of date, so if it is too early for things that low level... just let me know.

**Comment by Noviny** [comment]
@bill-kidwell 

Honestly, anything you see that needs fixing, it would be amazing to get help with. The documentation has now been merged in to master, so if you see something on the new website that's wrong, make a PR to update it and tag me and I'll jump on it.

**Comment by zacharysang** [comment]
Does anyone happen to know if SSL setup docs are currently being worked on? I just went through the process of that setup and experienced some gaps (Eg: configuration settings that needed to be set, but not mentioned) that required me to read through the source to figure out. If this isn't something already in the works, I'd be happy to work on this myself!

**Comment by christroutner** [comment]
@zacharysang I also struggled trying to figure out SSL setup with KeystoneJS. I think I left a thread on the Google group with the results of my research. I eventually figured it out and wrote up this readme on how to setup Nginx and a Let's Encrypt SSL:

https://github.com/skagitpublishing/docker-connextcms/tree/master/nginx

The directions focus on [ConnextCMS](http://connextcms.com), running in a docker container, but it should work equally well for a KeystoneJS installation.

**Comment by internetErik** [comment]
This is what I did for SSL
```
let keystoneInit = {
  'name': 'Marwen',
  'brand': 'Marwen',
  'static': '../public',
  'view engine': 'hbs',
  'mongo': process.env.MONGO_URI || 'mongodb://localhost/some-site',
  'emails': 'templates/emails',
  'cookie secret': process.env.COOKIE_SECRET,
  'auto update': true,
  'session': true,
  'auth': true,
  'user model': 'User',
  'port': process.env.PORT || 3000,
};

if(process.env.NODE_ENV === 'production') {
  keystoneInit['ssl']      = true; // true to start both, 'only' to start only sll server
  keystoneInit['ssl key']  = process.cwd() + '/some.key';
  keystoneInit['ssl cert'] = process.cwd() + '/some.crt';
  keystoneInit['ssl ca']   = process.cwd() + '/some.pem';
  keystoneInit['ssl port'] = process.env.SSL_PORT || 443;
}

keystone.init(keystoneInit);
```

**Comment by zacharysang** [comment]
@christroutner @internetErik  I guess I am referring more specifically to documenting the letsencrypt setup process via letsencrypt config. Following [this article](https://medium.com/keystone-js/lets-encrypt-keystonejs-81fd55db9a3d), I was able to fully setup SSL certificates and such using only environment variables (dotenv) and the configuration object passed into `keystone.init({...})` all within keystone.js. This functionality is really powerful and helpful for setting up keystone, but some of the necessary details are currently missing from the docs. While there is overlap with the greenlock-express module, it may still be worth documenting the various config settings that can be included.

Here is an annotated version of my config object passed to keystone.init({}):

```
'port': process.env.PORT || 3000,
'ssl port': process.env.SSL_PORT || 3001,
'ssl public port': 443, // different from `ssl port` if using iptables/ port forwarding
'ssl': 'force', // force redirects to https port 
'ssl cert': letsencryptPath + 'cert.pem', // path to generated certificate (generated at `$HOME/letsencrypt/etc` by default)
'ssl key': letsencryptPath + 'privkey.pem', // path to generated private key (same default as ssl cert)
	letsencrypt: {
		email: 'email@email.com',
		domains: 'domain@domain.com',
		register: true, // whether or not to automatically register with letsencrypt
		tos: true, // agreeing to letsencrypt's Terms of Service
		production: process.env.PRODUCTION, /* specifies if keystone should use the staging letsencrypt certification server or the production one (it is advised to be used during setup to avoid hitting the rate limit). Values should be `false` for staging (I excluded the .env variable since any value is read in as a string) or `true` for production ( :) ) */
}
```

**Comment by htor** [comment]
As part of streamlining the process of updating the docs, maybe we should start versioning the docs - at least for the API section? 

A little drop-down or selector with v3, v4 could point to the relevant versions of documentation that are compatible and people would be less confused if the older docs didn't disappear from history, as they may rely on them. The older versions would have a reference, as well as the newest.

A lot of popular libraries do this today: [vuejs](https://vuejs.org/v2/api/), [https://docs.angularjs.org/api](angularjs).

**Comment by stennie** [comment]
@htor As mentioned at the start of this discussion, the documentation is now a static site built using Gatsby. I couldn't find info on how to build the docs, so created #4654 (Add guide for building Keystone 4 docs) with some quick instructions.

Since the new documentation has been merged to master a while ago, I'm going to create & link separate tracking issues for any lingering suggestions from this discussion thread so the remaining tasks are clearer. If anyone has suggestions for documentation improvements, please create a new issue.

If anyone is interested in contributing to Keystone 4 documentation, please join the [KeystoneJS Community Slack](https://launchpass.com/keystonejs) for feedback and discussion.

Regards,
Stennie
