### ISSUE TITLE
defaultValue doesn't set default constraint for database schema column using knex adapter

### ISSUE THREAD

**Issue by josemf** [keystonejs/keystone#4215]
# Bug report

`defaultValue` config is not used in `addToTableSchema` field adapter methods for `Knex<Field>Interface`.

## Describe the bug

I'm not sure about your graphql mutation methods, I assume you probably fill this `defaultValue` config when adding rows to the database, but I think it would be a good practice to expose this to the `defaultTo` property in you field adapters, so they might use this to enforce a default value in the database schema:

Example for Text:
```javascript
  addToTableSchema(table) {
    const column = table.text(this.path);
    if (this.isUnique) column.unique();
    else if (this.isIndexed) column.index();
    if (this.isNotNullable) column.notNullable();
    if (typeof this.defaultTo !== 'undefined') column.defaultTo(this.defaultTo);
  }
```

Where this might be of no importance for most case scenarios I think might be reasonable to say that other keystone integrations might use the resulting database by directly querying into the relational database schema.

As for me, since I'm developing a database migrations framework that uses the `addToTableSchema` methods, I think it is a better value to have the defaultValue set onto the database schema.

https://github.com/josemf/keystone-adapter-knex-migrations

## To Reproduce

yarn create-tables

## Expected behaviour

A `default` constraint in database schema that uses the value set in `defaultValue` config

## Screenshots

N/A

## System information

N/A

## Additional context

N/A

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
