### ISSUE TITLE
KeystoneJS framework forum component or plugin

### ISSUE THREAD

**Issue by yao23** [keystonejs/keystone#4304]
Is there any default component or plugin for forum in KeystoneJS framework? (If no, is there any play to add one in roadmap?)

I found one but it's used for Keystone community and abandoned:
https://github.com/JedWatson/keystone-forum

**Comment by doodirock** [comment]
Would love this too!

**Comment by Wadimich** [comment]
I am currently working on my own project, based on keystonejs and writing forum. This will take some time, but, if you wish, i can upload forum files here, after it would be done.

**Comment by Wadimich** [comment]
So, i've did something, you can check it here: [https://github.com/Wadimich/KeystoneForums](url)

**Comment by Noviny** [comment]
@yao23 There isn't an official one, though I'm pretty darn impressed by the one @Wadimich has written that extends keystone. Forums aren't a core functionality of keystone, and something we are more interested in allowing keystone to help you construct a forum, not be the forum.

@Wadimich That's a really cool project. I'm curious what they key advantages you got from building this into keystone over building it with keystone were?

**Comment by Wadimich** [comment]
@Noviny Actually, i decided to make something different. I'm working on plugins, based on keystone, at this moment it works, i have folder, which can load models, overwrite models (need to make it extend, though), overrite and extend routes, templates, and public files. I made 2 plugins, the forum, like in my github and custom admin panel, based on vali-admin templates.
I don't want to fork keystone, just because i think, modifying keystone too difficult for my developer skill.

**Comment by Noviny** [comment]
@Wadimich Aah, sorry, didn't look closely enough at your code!

Definitely like the idea of this kind of thing as a plugin. So if I'm reading it right, this project is effectively an extension of the keystone project you get from the generator, and the goal is to wrap it up in the same way so others can use it as a project base?

**Comment by Wadimich** [comment]
@Noviny Yes, i'm using keystone as wrapper to make it more powerful. For other people i want to make it as simple as wordpress CMS.
