### ISSUE TITLE
Update react-dnd and remove react-dnd-html5-backend

### ISSUE THREAD

**Issue by sarahbethfederman** [keystonejs/keystone#4316]
As of react-dnd 2.2.3 it seems that react-dnd-html5-backend has been merged into core, can this be updated?

**Comment by vitalbone** [comment]
Hi @sarahbethfederman, apologies for the lateness of the reply. I think that this has been resolved since this issue was opened. Did you mean adding `react-dnd-html5-backend` into keystone core? If so, you'll find it has been added as a dependency (using v2.2.4) https://github.com/keystonejs/keystone/blob/master/package.json . Please let us know if you meant something else and we can try to find a fix, or please feel free to submit a PR. Thanks!

**Comment by sarahbethfederman** [comment]
Actually I meant that react-dnd-html5-backend is deprecated because it's now been merged into react-dnd. So it can be removed from the project so it's not duplicated. :)

**Comment by sarahbethfederman** [comment]
See: <https://github.com/react-dnd/react-dnd-html5-backend>
"** NOTE: React-Dnd has been restructured as a monorepo. This code has been merged into the the react-dnd main repository."

**Comment by vitalbone** [comment]
Oh my bad, thanks for the clarification.

Yes it's true that the code for `react-dnd-html5-backend` has been merged into the `react-dnd` repository as they have turned it into a monorepo. However the packages are still required/imported separately by the consumer.

- [You can see all the packages that are now available here](https://github.com/react-dnd/react-dnd/tree/master/packages).
- [The docs also highlight this](http://react-dnd.github.io/react-dnd/).

The best way to think of a monorepo is that it makes it easy for the maintainer to manage and version a bunch of packages all in one place but they're still able to publish them individually (eg, to NPM). I hope that makes sense.

**Comment by sarahbethfederman** [comment]
Ah ok, interesting! Thanks!
At the time I was trying to fork this to Preact so was trying to track all the places that the BSD license. No longer an issue :) Thanks!
