### ISSUE TITLE
Surface isUnique constraint errors in Admin UI

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#433]
Dependent on #431

When attempting to create an item which violates a `unique` constraint, the Admin UI does not surface any errors:

![unique-no-error](https://user-images.githubusercontent.com/612020/46780349-ff19b300-cd67-11e8-9f9e-2298cae003c0.gif)

Similarly for `update` mutations.

**Comment by MadeByMike** [comment]
@molomby Is this one still relevant?

**Comment by molomby** [comment]
#1857 fixed this for Mongo, not generally. We still get ugly messages on the Knex adapter:

<img width="381" alt="Screenshot 2020-01-30 at 11 11 24" src="https://user-images.githubusercontent.com/2416367/73408766-6b4f6a00-4351-11ea-9991-8bca2e9469c7.png">

This is also an example of a much further reaching security issue whereby GraphQL errors leak system internals (#2303).

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
