### ISSUE TITLE
Drilldown Not Working

### ISSUE THREAD

**Issue by PreslandBoy** [keystonejs/keystone#4349]
### Expected behavior

Applying the drilldown option should show data from the related model inside the parent model in the Admin UI.

### Actual/Current behavior
Drilldown does nothing when applied to many or single relationships.

```
var Event = new keystone.List('Event', {
	autokey: { path: 'slug', from: 'title', unique: true }, 
	drilldown: 'videos'
});

Event.add({
	name: { type: Types.Text, required: true, index: true },
	date: { type: Types.Date },
	gradesInvolved: { type: Types.Relationship, ref: 'Grade', many: true },
	images: { type: Types.CloudinaryImages },
	videos: { type: Types.Relationship, ref: 'Video', many: true },
	documents: { type: Types.CloudinaryImages }
});
```
The above code behaves as though the drilldown option is not specified.

### Steps to reproduce the actual/current behavior
Add the drilldown option to a model. 

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.5
| Node             | 7.5.0

**Comment by DanPen** [comment]
I'm having the same issue. I'm new to KeystoneJS, so I don't even know what a drilldown looks like in the admin UI.

**Comment by Jexah** [comment]
@DanPen The drilldown is different to what you would expect coming from a BI background. It appears to be the breadcrumbs near the top of the page: https://puu.sh/whKNE/0567fd1831.png

**Comment by PreslandBoy** [comment]
Ahhh yes that seems to be what it is. Looks like I'll need to make a custom interface to edit related items on the one page.

**Comment by stennie** [comment]
@**PreslandBoy** The drilldown option does appear to be unhelpfully named.

I suspect the actual option you were looking for might be to add a [Relationship Definition](http://keystonejs.netlify.com/documentation/database/relationships/) in order to display related data in the Admin UI.

For example, something like:

```
Video.relationship({ path: 'events', ref: 'Event', refPath: 'videos' });
```

Note that this relationship is defined in the model being referred to (Video) rather than the model with the editable `Types.Relationship` field (Event, in this example).

Regards,
Stennie
