### ISSUE TITLE
Types.Html not displaying as expected

### ISSUE THREAD

**Issue by quitequinn** [keystonejs/keystone#4356]
### Expected behavior
Type.Html displays and is editable.

### Actual/Current behavior
Types.Html not displaying as expected. You can add the field but it renders as visibility: hidden;.

### Steps to reproduce the actual/current behavior
Simple add a Type.Html field. 

ex.
'description: { type: Types.Html, wysiwyg: true, collapse:true },`

### Environment
Mac 10.12.5 
Chrome Version 59.0.3071.86 (Official Build) beta (64-bit)

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.5
| Node             |  8.0.0

**Comment by stennie** [comment]
@quitequinn This is working as expected since you included the `collapse:true` field option which hides the field by default:

> Displays an **+ add** link in the admin UI when the field has no value. Will completely hide field UI when `noedit` is also set to true, when the field has no value

If you remove the `collapse` option you should get an editable HTML textarea.

See [Field Options](http://keystonejs.netlify.com/api/field/options/) in the Keystone 4 documentation for other options.

Regards,
Stennie
