### ISSUE TITLE
Is it possible to use Angular as view engine instead of PUG?

### ISSUE THREAD

**Issue by SandstromEric** [keystonejs/keystone#4376]

**Comment by ghuroo** [comment]
I may not be an expert, but you're comparing a server template engine with a cliente framework.

It's not replaceable, but you can simply render a base template (in .pug) and then add all your javascript (angular.js).

For delivering data from the server to angular, you can either build API endpoints which request the DB (e.g. GET */api/blog/post/1 or build those DB requests on the home view and pass them through a res.local variable (e.g. res.local.blogPost) and on your home .pug template inject the local: window.blogPost = !{ JSON.stringify(blogPost) }; and later on something like $scope.blogPost = window.blogPost;

**Comment by SandstromEric** [comment]
Ye so if you basically can create an rest api and then let Angular 2 do the rest. I wonder how i then would structure the project. Any ideas how to execute it properly would be great! thanks!

**Comment by ghuroo** [comment]
@SandstromEric I have no experience with Angular 2, only with it's 1st version, so I can't help you with that.

But regardless of it's version, angular and your express app are separate things, so you should develop the way you're used to.

In my Angular 1 experience, I loaded the home view ("/" route) and then loaded all the frontend stuff like I usually do.

The only issue I had was regarding the Angular Router (ui-router), since I was using the HTML5 history api (no "#" on the URL), I had to remap all angular routes to the home route.

`
app.get('/', routes.views.home);
app.get('/example', routes.views.home);
app.get('/example2', routes.views.home);
`

**Comment by Noviny** [comment]
Thanks @ghuroo for answering this question.

What we do with react is just use html, and render a base html page which then pulls in our react files. I assume a similar approach would work for angular as well. Closing this as an issue.
