### ISSUE TITLE
Missing individual item link in admin panel for new added model

### ISSUE THREAD

**Issue by yao23** [keystonejs/keystone#4383]
### Expected behavior

Showing link to individual item page

### Actual/Current behavior

Individual item page link is missing, but could open the page after type the url in browser

### Steps to reproduce the actual/current behavior

Visit admin panel item page

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.5
| Node             | 4.4.0

I added a new model Item and it doesn't show the specific link for each item, but the page could be visited if I type url in browser.

For example, I could access the item with url (the id 5963c90021354f3217082840 is logged by console.log() when fetch items from MongoDB):

/keystone/items/5963c90021354f3217082840

but when I hover mouse on the item in admin panel item page, it doesn't show the item urls as posts in example do.

**Comment by icyretribution** [comment]
Have you defined default columns for your new model?

**Comment by yao23** [comment]
Yes, I do.

```
var keystone = require('keystone');
var Types = keystone.Field.Types;

var Item = new keystone.List('Item', {
  map: { id: 'itemId', name: 'title' },
  autokey: { path: 'slug', from: 'itemId', unique: true }
});

Item.add({
  itemId: { type: Types.Number, default: 0 },
  title: { type: String, required: true },
  state: { type: Types.Select, numeric: true, options: [{ value: 0, label: 'draft' }, { value: 1, label: 'published' }], default: 0 },
  description: { type: Types.Html, wysiwyg: true, height: 200 },
  image: { type: Types.CloudinaryImage },
  imagePath: { type: String, default: '' },
  url: { type: String, default: '' },
  createdTime: { type: Types.Date, required: true, default: Date.now() }
});

Item.defaultColumns = 'itemId|5%, title|20%, state|5%, createdTime|10%, description|60%';
Item.register();
```

**Comment by icyretribution** [comment]
So the issue I see is here:
your current map for id links to "itemId" which currently holds no "initial" attribute in your model.
also worth noting: each model includes a default "id" value as a unique key (this is the '5963c90021354f3217082840') which you accessed the "Item" with through admin.

The easiest fix to get your unique key loading as link is to change 'itemId' in your default columns to 'id'. This will give your title a link using the value. if you have a different desired effect, let me know.

**Comment by icyretribution** [comment]
Sorry, deleted the last reply; had to re-word a few things.

Your object models by default will contain a unique id. It is stored under the document object in mongodb as "_id".

You could effectively remove the itemId value (unless for some reason you need another, separate, redundant id value.)

also  "map: { id: 'itemId', name: 'title' }" is also unnecessary.

Your title is auto mapped to the key provided in the "_id" value for the sake of the admin interface.

also in your defaults, please feel free to remove 'itemId|5%,' as the id will be linked in the title as an alias.

**Comment by yao23** [comment]
1. I removed the "ID" from the default columns but it still shows in admin UI.
`Item.defaultColumns = 'title|20%, state|10%, createdTime|15%, description|55%';`
2. It conflicts with _id.ObjectID is the reason it doesn't work to use itemId as autoKey?

**Comment by icyretribution** [comment]
ok another few things i just didnt think of. stupid me.

1. 
```
**CHANGE THIS** 
autokey: { path: 'slug', from: '_id.ObjectID', unique: true }
**to**
autokey: { path: 'slug', from: 'title', unique: true }
```
--this will make your slug match your title. which is semantically more user friendly. I have no idea why i thought you wanted the craptastic ObjectID for a document route. its just not the easiest way for a user to read things ;) 
my bad there.

2. In order to get the ID column to dissappear, this is where the "map" attribute comes in. This is where your admin panel decides what to map the object's ID to (where the link goes to click on from admin as well)

set the map back with only a title.

```
var Item = new keystone.List('Item', {
        **map: { name: 'title' },**
	autokey: { path: 'slug', from: 'title', unique: true }
});
```
and, FYI it did work, but it was just a redundant reference to the same value. found in _id.ObjectID

**Comment by yao23** [comment]
```
var Item = new keystone.List('Item', {
  map: { name: 'title'},
  autokey: { path: 'slug', from: 'title', unique: true }
});
```
The above code works, but the default column order matters (it seems 1st column plays a significant role)
```
Item.defaultColumns = 'itemId|10%, title|20%, state|10%, createdTime|15%, description|45%';
```
It doesn't show link when hover on title (with itemId as 1st column)

```
Item.defaultColumns = 'title|20%, itemId|10%, state|10%, createdTime|15%, description|45%';
```
but the above code does (with title as 1st column)

**Comment by icyretribution** [comment]
I'm sorry I seem to be confused about what your expected result is.. I'll break down the model and describe what the parts will do in your scenario.


```
var Item = new keystone.List('Item', {
	map: { name: 'title' },
	autokey: { path: 'slug', from: 'title', unique: true }
});
```
**map: { }** 
_{name:}_
sets default sort column, overriding the generated _id.ObjectId default value. until you set this your sort column is always _id.ObjectId. In this instance, we are sorting by title. Remove the map line if you want your id to show as your first column. 
The link will always appear attached to the first column, but requires you to have a text present to wrap the <a></a> reference around. In your original request, you had no text returned because you had a bad pointer.
_{id:key}_
maps a field ( id) to a key value (key)

` autokey: { path: 'slug', from: 'title', unique: true }`

**autokey: { }**
 provides a uri friendly reference to a routed 'path: ' using the 'from: ' to indicate a DOM field. 
 in the case of our last usage, we are defining the slugs reference to  'title'. Therefore converting the title to a linkable value (somethin more like /keystone/items/hot-dog
rather than /keystone/items/5963c90021354f3217082840



**On to the columns.**

```
Item.defaultColumns = 'title|20%, state|5%, createdTime|10%, description|55%';
Item.register();

```
Unless you have overridden using the map value, the id will always show first. If you want it to stop showing, define the map{ name: ''} value, and remove it from the default columns.

Otherwise, restore the id:_id.ObjectId mapping reference, put the id back in front, and define the id size in your default columns, and your id will show as an admin field with link.


Hope this broke it down well enough.

Feel free to continue if you need further assistance.

**Comment by yao23** [comment]
Thanks a lot, it helps me understand model configuration in Keystone.
