### ISSUE TITLE
File field does not allow to pick the same image after click cancel.

### ISSUE THREAD

**Issue by miguelvvs** [keystonejs/keystone#4394]
# Bug report

## Describe the bug

On Admin UI using a File field, If the same file that was selected previously is selected after click "cancel" the field does not show it

## To Reproduce

it can be replicated in any list using the File field, a diff file for "/examples/todo/index.js" of To-Do example is attached.[To-Do-Diff.diff.zip](https://github.com/keystonejs/keystone/files/5599216/To-Do-Diff.diff.zip)

1. Go to Create Todo item.
2. Click on "Upload File" pick any valid file.
3. After getting the field update Click on "Cancel"
4. Click on "Upload File" pick the same file from step 2
5. The field does not show the selected file.

## Expected behavior

The File field should show the selected file all the time, even after a cancel action.

## Screenshots

N/A

## System information

it does not seem to be related to the system, but just in case.

- OS: MAC OS Catalina
- Browser: Google Chrome  86.0.4240.198

## Additional context

I have a proposal for a solution, related to the hidden input used to pick the file. however, I'm not able to open a pr since I cannot push a branch to the repo.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
