### ISSUE TITLE
[Contribution / Feature Request] Generic Image / Images Type

### ISSUE THREAD

**Issue by Max-Sum** [keystonejs/keystone#4416]
I am building a app using [Upyun](https://www.upyun.com) for image storage. But I have found the lack of a generic Image/Images type where I could implement the function.
There are several issues about Storage API and multiple file type, however most of them haven't got update since 2017.
I would like to contribute for the project about this. Could you tell me where can I start with?

Proposals:
 - Implement a generic image/images type, replacing CloudinaryImage Type
 - Refactor the project using ES2015 & ES2016
 - Migrate to Koa 2
 - Modulize the project

**Comment by Teranode** [comment]
Good luck getting replies on this project :/ as you can see through all the open issues, there's barely any replies at all.

**Comment by Noviny** [comment]
@Max-Sum Sorry for slow replies, and thankyou for your interest.

For uploading files to Upyun, I would recommend building an adapter, like our [s3 adapter](https://github.com/keystonejs/keystone-storage-adapter-s3). Adapters are us trying to break file adapters out to be modular rather than supporting them in keystone.

Cloudinary remains in keystone 4 core for legacy reasons.

If what you want is an image preview, having the option for the File field to preview an image would be I think a good contribution to keystone.

We are not looking to move to ES2015 until after 4 is released and stable, as we are still supporting older versions of node.

I am closing this as an issue, but feel free to continue talking here, and ask any followup questions.
