### ISSUE TITLE
Running KeystoneJS in a subdirectory

### ISSUE THREAD

**Issue by AMRoche** [keystonejs/keystone#442]
Hi guys! Trying to run KeystoneJS in a subdirectory, and had to do a lot of messing around just to make everything work properly on the front-end, but have now run in to the problem that elements in the admin panel CSS aren't loading ... any thoughts?

Basically, the site is running under the /news/ directory, with all requests to the server being proxied there. However, the keystone instance is trying to access its' own assets in the stylesheets at /keystone/ instead if /news/keystone/. I was able to get stylesheets by adding another proxy rule in to apache to get the CSS, but not entirely sure how to tackle this one!

Any help greatly appreciated!

**Comment by frederik** [comment]
That'd actually solve my problem as well - I've been looking into other ways to host keystone in a sub directory - seems like there is none.

@jtymann any new ideas on this one since October?

**Comment by jtymann** [comment]
Unfortunately I was researching this for a project, and ultimately decided to move a different direction. The fork at https://github.com/jtymann/keystone should be usable.

**Comment by frederik** [comment]
I ended up hijacking the res.send and res.redirect methods - its nasty because I string replace but then this replacement is only active for my keystone routes so my normal app - works out fine for now (without me having to fork).

Adding a prefix variable to the templates/less would be really great though. Default could be /keystone so nothing changes.

**Comment by mxstbr** [comment]
I'll close this due to inactivity, let me know by commenting if you still want this!

**Comment by Terrafire123** [comment]
Yes! I'm trying to do a reverse proxy, and because Keystone.js doesn't support something like webroot="", this has become a lot harder than it should be.

**Comment by peter-mouland** [comment]
I know plus 1 is super annoying, but due to the gap in comments, it's probably worth while adding why  a `webroot` would help us out.

locally, we don't need it, but on our CI env, they add `/app-name` to the urls which means using `/keystone` doesn't work.  So we'd be interested in using webroot for this reason
