### ISSUE TITLE
Saving on mobile does not work correctly

### ISSUE THREAD

**Issue by MillerApps** [keystonejs/keystone#4421]
### Expected behavior

Being able to save from a mobile web browser. 

### Actual/Current behavior
 
Currently saving clears all newly entered data, unless save is done multiple times. 

### Steps to reproduce the actual/current behavior
 Try saving data from a mobile browser. 

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         |  4 beta 5
| Node             |  6.11.2

**Comment by MillerApps** [comment]
Anyone out there?

**Comment by icyretribution** [comment]
Saving what? 
What mobile browser are you implying with "mobile browser"?
Your question needs a bit of clarification.

For example, are you saving a csv file from a data set in the admin panel?
Are you saving the contents of a page to an html file?

Nothing in specific is mentioned in your post other than the version of keystone.

As a general guideline, i would recommend a mention of the types of data you are working with, an example of the model you are using (you have no idea how many people make simple mistakes in the models), and a better run down of the client end environment (device, OS, browser if possible).

**Comment by MillerApps** [comment]
Saving content created in wysiwyg editor. The specific mobile browsers I have tested in are Chrome for iOS and Safari.

**Comment by MillerApps** [comment]
Here is my model as well as a video demonstration. 

```
var keystone = require('keystone');
var Types = keystone.Field.Types;

var Team = new keystone.List('Team', {
	autokey: {
		path: 'slug',
		from: 'title',
		unique: true
	},
	map: {
		name: 'title'
	}
});

Team.add({
	title: {
		type: String,
		required: true
	},
	bio: {
		type: Types.Html,
		wysiwyg: true,
		height: 150
	},
	description: {
		type: String
	},
	image: {
		type: Types.CloudinaryImage,
		folder: 'images',
		select: true,
		selectPrefix: 'images'
	}
});

Team.register();
```
[Video Demo](https://www.dropbox.com/s/dytfek9nidnqzc9/File%20Aug%2028%2C%207%2008%2025%20PM.mov?dl=0)

**Comment by icyretribution** [comment]
From my test bed, it worked great. There was however a slight delay between the Cloudinary upload to the post processing on the server end. This is probably due to the async request queue associated with the cloudinary image type.

You should be able to confirm whether this is your case or not by viewing your server console during the transaction. The original addition of a "team" model with my image had a huge impact on performance resulting in a 11156.828ms response time with the image upload. With the cloudinary image type, the expected behavior changes, due to the fact that the image upload must complete prior to saving your model.

**Comment by MillerApps** [comment]
Any fix for this?

**Comment by MillerApps** [comment]
Thanks! Not sure if this makes any difference but it only seems to do this for this model, all the others save as expected.
