### ISSUE TITLE
Azure AD - Authentication and Access control

### ISSUE THREAD

**Issue by hpramanik** [keystonejs/keystone#4422]
Hi,

I would like to know if there is any good example or steps for AD SSO integration with KeystoneJS Admin UI Authentication and GQL Access Control.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.

**Comment by diegoaguilar** [comment]
@hpramanik did you end up solving this?

**Comment by hpramanik** [comment]
No. It seems at that point of time admin UI could not be signed in via azure. So I went with the approach of custom ui and ditching the default Admin UI completely.
