### ISSUE TITLE
Keystone GraphQL playground, Next.js app and JSON request bodies result in stalled requests

### ISSUE THREAD

**Issue by ntamas** [keystonejs/keystone#4434]
# Bug report

## Describe the bug

I have a Keystone project that uses a Next.js app as frontend. Some of the Next.js routes are API requests (under `/pages/api`) and they consume JSON objects in the bodies of POST requests. When this project is started in dev mode and with logging enabled, any POST request with a JSON body that is sent to a Next.js API route results in stalled HTTP requests that are never responded to.

## To Reproduce

I don't have a minimal reproduction yet but I'll try to come up with one in the near future. However, I managed to narrow the issue down to a single line in the GraphQL playground app code; see below in "Additional context".

## Expected behaviour

HTTP requests should not stall; all requests should eventually be responded to.

## System information

- OS: macOS, but probably not relevant
- Browser: N/A, I am testing from the command line with `httpie`

## Additional context

The problem goes away if I remove the following line from `addDevQueryMiddlewares` in `@keystonejs/app-graphql-playground`:

```
app.use(bodyParser.json());
```

This probably works because Next.js also registers its own JSON body parser. My conjecture is that the second registration of the body parser attempts to parse already-parsed JSON again and throws an exception somewhere in the process.

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
