### ISSUE TITLE
More flexible way to work with JSON

### ISSUE THREAD

**Issue by arturkasperek** [keystonejs/keystone#4443]
I'm using keystone more than a year. It's good for making some typical collections, like Users, Posts e.t.c depending from project requirements. But problem comes when you want to give user more flexibility in settings of different modules on page. For example it's nice to give user ability to program sidebar menu, so user pick name of item, link and for example color for each item. Now is hard to describe such a settings with keystone schema. For now moment I'm leave normal textarea where user paste final JSON. Maybe for programmers it's ok, but for not technical guys it's not easy enough. 

Maybe we could make some system solution for that problem. So we could add field called JSON, and in settings we could provide schema, with that schema we will generate UI from already existing fields like Text, Color or CloudinaryImage. So it should look like here:
```
var schema = {
  name: {
    type: JSON,
    schema: {
      menuName: String
      items: {
        '$array': {
          name: String,
          link: String,
          image: CloudinaryImage,
          nested: {
            nestedString: String,
            nestedNumber: Number
          }
        }
      }
    }
  }
}
```
What you think about that idea ? How do you handle with not trivial data types ?
I found that you are working on nested lists https://github.com/keystonejs/keystone-test-project/pull/17/files, but question is if it is good idea to store that as a nested database structure instead string.

**Comment by blargity** [comment]
Hey @arturkasperek, indeed what you're describing is nested lists. It's a great idea to store it as a nested database structure instead of a string from the MongoDB point of view, but the challenge is that you won't be able to see or edit these in Keystone until after nested lists is a supported feature.

We're doing exactly what you're doing currently to work around it by storing JSON strings in fields.

I'm going to go ahead and close this issue in favour keeping further discussion of nested lists on that PR.
