### ISSUE TITLE
update handler violates unique index on email

### ISSUE THREAD

**Issue by r3wt** [keystonejs/keystone#4464]
### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 
| Node             |

**Comment by stennie** [comment]
Closing out stale issues. This specific error sounds specific to the model/application code. 

For future questions or bug reports, please fill out the GitHub issue template with expected behaviour, actual behaviour, steps to reproduce, and relevant version details for your environment.

Thanks,
Stennie
