### ISSUE TITLE
express-session memory leak

### ISSUE THREAD

**Issue by roccomuso** [keystonejs/keystone#4472]
The default "memory" storage for sessions suffer a well known memory leak. As pointed out on the `express-session` documentation. The usage is discouraged in production.

Consider using a leak-proof in-memory store by default: [memorystore](https://github.com/roccomuso/memorystore)

**Comment by wosevision** [comment]
This issue is already mentioned in the [Database Options section of the Keystone docs](http://keystonejs.com/docs/configuration/#options-database), as well as warned against for this reason, as well as provided an alternative for (via the `session store` configuration option).

It's encouraged to "bring your own session", which you can certainly set to `memorystore`, or preferably a database session so they can be shared across processes. Is there a problem with that option? `express-session` is really only meant as the most barebones option.
