### ISSUE TITLE
Improving Admin UI performance

### ISSUE THREAD

**Issue by mattdesl** [keystonejs/keystone#460]
I've noticed that my Admin UI is really slow. The Network tab shows 1-3 seconds to load a page (the database is empty). Most of this seems due to the fact that there is no minification or compression, and a lot of HTTP requests to get all the source and CSS.

In a fork I'm now bundling and minifying all the JS files together and it's greatly improved page load time:  
https://github.com/mattdesl/keystone/tree/minify

I'm still using the conditional script tags for Markdown, WYSIWYG, Code, etc. I have yet to concat and minify the CSS but I suspect that will also help improve page load time. Ideally, if we're in production, we should always be requesting minified CSS/JS, and bundling it where applicable.

If desired, we can conditionally use the minified JS only if the environment is `production`, otherwise use a [sourcemapped](https://www.npmjs.org/package/gulp-concat-sourcemap) (but not minified) bundle.

**Comment by dcousens** [comment]
Not quantifiable. Closing.  Please re-open if you have quantifiable results with which we can compare against. 

Movements toward this are being made with the use of `react`.

**Comment by ghuroo** [comment]
Problem:
Loading the Admin UI for the first time (after the server restarts) takes way too long (1min), and unfortunately slows down my productivity a lot.

Cause:
**fields.js** and **admin.js** take **> 1 min** to be generated

Proof:
![Proof](http://i.imgur.com/0gCJW6B.png)

Details:
Lately, more than ever, this is something I have been struggling with.
I don't want to be picky about it because having an auto-generated admin UI, even if slowly generated at first, is far better than not having one and it's the first reason for me to use KeystoneJS.
But unfortunately, since I'me developing my biggest project so far, I have to take a lot of consideration into how the Admin UI displays the data and enables any user to manage it = which translates in restarting the server all the time and checking the changes.
