### ISSUE TITLE
Issue on create new app

### ISSUE THREAD

**Issue by nasouhmr** [keystonejs/keystone#4612]
# Bug report

## Describe the bug
After installing keystonejs tried to create new app but its keeps fail after create mongodb connection.

## To Reproduce 

1.yarn create keystone-app my-app
2.then enter app info (name , mongodb, etc...)
3. See error :  "Error: No commits that release keystone were found. Try updating create-keystone-app and if this problem persists, please open an issue on GitHub."
4.i tried updating create-keystone-app with no success.
 
## System information

- OS: [Windows 10]
- Browser [Chrome]
- Node v14.0.0
- Yarn 1.22.4

**Comment by ganobrega** [comment]
Use another **node** version.
Try `nvm use v12`
Worked for me

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
