### ISSUE TITLE
What's the state of Keystone (again)?

### ISSUE THREAD

**Issue by jsundquist** [keystonejs/keystone#4638]
It seemed as though very briefly after #4551 was closed, there was a push to start getting some traction on fixing bugs and finally releasing Keystone out of beta.  That traction seemed to quickly diminish back to what the users of this library are used to. Meaning, there has been no word from the maintainers when it will be released, pull requests sitting un-merged, and issues going un-answered. 

Now I do realize it takes a lot of time and effort to maintain a product such as this one, but going completely silent doesn't help the user base at all. So once again, as a user of this library and depending on it, what is the state of Keystone.js?  I'm to the point that I may have to fork the project myself to fix any bugs that are found, make sure the dependencies stay up to date, and finally just become dependent on myself to keep it moving forward. However, with forking the project there is a good chance that the direction I take my fork may not be the direction keystone goes once there is progress again on the project.

So to the maintainers, when can we expect attention be placed on this project once again to get it out of beta and to a stable release?

**Comment by autoboxer** [comment]
@jsundquist, I'm working with the team as we speak to outline the direction of Keystone and add some transparency to what's going on.  The good news is that there is quite a bit of movement behind the scenes with Keystone, and it is in fact quite healthy.  I'll be making an announcement via Slack explaining what's going on within the next day or two.  As far as Keystone 4 and getting out of beta, I've been asked by @JedWatson to spearhead that effort, and while it's going to take a little time to get up and running and pull together some core contributors, it's a very high priority for the team to officially release.  We've been working to pare down the list of todos to just what's needed for a release and better set me up for the task at hand.  I don't see you on the Keystone Slack, but would be happy to add you if you'd like to keep abreast of any updates.

**Comment by autoboxer** [comment]
@jsundquist, that's all valid, and I agree that a simple acknowledgement goes a long way.  That's something I'll bring to the team and try to be better at as well.  Github is a difficult place to have conversations about a project as a whole, and while I was planning on posting the same info to #4551 as I'm going to post to Slack, not being on Slack will mean you'll miss out on some information.  If you'd prefer not to join, feel free to reach out to me ( jared.j.collier@gmail.com ) at any point and I'll do my best to get you the info you're looking for.  If you decide you do want to join the Slack channel, email me with your contact info and I'll send an invite your way.

As far as the pull requests not being acted on, I can't speak to the past, however, I can give you a general sense of where we're headed.  The top priority for Keystone 4 is to remove the beta tag, and my personal focus for the immediate future is going to be on tackling just the critical items to make that happen.  I can't say how long the effort will take, but I'm going to reach out to many people who have shown interest in helping, and the more people I can rally, the faster it will go.  I'm expecting to start a group of contributors that will meet regularly to discuss direction, pull requests, bugs, etc. in order to keep Keystone 4 healthy post-launch.  Once the beta tag is removed, I'll be focusing on the existing pull requests, yours included, and hopefully at that point it will start to feel like the project has momentum again.  If at any point you feel a fix you've worked on is high priority and should be acted on immediately, reference me in the issue or pull request and I'll be sure to take a look as soon as I can.

**Comment by alecwhittington** [comment]
@autoboxer sent you and email request for adding me to the slack channel. I'd like to keep up-to-date as well.

**Comment by autoboxer** [comment]
@marcwickenden, can you send me more info either via email ( jared.j.collier@gmail.com ) or Slack?  I'd love to get a little more info and chat about this.

**Comment by marcwickenden** [comment]
@autoboxer sent. Cheers!

**Comment by JedWatson** [comment]
Hopefully everyone's noticed the uptick in activity over the last week as things click into place, and some more new faces joining in the effort.

Like @autoboxer mentioned, our primary focus right now is getting on top of things as a team so we can move the project forward. In real terms, this means:

* sorting out our ability to test changes reliably and getting CI green
* triaging blocking issues and bugs with existing functionality (including the security issue you mentioned @marcwickenden)
* documentation

... and getting a `4.0.0` release out there that we can iterate on.

As I mentioned in #4551 we have been working to establish a longer term architectural roadmap for Keystone, which is going really well and I'm looking forward to sharing it with everyone.

But first we're working to make good on the enthusiasm that everyone has shown by unblocking the release of 4 and sorting out our foundations so we can go from there.

With that in mind, I'm going to close this issue - if anybody else wants to get involved our Slack is open (we'll have a public signup page in place within the next couple of days, or feel free to ping Jared via email in the meantime)

**Comment by stennie** [comment]
As mentioned earlier in this discussion, more contributors are being onboarded (👋) and we're working to get the project to a healthy state with more timely & effective communication, additional contributors, and a Keystone 4 release without a beta tag.

One of the current community challenges is too many channels (and not enough answers). For example, there is currently GitHub, Canny (née ProductPains), Gitter, Slack, KeystoneJS Google Group, and probably more. Without getting into extended debate on which tool is best for discussion in the longer term, we are focusing on Slack as a starting point to get the project moving.

There's now an open invite for anyone interested to [join the KeystoneJS Community Slack](https://launchpass.com/keystonejs) for feedback and discussion. Join the KeystoneJS Slack and introduce yourself!

Regards,
Stennie
