### ISSUE TITLE
Admin UI:  relationship values not appearing as tag boxes

### ISSUE THREAD

**Issue by a7me63azzab** [keystonejs/keystone#4642]
## I have a Model called Ozoma

`Ozoma.add({
    dishes:{type: Types.Relationship, ref: 'Dishe', many: true}
});
`
## the second model is called Dishe
`
Dishe.add({
    _belongTo: {type: Types.Relationship, ref: 'Ozoma'}
})
`
### this image is what appearing on admin ui
reference fields not appear in the parent field 
![select not appear](https://user-images.githubusercontent.com/13996786/40587408-e1f29102-61ce-11e8-89ec-0b33195fa686.png)

### but i can select fields  manually i want reference fields to be selected automatically
![select appear](https://user-images.githubusercontent.com/13996786/40587469-abc074ea-61cf-11e8-88ba-866b8d7f660b.png)

  
"keystone": "4.0.0-beta.5"

**Comment by stennie** [comment]
@a7me63azzab Can you provide more detail on what you are expecting to happen? What reference fields should be selected automatically?

Thanks,
Stennie

**Comment by stennie** [comment]
Based on the current description the relationship field appears to be working as expected. This was also reported against an older beta release of Keystone (`4.0.0-beta.5`), so I would suggest updating to the latest Keystone release (currently `4.0.0-rc.0`) as there have been many bug fixes & improvements since beta 5.

Regards,
Stennie
