### ISSUE TITLE
Beginner: Help with populating a GeoPoint field with lat/long information

### ISSUE THREAD

**Issue by RayKahn** [keystonejs/keystone#4679]
### NEED HELP

**This is not a bug but a request for help**. And I did [post on stackoverflow.com](https://stackoverflow.com/questions/50991186/how-to-use-google-map-with-keystonejs) to no avail thus far. My apologies for duplication of posting but I am stuck!
I am trying to auto-fill a GeoPoint field with lat/lng information after a user finishes entering name of a city. My model looks like the following:

```
var Location = new keystone.List('Location', {
	map: { name: 'title' },
	autokey: { path: 'slug', from: 'title', unique: true },
	sortable: true,

});
Location.add({
title: { label: 'Location name', type: String, required: true },
content: {
    product: { label: 'Product', type: Types.Select, options: 'Option1, Option2', default: 'Option1', index: true, required: true },
    address: { label: 'Address', type: String, required: true, initial: false },
    state: { label: 'State', type: Types.Select, options: usStates, index: true, required: true, initial: false},
    city: { label: 'City', type: String, required: true, initial: false},
    country: { label: 'Country', type: Types.Select, options: 'USA', default: 'USA', index: true },
    latlng: { label: 'GEO Location', type: Types.GeoPoint, enableMapsAPI: true, watch: 'city', value: getGEO},
    cloudinaryImages: { label: 'Location images', type: Types.CloudinaryImages },
},});
```
As can be observed I am using the **watch** flag. But watch happens only on creation and not update.
```
latlng: { label: 'GEO Location', type: Types.GeoPoint, enableMapsAPI: true,
 watch: 'city', value: getGEO},
```
And I declared my getGEO function as such (for now it's just a console call):

```
function getGEO() {
  console.log('HELLO WORLD...')
}
```

However, when I submit the generated form after filling in the rest of the fields (address, state, city, country) the function getGEO does not get called. As stated above getGEO is called only when a new Location is created (when user inputs Location name). What's the best way to achieve the following:

- User provides address, state, city, country

- getGEO (or some such function) is called and updates latlng field

- Data is saved to db

Additionally, I am not sure whether the model is the right place to call this function. Is there a better way to do this?
Thanks in advance.

**Comment by stennie** [comment]
@RayKahn I added a link to [your StackOverflow question](https://stackoverflow.com/questions/50991186/how-to-use-google-map-with-keystonejs) and commented there as well. 

I suspect you want to use a [Location field type](http://keystonejs.netlify.com/api/field/location) (which supports geocoding via Google Places API) rather than GeoPoint (which does not).

Stack Overflow is a more appropriate forum for programming questions, but can require some patience. We're trying to keep the GitHub issue queue focused on bug reports & feature suggestions, so I'm going to close the issue here and keep the discussion on Stack Overflow.

For future questions please include the specific version of Keystone you are using, as that is important context.

Regards,
Stennie
