### ISSUE TITLE
Images enhancements

### ISSUE THREAD

**Issue by bladey** [keystonejs/keystone#47]
- [ ] Make popup caption reflect the image URL and dimensions
- [ ] If no file reader support, add some kind of generic image that goes behind the upload icon (currently white with border).
- [ ] Animate in upload/remove/delete icons with opacity animation of image.

**Comment by wmertens** [comment]
@bladey since this predates the v0.4 React move, is this still something that will be worked on?

Frankly, there's way too many issues and I think it would be better to close this one until someone has a real PR. These are nice features, I would love to have them (also showing thumbnails for uploaded files), but I think they can get done without this tracking issue too…
