### ISSUE TITLE
What is best way to upgrade from beta release to RC

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#4722]
What is best way to upgrade from beta release to RC?

**Comment by internetErik** [comment]
Not sure if this is the best way, but I just updated the version in my package.json and ran npm install again. Everything continued to work as normal.

**Comment by stennie** [comment]
@chrisschaub As suggested by @internetErik, upgrading the keystone version in `package.json` and running `npm install` is the typical upgrade procedure.

Review the [Keystone release notes](https://github.com/keystonejs/keystone/releases) to see what has changed since the release you currently have installed.

Regards,
Stennie
