### ISSUE TITLE
How to redirect users after login

### ISSUE THREAD

**Issue by luismsaraiva** [keystonejs/keystone#4723]
How can I redirect all users to the homepage after they login from the KeystoneJS login?

Thanks

**Comment by stennie** [comment]
@luismsaraiva Users should be redirected to the Keystone admin UI after login.

Can you describe what type of users you are trying to redirect and where?

For example, do these users have `canAccessKeystone` set to `true` or `false`?

Regards,
Stennie

**Comment by stennie** [comment]
@luismsaraiva See https://github.com/keystonejs/keystone/issues/1489#issuecomment-114389081 for an example using the `signin redirect` configuration.

There's also a tracking issue #4678 for adding some documentation on redirection since this isn't currently covered in the Keystone v4 docs.

Regards,
Stennie

**Comment by luismsaraiva** [comment]
Thanks @stennie!
