### ISSUE TITLE
Markdown field type strips HTML attributes

### ISSUE THREAD

**Issue by CAYdenberg** [keystonejs/keystone#4764]
### Expected behavior

When using the Markdown field type, it should be possible to "switch" to HTML, since Markdown is a superset of HTML (with reasonable restrictions, like not including script tags maybe). This is useful for tables and other things that don't have a Markdown equivalent. 

### Actual/Current behavior

After saving, if the page in the admin interface is reloaded, any attributes are stripped from HTML tags. So `<div id="whatever"></div>` becomes `<div></div>`.

### Steps to reproduce the actual/current behavior

Create model with a Markdown field and enter some content. Anywhere within enter `<div id="whatever"></div>`. Save the post. Keystone reports that the post is successfully saved and the content does not change. Then reload the page. The HTML above is replaced with `<div></div>`.

The value of `wsiwyg` in the model definition does not seem to matter. Putting content within the tags does not seem to matter.

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         |  4.0.0
| Node.js          |  9.10.1
| Browser          |  Chromium 68 on Ubuntu whatsmybrowser.org/b/4CNDJC7

**Comment by stennie** [comment]
@CAYdenberg In order to mitigate JS/CSS injection, [Markdown Fields](https://keystonejs.netlify.com/api/field/markdown/) in Keystone 4 limit HTML tags and attributes using the [`sanitize-html`](https://github.com/punkave/sanitize-html) package.

`sanitize-html`'s [default options](https://github.com/punkave/sanitize-html#what-are-the-default-options) are intentionally restrictive, but you can allow additional HTML tags and/or attributes by including a `sanitizeOptions` object for your Markdown fields.

Regards,
Stennie

**Comment by CAYdenberg** [comment]
That's good enough for me :man_shrugging: Thanks for responding :heart:
