### ISSUE TITLE
deprecations and vulnerabilities still present in 4.0.0

### ISSUE THREAD

**Issue by ashbc** [keystonejs/keystone#4790]
Issues from #4648 seem to not have made it to 4.0.0.

### Expected behavior

`npm install keystone@4.0.0` should not produce deprecation warnings or warn about vulnerabilities.

### Actual/Current behavior

```
$ npm install --save keystone@4.0.0
npm WARN deprecated babyparse@0.4.6: Deprecated in favour of PapaParse, which now supports Node.js
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated scmp@1.0.2: scmp v2 uses improved core crypto comparison since Node v6.6.0
npm WARN deprecated letsencrypt-express@2.0.7: letsencrypt-express has been renamed to greenlock-express and will now be maintained as such.
npm WARN deprecated sprintf@0.1.1: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated localhost.daplie.com-certificates@1.2.5: this package has been deprecated
npm WARN deprecated letsencrypt@2.1.9: letsencrypt has been renamed to greenlock. Please find it at npm greenlock
npm WARN react-prop-toggle@1.0.2 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-prop-toggle@1.0.2 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN matbank@1.0.0 No description
npm WARN matbank@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ keystone@4.0.0
updated 1 package and audited 6062 packages in 24.763s
found 15 vulnerabilities (5 low, 10 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

```

### Steps to reproduce the actual/current behavior

`npm install keystone@4.0.0`

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0
| Node.js          | 10.6.0
| OS | Windows 7
| npm | 6.4.0

**Comment by stennie** [comment]
@ashbc The dependency updates for Keystone 4.0.0 addressed direct dependencies and non-breaking updates, but there are still some deprecation warnings and packages that do not have updated versions available on `npm`. There's an open issue to update `letsencrypt-express` (#4647) since this was a more involved task (see [`label:dependencies`](https://github.com/keystonejs/keystone/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Adependencies) for other open issues/discussions).

Per #4719, dependencies were also updated to use semver notation so newer package versions without breaking changes can be used without a new Keystone release.

There should be no critical dependency updates outstanding, but If you have any specific concerns for a dependency that has an available update on `npm`, please feel free to raise an issue (and perhaps a pull request).

Potential dependency updates will be reviewed prior to each maintenance release. 

Thanks,
Stennie

**Comment by ashbc** [comment]
Thanks

**Comment by dennismayr** [comment]
Somewhat related:
In your experience, is it safe to run `npm audit fix` on a KeystoneJS project without breaking functionality?

**Comment by dennismayr** [comment]
Thanks for clearing it up @stennie!

I’ll leave packages untouched then, running the app behind nginx.
