### ISSUE TITLE
User login with multiple email addresses

### ISSUE THREAD

**Issue by agmt5989** [keystonejs/keystone#4880]
### Expected behavior

In the User model with {... many: true ...}, a user should be able to login with any of the provided email addresses, especially if they came from update files.

### Actual/Current behavior

Entering all of the email addresses on file works, but that's absurd. Imagine a user entering email1@example.com,email2@example.com in the keystone signin page every time they want to login

### Steps to reproduce the actual/current behavior

In a fresh KeystoneJS install, set many: true in the email field of the User model. Then, in the admin application update, replace the user@keystonejs.com email with multiple emails as an array. It gets accepted by MongoDB. Now try to signin!

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 
| Node.js          | 11.6
| Browser          |

**Comment by agmt5989** [comment]
Nothing on this issue so far.

**Comment by gautamsi** [comment]
You intentionally want user to login with either of the 2+ email address? 

if you just want additional email address stored for users, create another field in User list for additional email addresses. You can display all of them in single field on user profile page putting login email as 1st item in array. If you allow user to change primary email then do the magic in your code before saving the object.

if you really want them to signin using multiple email, you can still use this additional field for manually looking up User object with email or additional email field matching the criteria and then calling keystone. session.signin method with the signin email saved for this user.  ref

https://github.com/JedWatson/sydjs-site/blob/af8599aa776f46d868f6462f0e113aca9ca8089a/routes/views/session/signin.js#L37
```
		keystone.session.signin({ email: req.body.email, password: req.body.password }, req, res, onSuccess, onFail);
```

**Comment by agmt5989** [comment]
I'm not sure I understand. Say I make changes to my copy of keystone, and was to re-implement the `doSignIn` method to accommodate for cases where the entered email appears at least once in an email field. How would I go? Would I need to replace the emailRegExp filter? I'm lost

**Comment by gautamsi** [comment]
nope, not that hard. 
explore the [sydjs source](https://github.com/JedWatson/sydjs-site), good for keystone based starter. 

I have created a fork of sydjs-site and changed it little bit so that you can use multiple email to login. 
see [multi-email-login](https://github.com/gautamsi/sydjs-site/tree/multi-email-login) branch for latest commit https://github.com/gautamsi/sydjs-site/commit/86038081854f0baa9e7d2490a3238c1b79fe7e85. 

caveat: KeyStone can only have plain text in TextArray field, you can not have Array of Email field type. So, no email validation when using KeyStone admin interface, but you dont have to use this anyways. 
give user a way on [profile page
](https://github.com/gautamsi/sydjs-site/blob/master/templates/views/site/me.jade)  (in this example - http://localhost:3000/me) to add multiple email, then store them in `emails` field (or any fild name of your choice). obviously you have to add logic for email confirmation etc, but once they have the additional emails stored in database, you can log them in as in commit

steps for this site demo:
1. clone
2. `yarn`
3. run mongodb
4. run `node keystone.js`
5. default user is created for the first time user@keystonejs.com
6. open `http://localhost:3000/keystone/users` and create a user, add multiple emails by using "Add Items"
7. open `http://localhost:3000/signin` for logging in, test emails one by one.

![image](https://user-images.githubusercontent.com/5769869/51212827-78b0d680-193f-11e9-87fb-f9503690d791.png)

**Comment by agmt5989** [comment]
Thanks man. I tried it. You've been a lot of help!!

**Comment by gautamsi** [comment]
did you checkout the branch `multi-email-login` from my fork?

**Comment by agmt5989** [comment]
I finally did. It turns out I'm only able to login with the first email address.

**Comment by gautamsi** [comment]
it would no work on `localhost:3000/keystone/signin`, you have to go to `localhost:3000/signin` this is custom route which also lets you sign in with google and other provider.

**Comment by gautamsi** [comment]
this is what I did to validate again on a different machine:
clone and initialize
```
git clone https://github.com/gautamsi/sydjs-site.git
git checkout multi-email-login
yarn
```
create/copy `.env` for cloudinary
run `node keystone.js`
now go to `/keystone` admin where you can add user and emails for them, I noticed that there may be issue with tinymce which may prevent the page sometime, just refresh the page again.  you should be able to "add item" for emails. 

once you setup user. you can go to `localhost:3000/signin` (this is custom form for signing in). You can now login with any email. 

once you are logged in, you can navigate to `/keystone` for admin access if you have given this privilege to user.

**Comment by agmt5989** [comment]
Ok, thanks. Checking it out now.

**Comment by agmt5989** [comment]
It works perfectly!
Thanks, man. I'm really grateful.
