### ISSUE TITLE
mutation `sendUserPasswordResetLink` does not return code IDENTITY_NOT_FOUND MULTIPLE_IDENTITY_MATCHES under any circumstances

### ISSUE THREAD

**Issue by TilakMaddy** [keystonejs/keystone#4952]
Graph Ql query

mutation `sendUserPasswordResetLink` does not return code IDENTITY_NOT_FOUND MULTIPLE_IDENTITY_MATCHES under any circumstances

when you request reset for an unregistered email the code IDENTITY_NOT_FOUND is not returned, instead it returns null

**Comment by timleslie** [comment]
Hi @TilakMaddy, this is probably because the `createAuth` argument ` protectIdentities` is set to true (the default). When this value is true we hide the error codes, because they represent a potential security risk. E.g. if I wanted to find out whether someone had an account on your system I could submit this query with their email address and if it returned `IDENTITY_NOT_FOUND` then I would know they didn't have an account. If it succeeded I would know that they *did* have an account.

Because of this potential risk in the next release we have decided to remove the ability to set `protectIdentities: false`.

I hope this clears up the situation. Please reopen the issue if you have more questions.
