### ISSUE TITLE
StorageAPI for Images and Files

### ISSUE THREAD

**Issue by grabbou** [keystonejs/keystone#526]
# Draft

To store Images, we have to use CloudinaryImage if we are on Heroku and so on or if we like ability to resize or manipulate our image. Not everybody is happy with paying monthly-fee for having only those features. Although Cloudinary is great - not everyone is using all of its features. That's why we need to kick our Image and Files to next level and make it like in other CMS systems.
## Storage API

**REPOSITORY**: https://github.com/grabbou/StorageAPI/

_Will be released as stand-alone NPM package and after that, integrated into Keystone._

Deliver `Keystone.StorageAPI` for developers to easily use storage (when available) in their projects. Storage API can be used either in fields or in our own views and modules. It's public. Define once, use multiple times. 

**Directory structure**

```
providers/
providers/storage/index.js // this is place for our 'class' **Storage**
providers/storage/....
providers/storage/amazon.js //name 'amazon' now is available as keystone.set('storage')
providers/storage/azure.js

// once we finish, it's time to write mailApi
providers/mail/index.js // mail resolver, works like storage one as well (obtain() method)
providers/mail/postmark.js
providers/mail/mandrill.js
providers/mail/smtp.js
```
### Storage
- `obtain(options)` returns current storage provider based on `keystone.set('storage')` specified. We can optionally pass argument `provider` here in case our custom field allows to set different provider for it (for example - files in S3, images in Cloudinary). Automatically checks whether given provider is available (file with it exists in our `providers` folder). 
### StorageClient
- `@constructor` - registers new client based on `keystone.set('storage config')`. This should be an object, specific for different providers. Can accept either single object (then we assume it's config for `keystone.set('storage')` or object array (in case we use multiple storage providers inside our app):

``` js
keystone.set('storage', {
   'azure': {},
   'amazon': {}
});
```
- `upload(options)`, `delete(options)`, `exists(options)` - easy manipulation
- `_ensureContainer()` - ensures that container exists - based on `keystone.set('storage container')`. We do not have any default value here as container name should be unique across cloud platform

_Please note, that async methods are wrapped within promises (`Q` library) to avoid callback chain and provider better functionality_

**List of supported providers to start with**
- Everything provided by `pkgcloud` - Amazon, Azure, HP, Rackspace, OpenShift
- Filesystem
- FTP / SFTP
### Pros:
- Use core, consistent storage layer to access file systems. Developers can now easily write their own modifications and fields using our API without thinking whether config is supported or not. Easier in maintaining. If API changes - only one file to edit, not 12 plugins that are interacting with them.
- No more hard-coded supported providers. We simply add new file under providers/storage and users can start using it automatically. Our `Storage` checks whether `keystone.set('storage')` provider is available, if not - throws `new Error('Unsupported provider')`.
- Users can easily create their own PR with new providers (or we can even include them as dependencies or think of plug & play architecture for the future).
## Fields

Removing multiple fields that are doing the same job and replacing them with following ones. We are going to delete `ui-azure.js`, `ui-s3file.js` and many many more (with CSS3 stylesheets as well! Going simple now!)
### File

Simple field for handling files. Accepts any storage (uses default one specified in the project). Returns false if uploaded file doesn't match allowedTypes.

**Schema:**
- `url {String}` - full_res url
- `file_name {String}`
- `provider {String}`
- `container {String}` - might be path in case we used FTP/SFTP.

**Accepted fields:**
- `required` - if file is required. If yes and no file provided, returns an error.
- `provider` - overwrites provider for that field. Remember to specify configuration. If array specified, multiple actions are performed.
- `size` - maximum size - if wrong, returns an error
- `allowedTypes`

**Available hooks**:
- pre: upload
- post: upload
### Image extends Field

Generic ImageField for uploading & handling images. Deletes `CloudinaryImage` as it's now built-in within this field. The same with other image-related fields.

**Schema:**
- inherited

**Accepted fields:** 
- inherited

**Underscored methods**
- Full Cloudinary API support (if Cloudinary is not default provider or provider for that field, use our wrapper for [`gm`](https://github.com/aheckmann/gm)). Key feature is to mimic Cloudinary functionality (the same method calls, almost the same effects). Our Node API simply checks whether image matching options specified is present on server, if not - we generate it and return a link. Please note that we are keeping ful-res image in the cloud storage just to have the ability to resize them in the future.

**Available hooks**:
- inherited
### Wysiwyg

Removes hard-coded CloudinarySupport. Allows to upload file to default storage provider when available. Allows overwriting that by specifying `keystone.set('wysiwyg storage')`. To enable image upload - call `keystone.set('wysiwyg image upload')`. It means you can now upload your wysiwyg images easily wherever you want. Either to FTP or Amazon S3. Want to resize your images while uploading? Easy! Just set `keystone.set('wysiwyg image options')` and we will adjust your input using `ImageField` undescored methods. No more resizing before uploading high-res photos.
## Breaking changes
- Removed all file fields and image fields. Replaced with those new ones.
- Removed lots of unnecessary `keystone.set` configs, like cloudinary and so on.
### Update 1
- After writing new field - we should move post/pre and other methods to basic Field class and implement them where possible. In most cases, they are all the same. In others, just make them abstract by throwing `new Error('Method not implemented')` so one can easily overwrite them and implement. Useful when you are writing everything from scratch and want to make sure that you declared everything needed to work.
### Update 2
- `updateHandler` needs to be rewritten. For now, we can add new fields to that case, but for the future, we should have in our field method returning value. Based on that value, we can decide what action we should take in `ActionQueue`. Something like `{Field}.getUploadHandlerType`. No need to modify core files after that.

**Comment by grabbou** [comment]
@sebmck @morenoh149 Yep, hasn't been updated, mainly because I was sick and changed the country in a meantime. Also - there were few issues with underlaying libraries waiting to be merged into their master branches. For now I'll probably focus on more important features with other team members and then we will carry on storage.js development all together (doing something alone is pretty boring :( ).

**Comment by sebmck** [comment]
@grabbou Keystone has come pretty far in the last few months, we've since had our first community meeting #812, would be great to see you at the next one.

**Comment by JedWatson** [comment]
@grabbou nice to see you back, hope you're better! we're nearly ready for the major new release with React and Express 4 so we'll pick this up after that goes out :)

**Comment by grabbou** [comment]
@sebmck Yeah, I can see that. I am glad it keeps developing. I think I'll speak with one of contributors on Slack to get an overview what's going on at the moment :)

@JedWatson Great work on React! Sorry for being away. Let's start contributing once again! :)

**Comment by okjake** [comment]
Any further progress on this? Can I help with it?

**Comment by JedWatson** [comment]
@okjake I'm *so* glad you asked. I've been busily wrapping up the rebuild of the Admin UI and this is the other major blocker to the new version, I'd really love someone to take it on and help with it.

Things have moved on quite a bit since @grabbou's work, and are encapsulated in the `file-fields` branch. It's quite out of date so I'll have to get it brought up to speed, and figure out what's required to complete it. @creynders may be able to help organise the effort as well, he did quite a bit of work with it last. Let me know your email so I can add you into our Slack and we can chat.

**Comment by okjake** [comment]
OK great! Just added my email to my profile.

**Comment by JedWatson** [comment]
Great, you're invited!

**Comment by mahnunchik** [comment]
Hi @JedWatson 

Any progress on this?

I need to implement something like this:
* validation that the image is not less than required size
* resize if image is larger than required size

It is quite difficult to implement it on the current implementation of `LocalFile`.

**Comment by christroutner** [comment]
@JedWatson I'd also love to help with this. @okjake  If you can take a half hour to bring me up to speed with what you've accomplished, I can dedicate a couple hours a week to help with the integration of this.

**Comment by jeffreypriebe** [comment]
@mahnunchik @christroutner Happy to help with this effort as well. A little more discussion over on the [Google Group post](https://groups.google.com/forum/#!topic/keystonejs/H5b-Y4i7Ev4).
I currently have a branch that does some integration of cloundinary & s3 images/files into the main editor and want to see the file & image management in Keystone grow into a more robust system.
(My work uses React and pre-integration Elemental and isn't setup as something to be folded into the main Keystone project ATM)

Let's get on the [Google Group Post](https://groups.google.com/forum/#!topic/keystonejs/H5b-Y4i7Ev4) for continued discussion.
cc: @okjake @JedWatson

**Comment by rnjailamba** [comment]
@jeffreypriebe  @christroutner @JedWatson @grabbou 
How are things going for this feature ? :)

**Comment by rnjailamba** [comment]
@jamlen  
a code snippet of using cloudinary pdf would be VERY helpful!!!

**Comment by jamlen** [comment]
@rnjailamba from memory I think the main bit that does it is `presentation.src({ transformation: 'mottram-thumb'})`, where I am referencing a predefined transformation, but you could just specify the transformation details. 

I use this in my model:

```js
Sermon.add({
//...
presentation: { type: Types.CloudinaryImage, collapse: true, allowedTypes:['application/pdf'], autoCleanup : true }
//....
});

Sermon.schema.virtual('thumbnail').get(function() {
    if (!this._.presentation.src()) {
        return {
            img: null,
            isPdf: false
        };
    }
    return {
        img: this._.presentation.src({ transformation: 'mottram-thumb'}),
        isPdf: this.presentation.format.toLowerCase() === 'pdf'
    };
});
```
and then this in the jade:
```jade
if sermon.presentation.exists
    if sermon.thumbnail.isPdf
        a(href=sermon.presentation.url).sermonImg
            img(src=sermon.thumbnail.img)
    else
        img(src=sermon.thumbnail.img)
else
    img(src='/images/nopdf.gif')
```

**Comment by LuganOcode** [comment]
Hi, I hope this is the right place to add this, I'm curious about whether or not it is possible to setup the S3 storage so that actual file uploads are performed not by keystone in a:
- Client → KeystoneJS → S3 flow
but instead:

1. Client (meta data and signing request) → Keystone
2. Keystone → sends timeout signed PUT request back to client with data size, etc. Client
3. Client → directly uploads actual file to S3

The application I am building performs a lot of file uploads, and in the past I have used this signing strategy in other application frameworks with good success.  

Below is a more concrete snippet of what this means.  
- http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-examples.html#Amazon_S3__Getting_a_pre-signed_URL_for_a_PUT_operation_with_a_specific_payload

In my experience this can quite significantly reduce load at no loss, especially since Keystone only stores the metadata anyway.

I'm sure I can tinker my way to this, but maybe there is already some kind of support for it that I am missing?

**Comment by JedWatson** [comment]
@LuganOcode this is something I'd like to look into for all the file-type fields once we've consolidated them, but that's looking like a post-0.4 thing. We need to get the foundations fixed before we build more features on top of them.

What _will_ be available though is the ability to pass the metadata directly to Keystone so in the meantime (with 0.4) you could handle the upload to S3 directly with an extension to your app then submit the metadata to Keystone.

**Comment by LuganOcode** [comment]
@JedWatson Thanks for the tip.  We are already using 0.4 beta - the React UI stuff was just too nice to pass up.  So one more hint then, if we go in the direction that you suggest, would this imply essentially not using the 'S3FileType', and instead just just using a custom model object, or you would instead mean using the standard S3FileType and just processing submissions with the metadata but without the actual files?  

Since this does seem to be the/an appropriate place, I'm going to point out one more small hiccup that we ran into with file uploads and the `updateHandler`.  In our application we are asking users to _create_ A/V files.  This forced us to custom-configure the _uploads because:

1. Client side javascript does not permit us to add a filetype input to an HTML form object programmatically.  The user must do it.  The only alternatives we could think of were to:
    1. Use a `FormData` object, and submit with an `XmlHTTPRequest` which means we screw up context handling and flash messages, among other things.
    2. Append the file as a blob in a hidden input.
2. The Keystone form processing API does not know how to process a blobfile that has been passed via a hidden input, I think because it is not in the 'files' section of the request.

In the end we just moved this work into the view controller, and replicated the work otherwise handled by the updatehandler (and I think ExpressJS is also maybe handling the temporary storage), but this is probably not the ultimate recommended way to handle such issues. 

BTW this is a quite amazing thing!

**Comment by wmertens** [comment]
See also https://github.com/keystonejs/keystone/issues/3209#issuecomment-236323406 for my take on how Storage Adapters are responsible for handling files, the rest of Keystone should just work with File objects (the bags of data that the Storage Adapter uses to represent the file).

**Comment by peterjohansson92** [comment]
Maby im in the wrong discussion for this question, but what is the status about using s3 instead of cloudinary in the wysiwyg editor for image uploading? Currently we use "wysiwyg cloudinary images" in the init, but is it possible to use s3 instead? If so, i would be very pleased if someone could tell me how.

**Comment by gautamsi** [comment]
Keystone 4 is going in maintenance mode. No major changes expected. see #4913 for details.

I see a PR was done for S3 image upload for wysiwyg in v4, see #1614
