### ISSUE TITLE
Security: AdminUI exposing real CUID's of users

### ISSUE THREAD

**Issue by qfunq** [keystonejs/keystone#6802]
# Bug report

The CUIDs of Users in the admin UI are indexed by CUIDs

## To Reproduce

Run the admin UI as usual, seeded with some Users

1. Go to '...'  http://localhost:3000/users
2. Click on any user (say content_manager).
3. Look at the url.
4. See: http://localhost:3000/users/ckukwhlv7u221kgesfzozj0p7

## Expected

The actual CUID should be hidden behind a slug.

http://localhost:3000/users/content_manager

Likewise any GQL error reporting should hide the CUID with a slug, or hash of the real data.

## System information

Keystone 25.1.0

**Comment by qfunq** [comment]
True ... forking has issues with keeping up to date, and unique slugs is hard to work round as well. Its a bit of a puzzle. I'll keep the issue open while I think a bit about if there is a solution at all. 

Perhaps its possible to match both slug and id for updates? Or expose the id, and have a hidden slug that only the admins can access? I'll see if there is any test code that looks like it might work ... its not helped by ...WhereInput only descending table relations ... (unless there's a workaround that I don't know about?)

**Comment by JedWatson** [comment]
A few things to note here:

* In Keystone we need a consistently available way of addressing items for relationships and the Admin UI to work. The `id` field is that thing, and is the _only_ field that's treated this way (everything else is optional).
* Keystone makes the core assumption that _if you can access an item, you can access its id_ and from a security perspective, the requirement is that this is OK. This is consistent with a vast majority of web systems; so much so that for example Apollo also implements the underlying expectation in its caching system that types have IDs available to the client.
* If you can uniquely identify an item by an immutable reference, whether that's by a string that looks like a slug or a UUID or integer (autoinc) **and** if you can use that reference to address the item and perform operations on it, the security implication is the same.

In other words, I'm not seeing what the actual security concern here is with revealing the IDs of items that a user can access. For example, I can see my twitter user ID, and those of my friends / followers, and any user I can find through search. Same with GitHub, through their API I can easily query all the IDs of people who've starred the keystone repo. IDs are not a thing you hide _for things you have access to_.

On the other hand, you should always be using **access control filters** to make sure nobody can see anything they shouldn't know the existence of. That's the point of the design; if you don't have access to an item (through filters) Keystone never reveals its existence at all, including through counts.

Re: this point:

> Perhaps its possible to match both slug and id for updates?

That's currently the case, have a look at the `UniqueWhere` inputs in your generated GraphQL schema, you can use _any_ of those to identify an item and perform operations on it.

### A guide to securing your app

* Use **filters** to completely hide the existence of items from users that shouldn't have access to them, and to filter out items users shouldn't be able to update or delete at all
* Use **operation** filters to prevent users performing actions entirely for lists
* Use **field** access control to hide sensitive data in fields that users should not be able to read or modify (email address is a great example of this, you should **always** put access control on an email field if untrusted users can access user records other their own)
* Use **item** access control or validation hooks as a last resort to prevent users setting values in items and fields they have access to update, where there are some values they _should not be able to set_ (for example if a user can update a relationship field, but only connect a subset of the possible related items)
* You have to reveal _some_ canonical way of addressing items publicly and consistently, in Keystone this is the ID field and the consistency of that is a critical aspect of the design that reduces overall system complexity

Hopefully all this helps, I'm going to close the issue so it doesn't show up as something for us to work on, as the system here is working as designed.
