### ISSUE TITLE
Enable `where` clauses on to-single Relationships

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#699]
## Example

```javascript
keystone.createList('Post', {
  fields: {
    title: { type: String },
    author: { type: Relationship, ref: 'User' },
  }
});
keystone.createList('User', {
  fields: {
    name: { type: String },
    bio: { type: String },
    isDeleted: { type: Checkbox, defaultValue: false },
  }
});
```

```graphql
query {
  Post(where: { id: "abc123" }) {
    title
    author(where: { isDeleted: false }) {
      name
      bio
    }
  }
}
```

I expect the `where: { isDeleted: false }` clause to cause the `author` field to be `null` when the condition doesn't match.

This avoids pulling in unnecessary data, and avoids client side checks (eg; selecting the `isDeleted` field, then do an in-code check for `true`.

**Comment by molomby** [comment]
@jesstelford -- On the original point (adding a `where` argument to Relationship fields) -- yeah great, could be handy. As you say..

> This avoids pulling in unnecessary data, and avoids client side checks

I don't see as much value for other types though. Eg., in your example...

```js
query {
  Post(where: { id: "abc123" }) {
    title
    author(where: { isDeleted: false }) {
      name(where: { value_not_contains: "<a swear word>" })
      bio(transform: { trim: 200 })
    }
  }
}
```

If I'm understanding, this would return..

* An item for each un-deleted users
* The first 200 letters of each users bio
* _Either_ their name or, if the field contained a cuss word, then `null`

I mean... _maybe_ for `Text` fields, since they can have any length, but `Boolean` fields?

--- 

Re: "transformations" -- This is nice one. It potentially lets you:

* Offload processing to the server
* Reduce bandwidth usage
* Remove the need to bundle libraries to the client (eg. if the server does date formatting as above, maybe you don't need a date library the browser)

These are most relevant to mobile and simple/light-weight frontends but it's a powerful pattern.

In terms of syntax, if we leverage the ability of Keystone field types to contribute multiple GraphQL fields we can return different GraphQL return types too. Could do something like..

```graphql
type User {
  name: String
  bio: String
  bio_trim(
    characters: Int!
    respectWordBoundaries: Boolean  # Defaults to false
    endSymbols: String  # Defaults to "..."
  ): String
  bio_length: Int  # Different GraphQL type than the main field
  createdAt: String!
  createdAt_format(format: String): String!
  isDeleted: Boolean
}
```

```graphql
query {
  Post(where: { id: "abc123" }) {
    title
    author(where: { isDeleted: false }) {
      name
      bio_trim(characters: 200, respectWordBoundaries: true)
      bio_length
      createdAt_format(format: "YYDDMM")
    }
  }
}
```
