### ISSUE TITLE
Keystone unexpectedly drop the database before the test execution

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#7263]
I've something like this:

```
import { setupTestRunner } from '@keystone-6/core/testing'
import config from './keystone'

const runner = setupTestRunner({ config })

test(
    'Keystone test',
    runner(async ({ context }) => {
        const posts = await context.query.Post.findMany()
        expect(posts).toHaveLength(1)
    }),
)
```

I've just executed the tests. And I lost all my local database data.
It seems that this is a problem. I didn't want to lose my local database.

It's better to add an extra argument to drop the database.
Or another way is to use another database for tests and drop it by default. 
But it's definitely not good to just drop the current database state.

**Comment by dcousens** [comment]
Hi @pahaz,

That sounds incredibly frustrating.

> Or another way is to use another database for tests and drop it by default.

The `config` object you provided to the test runner is how the underlying database for testing is configured.
The assumption is that if you are providing the `config.db` configuration,  _that_ is the database you want to use for testing.

Irrespective of whether a `dropDatabase` flag could be provided,  a test database will be mutated, potentially destructively, when running tests.

**You should only use a database that is THROWAWAY for testing purposes.**

All that said,  maybe a possibility to help prevent this in the future is to change the API to something like the following:

```
const runner = setupTestRunner({ 
  config, 
  db: { ... }
})
``` 

And or explicitly [re]introduce a `dropDatabase` flag - however, that is considered bad practice - and was removed previously - because it introduces a vector for side-effects when unit testing.

**Comment by dcousens** [comment]
`setupTestRunner` was removed from from `@keystone-6/core/testing`, and the only function that remains is `resetDatabase`.
This has been resolved.
