### ISSUE TITLE
Include changeset info on GitHub releases tab

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#795]
For example, this release: https://github.com/keystonejs/keystone-5/releases/tag/%40voussoir%2Fkeystone%401.0.0

Doesn't have the changeset info that exists here: https://github.com/keystonejs/keystone-5/blob/master/packages/keystone/CHANGELOG.md#100

**Comment by JedWatson** [comment]
I'd probably be in favour of wrapping the publish command to get around the foot-guns you mentioned @Noviny

i.e basically, add a `build-releases publish` task which creates the tags, and then runs `bolt publish-changed` under the hood in "dont create tags for me" mode. or something like that.

It would probably also make sense for it to `git push --tags` because publishing to npm and pushing tags should really be a single action. They're both pretty irreversible.

**Comment by MadeByMike** [comment]
@Noviny Any update on this with the new version of changeset?

**Comment by Noviny** [comment]
https://github.com/atlassian/changesets/issues/6 Is the changesets issue related to this - currently our oldest open issue!
