### ISSUE TITLE
Consider BackboneORM for database

### ISSUE THREAD

**Issue by kmalakoff** [keystonejs/keystone#838]
I just listened to NodeUp and noticed you were not aware of [BackboneORM](http://vidigami.github.io/backbone-orm/) for cross-database, client/server databases.

We support browser over HTTP, SQL variants (via knex), mongo, and in memory.

**Comment by grabbou** [comment]
Well, can somebody explain pros of changing Mongoose to another ORM? Apart from having ability to use other databases, I can't see any advantages. Generally, Keystone uses the database engine of its choice and I think that's fine as long as all the current features are working and we are not being blocked with further improvements by Mongoose or MongoDB design choices.

**Comment by sebmck** [comment]
@grabbou That's the main/only advantage/incentive right now and it's a massive one. The ability to allow different databases while retaining all keystone features would be awesome.

**Comment by JedWatson** [comment]
I think it's worth offering people the ability to choose a different database _as long as it doesn't limit KeystoneJS_, and _as long as we don't end up devoting a large amount of effort to cross-database support_.

I've never (personally) seen the promise of "database agnostic" work out well at a project level - you limit yourself from being able to take advantage of the strengths of any one platform, in order to support them all. Cross-platform ORMs I've worked with suffer for this (much more so at the level of abstracting the differences between document stores like MongoDB and relational databases like MySQL).

However, Keystone really doesn't _need_ a lot of database features; projects that are built on Keystone do. So as long as we can get what we need at the core level from another database and underlying ORM / package, great.

So while I wouldn't advocate "database agnostic" as a goal for a project, if we could implement it for Keystone, then at the outset you could choose the database platform that meets your requirements best and then build on that.

I have been thinking about whether we could move _some_ of the database interaction that we currently rely on Mongoose to provide into Keystone APIs (e.g. so you could `List.query` instead of `List.model.query`) as a fairly light-weight wrapper. That would let us build a very light-weight abstraction for ourselves (to handle basic tasks like querying / pagination) which would then let us plug in alternative underlying adapters.

We have enough roadmap features I think are really high value that I don't want to get bogged down developing or supporting a database abstraction layer. However, if we can find a good solution, or someone is willing to take on (and commit to supporting) a project that achieve this, then I'm on board.

**Comment by jamlen** [comment]
Just to throw another one in the ideas pot.... I've been looking at https://github.com/balderdashy/waterline recently.

**Comment by morenoh149** [comment]
I think waterline is a great option. Though I'm biased - I looked at sails a lot before getting into keystone.
And I've grown used to Mongoose haven't run into anything I'd need postgres support for. Though I'd love the flexibility to do so. Which both BackboneORM and Waterline offer.

**Comment by grabbou** [comment]
@jamlen still under 1.0 which kinda discards it as a main ORM for Keystone for now.

**Comment by jamlen** [comment]
@grabbou seriously??? Backbone ORM is also only at 0.7.x, node is only on 0.12....

A quick look through the packages that are "in" keystone show plenty of key packages that are not a 1.0, `async`, `react`, `marked` to point out a few.

**Comment by grabbou** [comment]
That's why I said "as long as they follow semver", the whole point was to think if Backbone ORM is stable enough or not ;)

**Comment by mxstbr** [comment]
I'll close this due to inactivity, we don't have any plans to integrate this currently. Moved to ProductPains: https://productpains.com/post/keystonejs/custom-orms

**Comment by kmalakoff** [comment]
Sounds like a good thing to do. It is hard to find a great cross-platform library in Node.js for abstracting various databases. Hopefully, a great solution will emerge soon.

**Comment by morenoh149** [comment]
I think nodal's ORM layer is very well thoughtout http://www.nodaljs.com/static/docs/index.html may have some RDBMS-isms due to primarily targeting postgres. But the author expressed support for other databases should be straightforward by writing an adapter https://github.com/keithwhor/nodal/tree/920dfbced62339b738d583dda7930392019e81d2/core/required/db/adapters

**Comment by bellsaladin** [comment]
I've started a project with the goal to support Mysql. The project has now a good foundation & implementation strategy.
https://github.com/bellsaladin/Keystone-Mysql

I have been using Keystone for quite a while now as light admin tool for some small projects and I aquired good knowledge on it's core functionning, at some point i felt the need for Mysql databases support, so i started a project with that goal.

I work on this project on free time only so I need help for this project to progress. **Any help is welcome**.
