### ISSUE TITLE
Auth Strategy and Authentication improvement

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#878]
Right now `admin-ui` is limited only to password strategy that has to be explicit.  Making implicit use of password strategy would help it use any Auth strategy. It actually depends on session middleware and not on password Auth Strategy. 

If you have a working Twitter Auth Strategy, once logged in you can login to admin ui without needing to authenticate again, you can make changes based on access control. 

In essence following changes would be needed. 

* Pass around Auth Strategy as instance rather than Type. I mean we should be able to do following
```js
const passwordAuthStrategy = new PasswordAuthStrategy(......);
const twitterAuthStrategy = new TwitterAuthStrategy(......);
const facebookAuthStrategy = new FacebookAuthStrategy(......);
keystone.useAuthStrategy(passwordAuthStrategy, twitterAuthStrategy, facebookAuthStrategy)
```
instead of `keystone.createAuthStrategy`. There may also be shorthand version, `keystone.auth.usePassword(....)` instead of two step in create then use. 

* As soon as you do above (`keystone.useAuthStrategy`/`keystone.auth.usePassword`), session middleware should be ready to use without the need explicit use of it in `admin-ui`. no harm in having explicit advanced configuration different from all others. 

* mount session middleware outside of `admin-ui` possibly with server/core with option to use existing session middleware for easy integration of keystone with existing express app.  Config option `authRoot` with default at `/auth/` can be used to mount all authentication related routes there. 

* Create theme-able generic page for login (similar to admin-ui login page), log out, connect etc, which could use widgets from the Auth plugin (twitter, facebook, google, insta etc.) This can also be an extension point for plugins to add their login widgets.
 

See my comment in https://github.com/keystonejs/keystone-5/pull/861#issuecomment-474196375  for original idea reference

**Comment by gautamsi** [comment]
I see you have moved session middleware code to `@keystone-alpha/session` package.

**Comment by bladey** [comment]
Hi all,

Thank you for taking the time to contribute to this issue.

In an effort to maintain the KeystoneJS project going forward, we're closing issues related to [Keystone 5](https://github.com/keystonejs/keystone-5) to make way for the next version called [Keystone Next](https://next.keystonejs.com).

The existing **Keystone 5** codebase has been moved to [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) which is now in a 6-12 month active maintenance phase.

You can learn more about the next version which we’re calling **Keystone Next**, which is now [in preview](https://next.keystonejs.com).

If you feel this issue is still relevant and require assistance, please open a new issue in the [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) repository.

Thank you for your continued support as we push towards this next major new version of KeystoneJS!
