### ISSUE TITLE
empty flash messages

### ISSUE THREAD

**Issue by freder** [keystonejs/keystone#883]
hi,

I would like to make use of keystone's flash messages, however the displayed messages end up empty:

```javascript
// what file is this? routes/views/index.js ? - Harry Moreno
var keystone = require('keystone');

exports = module.exports = function(req, res) {
	var view = new keystone.View(req, res);
	var locals = res.locals;

	locals.section = 'forum';

	view.on('init', function(next) {
		keystone.list('ForumThread').model
			.findOne({'slug': req.params.slug})
			.exec(function(err, result) {
				if (err) { return next(err); }
				if (!result) { 
					req.flash('warning', 'Thread not found.');
				} else {
					locals.thread = result;
				}				
				next();
			});
	});
	
	view.render('thread');
};
```

![screen shot 2015-01-09 at 14 13 25](https://cloud.githubusercontent.com/assets/724844/5680199/11a16546-980a-11e4-89e5-63a6fa3f6508.png)

any idea what's going wrong here?

thanks a lot in advance.

**Comment by snowkeeper** [comment]
Are you including the code in your template file?
```
include PATH_TO/flash-messages
...
+flash-messages(messages)
```

**Comment by freder** [comment]
I'm using handlebars, and the default layout that `yo keystone` created for me contains this:

```html
<div id="body">
	<!--
		Flash messages allow you to display once-off status messages to users, e.g. form
		validation errors, success messages, etc
	-->
	{{#if messages}}
	<div id="flash-messages" class="container">
		{{#if messages.info}}
		<div class="alert alert-info">
				{{{flashMessages messages.info}}}
		</div>
		{{/if}}
		{{#if messages.success}}
		<div class="alert alert-success">
				{{{flashMessages messages.success}}}
		</div>
		{{/if}}
		{{#if messages.warning}}
		<div class="alert alert-warning">
				{{{flashMessages messages.warning}}}
		</div>
		{{/if}}
		{{#if messages.error}}
		<div class="alert alert-danger">
				{{{flashMessages messages.error}}}
		</div>
		{{/if}}
	</div>
	{{/if}}
	<!-- The content block should contain the body of your template's content-->
	{{{body}}}
</div>
```

my view uses this default layout:

```html
{{!< default}}
<div class="container">
	[...]
</div>
```

**Comment by freder** [comment]
looking into the `flashMessages` helper (see my comments in the code):

```javascript
_helpers.flashMessages = function(messages) {
	var output = '';
	
	// ————————
	console.log(messages);
	// message is a string in my case — not an object.
	// that's why the following for loop does effectively nothing.
	// ————————

	for (var i = 0; i < messages.length; i++) {			
		if (messages[i].title) {
			output += '<h4>' + messages[i].title + '</h4>';
		}
		
		if (messages[i].detail) {
			output += '<p>' + messages[i].detail + '</p>';
		}
		
		if (messages[i].list) {
			output += '<ul>';
			for (var ctr = 0; ctr < messages[i].list.length; ctr++) {
				output += '<li>' + messages[i].list[ctr] + '</li>';
			}
			output += '</ul>';
		}
	}
	return new hbs.SafeString(output);
};
```

messages are expected to be objects, but are plain strings in my case.

doing `req.flash('warning', { title: 'Thread not found.'})` works, but that's not how it is described in [http://keystonejs.com/docs/getting-started/](http://keystonejs.com/docs/getting-started/) ...

**Comment by morenoh149** [comment]
this may be a case where the handlebars version of the generated app wasn't tested well enough. Could you share your entire project on github?

**Comment by freder** [comment]
here's a [link to the project](https://github.com/freder/keystone_883).

**Comment by ericwebster** [comment]
I don't know if this is still a problem for you but he helper function for handlebars was looking for a completely object structure than what was being returned from flashMessage. 

flashMessages returns an indexed array not an object like the handlebar helper function thought. I don't know if this was refactored at one point and they just missed this template. It was looking for 'title' 'detail' and 'list' object properties which I couldn't see how the flashMessage method would ever return that.

I just changed my handlebar helper to be..

'''javascript
	_helpers.flashMessages = function(messages) {
		var output = '';
		for (var i = 0; i < messages.length; i++) {
			output += '<h3>' + messages[i] + '</h3>';
		}
		return new hbs.SafeString(output);
	};
'''
be happy to PR this back to the yoman generator if you guys wanted.

**Comment by preslavrachev** [comment]
Still the case, it seems. I am working on a project that uses handlebars, and my flash messages also appear empty. I tried wrapping the message as an object, and it worked. If you look at the automatically generated helper though, I think they actually wanted it to be an object, rather than a simple string. It kind of makes sense, if you want to construct a complex message, with a title and some details. I think that the code is right, but the documentation is not up-to-date on that specific subject.

```javascript
_helpers.flashMessages = function(messages) {
		var output = '';
		for (var i = 0; i < messages.length; i++) {
			
			if (messages[i].title) {
				output += '<h4>' + messages[i].title + '</h4>';
			}
			
			if (messages[i].detail) {
				output += '<p>' + messages[i].detail + '</p>';
			}
			
			if (messages[i].list) {
				output += '<ul>';
				for (var ctr = 0; ctr < messages[i].list.length; ctr++) {
					output += '<li>' + messages[i].list[ctr] + '</li>';
				}
				output += '</ul>';
			}
		}
		return new hbs.SafeString(output);
	};
```

**Comment by hatzipanis** [comment]
@preslavrachev you're a life saver.

**Comment by JedWatson** [comment]
@hatzipanis @preslavrachev @ericwebster @freder 

is this something we should update in the yeoman generator to clarify this for future users?

**Comment by ddaddy** [comment]
I have also just struggled with blank flash messages.
I used the existing `requireUser` method to extend it to different types of user and eventually thanks to the comments above found my issue.

It seems that when redirecting to the keystone login, messages can be simple text
```
req.flash('error', 'Please sign in to access this page.');
res.redirect('/keystone/signin');
```
However if you redirect to any other page, the message is blank. You must use
```
req.flash('error', { detail: 'You cannot access that page.' });
res.redirect('/');
```

**Comment by jstockwin** [comment]
@ddaddy Are you also using handlebars? I believe the admin ui (specifically `/keystone/signin`) is rendered using jade, no matter which engine you use for your own pages. Therefore, it works on the signin page, but not `/`, since `/` is rendered using handlebars.

@JedWatson I believe this is still an issue in handlebars. Either the docs need updating, or there is a bug. If you are using handlebars, you MUST give an error e.g. `req.flash('error', { detail: 'You cannot access that page.' });` and not `req.flash('error', 'Please sign in to access this page.');`.

The docs [here](http://keystonejs.com/docs/getting-started/#routesviews-middleware) say 

"To use flash messages in your route controllers, do this:
`req.flash('info', 'Some information!');`"

which does not work using handlebars.

**Comment by ddaddy** [comment]
I am using `nunjucks`

**Comment by jstockwin** [comment]
If you use the object format, does the error display on `/keystone/signin`, or can you only achieve one or the other? 
`req.flash('error', { detail: 'You cannot access that page.' });`

**Comment by ddaddy** [comment]
Yes the object format works on the keystone signin page as well as just the text format.

**Comment by jstockwin** [comment]
@JedWatson @mxstbr 

I have also personally found that errors only really work when given like:
`req.flash('error', { title: 'An error occurred', detail: 'Error message' })`
and empty flash messages appear when using
`req.flash('error', 'Error message')`

Presumably either work when using jade, hence why it works fine in the admin UI, and presumably why you haven't come across this much yourselves. 

As @preslavrachev commented before this issue was closed, the code for handlebars flash message helper (and presumably nunjucks) seems to be expecting errors to be objects, not simple strings. The code is so specific that this seems intentional, none of the documentation on throwing errors shows them in this form. IMO this should be re-opened as either a bug, or as an issue on the docs.

I'd suggest an update to the docs (which I'm happy to do a PR for if you like) so that all errors are thrown using objects. However is it also worth updating the handlebars/nunjucks helpers so that errors which are not thrown as objects are still displayed, instead of these empty flash messages?

Alternatively, if errors are not supposed to be constructed in this object format, then the helpers need updating.

**Comment by mxstbr** [comment]
I wasn't involved when any of these decisions was taken, so I can't really comment. @JedWatson?
