### ISSUE TITLE
Add Access Control to Objects/Models other than the User Object/Model

### ISSUE THREAD

**Issue by adedot** [keystonejs/keystone#899]
I would like to add access control to Objects/Models other than the User Object/Model. From what I see, there is only access control for the a User being an admin for Keystone. 

For instance, I would like to add access control to Concept Object/Model that has a private field that only allows Posts to be viewed by Users if the user has a role/group allowed to access the Concept Object.

**Comment by peteruithoven** [comment]
This one seems relevant: https://github.com/keystonejs/keystone/issues/803

**Comment by wangpingsx** [comment]
@adedot 


Hi,

I got a solution without changing the source code of keystonejs.

-----------
>. The supper admin functionality: (only supper admin can create, delete users, common admin users can only change themselves)
Analysis with solutions: http://baiduhix.blogspot.co.uk/2015/02/keystone-more-deeper-supperadmin.html
The implementing code: http://baiduhix.blogspot.co.uk/2015/02/keystone-more-deeper-supperadmin-only.html

------------

>. Also If you want to add authorization for tables (collections): ( Access Control / Roles)
http://baiduhix.blogspot.co.uk/2015/02/keystone-more-deeper-authorization-role.html

-------------

Let me know if you have any issues.

Thanks,
Peter

**Comment by webteckie** [comment]
@wangpingsx interesting!  I should try your solution in my project as an intermittent solution and see how it goes.  Regarding the roles, I'm assuming a rules.js can be created and them imported.  Regarding the roles field in the User can that be a relationship to a Roles list?  Can you think of any drawbacks your solution may have?  Thanks!

**Comment by wangpingsx** [comment]
Hi @webteckie ,

"a rules.js", is a good idea. Then supper admin users can create new roles or delete roles by admin-ui. Then,  in user management view, supper admin can select roles instead of typing the role name (a plain String). 

This is defiantly a good idea!!!!

Adding multi-roles could be an issue, but you can get some clue from : 
http://demo.keystonejs.com/keystone/things/

![image](https://cloud.githubusercontent.com/assets/1758819/6057525/d428d8ee-ad16-11e4-9974-95e1d7264932.png)

Regarding drawbacks:

The only drawback I can see is the UE, when users click a restricted link, system will show the 500 page.

Hiding restricted links would be the best solution, but without changing keystonejs's source code, I think that is impossible.


@webteckie  I am writing my blog, I would like to copy your question and my answer into my blog: 
http://baiduhix.blogspot.co.uk/2015/02/keystone-more-deeper-authorization-q.html

I wish you happy with that, I will reference this link and a snapshot of your question including your photo.

Please let me know if you have any concern of this.


Thanks,
Peter

**Comment by wangpingsx** [comment]
Hi @webteckie ,

Sorry I found a problem of your "a roles.js model" solution. Actually it is no problem at all if you know how to query mongodb from a middleware (I don't know, I am a new starter of Nodejs and mongoose).

The reason is Keystonejs currently doesn't support embed object. the "roles" in your solution is a group of references of roles. The references are IDs, which means your req.user has a list of role IDs, you can't use IDs to verify current user's role, because they are meaningless numbers, you need anther query to mongodb to translate these role IDs to role names, then you can match roles with your authorisation rules.

Again, if you and make the query in middleware, it is not a big issue.

By the way, as i mentioned above, keystonejs currently doesn't support embed objects, I have anther blog to introduce my solution for that:

http://baiduhix.blogspot.co.uk/2015/01/a-new-type-of-keystonejs-objectarray_26.html
http://baiduhix.blogspot.co.uk/2015/01/a-new-type-of-keystonejs-objectarray.html

However, my solution only support strings and numbers for sub objects' fields.


Thanks,
Peter

**Comment by wangpingsx** [comment]
@webteckie 

I find some bugs of my solution, and I have fixed them:

http://baiduhix.blogspot.co.uk/2015/02/keystone-more-deeper-authorization-bugs.html

The latest code of my github project has fixed all of them.

Thanks,
Peter

**Comment by webteckie** [comment]
@wangpingsx yeah, to me unauthorized implies that someone should not even be able to see any of it.  If your solution still shows the items and lets users tamper with it then not sure.  It seems we still need the core keystone to do some stuff for us to make this tamper-proof.  btw, querying mongo to resolve the roles ID shouldn't be a problem, though.

**Comment by wangpingsx** [comment]
@webteckie  I have two auth control models:

1. On the list view. If you use this model, users cannot see the list view. (that can solve the issue you raise above)

2.On the item view. if you use this model, users still can see the list view, but not able to click to see detail (the item view).

Thanks,
Peter

**Comment by webteckie** [comment]
@wangpingsx ok, doesn't seem like a lot of effort to give it a quick test so I may still do that.  Will let you know!  Thanks!

**Comment by wangpingsx** [comment]
@webteckie  I think what your concern is the second bug which i mentioned here: 
http://baiduhix.blogspot.co.uk/2015/02/keystone-more-deeper-authorization-bugs.html

I was wrong, it is not an issue,  xxxxx/keystone/object/1223456634 will be blocked anyway.

BTW, please check my latest code from github, I have changed a little.

To try my project, the easiest way is using my json below for user table. After you checkout my code, run npm install. then you can run my project without changing anything. (otherwise you need define roles and auth rule.)

below json created user@keystonejs.com as a admin, userxx@keystonejs.com as a supper admin.

password is "admin".



/* 0 */
{
    "_id" : ObjectId("54d1e0160899fc3a05a3d14f"),
    "isSupperAdmin" : false,
    "isAdmin" : true,
    "password" : "$2a$10$pi12AcBRDoIRUdyY.co9QuS5OmAE0UzUGFY3OhLIBwxOo7964uKLG",
    "email" : "user@keystonejs.com",
    "name" : {
        "last" : "User aa1zzzzz",
        "first" : "Admin"
    },
    "__v" : 1,
    "roles" : [ 
        "aa", 
        "bb"
    ]
}

/* 1 */
{
    "_id" : ObjectId("54d1e0170899fc3a05a3d151"),
    "isSupperAdmin" : true,
    "isAdmin" : true,
    "password" : "$2a$10$RgZUFZUWcy5bD0zOuMbs6eUOAmdSsyXMzDG0iEG99V/r/dD7q.fdC",
    "email" : "userxx@keystonejs.com",
    "name" : {
        "last" : "Userxx1",
        "first" : "Adminxx"
    },
    "__v" : 1,
    "roles" : [ 
        "aa", 
        "cc"
    ]
}

/* 2 */
{
    "_id" : ObjectId("54d366f48414997408c4726b"),
    "password" : "$2a$10$LkjeKvdEM4mB1wcdKq3am.N94trUeFeUNlqIgVV4P/8rozGDExfM.",
    "email" : "aa@aa.com",
    "roles" : [],
    "name" : {
        "first" : "supperAdmin",
        "last" : ""
    },
    "__v" : 0,
    "isAdmin" : true,
    "isSupperAdmin" : true
}

**Comment by webteckie** [comment]
@wangpingsx I'm on to my regular job but a quick note just letting you know that I cloned your repo and saw your work live and looks pretty good.  I wonder if keystone core can be enhanced with a quick improvement to support a virtual "canAccessList" just like there's "canAccessKeystone" in the user model.  @JedWatson what do you think about all this?

**Comment by wangpingsx** [comment]
@webteckie  you can change models/user.js , instead of changing keystonejs core.

**Comment by webteckie** [comment]
@wangpingsx hmm...don't see how that would be done.  Perhaps the approach here is to disable the nav links for the lists the logged in user don't have access to.  Not sure how easy that would be to do.  I think it would easier if the nav links were objects.  For example:

```
    'posts': [
        posts: {show: true},
        post-comments: {show: true},
        post-categories: {show: true}
    ],
```

If a user was not authorized to manage post categories then the authorization middleware would crawl into the posts->post-categories nav and set {show: false}.

**Comment by webteckie** [comment]
Actually, instead of {show: [true/false]} above, it would be {roles: [a, b, c]}.  Only users that match the roles would get the nav links rendered.  Anyways, not sure.  This requires more research as, at least, one other alternative is to have the roles in the model.  The challenge is to get this working without keystone core intervention as you had started to do :-)

**Comment by adedot** [comment]
For the previous client that requested access control, I ended up using integrating node acl (https://github.com/OptimalBits/node_acl) into project. Access control was set when a the Model was "saved". Checking for whether a user had the permission for the resource occurred in the middleware through a function. This is more a custom solution based on the requirements. Anyways, I hope this information helps.

**Comment by webteckie** [comment]
After thinking about it, I think I will hold on putting any roles stuff in my project until I see the direction the keystone project takes with it.  But if someone is really in need of a quick roles solution your work should be an alternative for them.

**Comment by wangpingsx** [comment]
Hi my friends, try my solution, and try my sample project first, then you will know, I have solved everything for you. believe me!

Thanks,
Peter

**Comment by andrewlinfoot** [comment]
We're closing all feature requests to keep the issue tracker unpolluted. I've moved this to ProductPains: https://productpains.com/post/keystonejs/add-access-control-to-objectsmodels-other-than-the-user-objectmodel

**Comment by mrth2** [comment]
@wangpingsx 👍  I like your solution on creating superAdmin role. 
But now in keystone v4, the mount.js was removed and middleware pre routes won't be fired in keystone admin. Do you have any other solution? 
Thank you!
