### ISSUE TITLE
Server restarts canceled session persistence

### ISSUE THREAD

**Issue by linhanyang** [keystonejs/keystone#908]
Server restarts canceled session persistence or move out of the session persistence keystone source？？？

**Comment by snowkeeper** [comment]
Can you provide some more information?  How are you storing sessions (memoryStore, mongo)?  Does your cookie secret remain the same across restarts?

**Comment by JedWatson** [comment]
@linhanyang for sessions to persist across restarts you need to set `session store` to either `mongo` or `redis`. Keystone uses the in-memory datastore by default (because it is up to you to decide which database is better for your session needs).

Remember, the in-memory datastore is _not suitable for production_ (you should see a warning on startup in production alerting you to this)
