### ISSUE TITLE
Allow transformation options on CloudinaryAdapter

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone#920]
We should have an option to protect privacy by removing geo-location / geotag information from uploaded photos/images.

Cloudinary Supports this using "incoming transformations"
Ref: 
https://support.cloudinary.com/hc/en-us/community/posts/115003112391-Stripping-out-geo-location-data-on-upload
https://cloudinary.com/documentation/upload_images#incoming_transformations

We should also allow the usage of other Cloudinary options as passthrough

**Comment by MadeByMike** [comment]
This is out of scope for Keystone. A user may wish to upload files with geotag information as a requirement for what they are building. If they don't the correct way to filter this is hooks. 

If Keystone was purely a CMS I would agree we should add some support for this but we don't want to preprocess files. 

One thing I would support is if the Cloudinary allowed the user to configure any transformation options such as: 

```
  new CloudinaryAdapter({
    ...otherOptions,
    transformations: { width: 2000, height: 1000, crop: "limit" },
  });
```
This would allow users to strip any geo info without use having an explicit opinion on how this is done.

**Comment by VinayaSathyanarayana** [comment]
Thanks @MadeByMike There are a number of useful transformation by Cloudinary. We should support that.

Ref: https://cloudinary.com/documentation/image_transformations#targetText=Cloudinary%20allows%20you%20to%20easily,user%20experience%20and%20minimal%20bandwidth.

**Comment by VinayaSathyanarayana** [comment]
Hello... We should allow / enable usage of transformations provided by cloudinary

**Comment by molomby** [comment]
> This is out of scope for Keystone. A user may wish to upload files with geotag information as a requirement for what they are building. If they don't the correct way to filter this is hooks.

@MadeByMike, If I'm understanding correctly, the problem right now is we're blocking app developers from accessing the underlying functionality Cloudinary provides. There's no way to solve this with hooks since the transformation in question is an `incoming_transformation` that can only be applied on upload (and there is no upload hook).

@VinayaSathyanarayana is just asking that Keystone passes arbitrary config option though to Cloudinary, rather than only allowing creds to be specified. Something [like this](https://github.com/keystonejs/keystone/compare/molomby/passthough-cloudinary-uploadOptions), I think?

**Comment by VinayaSathyanarayana** [comment]
@molomby @MadeByMike - We should allow passing the options to Cloudinary so that the developer can leverage all the capabilities provided by Cloudinary.

**Comment by JedWatson** [comment]
Just jumping quickly to clarify that this _is_ something that we should support at the cloudinary adapter and field levels accordingly, i.e

- upload transformations and other options should be able to be configured at the cloudinary adapter level
- all transformations and other request-specific options should be available at the graphql level, exposed by the cloudinaryimage field

@VinayaSathyanarayana I can't give you an estimate on when this will land (I believe @molomby is looking at it at the moment) but wanted to acknowledge that this should be implemented in Keystone

**Comment by VinayaSathyanarayana** [comment]
Any progress on this?

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
