### ISSUE TITLE
Trying to modify LocalFile dest option before move

### ISSUE THREAD

**Issue by jesse-ae** [keystonejs/keystone#937]
The filename LocalFile option is helpful, but I'd also like to write files to a subdirectory derived from the document id. I've looked through LocalFileType.js and it looks like the pre.move hook doesn't give me a way to set the field options. Am I missing something?

The two options I need to change _after_ the doc id has been generated are dest and prefix.

**Comment by JohnnyEstilles** [comment]
At first I didn't see the usefulness of this feature, but after a few exchanges on [StackOverflow](http://stackoverflow.com/questions/28077011/how-to-specify-custom-dev-prefix-in-a-keystone-localfile-field) with @jesse-ae on the subject (please ignore my misguided answer to his question :-), he explained and made his case for his use-case and I eventually came around.

That said, I perceive some behavior issues with a custom `dest` we need to consider and decide upon before we move on. Since `dest` determines the ultimate destination path of uploaded file:

1. If on update, the `dest` changes, but no new file is uploaded, we would need to rename the existing file
2. If on update, a new file is uploaded and the `dest` changes simultaneously, we would need to delete the old/existing file prior to the upload (or else we would be leaving stranded/orphan files).

@jesse-ae, is this the behavior you're expecting?

Can @JedWatson or anyone other interested party weigh in on this? I want to make sure I'm not missing anything and I'm taking this in the right direction.

If the above behavior is acceptable, the easiest way to fix this, IMO, is to **optionally** allow both `dest` and `prefix` to be defined as functions, as we do with `format`.

Something like this:

```js
var Thing = new keystone.List('Thing', {
    autokey: { path: 'slug', from: 'title', unique: true }
});

Thing.add({
  image: {
    title: String,
    type: Types.LocalFile,
    dest: function(item, file) {
      return 'public/images/things/' + item.slug;
    },
    prefix: function(item, file) {
      return '/images/things/' + item.slug;
    },
    format: function(item, file) {
      return '<img src="/images/things/' + item.slug + '/' + file.filename + '" style="max-width:300px" />';
    }
  }
});
```

Making this an optional feature will allow `LocalFile` to be backwards compatible and should not inject any breaking changes. If there are not objections to my proposal and there aren't any other takers, I can take care of this issue.

> NOTE: @jesse-ae, @JedWatson has advised me that the 0.2.x branch is now frozen for new features, so in the event we do implement this, it will not be available until the 0.3.x version.

**Comment by jesse-ae** [comment]
@JohnnyEstilles, I'm all for this solution. I hadn't considered how changing the `dest` and `prefix` values would impact existing files, so thanks for thinking it through.

**Comment by JohnnyEstilles** [comment]
@jesse-ae, no problem. I'll wait for input from @JedWatson and the rest of the contributors before proceeding. I think that as long as I can make this backwards compatible there shouldn't be an issue, but I would still like fresh eyes on it.

**Comment by webteckie** [comment]
I think many other field options can benefit from having a function value to dynamically generate a field option value based on some other properties of the list, the keystone context, and/or overall run-time environment.   Couldn't a generic solution be implemented that works for any field option?

**Comment by JohnnyEstilles** [comment]
@webteckie, there's already a generic solution to generate dynamic values, Mongoose [virtuals](http://mongoosejs.com/docs/2.7.x/docs/virtuals.html).

Actually, in my original answer to @jesse-ae's question in [StackOverflow](http://stackoverflow.com/questions/28077011/how-to-specify-custom-dev-prefix-in-a-keystone-localfile-field) I recommended that he used virtuals. Unfortunately, in this case, @jesse-ae didn't just want to create new dynamic values, he wanted to alter the behavior of existing  Keystone `LocalFile` field type options (i.e. `dest` and `prefix`).

**Comment by webteckie** [comment]
@JohnnyEstilles hmmm...I thought field options could not access virtuals directly?  So taking the Select field as an example, you saying I can do something like:

```
var Thing = new keystone.List('Thing', {
  }
});

Thing.add({
    choice: {type: Types.Select, options: getOptions() },
})

Thing.schema.virtual('choice.options'.get(function {
    return "pizza, hamburger, burrito";
});
```

**Comment by JohnnyEstilles** [comment]
@webteckie, I see what you mean. I think I misunderstood what you were proposing because I was looking at it in the context of @jesse-ae issue. @jesse-ae's use case and yours are fundamentally different. In @jesse-ae's, the generated values for `dest` and `prefix` have no meaning or even use before the item/field is saved. In yours `options` is required before an item is saved in order to generate the UI. And, of course, virtuals are not available at this point.

My proposed solution for @jesse-ae's issue is for `dest` and `prefix` to accept functions, the evaluation of which will be deferred until they are used. I supposed, theoretically, we could change the way options are evaluated to allow for this behavior. This goes way beyond the scope of what I was proposing, but it's definitely doable.

I guess my question is, do we really want this behavior available for all field options? I just foresee a lot of potential problems by developers misusing a feature like this. I'm all for allowing it for specific options, with well-defined use-cases.

Maybe this is a good thing and I'm not seeing the picture. Would anyone care to show me the light? :-)

**Comment by webteckie** [comment]
@JohnnyEstilles I guess it's a concern to attempt a generic solution.  Then we should address this on a per field basis outside of the issue being  addressed here.

**Comment by geloescht** [comment]
Any news on this? I want to put uploaded pictures into different directories depending on a category field. Those directories might get processed manually and are going contain a huge number of images, so I'd like to avoid putting all files in one giant directory.
I vote for providing a middleware hook instead of turning the dest option into a function. This feature is too complex to be exposed in a function. In order to compute the final path, filesystem operations might be required and functions always return synchronously.

**Comment by mxstbr** [comment]
As far as I can tell this is solved so I'll close this. Feel free to comment again if you think that was a mistake!

**Comment by Pyav123** [comment]
@geloescht ,I am new to keystonejs and  I also need this feature so that I can manage large set of images. Will you mind sharing the code? I understood that you have used pre post hooks but , are you allowing admin user to define their own path and how you are handling creation of nested folders?
