### ISSUE TITLE
v0.3.0:  Code Field with {noedit: true} renders minified/compressed code

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#939]
This may be addressed when the Code Field is improved; nevertheless I'm adding this issue to make sure it doesn't fall through the cracks.  If I create a list that has a code field with "noedit: true" as follows:

    box: { type: Types.Code, lang: 'less', noedit: true }

the Admin UI will render the code in that box minified/compressed.  In my use case, this is undesirable and other than being non-editable the content should look just as if the noedit was set to false.

**Comment by JedWatson** [comment]
I've fixed this by always rendering CodeMirror and setting the `readOnly` option to the `noedit` value.

This means that when language support is added back in, noedit fields will still be syntax-hilighted correctly.

It's a _little_ strange that the field looks like the normal editable version, and you can focus it even though it's read-only, which is different to other fields, but otherwise selecting text and copy/paste doesn't work, so I think it's a good compromise (until we can come up with a better solution at least).

**Comment by JedWatson** [comment]
Update: I've disabled the focus styling when code fields are set to `noedit`, so at least it doesn't look like you should be able to type in it. The caret still appears but it's better than before.

**Comment by webteckie** [comment]
@JedWatson confirming that this now works as expected.  Not sure what you meant above by "copy/paste doesn't work" but I can copy out of that no-edit box and paste somewhere else.  Thanks!
